Repository astral-sh/uv, pull requests merged in 2024-10, with the labels that each got.

#7824 Respect `tool.uv.environments` for legacy virtual workspace roots
  crates/uv-workspace/src/workspace.rs
  crates/uv/tests/lock.rs
Labels: bug

#7826 Remove unnecessary index location methods
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
Labels: internal

#7833 expose `FlatDistributions` struct in public API
  crates/uv-resolver/src/lib.rs
Labels: rustlib

#7840 Follow-up: Add gitignore to dist directory
  crates/uv-publish/src/lib.rs
Labels: internal

#7832 Reduce file reading boilerplace in tests
  crates/uv/tests/branching_urls.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/ecosystem.rs
  crates/uv/tests/edit.rs
  crates/uv/tests/export.rs
  crates/uv/tests/init.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/lock_scenarios.rs
  crates/uv/tests/python_pin.rs
  crates/uv/tests/run.rs
  crates/uv/tests/sync.rs
  crates/uv/tests/tree.rs
  crates/uv/tests/workflow.rs
  scripts/scenarios/templates/lock.mustache
Labels: internal, testing

#7837 Use `uv publish` instead of twine in docs
  docs/guides/integration/alternative-indexes.md
Labels: documentation

#7823 Add detailed errors for `tool.uv.sources` deserialization failures
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-distribution/src/metadata/requires_dist.rs
  crates/uv-workspace/src/pyproject.rs
  uv.schema.json
Labels: error messages

#7847 Accept `git+` prefix in `tool.uv.sources`
  crates/uv-workspace/src/pyproject.rs
  crates/uv/tests/lock.rs
Labels: bug

#7825 Use build failure hints for `dotenv` errors, rather than in `uv add`
  Cargo.lock
  crates/uv-dispatch/src/lib.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/diagnostics.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/suggestions.json
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/build.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_sync.rs
Labels: error messages

#7849 Improve error message copy for failed builds
  crates/uv-build-frontend/src/error.rs
  crates/uv-build-frontend/src/lib.rs
  crates/uv/tests/build.rs
  crates/uv/tests/edit.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_sync.rs
  crates/uv/tests/sync.rs
Labels: error messages

#5511 Respect `PAGER` env var when paging in `uv help` command
  crates/uv/src/commands/help.rs
Labels: cli

#6857 GitLab Integration documentation
  .prettierignore
  docs/guides/index.md
  docs/guides/integration/gitlab.md
  docs/guides/integration/index.md
  mkdocs.template.yml
Labels: documentation

#7578 Clarify locking and resolving without package name
  crates/uv/src/commands/project/lock.rs
Labels: internal

#7852 Bump version to 0.4.18
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#7855 Rename `install-wheel-rs` library
  crates/uv-bench/benches/uv.rs
  crates/uv-cli/src/lib.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-install-wheel/Cargo.toml
  crates/uv-installer/src/installer.rs
  crates/uv-installer/src/uninstall.rs
  crates/uv-python/src/interpreter.rs
  crates/uv-settings/src/combine.rs
  crates/uv-settings/src/settings.rs
  crates/uv-tool/src/lib.rs
  crates/uv/src/commands/build.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/settings.rs
Labels: internal

#7861 Fix code block title in Gitlab integration docs
  docs/guides/integration/gitlab.md
Labels: documentation

#7868 Add missing bound on tomli tests
  crates/uv/tests/pip_install.rs
Labels: internal

#7850 Display the target virtual environment path if non-default
  crates/uv/src/commands/pip/check.rs
  crates/uv/src/commands/pip/freeze.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/list.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/show.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/pip/tree.rs
  crates/uv/src/commands/pip/uninstall.rs
  crates/uv/tests/export.rs
  crates/uv/tests/pip_install.rs
Labels: cli

#7739 Support uv run --script
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/run.rs
  docs/reference/cli.md
Labels: cli

#7874 Rename `project::FoundInterpreter` to `ProjectInterpreter`
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/tree.rs
Labels: internal

#7871 Use an enum for free-threaded Python requests
  crates/uv-python/src/discovery.rs
  crates/uv-python/src/downloads.rs
  crates/uv-python/src/lib.rs
  crates/uv/src/commands/build.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/init.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/python/find.rs
  crates/uv/src/commands/venv.rs
Labels: internal

#7877 chore(ci): bump macos-12 intel runner to macos-13 intel runner
  .github/workflows/build-binaries.yml
  .github/workflows/ci.yml
Labels: releases

#7900 Organize downloads by prioritizing the platform, then the architecture.
  crates/uv-python/download-metadata.json
  crates/uv-python/fetch-download-metadata.py
  crates/uv-python/src/downloads.inc
Labels: internal

#7867 Allow `py3x-none` tags in newer than Python 3.x
  crates/uv-resolver/src/requires_python.rs
  crates/uv/tests/snapshots/ecosystem__transformers-lock-file.snap
Labels: bug

#7902 Always ignore `cp2` wheels in resolution
  crates/uv-resolver/src/requires_python.rs
  crates/uv/tests/snapshots/ecosystem__home-assistant-core-lock-file.snap
  crates/uv/tests/snapshots/ecosystem__packse-lock-file.snap
  crates/uv/tests/snapshots/ecosystem__transformers-lock-file.snap
  crates/uv/tests/snapshots/ecosystem__warehouse-lock-file.snap
  crates/uv/tests/snapshots/workflow__packse_add_remove_existing_package_noop-2.snap
  crates/uv/tests/snapshots/workflow__packse_add_remove_one_package-2.snap
  crates/uv/tests/snapshots/workflow__packse_promote_transitive_to_direct_then_remove-2.snap
  crates/uv/tests/workflow.rs
Labels: bug

#7904 Respect project upper bounds when filtering wheels on requires-python
  crates/uv-resolver/src/requires_python.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/snapshots/ecosystem__warehouse-lock-file.snap
Labels: enhancement

#7916 Fix documentation (projects guide) regarding adding a git dependency
  docs/guides/projects.md
Labels: documentation

#7864 Preserve case-insensitive sorts in `uv add`
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv/tests/edit.rs
Labels: enhancement

#7922 Trim commits when reading from Git refs
  crates/uv-cache-info/src/commit_info.rs
Labels: bug

#7921 Clear publish progress bar on retry
  crates/uv-publish/src/lib.rs
  crates/uv/src/commands/reporters.rs
Labels: bug

#7923 Use a higher timeout for publishing
  crates/uv-client/src/base_client.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv/src/commands/publish.rs
Labels: bug

#7927 Ignore `UV_CACHE_DIR` during tests
  .github/workflows/ci.yml
  crates/uv/tests/common/mod.rs
  crates/uv/tests/help.rs
  crates/uv/tests/pip_uninstall.rs
Labels: internal

#7941 Clarify project environment creation a little
  docs/concepts/projects.md
Labels: documentation

#7944 fix uninstallation command for windows on documentation
  docs/getting-started/installation.md
Labels: documentation, windows

#7946 Clearly specify the minimum supported Windows Server version in the document
  docs/reference/platforms.md
Labels: windows

#7942 Add failing `uv add --dev` self-reference test
  crates/uv/tests/edit.rs
Labels: testing

#7943 Allow self-depedencies in the `dev` section
  crates/uv/src/commands/project/add.rs
  crates/uv/tests/edit.rs
Labels: bug

#7781 Metadata transformation for the build backend
  Cargo.lock
  Cargo.toml
  crates/uv-build-backend/Cargo.toml
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/metadata.rs
  crates/uv-build-backend/src/pep639_glob.rs
  crates/uv-pypi-types/src/metadata/metadata23.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/build_backend.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/lib.rs
Labels: preview

#7961 Implement build backend metadata
  Cargo.lock
  crates/uv-build-backend/Cargo.toml
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/metadata.rs
  crates/uv/src/commands/build_backend.rs
  crates/uv/src/lib.rs
Labels: preview

#7948 Add Python 3.13 classifier
  pyproject.toml
Labels: releases

#7975 Fix parsing of `gnueabi` libc variants in Python version requests
  crates/uv-python/src/platform.rs
Labels: bug

#7971 Add 3.13 support to the platform reference
  docs/reference/platforms.md
Labels: documentation

#7966 Basic functional build backend wheels
  Cargo.lock
  crates/uv-build-backend/Cargo.toml
  crates/uv-build-backend/src/lib.rs
  crates/uv/tests/build_backend.rs
  crates/uv/tests/common/mod.rs
Labels: preview

#7972 Bump patch Python versions for project
  .python-versions
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/venv.rs
  docs/guides/scripts.md
Labels: internal, testing

#7928 Show interpreter source during Python discovery query errors
  crates/uv-python/src/discovery.rs
Labels: error messages

#7984 Show verbose logs during smoke test
  .github/workflows/ci.yml
Labels: internal, testing

#7982 Show verbose output during integration tests
  .github/workflows/ci.yml
Labels: internal, testing

#7989 Remove `PythonPreference` toggle based on `UV_TEST_PYTHON_PATH`
  crates/uv-python/src/discovery.rs
  crates/uv/src/settings.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/python_find.rs
  crates/uv/tests/python_pin.rs
  crates/uv/tests/show_settings.rs
Labels: internal

#7991 Bump version to 0.4.19
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#7979 Fix problems with build backend metadata files
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/metadata.rs
Labels: preview

#8000 Fix and improve GitLab integration docs
  docs/guides/integration/gitlab.md
Labels: documentation

#7980 Build backend: Logging and more checks
  crates/uv-build-backend/src/lib.rs
Labels: preview

#7986 Check consistency between prepare and build step
  crates/uv-build-backend/src/lib.rs
  crates/uv/src/commands/build_backend.rs
Labels: preview

#8010 Add managed downloads for CPython 3.13.0 final
  crates/uv-python/download-metadata.json
  crates/uv-python/src/downloads.inc
Labels: enhancement

#7882 Add snapshot testing to contribution guide
  CONTRIBUTING.md
Labels: documentation

#8016 Bump version to 0.4.20
  CHANGELOG.md
  Cargo.lock
  crates/uv-build-backend/src/lib.rs
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#8018 Some changelog touchups
  CHANGELOG.md
Labels: internal

#8020 Add prerelease compatibility check
  crates/uv-python/src/discovery.rs
  crates/uv-python/src/downloads.inc
  crates/uv-python/src/downloads.inc.mustache
  crates/uv-python/src/downloads.rs
  crates/uv-python/src/installation.rs
  crates/uv-python/src/interpreter.rs
  crates/uv-python/template-download-metadata.py
Labels: bug

#7695 Add note about `uvx` to `uv tool run` short help
  crates/uv-cli/src/lib.rs
Labels: cli

#8021 Bump netrc crate to latest commit
  Cargo.lock
  Cargo.toml
Labels: bug, windows

#8012 Avoid deleting a project environment directory if we cannot tell if a `pyvenv.cfg` file exists
  crates/uv/src/commands/project/mod.rs
Labels: bug

#8038 Remove the newly created tool environment if sync failed
  crates/uv/src/commands/tool/install.rs
  crates/uv/tests/tool_install.rs
Labels: bug

#8043 Add codeberg integration test for uv publish
  .github/workflows/ci.yml
  scripts/publish/test_publish.py
Labels: internal

#8044 Support `pip install --exact`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/pip_install.rs
  docs/reference/cli.md
Labels: enhancement, cli

#8006 fix: Improve compatibility with VSCode PS1 prompt
  crates/uv-virtualenv/src/activator/activate
Labels: bug

#7819 docs(dependency-bots): mention PEP 723 + some improvements
  docs/guides/integration/dependency-bots.md
Labels: documentation

#8049 Enable HTTP/2 in reqwest
  Cargo.lock
  Cargo.toml
Labels: enhancement

#8055 chore(renovate): move out of deprecated options
  .github/renovate.json5
Labels: internal

#7897 Fix handling of != intersections in `requires-python`
  crates/uv-resolver/src/requires_python.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/sync.rs
Labels: bug

#8060 Add gap-preserving range-to-PEP 440 routine
  Cargo.toml
  crates/uv-pep440/src/version_specifier.rs
  crates/uv-resolver/src/requires_python.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/sync.rs
Labels: enhancement

#6721 document --reinstall with --exclude-newer to ensure downgrades
  docs/concepts/resolution.md
Labels: documentation

#8061 Use comma-separated values for `UV_FIND_LINKS`
  crates/uv-cli/src/lib.rs
  docs/configuration/environment.md
Labels: bug

#8056 Fix `uv python pin 3.13t` failure when parsing version for project requires check
  crates/uv-python/src/discovery.rs
  crates/uv/src/commands/python/pin.rs
  crates/uv/tests/python_pin.rs
Labels: bug

#8077 Avoid verbose warnings for non-existent cache keys
  crates/uv-cache-info/src/cache_info.rs
Labels: tracing

#8081 Update pip compatibility guide to note transitive URL dependency support
  docs/pip/compatibility.md
Labels: documentation

#8078 Downgrade installer verbose logging to trace
  crates/uv-install-wheel/src/linker.rs
  crates/uv-install-wheel/src/uninstall.rs
Labels: tracing

#8053 fix bug where MarkerTree::is_disjoint was sometimes not commutative
  crates/uv-pep508/src/marker/algebra.rs
  crates/uv-pep508/src/marker/tree.rs
Labels: bug

#8083 Treat resolver failures as fatal in lockfile validation
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/lock.rs
Labels: bug

#8096 Support `uv export --no-header`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/export.rs
  docs/reference/cli.md
Labels: enhancement

#8101 Use `git config --get` for author information for improved backwards compatibility
  crates/uv/src/commands/project/init.rs
Labels: bug

#6375 feat: Support remote scripts with `uv run`
  crates/uv-cli/src/lib.rs
  crates/uv/Cargo.toml
  crates/uv/src/lib.rs
  crates/uv/tests/run.rs
  docs/reference/cli.md
Labels: enhancement

#8105 ci(docker): support python 3.13 images
  .github/workflows/build-docker.yml
  docs/guides/integration/docker.md
Labels: enhancement

#8112 Use `--with-requirements` in `uvx` error hint
  crates/uv-requirements/src/sources.rs
  crates/uv/src/lib.rs
Labels: error messages

#8111 Support PEP 723 metadata with `uv run -`
  crates/uv-scripts/src/lib.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/lib.rs
  crates/uv/tests/run.rs
Labels: enhancement

#8113 Use separate types for stdin vs. file-based PEP 723 scripts
  crates/uv-scripts/src/lib.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/lib.rs
Labels: internal

#8114 Encapsulate tempfile within `uv run`
  crates/uv-scripts/src/lib.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/lib.rs
  crates/uv/tests/run.rs
Labels: internal

#8117 Use a single error type for `uv-requirements`
  crates/uv-requirements/src/extras.rs
  crates/uv-requirements/src/lib.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/tool/run.rs
Labels: internal

#8115 Capitalize error messages from lockfile
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_source_ambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_source_version_ambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_version_ambiguous.snap
  crates/uv/tests/lock.rs
  crates/uv/tests/sync.rs
Labels: error messages

#7909 feat: add comma value-delimiter to with argument in tool run args to allow for multiple arguments in with flag
  crates/uv-cli/src/lib.rs
  crates/uv/tests/tool_run.rs
Labels: cli

#8125 Keep the instructions for the Windows standalone installer consistent across the README and the documentation.
  README.md
Labels: documentation

#8140 Avoid excluding valid wheels for exact `requires-python` bounds
  crates/uv-resolver/src/requires_python.rs
  crates/uv-resolver/src/requires_python/tests.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#8143 Fix typos in --no-... option names in no-op warnings
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/init.rs
  crates/uv/src/commands/project/remove.rs
Labels: bug

#8142 Update dependencies.md with typo fix (stands -> standards)
  docs/concepts/dependencies.md
Labels: documentation

#8052 Support for wildcard in UV_INSECURE_HOST
  crates/uv-configuration/src/trusted_host.rs
  crates/uv-configuration/src/trusted_host/tests.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_sync.rs
  crates/uv/tests/it/show_settings.rs
  crates/uv/tests/it/sync.rs
Labels: configuration

#8109 Implement `uv tree --no-dev`
  crates/uv-cli/src/lib.rs
  crates/uv-resolver/src/lock/tree.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/tree.rs
  docs/reference/cli.md
Labels: cli

#8147 Use shared index when fetching metadata in lock satisfaction routine
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/it/lock.rs
Labels: performance

#8145 Improve major-minor bounds on requires-python
  crates/uv-resolver/src/requires_python.rs
  crates/uv-resolver/src/requires_python/tests.rs
Labels: internal

#8146 Use shared resolver state between add and lock
  crates/uv-once-map/src/lib.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
Labels: bug

#8065 Use `uv publish` to publish itself
  .github/workflows/publish-pypi.yml
Labels: internal

#8150 docs: correct typo in `index.md`
  docs/index.md
Labels: documentation

#8174 Fix mkdocs workflow
  .github/workflows/ci.yml
Labels: internal

#8180 Fix error message consistency for broken virtual environments due to `pyvenv.cfg`
  crates/uv-install-wheel/src/lib.rs
  crates/uv-python/src/virtualenv.rs
Labels: error messages

#8179 Include `uvx` installation in Docker examples
  docs/guides/integration/docker.md
  docs/guides/integration/fastapi.md
Labels: documentation

#8182 Disable `cargo xwin clippy` in trampoline job
  .github/workflows/ci.yml
Labels: internal

#8187 fix(ci): adjust xwin timeout and revert xwin jobs being disabled
  .github/workflows/ci.yml
Labels: internal

#8100 Add support for managed installs of free-threaded Python
  .github/workflows/ci.yml
  crates/uv-python/download-metadata.json
  crates/uv-python/fetch-download-metadata.py
  crates/uv-python/src/discovery.rs
  crates/uv-python/src/downloads.inc
  crates/uv-python/src/downloads.inc.mustache
  crates/uv-python/src/downloads.rs
  crates/uv-python/src/installation.rs
  crates/uv-python/src/interpreter.rs
  crates/uv-python/src/managed.rs
  crates/uv-python/template-download-metadata.py
  crates/uv/src/commands/python/install.rs
Labels: enhancement

#8188 Bump version to v0.4.21
  CHANGELOG.md
  Cargo.lock
  crates/uv-build-backend/src/tests.rs
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#8171 Add bad backtracking test cases
  scripts/requirements/backtracking/apache-beam-dill.in
  scripts/requirements/backtracking/numpy-numba.in
  scripts/requirements/backtracking/numpy-sparse.in
  scripts/requirements/backtracking/sentry.in
  scripts/requirements/backtracking/starlette-fastapi.in
Labels: internal, resolver

#8191 Do not use free-threaded interpreters without a free-threaded request
  crates/uv-python/src/discovery.rs
Labels: bug

#8192 Don't recommend `--prerelease=allow` for source dist builds
  crates/uv-dispatch/src/lib.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/options.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/src/lib.rs
  crates/uv/tests/it/pip_install.rs
Labels: bug, error messages

#8158 Support interactive input in `uv publish`
  Cargo.lock
  crates/uv-console/src/lib.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/publish.rs
Labels: preview

#8045 Publish: Password requires username
  crates/uv/src/commands/publish.rs
Labels: bug

#8205 Mock uv version in build backend tests
  Cargo.lock
  crates/uv-build-backend/Cargo.toml
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/metadata.rs
  crates/uv-build-backend/src/metadata/tests.rs
  crates/uv-build-backend/src/tests.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/build_backend.rs
Labels: internal

#8193 chore(uv): more env var mappings
  crates/uv-cli/Cargo.toml
  crates/uv-cli/build.rs
Labels: internal

#8196 Prefer optimized builds for freethreaded Python downloads
  crates/uv-python/download-metadata.json
  crates/uv-python/fetch-download-metadata.py
  crates/uv-python/src/downloads.inc
Labels: bug

#8204 Publish: Workaround using raw filename
  crates/uv-publish/src/lib.rs
  crates/uv-publish/src/tests.rs
  crates/uv/src/commands/publish.rs
Labels: bug, preview

#8211 Publish: Better message for missing password
  crates/uv/src/commands/publish.rs
Labels: enhancement, preview

#7172 Respect `[tool.uv.sources]` in build requirements
  Cargo.lock
  crates/uv-build-frontend/Cargo.toml
  crates/uv-build-frontend/src/error.rs
  crates/uv-build-frontend/src/lib.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/src/lib.rs
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-distribution/src/metadata/mod.rs
  crates/uv-distribution/src/metadata/requires_dist.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-types/src/traits.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/tests/it/sync.rs
  docs/concepts/dependencies.md
  docs/guides/publish.md
Labels: enhancement

#8222 Fix AWS CodeArtifact UV_PUBLISH_URL
  docs/guides/integration/alternative-indexes.md
Labels: documentation, preview

#8216 Retain old python-build-standalone releases
  crates/uv-python/download-metadata.json
  crates/uv-python/fetch-download-metadata.py
  crates/uv-python/src/downloads.inc
Labels: bug

#8220 Run `uv build` builds in the source distribution bucket
  crates/uv-cache/src/lib.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/tests/it/build.rs
Labels: bug

#8224 Reuse the result of `which git`
  Cargo.lock
  crates/uv-git/Cargo.toml
  crates/uv-git/src/git.rs
  crates/uv-git/src/lib.rs
  crates/uv/src/commands/project/init.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_install.rs
Labels: performance

#7481 Add support for named and explicit indexes
  Cargo.lock
  crates/uv-cli/src/lib.rs
  crates/uv-cli/src/options.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution-types/src/index.rs
  crates/uv-distribution-types/src/index_url.rs
  crates/uv-distribution-types/src/lib.rs
  crates/uv-distribution-types/src/resolution.rs
  crates/uv-distribution/src/index/registry_wheel_index.rs
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-distribution/src/metadata/requires_dist.rs
  crates/uv-installer/src/plan.rs
  crates/uv-pep508/src/verbatim_url.rs
  crates/uv-pypi-types/src/requirement.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/resolver/indexes.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv-scripts/Cargo.toml
  crates/uv-scripts/src/lib.rs
  crates/uv-settings/src/settings.rs
  crates/uv-workspace/Cargo.toml
  crates/uv-workspace/src/pyproject.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv-workspace/src/workspace/tests.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/show_settings.rs
  crates/uv/tests/it/sync.rs
  docs/concepts/dependencies.md
  docs/configuration/environment.md
  docs/configuration/index.md
  docs/configuration/indexes.md
  docs/pip/compatibility.md
  docs/reference/cli.md
  docs/reference/settings.md
  mkdocs.template.yml
  uv.schema.json
Labels: enhancement

#7741 Enable environment variable authentication for named indexes
  Cargo.lock
  crates/uv-auth/src/credentials.rs
  crates/uv-auth/src/lib.rs
  crates/uv-distribution-types/Cargo.toml
  crates/uv-distribution-types/src/index.rs
  crates/uv-distribution-types/src/index_url.rs
  crates/uv-distribution/src/index/registry_wheel_index.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/venv.rs
  crates/uv/tests/it/lock.rs
  docs/configuration/indexes.md
Labels: registry, security

#7746 Add index URLs when provided via `uv add --index` or `--default-index`
  crates/uv-cli/src/lib.rs
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/lock.rs
Labels: enhancement, cli

#7769 Allow multiple pinned indexes in `tool.uv.sources`
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/fork_indexes.rs
  crates/uv-resolver/src/fork_urls.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv-resolver/src/resolver/batch_prefetch.rs
  crates/uv-resolver/src/resolver/fork_map.rs
  crates/uv-resolver/src/resolver/index.rs
  crates/uv-resolver/src/resolver/indexes.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-workspace/src/pyproject.rs
  crates/uv/tests/it/lock.rs
  docs/concepts/dependencies.md
  docs/configuration/indexes.md
Labels: enhancement

#8230 Invalid cache when adding lower bound to lockfile
  crates/uv/src/commands/project/add.rs
Labels: bug

#7747 Pin named indexes in `uv add`
  crates/uv-workspace/src/pyproject.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/tests/it/edit.rs
Labels: enhancement, cli

#7910 Respect named `--index` and `--default-index` values in `tool.uv.sources`
  crates/uv-build-frontend/src/lib.rs
  crates/uv-cli/src/lib.rs
  crates/uv-cli/src/options.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution-types/src/index.rs
  crates/uv-distribution-types/src/lib.rs
  crates/uv-distribution-types/src/origin.rs
  crates/uv-distribution-types/src/pip_index.rs
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-distribution/src/metadata/mod.rs
  crates/uv-distribution/src/metadata/requires_dist.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-settings/src/combine.rs
  crates/uv-settings/src/settings.rs
  crates/uv-types/src/traits.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/show_settings.rs
Labels: enhancement

#8234 Avoid showing lower-bound warning outside of explicit lock and sync
  crates/uv-bench/benches/uv.rs
  crates/uv-build-frontend/src/lib.rs
  crates/uv-configuration/src/bounds.rs
  crates/uv-configuration/src/lib.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/src/lib.rs
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-distribution/src/metadata/mod.rs
  crates/uv-distribution/src/metadata/requires_dist.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-types/src/traits.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/commands/venv.rs
  crates/uv/tests/it/edit.rs
Labels: error messages

#8235 Ignore sources in build requirements for non-source trees
  crates/uv-distribution/src/source/mod.rs
Labels: bug

#8233 chore(uv): update env vars map to include newly added ones
  Cargo.lock
  crates/uv-auth/Cargo.toml
  crates/uv-auth/src/credentials.rs
  crates/uv-cli/src/lib.rs
  crates/uv-static/src/env_vars.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_install.rs
Labels: internal

#8237 Respect relative paths in `uv build` sources
  crates/uv-build-frontend/src/lib.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-types/src/traits.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/tests/it/build.rs
Labels: bug

#8249 Make rkyv optional in pep440-rs
  Cargo.toml
  crates/uv-pep440/Cargo.toml
  crates/uv-pep440/src/version.rs
  crates/uv-pep440/src/version_specifier.rs
Labels: internal

#8243 docs: remove "Only a single source may be defined for each dependency"
  docs/concepts/dependencies.md
Labels: documentation

#8250 Fix flaky test in `build.rs`
  crates/uv/tests/it/build.rs
Labels: testing

#8226 Avoid writing duplicate index URLs with `--emit-index-url`
  crates/uv/src/commands/pip/compile.rs
  crates/uv/tests/it/pip_compile.rs
Labels: bug

#8254 Update to hyper v1.5.0
  Cargo.lock
Labels: internal

#8259 Allow users to incorporate Git tags into dynamic cache keys
  crates/uv-cache-info/src/cache_info.rs
  crates/uv-cache-info/src/commit_info.rs
  crates/uv-cache-info/src/git_info.rs
  crates/uv-cache-info/src/lib.rs
  crates/uv-settings/src/settings.rs
  docs/concepts/cache.md
  docs/reference/settings.md
  uv.schema.json
Labels: enhancement

#8245 Update PubGrub
  Cargo.lock
  Cargo.toml
  crates/uv/tests/it/pip_install_scenarios.rs
Labels: enhancement

#8256 Respect index priority when storing credentials
  crates/uv-distribution-types/src/index_url.rs
  crates/uv-distribution/src/index/registry_wheel_index.rs
  crates/uv-resolver/src/lock/mod.rs
Labels: bug

#8264 Show hint in resolution failure on `Forbidden` (`403`) or `Unauthorized` (`401`)
  Cargo.lock
  Cargo.toml
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution-types/Cargo.toml
  crates/uv-distribution-types/src/index_url.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_install.rs
Labels: error messages

#7937 Add upgrade note to README
  README.md
Labels: documentation

#8240 Improve styling of `requires-python` warnings
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/it/lock.rs
Labels: tracing

#8239 Fix selection of free-threaded interpreters during default Python discovery
  .github/workflows/ci.yml
  crates/uv-python/src/discovery.rs
Labels: bug

#8270 Update to `cargo-dist` v0.23.0
  .github/workflows/release.yml
  Cargo.toml
  docs/getting-started/installation.md
Labels: releases

#8104 Add support for reading PEP 735 dependency groups
  crates/uv-workspace/src/pyproject.rs
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv-workspace/src/workspace/tests.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/settings.rs
Labels: internal, compatibility

#8273 Narrow what the pip3.<minor> logic drops from entry points.
  crates/uv-install-wheel/src/script.rs
Labels: bug

#8277 Update Saleor ecosystem snapshot
  crates/uv/tests/it/snapshots/it__ecosystem__saleor-lock-file.snap
Labels: testing

#8278 Fix test fixtures to reflect installer new error messages
  crates/uv/tests/it/build.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/pip_sync.rs
  crates/uv/tests/it/sync.rs
  crates/uv/tests/it/tool_install.rs
Labels: testing
