Repository astral-sh/uv, pull requests merged in 2024-05, with the labels that each got.

#2548 Allow `--force` to overwrite existing virtualenv
  crates/uv-build/src/lib.rs
  crates/uv-fs/src/lib.rs
  crates/uv-virtualenv/src/bare.rs
  crates/uv-virtualenv/src/lib.rs
  crates/uv-virtualenv/src/main.rs
  crates/uv/src/cli.rs
  crates/uv/src/commands/run.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
  crates/uv/tests/venv.rs
Labels: enhancement, cli

#3328 Accept `--no-upgrade`, `--no-refresh`, etc. on the CLI
  crates/uv-cache/src/lib.rs
  crates/uv-configuration/src/package_options.rs
  crates/uv/src/cli.rs
  crates/uv/src/settings.rs
Labels: cli

#3336 Add missing optional rkyv feature bound
  crates/distribution-filename/Cargo.toml
Labels: internal

#3337 Remove `Into::into`
  crates/pypi-types/src/simple_json.rs
Labels: internal

#3329 Move `py` launcher handling into separate module
  crates/uv-interpreter/src/find_python.rs
  crates/uv-interpreter/src/lib.rs
  crates/uv-interpreter/src/py_launcher.rs
Labels: internal

#3330 Update toolchain discovery to avoid runtime panic
  crates/uv-dev/src/fetch_python.rs
  crates/uv-interpreter/src/managed/find.rs
Labels: internal

#3332 Separate interpreter selectors into `implementation` and `platform` modules
  crates/uv-interpreter/src/implementation.rs
  crates/uv-interpreter/src/lib.rs
  crates/uv-interpreter/src/managed/downloads.rs
  crates/uv-interpreter/src/managed/find.rs
  crates/uv-interpreter/src/platform.rs
Labels: internal

#3331 Split virtual environment detection into a dedicated module
  crates/uv-interpreter/src/environment.rs
  crates/uv-interpreter/src/environment/cfg.rs
  crates/uv-interpreter/src/environment/mod.rs
  crates/uv-interpreter/src/environment/virtualenv.rs
  crates/uv-interpreter/src/find_python.rs
  crates/uv-interpreter/src/interpreter.rs
  crates/uv-interpreter/src/lib.rs
  crates/uv-interpreter/src/virtualenv.rs
  crates/uv-virtualenv/src/bare.rs
Labels: internal

#3345 require serde and rkyv everywhere; remove optional serde and rkyv features
  crates/distribution-filename/Cargo.toml
  crates/distribution-filename/src/source_dist.rs
  crates/distribution-filename/src/wheel.rs
  crates/distribution-types/Cargo.toml
  crates/pep440-rs/Cargo.toml
  crates/pep440-rs/src/version.rs
  crates/pep440-rs/src/version_specifier.rs
  crates/pep508-rs/Cargo.toml
  crates/pep508-rs/src/lib.rs
  crates/pep508-rs/src/marker.rs
  crates/pep508-rs/src/unnamed.rs
  crates/pep508-rs/src/verbatim_url.rs
  crates/platform-tags/Cargo.toml
  crates/pypi-types/Cargo.toml
  crates/requirements-txt/Cargo.toml
  crates/uv-build/Cargo.toml
  crates/uv-client/Cargo.toml
  crates/uv-configuration/Cargo.toml
  crates/uv-configuration/src/authentication.rs
  crates/uv-configuration/src/build_options.rs
  crates/uv-configuration/src/config_settings.rs
  crates/uv-configuration/src/name_specifiers.rs
  crates/uv-configuration/src/target_triple.rs
  crates/uv-distribution/Cargo.toml
  crates/uv-interpreter/Cargo.toml
  crates/uv-normalize/Cargo.toml
  crates/uv-normalize/src/extra_name.rs
  crates/uv-normalize/src/package_name.rs
  crates/uv-resolver/Cargo.toml
  crates/uv-resolver/src/exclude_newer.rs
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/prerelease_mode.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv-resolver/src/resolution_mode.rs
  crates/uv-workspace/Cargo.toml
Labels: internal, rustlib

#3361 Update Rust to v1.78
  crates/platform-tags/src/tags.rs
  crates/uv-build/src/lib.rs
  crates/uv-cache/src/lib.rs
  crates/uv-configuration/src/build_options.rs
  crates/uv-configuration/src/target_triple.rs
  crates/uv-resolver/src/pubgrub/package.rs
  crates/uv/src/shell.rs
  crates/uv/tests/pip_compile.rs
  rust-toolchain.toml
  uv.schema.json
Labels: internal

#3362 Unset target when creating virtual environments
  crates/uv-interpreter/src/interpreter.rs
  crates/uv/tests/pip_sync.rs
Labels: bug

#3363 Respect `editable = true` setting in sources map
  Cargo.lock
  crates/distribution-types/src/requirement.rs
  crates/uv-requirements/Cargo.toml
  crates/uv-requirements/src/specification.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#3364 Tweak some of the `tool.uv.sources` error messages for consistency
  crates/distribution-types/src/requirement.rs
  crates/uv-requirements/src/pyproject.rs
  uv.schema.json
Labels: error messages

#3277 Use preview mode for tool.uv.sources
  crates/uv-requirements/src/pyproject.rs
  crates/uv-requirements/src/specification.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/src/commands/pip_uninstall.rs
  crates/uv/src/commands/run.rs
  crates/uv/src/main.rs
  crates/uv/tests/pip_install.rs
Labels: preview

#3365 Fix Git URL construction in `tool.uv.sources`
  crates/uv-requirements/src/pyproject.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#3373 Use canonical URLs in satisfaction check
  Cargo.lock
  crates/uv-installer/Cargo.toml
  crates/uv-installer/src/satisfies.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#3374 Add branch and tag variants to Git reference
  crates/uv-git/src/git.rs
  crates/uv-git/src/lib.rs
  crates/uv-requirements/src/pyproject.rs
  crates/uv/tests/pip_compile.rs
Labels: internal, preview

#3376 Update activation scripts from virtualenv
  Cargo.lock
  crates/uv-virtualenv/Cargo.toml
  crates/uv-virtualenv/src/activator/activate.fish
  crates/uv-virtualenv/src/activator/activate.ps1
  crates/uv-virtualenv/src/activator/activate_this.py
  crates/uv-virtualenv/src/bare.rs
Labels: bug

#3377 Use `Cow` for source call
  crates/distribution-types/src/specified_requirement.rs
  crates/uv-installer/src/site_packages.rs
Labels: internal

#3379 Detect current venv when `uv` is invoked from within a virtualenv
  crates/uv-interpreter/src/virtualenv.rs
Labels: bug

#3382 Add `UV_CUSTOM_COMPILE_COMMAND` to environment variable docs
  README.md
Labels: documentation

#3399 Make pubgrub an allowed ident
  clippy.toml
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/pubgrub/package.rs
  crates/uv-resolver/src/pubgrub/priority.rs
  crates/uv-resolver/src/pubgrub/specifier.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/src/shell.rs
Labels: internal

#3398 Better error for unsupported Python version
  crates/uv-interpreter/python/get_interpreter_info.py
  crates/uv-interpreter/src/find_python.rs
  crates/uv-interpreter/src/interpreter.rs
Labels: error messages

#3401 Move pep508-rs `Cursor` into its own module
  crates/pep508-rs/src/cursor.rs
  crates/pep508-rs/src/lib.rs
  crates/pep508-rs/src/marker.rs
  crates/pep508-rs/src/unnamed.rs
Labels: internal

#3403 Improve non-git error message
  crates/distribution-types/src/parsed_url.rs
  crates/distribution-types/src/requirement.rs
  crates/distribution-types/src/specified_requirement.rs
  crates/requirements-txt/src/lib.rs
  crates/uv-build/src/lib.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/pyproject.rs
  crates/uv-resolver/src/preferences.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/tests/pip_compile.rs
Labels: preview

#3406 Revise comment on virtualenv discovery from cwd
  crates/uv-interpreter/src/virtualenv.rs
Labels: internal

#3254 Rename `distribution_types::VersionOrUrl` to `VersionOrUrlRef`
  crates/distribution-types/src/cached.rs
  crates/distribution-types/src/installed.rs
  crates/distribution-types/src/lib.rs
  crates/distribution-types/src/resolved.rs
  crates/distribution-types/src/traits.rs
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/pubgrub/distribution.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/reporter.rs
  crates/uv/src/commands/reporters.rs
Labels: internal

#3413 Remove unnecessary uses of `DashMap` and `Arc`
  crates/uv-build/src/lib.rs
  crates/uv-client/src/cached_client.rs
  crates/uv-client/src/flat_index.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/locks.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-installer/src/downloader.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/source_tree.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv-resolver/src/resolver/index.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv-types/src/traits.rs
Labels: internal

#3415 List and uninstall legacy editables
  PIP_COMPATIBILITY.md
  crates/distribution-types/src/installed.rs
  crates/install-wheel-rs/src/lib.rs
  crates/install-wheel-rs/src/uninstall.rs
  crates/uv-installer/src/site_packages.rs
  crates/uv-installer/src/uninstall.rs
  crates/uv/src/commands/pip_freeze.rs
  crates/uv/tests/pip_freeze.rs
  crates/uv/tests/pip_list.rs
  crates/uv/tests/pip_uninstall.rs
Labels: enhancement, compatibility

#3412 Preserve given for `tool.uv.sources` paths
  crates/uv-requirements/src/pyproject.rs
  crates/uv/tests/pip_compile.rs
Labels: bug, preview

#3418 Add hint to use a venv to `pip sync --user`
  crates/uv/src/compat/mod.rs
Labels: error messages

#3253 Make `Requirement` generic over url type
  crates/distribution-types/src/lib.rs
  crates/pep508-rs/src/cursor.rs
  crates/pep508-rs/src/lib.rs
  crates/pep508-rs/src/marker.rs
  crates/pep508-rs/src/unnamed.rs
  crates/pep508-rs/src/verbatim_url.rs
  crates/pypi-types/src/lenient_requirement.rs
  crates/pypi-types/src/metadata.rs
Labels: internal

#3424 add compat arg --user error message to pip install
  crates/uv/src/cli.rs
  crates/uv/src/compat/mod.rs
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
Labels: error messages

#3428 Always activate non-pep508-extensions
  Cargo.toml
  crates/requirements-txt/Cargo.toml
  crates/uv-interpreter/Cargo.toml
Labels: internal

#3416 Rename `--force` to `--allow-existing`
  crates/uv-fs/src/lib.rs
  crates/uv-virtualenv/src/bare.rs
  crates/uv-virtualenv/src/lib.rs
  crates/uv/src/cli.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
  crates/uv/tests/venv.rs
Labels: cli

#3433 Bump version to v0.1.40
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: release

#3431 Use top-level `--isolated` for `uv run`
  crates/uv/src/cli.rs
  crates/uv/src/commands/run.rs
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
Labels: cli, preview

#3434 Move PyO3 derive down
  crates/pep508-rs/src/marker.rs
Labels: internal

#3443 Remove unconstrained version error from requirements
  crates/uv-requirements/src/pyproject.rs
Labels: bug

#3446 Bump version to v0.1.41
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: release

#3448 Remove some `allow(unused)`
  crates/uv/src/commands/mod.rs
Labels: internal

#3335 Use generic pubgrub incompatibility reason
  Cargo.lock
  Cargo.toml
  crates/distribution-types/src/prioritized_distribution.rs
  crates/uv-resolver/src/dependency_provider.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_install_scenarios.rs
  crates/uv/tests/pip_sync.rs
Labels: error messages

#3453 Improve trailing version string error message
  crates/pep440-rs/src/version.rs
  crates/pep440-rs/src/version_specifier.rs
  crates/uv/tests/pip_list.rs
Labels: error messages

#3460 Upgrade `async_http_range_reader` to v0.8.0
  Cargo.lock
  Cargo.toml
  crates/uv-client/src/registry_client.rs
Labels: bug

#3461 Improve JSON Schema and add export script
  crates/distribution-types/src/index_url.rs
  crates/uv-configuration/src/name_specifiers.rs
  crates/uv-configuration/src/target_triple.rs
  crates/uv-interpreter/src/python_version.rs
  crates/uv-normalize/src/extra_name.rs
  crates/uv-normalize/src/package_name.rs
  crates/uv-requirements/src/pyproject.rs
  crates/uv-resolver/src/exclude_newer.rs
  scripts/update_schemastore.py
  uv.schema.json
Labels: configuration

#3465 Ignore `compile_invalid_pyc_invalidation_mode` on macOS
  crates/uv/tests/pip_sync.rs
Labels: testing

#3464 Set stack size for remaining `install` and `sync` tests
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_sync.rs
Labels: testing

#3462 Merge user and workspace settings
  crates/uv-configuration/src/config_settings.rs
  crates/uv-workspace/src/combine.rs
  crates/uv-workspace/src/lib.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/main.rs
Labels: configuration

#3467 Add basic documentation for persistent configuration
  README.md
Labels: documentation, configuration

#3469 Use last non-EOL version for `--python-platform` macOS
  crates/uv-configuration/src/target_triple.rs
  uv.schema.json
Labels: configuration

#3470 Respect `MACOSX_DEPLOYMENT_TARGET` in `--python-platform`
  Cargo.lock
  README.md
  crates/uv-configuration/Cargo.toml
  crates/uv-configuration/src/target_triple.rs
  uv.schema.json
Labels: enhancement, configuration

#3447 Use environment layering for `uv run --with`
  crates/uv/src/commands/workspace/run.rs
  crates/uv/tests/pip_compile.rs
Labels: preview

#3472 Bump version to v0.1.42
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: release

#3269 Annotate sources of requirements
  crates/distribution-types/src/annotation.rs
  crates/distribution-types/src/lib.rs
  crates/distribution-types/src/requirement.rs
  crates/distribution-types/src/resolution.rs
  crates/distribution-types/src/specified_requirement.rs
  crates/pep508-rs/src/lib.rs
  crates/pep508-rs/src/unnamed.rs
  crates/requirements-txt/src/lib.rs
  crates/requirements-txt/src/requirement.rs
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-basic.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-constraints-a.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-constraints-b.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-editable.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-for-poetry.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-include-a.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-include-b.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-poetry-with-hashes.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-small.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-whitespace.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-basic.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-constraints-a.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-constraints-b.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-for-poetry.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-include-a.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-include-b.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-poetry-with-hashes.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-small.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-unix-bare-url.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-whitespace.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-windows-bare-url.txt.snap
  crates/uv-dev/src/resolve_many.rs
  crates/uv-fs/src/path.rs
  crates/uv-installer/src/site_packages.rs
  crates/uv-requirements/src/pyproject.rs
  crates/uv-requirements/src/specification.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_compile_scenarios.rs
Labels: enhancement

#3476 Skip Python 2 versions when locating Python
  crates/uv-interpreter/src/find_python.rs
  crates/uv-interpreter/src/lib.rs
Labels: bug

#3478 Add a dedicated struct for source annotations
  crates/distribution-types/src/annotation.rs
  crates/distribution-types/src/requirement.rs
  crates/pep508-rs/src/lib.rs
  crates/pep508-rs/src/unnamed.rs
  crates/requirements-txt/src/lib.rs
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-basic.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-constraints-a.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-constraints-b.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-editable.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-for-poetry.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-include-a.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-include-b.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-poetry-with-hashes.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-small.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-whitespace.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-basic.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-constraints-a.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-constraints-b.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-for-poetry.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-include-a.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-include-b.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-poetry-with-hashes.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-small.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-unix-bare-url.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-whitespace.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-windows-bare-url.txt.snap
  crates/uv-dev/src/resolve_many.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv/src/commands/pip_compile.rs
Labels: internal

#3479 Filter irrelevant requirements from source annotations
  crates/uv/src/commands/pip_compile.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#3485 Add test case for authenticated index url from requirements file
  crates/uv/tests/pip_install.rs
Labels: testing

#3489 Rebrand workspace API as project API
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
Labels: preview

#3488 Run `cargo update`
  Cargo.lock
Labels: internal

#3494 Discover `uv run` projects hierarchically
  crates/uv-requirements/src/sources.rs
  crates/uv-requirements/src/specification.rs
  crates/uv/src/commands/project/discovery.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
Labels: enhancement, preview

#3495 Use defaults in `RequirementsSpecification` constructors
  crates/uv-requirements/src/specification.rs
Labels: internal

#3496 Read package name from `pyproject.toml` in `uv run`
  crates/uv/src/commands/project/discovery.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
Labels: preview

#3497 Read and write `uv.lock` based on project root
  crates/uv/src/commands/project/discovery.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/sync.rs
Labels: enhancement, preview

#3498 Allow clippy map-unwrap-or
  Cargo.toml
Labels: internal

#3501 Re-add dummy serde feature to pep440-rs and pep508-rs
  crates/pep440-rs/Cargo.toml
  crates/pep508-rs/Cargo.toml
Labels: internal

#3499 Create virtualenv if it doesn't exist in project API
  crates/uv-interpreter/src/environment.rs
  crates/uv-interpreter/src/find_python.rs
  crates/uv-interpreter/src/lib.rs
  crates/uv-interpreter/src/py_launcher.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/pip_sync.rs
Labels: enhancement, preview

#3505 uv-resolver: make hashes optional
  Cargo.lock
  crates/uv-resolver/Cargo.toml
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__hash_required_missing.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__hash_required_present.snap
Labels: internal

#3493 Consolidate concurrency limits
  Cargo.lock
  README.md
  crates/bench/Cargo.toml
  crates/bench/benches/uv.rs
  crates/uv-build/src/lib.rs
  crates/uv-configuration/src/concurrency.rs
  crates/uv-configuration/src/lib.rs
  crates/uv-dev/Cargo.toml
  crates/uv-dev/src/build.rs
  crates/uv-dev/src/resolve_cli.rs
  crates/uv-dev/src/resolve_many.rs
  crates/uv-dispatch/Cargo.toml
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-installer/src/downloader.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/source_tree.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv-resolver/tests/resolver.rs
  crates/uv-workspace/src/combine.rs
  crates/uv-workspace/src/settings.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
  uv.schema.json
Labels: configuration

#3517 Avoid keyword arguments for PEP 517 build hooks
  crates/uv-build/src/lib.rs
Labels: compatibility

#3524 Make cache clearing robust to directories without read permissions
  crates/uv-cache/src/removal.rs
Labels: bug

#3526 Remove unused `seek` methods
  crates/uv-extract/src/lib.rs
  crates/uv-extract/src/seek.rs
Labels: internal

#3533 Get `cargo shear` passing
  Cargo.lock
  Cargo.toml
  crates/bench/Cargo.toml
  crates/uv-dispatch/Cargo.toml
  crates/uv-fs/Cargo.toml
  crates/uv/Cargo.toml
Labels: internal

#3535 Fix `cfg_attr` ignore for macOS
  crates/uv/tests/pip_sync.rs
Labels: testing

#3536 Add HTTPS and SSH hints to scheme error
  crates/distribution-types/src/lib.rs
Labels: error messages

#3521 Add test case for `--only-binary` with editable requirement
  crates/uv/tests/pip_install.rs
Labels: testing

#3519 Make `Directory` its own distribution kind
  crates/distribution-types/src/buildable.rs
  crates/distribution-types/src/cached.rs
  crates/distribution-types/src/lib.rs
  crates/distribution-types/src/resolution.rs
  crates/uv-cache/src/lib.rs
  crates/uv-distribution/src/index/built_wheel_index.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-installer/src/plan.rs
  crates/uv-requirements/src/source_tree.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__hash_optional_missing.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__hash_required_missing.snap
  crates/uv/tests/pip_install.rs
Labels: internal

#3525 Apply advisory locks when building source distributions
  crates/uv-cache/src/lib.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv/tests/pip_sync.rs
Labels: bug

#3550 Increase verbosity of credential fetch logs
  crates/uv-auth/src/middleware.rs
Labels: tracing

#3551 Clone individual files on windows ReFS
  crates/install-wheel-rs/src/linker.rs
Labels: bug, windows

#3552 Rename "constraints" to "dependencies" in resolver
  crates/uv-resolver/src/resolver/mod.rs
Labels: internal

#3553 Add a `PubGrubRequirement` struct
  crates/uv-resolver/src/pubgrub/dependencies.rs
Labels: internal

#3558 Make isolated a global argument
  crates/uv/src/cli.rs
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
Labels: bug, cli

#3561 Add test case demonstrating failure with `--only-binary` and dependent editables
  crates/uv/tests/pip_install.rs
Labels: testing

#3563 Avoid attempting to build editables when fetching metadata
  crates/uv-resolver/src/editables.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#3564 Bump version to v0.1.43
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: release

#3426 Add parsed url to PubGrubPackage
  Cargo.lock
  crates/distribution-types/src/lib.rs
  crates/distribution-types/src/parsed_url.rs
  crates/uv-distribution/src/git.rs
  crates/uv-distribution/src/lib.rs
  crates/uv-git/src/git.rs
  crates/uv-resolver/Cargo.toml
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/pubgrub/distribution.rs
  crates/uv-resolver/src/pubgrub/package.rs
  crates/uv-resolver/src/redirect.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/urls.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_sync.rs
  crates/uv/tests/venv.rs
Labels: internal

#3429 Add parsed URL fields to `Dist` variants
  Cargo.lock
  crates/distribution-types/src/lib.rs
  crates/uv-client/tests/remote_metadata.rs
  crates/uv-dev/src/wheel_metadata.rs
  crates/uv-installer/Cargo.toml
  crates/uv-installer/src/plan.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/unnamed.rs
Labels: internal

#3565 Move `pip` commands into their own module
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/pip/check.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/freeze.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/list.rs
  crates/uv/src/commands/pip/mod.rs
  crates/uv/src/commands/pip/show.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/pip/uninstall.rs
Labels: internal

#3430 Use the term path instead of local file consistently
  crates/distribution-types/src/cached.rs
  crates/distribution-types/src/lib.rs
  crates/distribution-types/src/parsed_url.rs
  crates/distribution-types/src/requirement.rs
  crates/uv-resolver/src/resolver/urls.rs
Labels: internal

#3457 Preserve parsed url in ResolvedDist -> Requirement
  crates/distribution-types/src/requirement.rs
  crates/distribution-types/src/resolution.rs
  crates/uv-installer/src/plan.rs
  crates/uv-installer/src/satisfies.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/pyproject.rs
  crates/uv-resolver/src/resolver/urls.rs
Labels: internal

#3566 Remove unused `installed` field from `Plan`
  crates/uv-dispatch/src/lib.rs
  crates/uv-installer/src/plan.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/mod.rs
Labels: internal

#3458 Reduce `GitSourceDist` URL usage
  crates/distribution-types/src/lib.rs
  crates/uv-distribution/src/index/built_wheel_index.rs
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/redirect.rs
Labels: internal

#3567 Move dry-run method to the top-level
  crates/uv/src/commands/pip/install.rs
Labels: internal

#3568 Unify editable handling between `sync` and `install`
  crates/uv-installer/src/editable.rs
  crates/uv-installer/src/lib.rs
  crates/uv-installer/src/plan.rs
  crates/uv/src/commands/pip/editables.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/mod.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/tests/pip_install.rs
Labels: internal

#3574 Fix typo in traits.rs
  crates/uv-types/src/traits.rs
Labels: documentation

#3580 Reduce sensitivity of unknown option error
  crates/uv-interpreter/src/find_python.rs
Labels: bug

#3581 Explain hash tie-breaking in distribution comparisons
  crates/distribution-types/src/prioritized_distribution.rs
  crates/uv-resolver/src/flat_index.rs
  crates/uv-resolver/src/version_map.rs
Labels: internal

#3582 Remove `pacman` from README
  README.md
Labels: documentation

#3569 Fix install_registry_source_dist_cached on Gentoo
  crates/uv/tests/pip_sync.rs
Labels: testing

#3584 Create lib64 symlink for 64-bit, non-macOS, POSIX environments
  crates/uv-interpreter/python/get_interpreter_info.py
  crates/uv-interpreter/src/interpreter.rs
  crates/uv-interpreter/src/lib.rs
  crates/uv-interpreter/src/pointer_size.rs
  crates/uv-virtualenv/src/bare.rs
Labels: bug, compatibility

#3586 Split extra validation from graph construction
  crates/uv-resolver/src/resolution.rs
Labels: internal

#3590 Rename `sourcedist` to `sdist` in lockfile
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__hash_optional_missing.snap
Labels: preview

#3589 Add hashes and versions to all distributions
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv-resolver/src/resolver/mod.rs
Labels: preview

#3591 Remove some editable branches in resolution
  crates/uv-resolver/src/resolution.rs
Labels: internal

#3592 Move `extras` onto annotated distribution
  crates/uv-resolver/src/resolution.rs
Labels: internal

#3596 Allow local versions in wheel filenames
  crates/install-wheel-rs/src/linker.rs
Labels: compatibility

#3597 Split `resolution.rs` into multiple files
  crates/uv-resolver/src/resolution/display.rs
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv-resolver/src/resolution/mod.rs
Labels: internal

#3603 Respect installed packages in `uv run`
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
Labels: bug, preview

#3605 Remove binary from `uv-virtualenv` crate
  Cargo.lock
  crates/uv-virtualenv/Cargo.toml
  crates/uv-virtualenv/src/main.rs
Labels: internal

#3606 Remove `resolve_cli.rs` and `resolve_many.rs`
  Cargo.lock
  crates/uv-dev/Cargo.toml
  crates/uv-dev/src/main.rs
  crates/uv-dev/src/resolve_cli.rs
  crates/uv-dev/src/resolve_many.rs
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv-resolver/src/resolution/mod.rs
Labels: internal

#3608 Add missing `"directory"` branch in source match
  crates/uv-resolver/src/lock.rs
Labels: bug, preview

#3607 Separate cache construction from initialization
  crates/bench/benches/uv.rs
  crates/uv-cache/src/cli.rs
  crates/uv-cache/src/lib.rs
  crates/uv-client/tests/remote_metadata.rs
  crates/uv-client/tests/user_agent_version.rs
  crates/uv-dev/src/build.rs
  crates/uv-dev/src/compile.rs
  crates/uv-dev/src/wheel_metadata.rs
  crates/uv-interpreter/src/find_python.rs
  crates/uv-interpreter/src/interpreter.rs
  crates/uv-interpreter/src/py_launcher.rs
  crates/uv-resolver/tests/resolver.rs
  crates/uv/src/main.rs
  crates/uv/tests/common/mod.rs
Labels: bug

#3609 Add local path conversions from lockfile
  crates/uv-resolver/src/lock.rs
Labels: preview

#3616 Add `Combine` implementations for non-`Vec` types
  crates/uv-workspace/src/combine.rs
Labels: internal

#3619 Add serialization and deserialization for `--find-links`
  crates/distribution-types/src/index_url.rs
  crates/uv/tests/pip_compile.rs
Labels: bug, configuration

#3623 Add basic tests for lockfile generation
  crates/uv/src/cli.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/tests/lock.rs
Labels: testing

#3622 Discard markers on editable requirements
  crates/requirements-txt/src/lib.rs
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-editable.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-unix-editable.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-windows-editable.txt.snap
  crates/requirements-txt/test-data/requirements-txt/editable.txt
Labels: bug, compatibility

#3629 Parse and store extras on editables
  crates/pep508-rs/src/lib.rs
  crates/requirements-txt/src/lib.rs
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-unix-editable.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-windows-editable.txt.snap
  crates/requirements-txt/test-data/requirements-txt/editable.txt
  crates/uv-requirements/src/specification.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/editables.rs
Labels: enhancement

#3600 feat: move to cargo-xwin for clippy
  .github/workflows/ci.yml
Labels: internal

#3637 Fix source annotation in pip compile `annotation-style=line` output
  crates/uv-resolver/src/resolution/display.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#3627 Parallelize Resolver
  Cargo.lock
  crates/bench/benches/uv.rs
  crates/once-map/Cargo.toml
  crates/once-map/src/lib.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-installer/src/plan.rs
  crates/uv-installer/src/site_packages.rs
  crates/uv-interpreter/src/environment.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/source_tree.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv-resolver/Cargo.toml
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/preferences.rs
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv-resolver/src/resolver/batch_prefetch.rs
  crates/uv-resolver/src/resolver/index.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/tests/resolver.rs
  crates/uv-types/src/traits.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/editables.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
Labels: performance

#3641 Use `FxHasher` in resolver
  crates/once-map/src/lib.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv-resolver/src/resolver/index.rs
  crates/uv-resolver/src/resolver/mod.rs
Labels: internal

#3630 Support lossless serialization for Git dependencies in lockfile
  crates/uv-git/src/sha.rs
  crates/uv-resolver/src/lock.rs
  crates/uv/tests/lock.rs
Labels: preview

#3633 Add direct URL conversion to lockfile
  crates/distribution-types/src/lib.rs
  crates/uv-resolver/src/lock.rs
  crates/uv/tests/lock.rs
Labels: preview

#3647 Use `ParsedGitUrl` to recreate Git source kind URL
  crates/uv-resolver/src/lock.rs
  crates/uv/tests/lock.rs
Labels: internal

#3646 Add `UV_CONCURRENT_INSTALLS` variable in favor of `RAYON_NUM_THREADS`
  Cargo.lock
  README.md
  crates/uv-configuration/src/concurrency.rs
  crates/uv-workspace/src/combine.rs
  crates/uv-workspace/src/settings.rs
  crates/uv/Cargo.toml
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
  uv.schema.json
Labels: configuration

#3649 Add registry source distribution support to lockfile
  crates/uv-resolver/src/lock.rs
  crates/uv/tests/lock.rs
Labels: preview

#3631 Make `from_rev` take an owned value
  crates/uv-git/src/git.rs
  crates/uv-git/src/lib.rs
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/redirect.rs
Labels: internal

#3645 Pin the zip crate to 0.6
  .github/renovate.json5
  Cargo.lock
  Cargo.toml
  crates/install-wheel-rs/src/wheel.rs
Labels: internal, upstream

#3655 URL-decode hashes in HTML fragments
  crates/uv-client/src/html.rs
Labels: bug, compatibility

#3653 Add `UV_CONFIG_FILE` environment variable to documentation
  README.md
  crates/uv/src/cli.rs
Labels: documentation

#3652 Add registry file size to lockfile
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__hash_optional_missing.snap
  crates/uv/tests/lock.rs
Labels: preview

#3656 Track parsed Git URL components in `GitSourceUrl`
  crates/distribution-types/src/buildable.rs
  crates/uv-distribution/src/git.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv-resolver/src/redirect.rs
  crates/uv/tests/pip_compile.rs
Labels: internal

#3666 Explicitly mention `--user` in compatibility guide
  PIP_COMPATIBILITY.md
Labels: documentation

#3659 Move `update_environment` from `run` to the `project` namespace
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
Labels: internal

#3667 Remove subdirectory from direct wheel URL type
  crates/distribution-types/src/lib.rs
  crates/distribution-types/src/parsed_url.rs
  crates/distribution-types/src/resolution.rs
  crates/uv-client/tests/remote_metadata.rs
  crates/uv-dev/src/wheel_metadata.rs
  crates/uv-installer/src/plan.rs
  crates/uv-resolver/src/lock.rs
Labels: internal

#3650 Remove `SourceDistFilename` from `RegistrySourceDist`
  crates/distribution-types/src/buildable.rs
  crates/distribution-types/src/lib.rs
  crates/distribution-types/src/resolution.rs
  crates/distribution-types/src/resolved.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-resolver/src/flat_index.rs
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/version_map.rs
Labels: internal

#3651 Use filename trait for `WheelWire` conversion
  crates/distribution-types/src/error.rs
  crates/distribution-types/src/lib.rs
  crates/uv-installer/src/plan.rs
  crates/uv-resolver/src/lock.rs
Labels: bug

#3618 Apply combination logic to merge CLI and persistent configuration
  crates/uv/src/settings.rs
  crates/uv/tests/pip_compile.rs
Labels: configuration

#3639 Refactor editables for supporting them in bluejay commands
  crates/uv-installer/src/site_packages.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-resolver/src/editables.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/manifest.rs
  crates/uv-resolver/src/resolution/display.rs
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/urls.rs
  crates/uv-types/src/traits.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/mod.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/editables.rs
  crates/uv/src/main.rs
Labels: preview

#3671 Always print JSON output with --format json
  crates/uv/src/commands/pip/list.rs
  crates/uv/tests/pip_list.rs
Labels: bug

#3680 Add rustdoc links to `marker.rs` documentation
  crates/pep508-rs/src/marker.rs
Labels: documentation

#3681 Evaluate arbitrary markers to `false`
  crates/pep508-rs/src/marker.rs
  crates/uv-resolver/src/marker.rs
Labels: bug

#3682 Write relative paths with unnamed requirement syntax
  crates/uv-resolver/src/resolution/display.rs
  crates/uv-resolver/src/resolution/mod.rs
  crates/uv/tests/pip_compile.rs
Labels: compatibility

#3658 Add notes for testing on windows
  CONTRIBUTING.md
Labels: documentation, windows

#3690 Improve `DirWithoutEntrypoint` error message
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/index/built_wheel_index.rs
  crates/uv-distribution/src/source/mod.rs
Labels: error messages

#3691 Better error message for `uv run` failures
  crates/uv/src/commands/project/run.rs
Labels: error messages, preview

#3692 Support editables in `uv sync`
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
Labels: preview

#3688 Arc-wrap `PubGrubPackage` for cheap cloning in pubgrub
  crates/uv-resolver/Cargo.toml
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/pubgrub/mod.rs
  crates/uv-resolver/src/pubgrub/package.rs
  crates/uv-resolver/src/pubgrub/priority.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv-resolver/src/resolver/batch_prefetch.rs
  crates/uv-resolver/src/resolver/mod.rs
Labels: performance
