Repository astral-sh/uv, pull requests merged in 2024-06, with the labels that each got.

#3954 Add Git resolver in lieu of static hash map
  Cargo.lock
  crates/bench/Cargo.toml
  crates/bench/benches/uv.rs
  crates/uv-dev/Cargo.toml
  crates/uv-dev/src/build.rs
  crates/uv-dispatch/Cargo.toml
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/Cargo.toml
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/git.rs
  crates/uv-distribution/src/lib.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-git/Cargo.toml
  crates/uv-git/src/lib.rs
  crates/uv-git/src/resolver.rs
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/redirect.rs
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/urls.rs
  crates/uv-resolver/tests/resolver.rs
  crates/uv-types/Cargo.toml
  crates/uv-types/src/traits.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/venv.rs
Labels: internal

#3956 Respect resolved Git SHAs in `uv lock`
  crates/uv-git/src/lib.rs
  crates/uv-git/src/resolver.rs
  crates/uv-requirements/src/upgrade.rs
  crates/uv-resolver/src/lock.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/lock.rs
Labels: enhancement, preview

#3961 Move reference check into `uv-git`
  crates/uv-git/src/resolver.rs
  crates/uv-resolver/src/resolver/urls.rs
Labels: internal

#3962 Remove some `anyhow` usages
  crates/distribution-types/src/lib.rs
  crates/distribution-types/src/traits.rs
  crates/uv-client/tests/user_agent_version.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-git/src/resolver.rs
  crates/uv-installer/src/uninstall.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv-resolver/src/pubgrub/specifier.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv/src/commands/pip/operations.rs
Labels: internal

#3866 Draft for user docs for workspaces
  docs/workspaces.md
Labels: documentation, preview

#3963 fix: add missing ppc64le alias for powerpc64le
  crates/platform-tags/src/platform.rs
Labels: bug

#3864 Add `uv run --package`
  Cargo.lock
  crates/uv-distribution/src/workspace.rs
  crates/uv-installer/Cargo.toml
  crates/uv-installer/src/plan.rs
  crates/uv-installer/src/satisfies.rs
  crates/uv/src/cli.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/workspace.rs
Labels: preview

#3967 Avoid re-adding solutions to forked state
  crates/uv-resolver/src/resolver/mod.rs
Labels: bug, preview

#3969 Use universal resolution in `uv lock`
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/python_requirement.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/workspace.rs
Labels: preview

#3966 Windows: Statically linked C runtime
  .cargo/config.toml
Labels: windows

#3984 Add index URL parameters to Project CLI
  crates/uv/src/cli.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
Labels: preview

#3970 Remove unstable uv lock from pip interface
  crates/uv/src/cli.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
  crates/uv/tests/lock.rs
Labels: preview

#3988 Update pubgrub to d4795a31be17669aba11eb741b4a9086acc3eb11
  Cargo.lock
  Cargo.toml
Labels: internal

#3989 Fix reference to `--python-version` patch behavior
  crates/uv/src/cli.rs
Labels: documentation

#3992 Use `PubGrubPython` type in Python incompatibility reporting
  crates/distribution-types/src/prioritized_distribution.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/version_map.rs
Labels: internal

#3993 Remove need to return Python version in `get_dependencies`
  crates/uv-resolver/src/resolver/mod.rs
Labels: internal

#3958 Normalize extras in lockfile
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__hash_optional_missing.snap
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/lock.rs
Labels: preview

#3996 Remove Python from available versions
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/resolver/mod.rs
Labels: internal

#3999 Remove some unnecessary `Interpreter` clones
  crates/bench/benches/uv.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
Labels: internal

#4001 Remove unused `dummy` method
  crates/uv-distribution/src/workspace.rs
Labels: internal

#4000 Make target Python version an optional field
  crates/bench/benches/uv.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/python_requirement.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv-resolver/tests/resolver.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/operations.rs
Labels: internal

#4005 Run `cargo update`
  Cargo.lock
Labels: internal

#4010 `impl TryFrom<&VersionSpecifiers> for PubGrubSpecifier`
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/pubgrub/specifier.rs
  crates/uv-resolver/src/resolver/mod.rs
Labels: internal

#4012 Don't copy gitignored files in workspace tests
  Cargo.lock
  crates/uv/Cargo.toml
  crates/uv/tests/common/mod.rs
  crates/uv/tests/workspace.rs
  scripts/workspaces/.gitignore
Labels: internal

#3933 Log transient network request failures
  Cargo.lock
  crates/uv-client/Cargo.toml
  crates/uv-client/src/base_client.rs
Labels: error messages, tracing

#3998 Respect `Requires-Python` in universal resolution
  Cargo.lock
  crates/uv-distribution/src/pyproject.rs
  crates/uv-resolver/src/pubgrub/specifier.rs
  crates/uv-resolver/src/python_requirement.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/tests/lock.rs
Labels: preview

#4004 Avoid work-stealing in bytecode compilation
  crates/uv-installer/src/compile.rs
Labels: performance

#3995 Bias towards local directories for bare editable requirements
  crates/requirements-txt/src/lib.rs
  crates/requirements-txt/src/requirement.rs
  crates/uv-requirements/src/specification.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#4021 Add a hint for `Requires-Python`
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv/tests/lock.rs
Labels: error messages

#4035 Remove unnecessary requirements conversions
  crates/uv-requirements/src/lookahead.rs
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv-resolver/src/resolver/mod.rs
Labels: internal

#4038 Preserve fragments when applying verbatim redirects
  crates/uv-resolver/src/redirect.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#4042 Mute nightly lint fix to mute stable warning
  Cargo.toml
Labels: internal

#4026 Display selected interpreter sources during not selected error
  crates/uv-interpreter/src/discovery.rs
  crates/uv-interpreter/src/lib.rs
Labels: internal, error messages

#4020 Move `uv-interpreter::managed::*` modules into crate top-level
  crates/uv-dev/src/fetch_python.rs
  crates/uv-interpreter/download-metadata.json
  crates/uv-interpreter/fetch-download-metadata.py
  crates/uv-interpreter/src/downloads.inc
  crates/uv-interpreter/src/downloads.inc.mustache
  crates/uv-interpreter/src/downloads.rs
  crates/uv-interpreter/src/lib.rs
  crates/uv-interpreter/src/managed.rs
  crates/uv-interpreter/src/managed/mod.rs
  crates/uv-interpreter/template-download-metadata.py
Labels: internal

#4027 Add `ProvidedPath` to interpreter sources considered when `UV_TEST_PYTHON_PATH` is set
  crates/uv-interpreter/src/discovery.rs
Labels: internal

#4049 Drop `git` dependency from `pip_entrypoints` test
  crates/uv/tests/pip_sync.rs
Labels: testing

#4046 Use standard path filters for `uv venv` tests
  crates/uv/tests/common/mod.rs
  crates/uv/tests/venv.rs
Labels: internal

#4051 Avoid dropping `pip sync` requirements with markers
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/pip_sync.rs
Labels: bug

#4048 Store explicit project on workspace member
  crates/uv-distribution/src/requirement_lowering.rs
  crates/uv-distribution/src/workspace.rs
  crates/uv/src/commands/project/lock.rs
Labels: internal

#4029 Use `PythonEnvironment` API in `uv venv`
  crates/uv-interpreter/src/environment.rs
  crates/uv/src/commands/venv.rs
Labels: internal

#4054 Remove unused `Requirements` struct
  crates/pypi-types/src/requirement.rs
Labels: internal

#4055 Reduce visibility of `lowering`
  crates/uv-distribution/src/lib.rs
  crates/uv-distribution/src/metadata.rs
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-distribution/src/metadata/mod.rs
  crates/uv-distribution/src/pyproject.rs
Labels: internal

#4057 Remove unused PEP 621 error
  crates/uv-distribution/src/pyproject.rs
Labels: internal

#4058 Avoid building packages with dynamic versions
  crates/pypi-types/src/metadata.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/lib.rs
  crates/uv-distribution/src/metadata/mod.rs
  crates/uv-distribution/src/metadata/requires_dist.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-requirements/src/source_tree.rs
  crates/uv/tests/pip_compile.rs
Labels: performance

#4060 Bump version to v0.2.7
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: release

#4043 Retry flaky `compile_invalid_pyc_invalidation_mode` test
  crates/uv/tests/pip_sync.rs
Labels: internal

#4065 Track supported Python range in lockfile
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/python_requirement.rs
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__hash_optional_missing.snap
  crates/uv/tests/lock.rs
Labels: preview

#4070 Default to current Python minor if `Requires-Python` is absent
  crates/pep440-rs/src/version_specifier.rs
  crates/uv-distribution/src/workspace.rs
  crates/uv-interpreter/src/interpreter.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/lock_scenarios.rs
  scripts/workspaces/albatross-in-example/examples/bird-feeder/pyproject.toml
  scripts/workspaces/albatross-in-example/pyproject.toml
  scripts/workspaces/albatross-just-project/pyproject.toml
  scripts/workspaces/albatross-project-in-excluded/excluded/bird-feeder/pyproject.toml
  scripts/workspaces/albatross-project-in-excluded/pyproject.toml
  scripts/workspaces/albatross-root-workspace/packages/bird-feeder/pyproject.toml
  scripts/workspaces/albatross-root-workspace/packages/seeds/pyproject.toml
  scripts/workspaces/albatross-root-workspace/pyproject.toml
  scripts/workspaces/albatross-virtual-workspace/packages/albatross/pyproject.toml
  scripts/workspaces/albatross-virtual-workspace/packages/bird-feeder/pyproject.toml
  scripts/workspaces/albatross-virtual-workspace/packages/seeds/pyproject.toml
Labels: preview

#4073 Fix `uv venv` handling when `VIRTUAL_ENV` refers to an non-existant environment
  crates/uv/src/commands/venv.rs
Labels: bug

#4074 Add regression test for `VIRTUAL_ENV` and `uv venv` interaction
  crates/uv/tests/venv.rs
Labels: testing

#4082 Respect existing `.egg-link` files in site packages
  crates/distribution-types/src/installed.rs
  crates/distribution-types/src/traits.rs
  crates/uv-installer/src/site_packages.rs
  crates/uv-installer/src/uninstall.rs
  crates/uv/src/commands/pip/freeze.rs
Labels: compatibility

#4083 Remove integration tests from `uv-resolver`
  Cargo.lock
  crates/uv-resolver/Cargo.toml
  crates/uv-resolver/src/preferences.rs
  crates/uv-resolver/tests/resolver.rs
Labels: testing

#4084 Prefix sys fields with `sys_` consistently on Interpreter
  crates/uv-cache/src/lib.rs
  crates/uv-interpreter/python/get_interpreter_info.py
  crates/uv-interpreter/src/environment.rs
  crates/uv-interpreter/src/interpreter.rs
  crates/uv-interpreter/src/lib.rs
  crates/uv-virtualenv/src/bare.rs
Labels: internal

#4093 Fix logging in uv-dev
  crates/uv-dev/src/main.rs
Labels: internal

#4095 Avoid extra-only filtering for constraints
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#4104 Avoid enforcing distribution ID uniqueness for extras
  crates/uv-resolver/src/lock.rs
  crates/uv/tests/lock.rs
Labels: bug, preview

#4086 Ignore upper-bounds on `Requires-Python`
  crates/uv-resolver/src/pubgrub/specifier.rs
  crates/uv-resolver/src/python_requirement.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv/tests/lock.rs
Labels: preview

#4105 Add install link for specific version to README
  README.md
Labels: documentation

#4107 Bump version to v0.2.9
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: release

#4016 Lock all packages in workspace
  Cargo.lock
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-distribution/src/pyproject.rs
  crates/uv-distribution/src/workspace.rs
  crates/uv-requirements/src/upgrade.rs
  crates/uv-resolver/Cargo.toml
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/resolver/urls.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/workspace.rs
Labels: preview

#4041 Use union of `requires-python` in workspace
  Cargo.lock
  crates/pep440-rs/src/version_specifier.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/pubgrub/mod.rs
  crates/uv-resolver/src/pubgrub/specifier.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
Labels: preview

#4111 Avoid showing dev hints for Python requirements
  crates/uv-resolver/src/pubgrub/report.rs
Labels: bug, error messages

#4085 Add support for `--prefix`
  crates/uv-interpreter/src/environment.rs
  crates/uv-interpreter/src/interpreter.rs
  crates/uv-interpreter/src/lib.rs
  crates/uv-interpreter/src/prefix.rs
  crates/uv-interpreter/src/target.rs
  crates/uv-workspace/src/combine.rs
  crates/uv-workspace/src/settings.rs
  crates/uv/src/cli.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/pip/uninstall.rs
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/pip_sync.rs
  uv.schema.json
Labels: compatibility

#4116 Remove PubGrub dependency from `uv`
  Cargo.lock
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/python_requirement.rs
  crates/uv-resolver/src/requires_python.rs
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
Labels: internal

#4030 Use `PythonEnvironment` API in `uv pip compile`
  crates/uv/src/commands/pip/compile.rs
Labels: internal

#4061 Include non-standard ports in keyring host queries
  crates/uv-auth/src/keyring.rs
  crates/uv-auth/src/middleware.rs
Labels: bug

#4118 Set `--dev` to default for `uv run` and `uv sync`
  crates/uv/src/cli.rs
  crates/uv/src/settings.rs
  crates/uv/tests/lock.rs
Labels: preview

#4112 Add extra and dev dependency validation to lockfile
  crates/uv-resolver/src/lock.rs
Labels: error messages, preview

#4114 Rename `Dependency.id` to `Dependency.distribution_id`
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__hash_required_present.snap
Labels: internal

#4140 Omit URL dependencies from pre-release hints
  crates/uv-resolver/src/pubgrub/report.rs
Labels: bug, error messages

#4121 Refactor `uv-toolchain` types
  crates/bench/benches/uv.rs
  crates/uv-dev/src/build.rs
  crates/uv-dev/src/compile.rs
  crates/uv-toolchain/src/discovery.rs
  crates/uv-toolchain/src/downloads.rs
  crates/uv-toolchain/src/environment.rs
  crates/uv-toolchain/src/lib.rs
  crates/uv-toolchain/src/managed.rs
  crates/uv-toolchain/src/toolchain.rs
  crates/uv-virtualenv/src/lib.rs
  crates/uv/src/commands/pip/check.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/freeze.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/list.rs
  crates/uv/src/commands/pip/show.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/pip/uninstall.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/commands/venv.rs
  crates/uv/tests/common/mod.rs
Labels: internal

#4134 Update `uv run` and `uv tool run` to use `Toolchain::find`
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/tool/run.rs
Labels: internal

#4123 Track `Markers` via a PubGrub package variant
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/pubgrub/package.rs
  crates/uv-resolver/src/pubgrub/priority.rs
  crates/uv-resolver/src/resolver/batch_prefetch.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/lock_scenarios.rs
Labels: bug, preview

#4146 Update `init_environment` to use `Toolchain::find_default` API
  crates/uv/src/commands/project/mod.rs
Labels: internal

#4144 Drop "registry" prefix from request timeout log
  crates/uv-client/src/base_client.rs
Labels: tracing

#4147 Do not create a virtual environment when locking
  crates/uv-distribution/src/workspace.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
Labels: preview

#4145 Accept `file://` URLs for `requirements.txt` et all references
  crates/requirements-txt/src/lib.rs
  crates/uv/src/cli.rs
  crates/uv/tests/pip_compile.rs
Labels: compatibility

#4149 Avoid pre-fetching for unbounded minimum versions
  crates/uv-resolver/src/resolver/batch_prefetch.rs
  crates/uv-resolver/src/resolver/mod.rs
Labels: bug

#4135 make universal resolver fork only when markers are disjoint
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/lock_scenarios.rs
  crates/uv/tests/pip_compile_scenarios.rs
  crates/uv/tests/pip_install_scenarios.rs
  scripts/scenarios/requirements.in
  scripts/scenarios/requirements.txt
Labels: preview

#4155 Allow transitive URLs via recursive extras
  crates/uv-requirements/src/lookahead.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#4150 Cap `Requires-Python` comparisons at the patch version
  crates/uv-resolver/src/requires_python.rs
  crates/uv/tests/lock.rs
Labels: preview

#4156 Add incorrect conditional-extra test
  crates/uv/tests/lock.rs
Labels: testing, preview

#4158 Fix PEP 508 link in preview doc `specifying_dependencies`
  docs/specifying_dependencies.md
Labels: documentation, preview

#4159 Fix test snapshot for `lock_conditional_dependency_extra`
  crates/uv/tests/lock.rs
Labels: internal

#4165 Remove version from graph edge
  crates/uv-resolver/src/resolution/graph.rs
Labels: internal

#4167 Skip version iteration for non-base packages
  crates/uv-resolver/src/resolution/graph.rs
Labels: internal

#4170 [`README.md`] Fix various typos
  README.md
Labels: documentation

#4175 Reduce visibility of `pyproject.toml` fields
  crates/pypi-types/src/metadata.rs
Labels: internal

#4176 Move PEP 440 and PEP 508 parsing out of TOML deserialization
  Cargo.lock
  crates/pypi-types/Cargo.toml
  crates/pypi-types/src/metadata.rs
Labels: internal

#4183 Respect `--find-links` in `lock` and `sync`
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
Labels: preview

#4184 Fix existing typos and enable `typos` in CI
  .github/workflows/ci.yml
  CHANGELOG.md
  _typos.toml
  crates/install-wheel-rs/src/uninstall.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-toolchain/src/lib.rs
  crates/uv-toolchain/src/toolchain.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/pip_install_scenarios.rs
  crates/uv/tests/venv.rs
Labels: internal

#4181 Add `pyproject.toml` to CLI help
  crates/uv/src/cli.rs
Labels: cli

#4192 Fix python3.13 on windows CI job by pinning older version
  .github/workflows/ci.yml
Labels: internal

#4174 Ignore tags in universal resolution
  crates/bench/benches/uv.rs
  crates/distribution-types/src/prioritized_distribution.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-resolver/src/flat_index.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/venv.rs
Labels: preview

#4168 Remove `PubGrubPackage` dependency from `ResolutionGraph`
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/sync.rs
Labels: internal, preview

#4195 Document bytecode compilation in pip compatibility guide
  PIP_COMPATIBILITY.md
Labels: documentation

#4196 Fix `>=` to `==` typo in `is_contained_by` docs
  crates/uv-resolver/src/requires_python.rs
Labels: documentation, internal

#4138 Implement `Toolchain::find_or_fetch` and use in `uv venv --preview`
  Cargo.lock
  crates/uv-dev/Cargo.toml
  crates/uv-dev/src/fetch_python.rs
  crates/uv-toolchain/src/discovery.rs
  crates/uv-toolchain/src/downloads.rs
  crates/uv-toolchain/src/lib.rs
  crates/uv-toolchain/src/managed.rs
  crates/uv-toolchain/src/toolchain.rs
  crates/uv/src/commands/venv.rs
Labels: preview

#4143 Fetch managed toolchains in `uv run`
  crates/uv/src/commands/project/run.rs
Labels: preview

#4163 Add `uv toolchain list`
  crates/uv-toolchain/src/downloads.rs
  crates/uv-toolchain/src/managed.rs
  crates/uv/src/cli.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/toolchain/list.rs
  crates/uv/src/commands/toolchain/mod.rs
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
Labels: preview

#4182 Improve static metadata extraction for Poetry projects
  crates/pypi-types/src/metadata.rs
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv/tests/pip_compile.rs
Labels: error messages

#3945 Recreate project environment if `--python` or `requires-python` doesn't match
  crates/uv-toolchain/src/discovery.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/main.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/run.rs
  crates/uv/tests/workspace.rs
Labels: preview

#4164 Add `uv toolchain install`
  crates/uv-toolchain/src/discovery.rs
  crates/uv-toolchain/src/managed.rs
  crates/uv/src/cli.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/toolchain/install.rs
  crates/uv/src/commands/toolchain/mod.rs
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
Labels: preview

#4031 Clarify role of `--system` flag in README
  README.md
Labels: documentation

#4201 Bump version to 0.2.10
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: release

#4202 Exclude preview items from changelog
  pyproject.toml
Labels: release

#4200 Avoid crash for `XDG_CONFIG_HOME=/dev/null`
  crates/uv-workspace/src/workspace.rs
Labels: bug

#4203 Improve `uv toolchain list` implementation
  crates/uv/src/commands/toolchain/list.rs
Labels: internal

#4210 Document Windows 10 requirement
  README.md
Labels: documentation, windows

#4208 Always install as editable when duplicates are requested
  crates/uv-resolver/src/resolver/urls.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#4211 Remove project dependency from `sync`
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
Labels: internal

#4221 Remove usages of verbatim URL in URL resolver
  crates/pypi-types/src/parsed_url.rs
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/resolver/urls.rs
Labels: internal

#4218 Improve handling of missing interpreters during discovery
  crates/uv-toolchain/src/discovery.rs
  crates/uv-toolchain/src/interpreter.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_sync.rs
Labels: bug

#4222 Update test context to avoid discovery of external Pythons
  crates/uv/tests/common/mod.rs
  crates/uv/tests/run.rs
Labels: testing

#4224 Fix `pip_compile::missing_venv` test
  crates/uv/tests/pip_compile.rs
Labels: internal

#4171 feat: mTLS support
  README.md
  crates/uv-client/src/base_client.rs
  crates/uv-client/src/lib.rs
  crates/uv-client/src/tls.rs
Labels: enhancement

#4216 Refactor project interpreter request for `requires-python` specifiers
  crates/uv/src/commands/project/mod.rs
Labels: preview

#4226 Add support for local directories with `--index-url`
  crates/distribution-types/src/file.rs
  crates/distribution-types/src/index_url.rs
  crates/pep508-rs/src/verbatim_url.rs
  crates/uv-client/src/error.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv/src/cli.rs
  crates/uv/tests/pip_install.rs
Labels: enhancement, compatibility

#4225 Migrate lock errors to `thiserror`
  crates/uv-resolver/src/lock.rs
Labels: internal

#4205 Support locking relative paths
  crates/distribution-types/src/buildable.rs
  crates/distribution-types/src/cached.rs
  crates/distribution-types/src/lib.rs
  crates/distribution-types/src/resolution.rs
  crates/pypi-types/src/parsed_url.rs
  crates/pypi-types/src/requirement.rs
  crates/requirements-txt/src/lib.rs
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-unix-bare-url.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-unix-editable.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-windows-bare-url.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-windows-editable.txt.snap
  crates/uv-distribution/src/index/built_wheel_index.rs
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-distribution/src/workspace.rs
  crates/uv-installer/src/plan.rs
  crates/uv-installer/src/satisfies.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/resolver/locals.rs
  crates/uv-resolver/src/resolver/urls.rs
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__hash_optional_missing.snap
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/lock_scenarios.rs
  crates/uv/tests/workspace.rs
Labels: preview

#4232 De-duplicate resolution environment logic
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/mod.rs
  crates/uv/src/commands/pip/sync.rs
Labels: internal

#4233 Allow direct URLs for dev dependencies
  crates/uv-requirements/src/lookahead.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/tests/lock.rs
Labels: bug, preview

#4234 Warn when 'requires-python' does not include a lower bound
  crates/distribution-types/src/file.rs
  crates/uv-resolver/src/requires_python.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/lock.rs
Labels: error messages, preview

#4248 Improve output when an older toolchain version is already installed
  crates/uv/src/commands/toolchain/install.rs
Labels: tracing, preview

#4247 Make missing `METADATA` file a recoverable error
  Cargo.lock
  crates/uv-client/Cargo.toml
  crates/uv-client/src/error.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/resolver/availability.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
Labels: bug

#4253 Represent build tag as `u64`
  crates/distribution-filename/src/build_tag.rs
  crates/distribution-filename/src/snapshots/distribution_filename__wheel__tests__ok_build_tag.snap
  crates/distribution-filename/src/wheel.rs
  crates/uv-cache/src/lib.rs
Labels: bug

#4251 Add changelog for preview changes
  CHANGELOG-PREVIEW.md
  pyproject.toml
  scripts/release.sh
Labels: preview

#4254 Re-add `aarch64-unknown-linux-gnu` binary to release assets
  .github/workflows/build-binaries.yml
  Cargo.toml
Labels: release

#4258 Bump version to v0.2.11
  CHANGELOG-PREVIEW.md
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: release

#4260 Flatten ORs and ANDs in marker construction
  crates/pep508-rs/src/marker.rs
Labels: enhancement

#4261 Move project commands into their own subcommand struct
  crates/uv/src/cli.rs
  crates/uv/src/main.rs
Labels: internal, cli

#4262 DRY up index argument parsing
  crates/uv/src/settings.rs
Labels: internal, configuration

#4263 Deduplicate markers during normalization
  crates/uv-resolver/src/marker.rs
Labels: bug

#4259 Add uv version to debug output
  crates/uv/src/main.rs
  crates/uv/tests/cache_prune.rs
Labels: cli

#4268 Use relative path for lib64 symlink
  crates/uv-virtualenv/src/bare.rs
Labels: compatibility

#4269 Fix doc for `uv add` cli command s/remove/add/
  crates/uv/src/cli.rs
Labels: documentation

#4271 Allow normalization to completely eliminate markers
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/marker.rs
Labels: bug

#4275 Use consistent order for extra groups in lockfile
  crates/uv-resolver/src/lock.rs
Labels: bug

#4280 Use registry URL for fetching source distributions from lockfile
  crates/uv-resolver/src/lock.rs
  crates/uv/tests/lock.rs
Labels: bug, preview

#4278 Use `FxHashMap` for available versions
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/pubgrub/report.rs
Labels: internal

#4283 Avoid treating direct path archives as always dynamic
  crates/uv-installer/src/satisfies.rs
  crates/uv/tests/pip_sync.rs
Labels: bug

#4282 Respect `requires-python` in `uv lock`
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
Labels: bug, preview

#4279 Improve local testing docs for packse
  scripts/scenarios/generate.py
Labels: internal

#4287 Add `UV_EXCLUDE_NEWER` environment variable
  README.md
  crates/uv/src/cli.rs
Labels: configuration

#4285 Use separate path types for directories and files
  crates/distribution-types/src/cached.rs
  crates/distribution-types/src/error.rs
  crates/distribution-types/src/lib.rs
  crates/distribution-types/src/resolution.rs
  crates/pypi-types/src/parsed_url.rs
  crates/pypi-types/src/requirement.rs
  crates/requirements-txt/src/lib.rs
  crates/requirements-txt/src/requirement.rs
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-unix-bare-url.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-unix-editable.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-windows-bare-url.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-windows-editable.txt.snap
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-distribution/src/pyproject.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-distribution/src/workspace.rs
  crates/uv-installer/src/plan.rs
  crates/uv-installer/src/satisfies.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/resolver/locals.rs
  crates/uv-resolver/src/resolver/urls.rs
  crates/uv-types/src/hash.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_sync.rs
  uv.schema.json
Labels: internal

#4288 Rename some internal settings structs
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
Labels: internal

#4067 Allow specific `--only-binary` and `--no-binary` packages to override `:all:`
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-installer/src/plan.rs
  crates/uv-resolver/src/flat_index.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/pip_install.rs
Labels: enhancement

#4284 Add `BuildOptions` for centralized combination of `NoBuild` and `NoBinary`
  crates/bench/benches/uv.rs
  crates/uv-configuration/src/build_options.rs
  crates/uv-dev/src/build.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-installer/src/plan.rs
  crates/uv-resolver/src/flat_index.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv-types/src/traits.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/venv.rs
Labels: internal

#4290 Move the preview changelog so the GitHub Release shows stable changes
  PREVIEW-CHANGELOG.md
  scripts/release.sh
Labels: release

#4293 Tweak copy on some command-line arguments
  crates/uv/src/cli.rs
Labels: documentation
