Repository astral-sh/uv, pull requests merged in 2024-03, with the labels that each got.

#1982 Future-proof pip entrypoints special case
  crates/install-wheel-rs/src/script.rs
  crates/uv/tests/pip_sync.rs
Labels: compatibility

#2101 Add support for `--system-site-packages` in `uv venv`
  crates/gourgeist/src/bare.rs
  crates/gourgeist/src/lib.rs
  crates/gourgeist/src/main.rs
  crates/uv-build/src/lib.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/main.rs
Labels: enhancement, compatibility, cli

#2102 Centralize virtualenv path construction
  crates/gourgeist/src/bare.rs
  crates/gourgeist/src/lib.rs
  crates/uv-interpreter/src/interpreter.rs
  crates/uv-interpreter/src/lib.rs
  crates/uv-interpreter/src/python_environment.rs
  crates/uv-interpreter/src/sysconfig.rs
  crates/uv-interpreter/src/virtualenv.rs
  crates/uv-interpreter/src/virtualenv_layout.rs
Labels: internal

#2114 Consider editable dependencies to be 'direct'
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/prerelease_mode.rs
  crates/uv-resolver/src/resolution_mode.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#2117 Use `prefix` instead of `base_prefix` for environment root
  crates/uv-interpreter/src/python_environment.rs
Labels: bug

#2118 Rename `gourgeist` to `uv-virtualenv`
  Cargo.lock
  crates/README.md
  crates/gourgeist/README.md
  crates/gourgeist/benchmark.sh
  crates/gourgeist/compare_in_git.sh
  crates/gourgeist/imasnake.py
  crates/gourgeist/oranda.json
  crates/gourgeist/static/gourgeist.png
  crates/gourgeist/venv_checker.py
  crates/uv-build/Cargo.toml
  crates/uv-build/src/lib.rs
  crates/uv-dev/Cargo.toml
  crates/uv-dispatch/Cargo.toml
  crates/uv-resolver/Cargo.toml
  crates/uv-virtualenv/Cargo.toml
  crates/uv-virtualenv/README.md
  crates/uv-virtualenv/src/_virtualenv.py
  crates/uv-virtualenv/src/activate
  crates/uv-virtualenv/src/activator/.gitattributes
  crates/uv-virtualenv/src/activator/activate
  crates/uv-virtualenv/src/activator/activate.bat
  crates/uv-virtualenv/src/activator/activate.csh
  crates/uv-virtualenv/src/activator/activate.fish
  crates/uv-virtualenv/src/activator/activate.nu
  crates/uv-virtualenv/src/activator/activate.ps1
  crates/uv-virtualenv/src/activator/activate_this.py
  crates/uv-virtualenv/src/activator/deactivate.bat
  crates/uv-virtualenv/src/activator/pydoc.bat
  crates/uv-virtualenv/src/bare.rs
  crates/uv-virtualenv/src/lib.rs
  crates/uv-virtualenv/src/main.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/venv.rs
  crates/uv/src/main.rs
  ruff.toml
Labels: internal

#2119 Remove `camino` from `uv-virtualenv`
  Cargo.lock
  Cargo.toml
  crates/uv-virtualenv/Cargo.toml
  crates/uv-virtualenv/src/bare.rs
  crates/uv-virtualenv/src/lib.rs
  crates/uv-virtualenv/src/main.rs
Labels: internal

#2100 feat: report line and column on requirements parser errors
  crates/requirements-txt/src/lib.rs
Labels: error messages

#2124 docs: add note about ssl_cert_file env var
  README.md
Labels: documentation

#2125 Preserve environment variables in resolved Git dependencies
  crates/pep508-rs/src/verbatim_url.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/redirect.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv-traits/src/lib.rs
Labels: bug

#2131 Add caveats on `--system` support to the README
  README.md
Labels: documentation

#2128 Allow empty extras in `pep508-rs` and add more corner case to tests
  crates/pep508-rs/src/lib.rs
  crates/requirements-txt/src/lib.rs
Labels: bug, compatibility

#2121 Adjust base Python lookup logic for Windows
  crates/uv-interpreter/src/get_interpreter_info.py
  crates/uv-interpreter/src/interpreter.rs
  crates/uv-virtualenv/src/bare.rs
  crates/uv/tests/venv.rs
Labels: bug, windows

#2140 Use space as delimiter for `UV_EXTRA_INDEX_URL`
  crates/uv/src/main.rs
Labels: bug, compatibility

#2137 Make an empty string behave like the default
  crates/uv/src/main.rs
Labels: compatibility

#2141 Add tests for empty index URL environment variable
  crates/uv/tests/pip_compile.rs
Labels: internal

#2143 Expand environment variables in `-r` and `-c` subfile paths
  crates/pep508-rs/src/lib.rs
  crates/pep508-rs/src/verbatim_url.rs
  crates/requirements-txt/src/lib.rs
  crates/uv/tests/pip_compile.rs
Labels: compatibility

#2151 Make WHEEL parsing error line numbers one indexed.
  crates/install-wheel-rs/src/wheel.rs
Labels: error messages

#2110 Better offline error message
  crates/uv-client/Cargo.toml
  crates/uv-client/src/cached_client.rs
  crates/uv-client/src/error.rs
  crates/uv-client/src/flat_index.rs
  crates/uv-client/src/lib.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution/src/error.rs
Labels: error messages

#2166 Expose the `--exclude-newer` flag
  README.md
  crates/uv/src/main.rs
  crates/uv/tests/pip_compile.rs
Labels: enhancement

#2168 Centralize up-to-date checking for path installations
  crates/uv-cache/src/lib.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/index/built_wheel_index.rs
  crates/uv-installer/src/editable.rs
  crates/uv-installer/src/lib.rs
  crates/uv-installer/src/plan.rs
  crates/uv-installer/src/site_packages.rs
  crates/uv/src/commands/pip_sync.rs
Labels: internal

#2170 Allow empty values in WHEEL files
  crates/install-wheel-rs/src/wheel.rs
Labels: bug

#2169 Respect local freshness when auditing installed environment
  crates/uv-installer/src/plan.rs
  crates/uv-installer/src/site_packages.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#2173 Use simpler pip-like `Scheme` for install paths
  Cargo.lock
  crates/install-wheel-rs/src/lib.rs
  crates/install-wheel-rs/src/linker.rs
  crates/install-wheel-rs/src/wheel.rs
  crates/pypi-types/src/lib.rs
  crates/pypi-types/src/scheme.rs
  crates/uv-interpreter/Cargo.toml
  crates/uv-interpreter/src/get_interpreter_info.py
  crates/uv-interpreter/src/interpreter.rs
  crates/uv-interpreter/src/lib.rs
  crates/uv-interpreter/src/virtualenv.rs
  crates/uv-virtualenv/Cargo.toml
  crates/uv-virtualenv/src/bare.rs
Labels: internal

#2123 Set `.metadata` suffix on URL path
  crates/uv-client/src/registry_client.rs
Labels: bug, compatibility

#2176 Respect markers on URL dependencies in editables
  crates/uv-resolver/src/resolver/urls.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#2190 Extend `system-install.yml` to include virtualenv operations
  .github/workflows/system-install.yml
  scripts/check_system_python.py
Labels: testing

#2186 Fallback to non-range requests when HEAD returns 404
  crates/uv-client/src/error.rs
Labels: compatibility

#2204 Respect nested editable requirements in parser
  crates/requirements-txt/src/lib.rs
Labels: bug

#2206 Allow direct URLs in optional dependencies in editables
  crates/uv-resolver/src/resolver/urls.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#2207 Make direct dependency detection respect markers
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/prerelease_mode.rs
  crates/uv-resolver/src/resolution_mode.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/yanks.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#2209 Expand Windows shim detection to include `python3.12.exe`
  crates/uv-interpreter/src/python_query.rs
Labels: bug, windows

#2212 Avoid Windows Store shims in `--python python3`-like invocations
  crates/uv-interpreter/src/interpreter.rs
  crates/uv-interpreter/src/python_query.rs
Labels: bug, windows

#2215 HTML-decode URLs in HTML indexes
  crates/uv-client/src/html.rs
Labels: bug, registry

#2214 Respect `py --list-paths` fallback in `--python python3` invocations
  crates/uv-interpreter/src/python_query.rs
Labels: bug, windows

#2188 Query interpreter to determine correct `virtualenv` paths
  Cargo.lock
  crates/pypi-types/src/scheme.rs
  crates/uv-interpreter/src/get_interpreter_info.py
  crates/uv-interpreter/src/interpreter.rs
  crates/uv-virtualenv/Cargo.toml
  crates/uv-virtualenv/src/bare.rs
Labels: compatibility, virtualenv

#2193 Respect non-`sysconfig`-based system Pythons
  .github/workflows/system-install.yml
  crates/platform-tags/src/lib.rs
  crates/uv-interpreter/src/get_interpreter_info.py
Labels: bug, compatibility

#2221 Show appropriate activation command based on shell detection
  crates/uv/src/commands/venv.rs
  crates/uv/src/main.rs
  crates/uv/src/shell.rs
Labels: bug

#2223 Escape Windows paths with spaces in `venv` activation command
  crates/uv/src/commands/venv.rs
Labels: windows

#2108 Include exit code for build failures
  crates/uv-build/src/lib.rs
  crates/uv-interpreter/src/interpreter.rs
  crates/uv-interpreter/src/lib.rs
  crates/uv-interpreter/src/python_query.rs
Labels: error messages

#2115 Implement `uv pip show`
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/pip_show.rs
  crates/uv/src/main.rs
  crates/uv/tests/pip_show.rs
Labels: enhancement, compatibility, cli

#2227 Add `.stdout()` and `.stderr()` outputs to `Printer`
  crates/uv/src/commands/cache_clean.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_freeze.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_list.rs
  crates/uv/src/commands/pip_show.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/src/commands/pip_uninstall.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/main.rs
  crates/uv/src/printer.rs
Labels: bug

#2226 feat: cmd.exe detection heuristic
  crates/uv/src/commands/venv.rs
  crates/uv/src/shell.rs
Labels: enhancement, windows

#2081 Support remote `https://` requirements files (#1332)
  Cargo.lock
  Cargo.toml
  crates/requirements-txt/Cargo.toml
  crates/requirements-txt/src/lib.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-fs/src/lib.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/src/commands/pip_uninstall.rs
  crates/uv/src/main.rs
  crates/uv/src/requirements.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_sync.rs
  crates/uv/tests/pip_uninstall.rs
Labels: configuration

#2225 ci: maturing version uses env var
  .github/workflows/build-binaries.yml
Labels: no-build

#2229 Make `Client` optional in `requirements-txt`
  Cargo.lock
  crates/requirements-txt/Cargo.toml
  crates/requirements-txt/src/lib.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/requirements.rs
Labels: internal

#2237 test: pip_list: Fix replacement pattern computation
  crates/uv/tests/pip_list.rs
Labels: testing

#2250 Stop exposing `client_raw`
  crates/uv-client/src/registry_client.rs
Labels: internal

#2249 Implement `--break-system-packages`
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/src/commands/pip_uninstall.rs
  crates/uv/src/main.rs
Labels: compatibility

#2241 feat: Add netrc authentication to uv-client
  Cargo.lock
  Cargo.toml
  crates/uv-client/Cargo.toml
  crates/uv-client/src/registry_client.rs
  crates/uv-client/tests/netrc_auth.rs
Labels: enhancement

#2244 Add `PIP_COMPATIBILITY.md` to document known deviations from `pip`
  PIP_COMPATIBILITY.md
  README.md
Labels: documentation

#2255 Cache wheel metadata in no-PEP 658 fallback
  crates/uv-client/src/registry_client.rs
Labels: performance

#2259 Close `RECORD` after reading entries during uninstall
  crates/install-wheel-rs/src/uninstall.rs
Labels: bug

#2262 Fix typo in `PIP_COMPATIBILITY.md`
  PIP_COMPATIBILITY.md
Labels: documentation

#2272 Fix uv-fs extras by removing dead code
  crates/uv-distribution/Cargo.toml
  crates/uv-fs/src/lib.rs
Labels: internal

#2273 Fix parsing requirement where a variable follows an operator without a space
  crates/pep508-rs/src/lib.rs
  crates/pep508-rs/src/marker.rs
Labels: bug

#2275 Use insta in pep508_rs
  Cargo.lock
  crates/pep508-rs/Cargo.toml
  crates/pep508-rs/src/lib.rs
  crates/pep508-rs/src/marker.rs
Labels: internal

#2258 Add support for `--no-build-isolation`
  PIP_COMPATIBILITY.md
  crates/uv-build/src/lib.rs
  crates/uv-dev/src/build.rs
  crates/uv-dev/src/install_many.rs
  crates/uv-dev/src/resolve_cli.rs
  crates/uv-dev/src/resolve_many.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-interpreter/src/python_environment.rs
  crates/uv-resolver/tests/resolver.rs
  crates/uv-traits/src/lib.rs
  crates/uv-virtualenv/src/lib.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/compat/mod.rs
  crates/uv/src/main.rs
  crates/uv/tests/pip_install.rs
Labels: enhancement, compatibility

#2279 Fix Conda Python detection on Windows
  crates/uv-interpreter/src/python_environment.rs
Labels: bug, windows

#2278 Retry on python interpreter launch failures
  crates/uv-installer/src/compile.rs
  crates/uv-installer/src/pip_compileall.py
Labels: bug

#2281 Add Conda tests to `system-install.yml`
  .github/workflows/system-install.yml
  crates/uv-virtualenv/src/bare.rs
  scripts/check_system_python.py
Labels: testing

#2284 Use reparse points to detect Windows installer shims
  Cargo.lock
  Cargo.toml
  crates/uv-fs/src/path.rs
  crates/uv-interpreter/Cargo.toml
  crates/uv-interpreter/src/python_query.rs
Labels: bug, windows

#2288 Address review feedback on reparse points
  crates/uv-interpreter/Cargo.toml
  crates/uv-interpreter/src/python_query.rs
  crates/uv/Cargo.toml
Labels: internal

#2285 Allow more-precise Git URLs to override less-precise Git URLs
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/resolver/urls.rs
  crates/uv/tests/pip_compile.rs
Labels: enhancement

#2294 Move source distribution unpacking out of `build`
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/src/lib.rs
  crates/uv-dev/src/build.rs
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv/tests/pip_compile.rs
Labels: performance, internal

#2295 Encapsulate header parsing for metadata files
  crates/pypi-types/src/metadata.rs
Labels: internal

#2293 Add support for Metadata 2.2
  crates/distribution-types/src/installed.rs
  crates/pypi-types/src/metadata.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-installer/src/editable.rs
  crates/uv-resolver/src/editables.rs
  crates/uv-resolver/src/manifest.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv-resolver/src/resolver/index.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv/tests/pip_compile.rs
Labels: enhancement

#2297 Added ability to select bytecode invalidation mode of generated .pyc
  crates/uv-installer/src/compile.rs
  crates/uv-installer/src/pip_compileall.py
  crates/uv/tests/common/mod.rs
  crates/uv/tests/pip_sync.rs
Labels: enhancement

#1298 Refactor incompatiblity tracking for distributions
  Cargo.lock
  crates/distribution-types/Cargo.toml
  crates/distribution-types/src/prioritized_distribution.rs
  crates/pypi-types/src/simple_json.rs
  crates/uv-client/src/flat_index.rs
  crates/uv-dev/src/install_many.rs
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/finder.rs
  crates/uv-resolver/src/pins.rs
  crates/uv-resolver/src/python_requirement.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv-resolver/src/yanks.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/tests/pip_install_scenarios.rs
Labels: internal

#2307 Add a custom suggestion to install wheel into the build environment
  crates/uv-build/src/lib.rs
Labels: error messages

#2314 Communicate PEP 517 hook results via files
  crates/uv-build/src/lib.rs
Labels: bug

#2318 Document the environment variables that uv respects
  README.md
  crates/uv-cache/src/cli.rs
Labels: documentation

#2319 Address #2220 (slow download perf against PyPi mirror)
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-extract/src/stream.rs
Labels: performance

#2322 Move `Error` methods off of `ErrorKind`
  crates/uv-client/src/cached_client.rs
  crates/uv-client/src/error.rs
  crates/uv-client/src/flat_index.rs
  crates/uv-client/src/registry_client.rs
Labels: internal

#2324 Move wheel download into a shared method
  crates/uv-distribution/src/distribution_database.rs
Labels: internal

#2335 Fix failing install_extra_index_url_has_priority test
  crates/uv/tests/pip_install.rs
Labels: internal

#2334 Rename and document venv discoveries
  crates/uv-interpreter/src/find_python.rs
  crates/uv-interpreter/src/interpreter.rs
  crates/uv-interpreter/src/lib.rs
  crates/uv-interpreter/src/python_environment.rs
  crates/uv/src/commands/pip_compile.rs
Labels: internal

#2337 Update `install_extra_index_url_has_priority` to avoid packaging breakage
  crates/uv/tests/pip_install.rs
Labels: testing

#2336 Remove duplicate `INSTALLER` in `RECORD`
  crates/install-wheel-rs/src/wheel.rs
Labels: bug

#2339 Use helpers in all editable tests
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_freeze.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_list.rs
  crates/uv/tests/pip_show.rs
  crates/uv/tests/pip_sync.rs
  crates/uv/tests/pip_uninstall.rs
Labels: testing

#2325 Avoid duplicating authorization header with netrc
  Cargo.lock
  Cargo.toml
  crates/uv-client/Cargo.toml
  crates/uv-client/src/middleware.rs
  crates/uv-client/src/registry_client.rs
Labels: bug

#2320 Add `Seek` fallback for zip files
  crates/install-wheel-rs/src/lib.rs
  crates/install-wheel-rs/src/metadata.rs
  crates/uv-client/src/error.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-client/src/remote_metadata.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/download.rs
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-extract/src/error.rs
  crates/uv-extract/src/lib.rs
  crates/uv-extract/src/seek.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_sync.rs
Labels: bug, compatibility

#2340 install_extra_index_url_has_priority without exclude newer
  crates/uv/tests/pip_install.rs
Labels: testing

#2345 Remove unnnecesary Windows stack size changes
  crates/uv/tests/pip_install.rs
Labels: testing

#2348 Write relative paths for scripts in data directory
  crates/install-wheel-rs/src/wheel.rs
Labels: bug

#2341 Remove `wheel` from default PEP 517 backend
  crates/uv-build/src/lib.rs
Labels: compatibility

#2350 Initialize client lazily for remote requirements files
  Cargo.lock
  crates/requirements-txt/Cargo.toml
  crates/requirements-txt/src/lib.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/src/commands/pip_uninstall.rs
  crates/uv/src/requirements.rs
  crates/uv/tests/pip_install.rs
Labels: performance

#2301 Add a `-vv` log level and make `-v` more readable
  Cargo.lock
  Cargo.toml
  crates/uv-interpreter/src/interpreter.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/Cargo.toml
  crates/uv/src/logging.rs
  crates/uv/src/main.rs
Labels: tracing

#2360 Ignore inverse dependencies when building graph
  crates/uv-resolver/src/resolution.rs
Labels: bug

#2354 Add env UV_SYSTEM as alias to --system
  README.md
  crates/uv/src/main.rs
Labels: configuration

#2369 Add dedicated error message for direct filesystem paths in requirements
  crates/pep508-rs/src/lib.rs
Labels: error messages

#2373 Skip prefetching when `--no-deps` is specified
  crates/uv-resolver/src/resolver/mod.rs
Labels: bug

#2362 Enable TLS native root toggling at runtime
  Cargo.lock
  Cargo.toml
  README.md
  crates/uv-client/Cargo.toml
  crates/uv-client/src/lib.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-client/src/tls.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/src/main.rs
Labels: performance, breaking

#2347 Implement "Requires" field in `pip show`
  crates/uv/src/commands/pip_show.rs
  crates/uv/tests/pip_show.rs
Labels: enhancement, cli

#2312 Move system install tests into normal CI
  .github/workflows/ci.yml
  .github/workflows/system-install.yml
Labels: testing

#2370 Use musl for system test builds
  .github/workflows/ci.yml
Labels: testing

#2376 Do not bump the minor version on breaking changes
  pyproject.toml
Labels: internal

#2384 Update pubgrub
  Cargo.lock
  Cargo.toml
Labels: internal

#2396 Use local package instead of `transitive_url_dependency.zip`
  crates/uv/tests/pip_compile.rs
  scripts/editable-installs/hatchling_editable/pyproject.toml
Labels: testing

#2394 Expand environment variables prior to detecting scheme
  crates/distribution-types/src/index_url.rs
  crates/pep508-rs/src/lib.rs
  crates/pep508-rs/src/verbatim_url.rs
  crates/requirements-txt/src/lib.rs
  crates/uv-resolver/src/redirect.rs
  crates/uv-resolver/src/resolver/urls.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#2393 Fix bug where `--no-binary :all:` prevented build of editable packages
  crates/uv-dispatch/src/lib.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#2395 Trim injected `python_version` marker to (major, minor)
  crates/pep508-rs/src/marker.rs
  crates/uv-interpreter/src/interpreter.rs
  crates/uv-interpreter/src/python_version.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/python_requirement.rs
  crates/uv-resolver/src/resolver/mod.rs
Labels: bug

#2399 Run `cargo update`
  Cargo.lock
Labels: internal

#2401 feat: keep backwards compatibility with `SSL_CERT_FILE` without requiring `--native-tls`
  README.md
  crates/uv-client/src/registry_client.rs
Labels: enhancement

#2381 Move architecture and operating system probing to Python
  Cargo.lock
  Cargo.toml
  crates/install-wheel-rs/Cargo.toml
  crates/install-wheel-rs/src/lib.rs
  crates/platform-host/Cargo.toml
  crates/platform-host/src/lib.rs
  crates/platform-host/src/linux.rs
  crates/platform-host/src/mac_os.rs
  crates/platform-tags/Cargo.toml
  crates/platform-tags/src/lib.rs
  crates/platform-tags/src/platform.rs
  crates/platform-tags/src/tags.rs
  crates/uv-build/Cargo.toml
  crates/uv-dev/Cargo.toml
  crates/uv-dev/src/build.rs
  crates/uv-dev/src/compile.rs
  crates/uv-dev/src/install_many.rs
  crates/uv-dev/src/resolve_cli.rs
  crates/uv-dev/src/resolve_many.rs
  crates/uv-dispatch/Cargo.toml
  crates/uv-interpreter/Cargo.toml
  crates/uv-interpreter/python/__init__.py
  crates/uv-interpreter/python/get_interpreter_info.py
  crates/uv-interpreter/python/packaging/LICENSE.APACHE
  crates/uv-interpreter/python/packaging/LICENSE.BSD
  crates/uv-interpreter/python/packaging/README.md
  crates/uv-interpreter/python/packaging/__init__.py
  crates/uv-interpreter/python/packaging/_elffile.py
  crates/uv-interpreter/python/packaging/_manylinux.py
  crates/uv-interpreter/python/packaging/_musllinux.py
  crates/uv-interpreter/src/find_python.rs
  crates/uv-interpreter/src/interpreter.rs
  crates/uv-interpreter/src/lib.rs
  crates/uv-interpreter/src/python_environment.rs
  crates/uv-resolver/Cargo.toml
  crates/uv-resolver/tests/resolver.rs
  crates/uv-virtualenv/Cargo.toml
  crates/uv-virtualenv/src/lib.rs
  crates/uv-virtualenv/src/main.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_freeze.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_list.rs
  crates/uv/src/commands/pip_show.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/src/commands/pip_uninstall.rs
  crates/uv/src/commands/venv.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/venv.rs
Labels: bug

#2402 Add system install test for CentOS
  .github/workflows/ci.yml
Labels: testing

#2423 Fix tests on main
  crates/uv/tests/pip_compile.rs
Labels: testing

#2420 Remove `django` as a common test package
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_install.rs
Labels: testing

#2427 Refactor `AuthenticationStore` to inline credentials
  Cargo.lock
  Cargo.toml
  crates/distribution-types/src/file.rs
  crates/uv-auth/Cargo.toml
  crates/uv-auth/src/lib.rs
  crates/uv-auth/src/middleware.rs
  crates/uv-auth/src/store.rs
  crates/uv-client/src/flat_index.rs
  crates/uv-client/src/registry_client.rs
Labels: internal

#2421 Update pubgrub for faster range operations
  Cargo.lock
  Cargo.toml
  scripts/requirements/bio_embeddings.in
Labels: performance

#2425 Document HTTP authentication
  PIP_COMPATIBILITY.md
  README.md
Labels: documentation

#2435 Bump version to 0.1.19
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: internal

#2436 Add a performance section to the CHANGELOG
  pyproject.toml
Labels: internal

#2437 Update packse development documentation to include `--no-hash` flag
  scripts/scenarios/generate.py
Labels: documentation, internal

#2440 Simplify the packse scenario package name filters
  crates/uv/tests/pip_compile_scenarios.rs
  crates/uv/tests/pip_install_scenarios.rs
  scripts/scenarios/generate.py
  scripts/scenarios/templates/compile.mustache
  scripts/scenarios/templates/install.mustache
Labels: internal, testing

#2196 Error when direct URL requirements don't match `Requires-Python`
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_sync.rs
Labels: bug, error messages

#2446 Add in-URL credentials to store prior to creating requests
  crates/distribution-types/src/file.rs
  crates/distribution-types/src/index_url.rs
  crates/pypi-types/src/base_url.rs
  crates/uv-auth/src/middleware.rs
  crates/uv-auth/src/store.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/src/commands/venv.rs
Labels: bug

#2448 Bump version to v0.1.20
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: internal

#2451 Replace boto3.in with slow scenario
  scripts/requirements/boto3.in
  scripts/requirements/compiled/boto3.txt
Labels: internal

#2441 Loosen `.dist-info` validation to accept arbitrary versions
  crates/install-wheel-rs/src/lib.rs
  crates/install-wheel-rs/src/linker.rs
  crates/install-wheel-rs/src/metadata.rs
Labels: compatibility

#2461 Avoid panicking on cannot-be-a-base URLs
  crates/cache-key/src/canonical_url.rs
Labels: bug

#2462 Update packse to pull in additional local version tests
  crates/uv-cache/src/lib.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv/tests/pip_compile_scenarios.rs
  crates/uv/tests/pip_install_scenarios.rs
  scripts/scenarios/generate.py
  scripts/scenarios/requirements.in
  scripts/scenarios/requirements.txt
Labels: testing

#2468 Pull in `packse` tests for post releases
  crates/uv-resolver/src/pubgrub/specifier.rs
  crates/uv/tests/pip_compile_scenarios.rs
  crates/uv/tests/pip_install_scenarios.rs
  scripts/scenarios/generate.py
  scripts/scenarios/requirements.in
  scripts/scenarios/requirements.txt
Labels: testing

#2417 Add additional ARM targets to release
  .github/workflows/build-binaries.yml
  Cargo.toml
  crates/platform-tags/src/platform.rs
  crates/platform-tags/src/tags.rs
Labels: release

#2471 Make > operator exclude post and local releases
  crates/pep440-rs/src/version.rs
  crates/uv-cache/src/lib.rs
  crates/uv-resolver/src/pubgrub/specifier.rs
  crates/uv/tests/pip_install_scenarios.rs
  scripts/scenarios/generate.py
  scripts/scenarios/requirements.in
Labels: bug

#2474 Update packse to pull in additional post tests
  crates/uv/tests/pip_install_scenarios.rs
  scripts/scenarios/requirements.in
  scripts/scenarios/requirements.txt
Labels: testing

#2473 Remove NumPy from editable test
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_list.rs
  crates/uv/tests/pip_show.rs
  scripts/editable-installs/poetry_editable/pyproject.toml
Labels: testing

#2463 Add test case for URL with basic authentication
  crates/uv/tests/pip_install.rs
Labels: testing

#2431 Introduce a `BaseClient` for construction of canonical configured client
  crates/uv-client/src/base_client.rs
  crates/uv-client/src/cached_client.rs
  crates/uv-client/src/flat_index.rs
  crates/uv-client/src/lib.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-client/tests/netrc_auth.rs
  crates/uv-client/tests/user_agent_version.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/source/mod.rs
Labels: internal

#2485 chore: remove repetitive words
  crates/uv-auth/src/lib.rs
  crates/uv-installer/src/site_packages.rs
Labels: documentation

#2430 Add support for PyTorch-style local version semantics
  PIP_COMPATIBILITY.md
  crates/pep440-rs/src/lib.rs
  crates/pep440-rs/src/version_specifier.rs
  crates/pep508-rs/src/lib.rs
  crates/pep508-rs/src/marker.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/resolver/locals.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/pip_compile_scenarios.rs
  crates/uv/tests/pip_install_scenarios.rs
  scripts/scenarios/generate.py
Labels: bug, enhancement

#2492 Add support for Hatch's `{root:uri}` paths in editable installs
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/src/lib.rs
  crates/uv/tests/pip_compile.rs
  scripts/editable-installs/root_editable/README.md
  scripts/editable-installs/root_editable/pyproject.toml
  scripts/editable-installs/root_editable/root_editable/__init__.py
Labels: compatibility

#2482 Add snapshot test for platform tags
  Cargo.lock
  crates/platform-tags/Cargo.toml
  crates/platform-tags/src/tags.rs
Labels: testing

#2483 Fix priority of platform tags for manylinux
  crates/platform-tags/src/tags.rs
Labels: bug

#2503 Re-add support for pyenv shims
  crates/uv-interpreter/src/interpreter.rs
Labels: bug

#2505 Fix operating system detection on *BSD
  crates/uv-interpreter/python/get_interpreter_info.py
Labels: bug

#2506 Shrink `solve()` a little by moving formatting out
  crates/distribution-types/src/prioritized_distribution.rs
  crates/uv-resolver/src/resolver/mod.rs
Labels: internal

#2380 Add numpy to system import tests
  .github/workflows/ci.yml
  scripts/check_system_python.py
Labels: testing

#2496 Drop `macosx_10_0` from compatible wheel tags on `aarch64`
  crates/platform-tags/src/tags.rs
Labels: bug

#2502 Allow direct file path requirements to include fragments
  crates/pep508-rs/src/lib.rs
  crates/pep508-rs/src/verbatim_url.rs
Labels: bug

#2516 Validate required package names against wheel package names
  crates/distribution-types/src/error.rs
  crates/distribution-types/src/lib.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_sync.rs
Labels: bug

#2480 Tweak `uv pip check` output for consistency with other interfaces
  crates/uv-installer/src/lib.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/pip_check.rs
  crates/uv/tests/pip_check.rs
Labels: internal

#2517 Bump version to v0.1.21
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: release

#2518 Fix wheel builds and uploads for musl ARM
  .github/workflows/build-binaries.yml
Labels: release

#2532 Preserve hashes for pinned packages
  Cargo.lock
  crates/pypi-types/src/simple_json.rs
  crates/uv-client/src/html.rs
  crates/uv-resolver/Cargo.toml
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/manifest.rs
  crates/uv-resolver/src/preferences.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/yanks.rs
  crates/uv-resolver/tests/resolver.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/requirements.rs
  crates/uv/tests/pip_compile.rs
Labels: bug, compatibility

#1968 Add example for compile current env packages
  README.md
Labels: documentation

#2531 Add a system install test for Fedora
  .github/workflows/ci.yml
Labels: testing

#2536 Use `Box<str>` in Hashes to reduce size
  crates/pypi-types/src/simple_json.rs
  crates/uv-client/src/html.rs
Labels: internal

#2535 Add a purelib-only package to the system install tests
  scripts/check_system_python.py
Labels: testing

#2544 Add uv pip check diagnostics to PIP_COMPATIBILITY.md
  PIP_COMPATIBILITY.md
Labels: documentation
