Repository astral-sh/uv, pull requests merged in 2024-02, with the labels that each got.

#1328 Drop license badge for now; cached as UNKNOWN on CDNs
  README.md
Labels: internal

#1345 grammar nit
  README.md
Labels: documentation

#1365 Replace "novel" in README
  README.md
Labels: documentation

#1333 Re-add license badge to the README
  README.md
Labels: documentation

#1381 Fix search for `python.exe` on Windows
  crates/uv-interpreter/src/python_query.rs
Labels: bug, windows

#1380 uv-cache: Add hidden alias for --no-cache-dir
  crates/uv-cache/src/cli.rs
Labels: compatibility

#1383 Add `UV_NO_CACHE` environment variable
  crates/uv-cache/src/cli.rs
Labels: enhancement

#1389 Improve error message for invalid sdist archives
  crates/uv-distribution/src/error.rs
  crates/uv-extract/src/error.rs
  crates/uv-extract/src/sync.rs
Labels: error messages

#1387 Tweak some grammar in the README
  README.md
Labels: documentation

#1385 nit: make bootstrap/install.py executable
  scripts/bootstrap/install.py
Labels: enhancement, internal

#1406 Avoid import contextlib in `_virtualenv`
  crates/gourgeist/src/_virtualenv.py
Labels: performance

#1379 Add `--upgrade` support to `pip install`
  crates/uv-installer/src/plan.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/main.rs
  crates/uv/tests/pip_install.rs
Labels: enhancement

#1394 Add `-U`/`-P` short flags for `--upgrade`/`--upgrade-package`
  crates/uv/src/main.rs
Labels: compatibility

#1409 Add fix-up for trailing comma with trailing space
  crates/pypi-types/src/lenient_requirement.rs
Labels: bug

#1410 Add fix-up for invalid star comparison with major-only version
  crates/pypi-types/src/lenient_requirement.rs
Labels: bug

#1411 Update README.md to include venv activate
  README.md
Labels: documentation

#1421 Parse `-r` and `-c` entries as relative to containing file
  crates/requirements-txt/src/lib.rs
  crates/requirements-txt/test-data/requirements-txt/constraints-a.txt
  crates/uv/tests/pip_compile.rs
Labels: bug

#1428 Ignore invalid extra named `.none`
  crates/pypi-types/src/lenient_requirement.rs
  crates/pypi-types/src/metadata.rs
  crates/uv-normalize/src/lib.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#1423 chore(docs): update wording and add `alt` tag
  README.md
Labels: documentation

#1443 Allow empty fragments in HTML parser
  crates/uv-client/src/html.rs
Labels: bug

#1434 fix(docs): adjust link
  CONTRIBUTING.md
Labels: documentation

#1424 Provide example of file based package install.
  README.md
Labels: documentation

#1459 Fix list rendering in `venv --help` output
  crates/uv/src/main.rs
Labels: bug

#1493 only parse /bin/sh (not /bin/ls)
  crates/platform-host/src/linux.rs
Labels: bug

#1494 Copy over editorconfig and set line ending to LF
  .editorconfig
  .gitattributes
Labels: internal

#1498 Use string display instead of debug for url parse trace
  crates/uv-client/src/html.rs
Labels: tracing

#1435 Support recursive extras
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/pip_install_scenarios.rs
  scripts/scenarios/update.py
Labels: bug

#1334 Add `pip install --constraint` test coverage
  crates/uv/tests/pip_install.rs
Labels: testing

#1519 Add warning for empty requirements files
  Cargo.lock
  crates/requirements-txt/Cargo.toml
  crates/requirements-txt/src/lib.rs
  crates/uv/src/requirements.rs
  crates/uv/tests/pip_install.rs
Labels: error messages, tracing

#1515 Add support for `UV_EXTRA_INDEX_URL`
  crates/uv-dev/src/resolve_cli.rs
  crates/uv/src/main.rs
Labels: enhancement, compatibility

#1529 pypi-types: fix lenient requirement parsing
  crates/pypi-types/src/lenient_requirement.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#1541 Apply percent-decoding to file-based URLs
  Cargo.lock
  Cargo.toml
  crates/uv-fs/Cargo.toml
  crates/uv-fs/src/path.rs
Labels: bug

#1540 change indent to sensible value
  .editorconfig
Labels: internal

#1543 Use comparable representation for `PackageId`
  crates/distribution-types/src/id.rs
  crates/distribution-types/src/traits.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#1544 Apply percent-decoding to filepaths in HTML find-links
  Cargo.lock
  crates/uv-client/Cargo.toml
  crates/uv-client/src/html.rs
Labels: bug

#1507 Fix trailing commas on `Requires-Python` in HTML indexes
  crates/uv-client/src/html.rs
Labels: bug

#1546 Avoid attempting rename in copy fallback path
  crates/install-wheel-rs/src/linker.rs
Labels: bug

#1531 Add support for extras in editable requirements
  crates/uv-resolver/src/resolution.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/pip_compile.rs
  scripts/editable-installs/black_editable/pyproject.toml
Labels: bug

#1555 Remove URL encoding when determining file name
  Cargo.lock
  crates/distribution-types/Cargo.toml
  crates/distribution-types/src/error.rs
  crates/distribution-types/src/lib.rs
  crates/distribution-types/src/traits.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-resolver/src/resolver/mod.rs
Labels: bug

#1556 Support MD5 hashes
  crates/distribution-types/src/lib.rs
  crates/pypi-types/src/simple_json.rs
  crates/uv-client/src/flat_index.rs
  crates/uv-client/src/html.rs
Labels: compatibility

#1425 infra: source github templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#1558 Allow repeated dependencies when installing
  crates/distribution-types/src/lib.rs
  crates/uv-installer/src/plan.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/tests/pip_sync.rs
Labels: bug

#1565 Enforce URL constraints for non-URL dependencies
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#1564 Allow non-nested archives for `hexdump` and others
  crates/uv-build/src/lib.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-extract/src/error.rs
  crates/uv-extract/src/sync.rs
Labels: compatibility

#1568 Improve tracing when encountering invalid `requires-python` values
  crates/distribution-types/src/file.rs
  crates/pep440-rs/src/version_specifier.rs
Labels: error messages, tracing

#1590 Always run `get_requires_for_build_wheel`
  crates/uv-build/src/lib.rs
Labels: bug

#1574 Add graceful fallback for Artifactory indexes
  Cargo.lock
  Cargo.toml
  crates/uv-client/src/error.rs
  crates/uv-client/src/registry_client.rs
Labels: bug

#1577 Consistent use of `BIN_NAME` in activation scripts
  crates/gourgeist/src/activator/activate
  crates/gourgeist/src/activator/activate.csh
  crates/gourgeist/src/activator/activate.fish
  crates/gourgeist/src/activator/activate.nu
  crates/gourgeist/src/activator/activate_this.py
Labels: bug

#1322 Change benchmarks to use 3.12.1
  scripts/bench/__main__.py
Labels: internal

#1607 Avoid propagating top-level options to sub-resolutions
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/venv.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#1610 Add license to activator scripts
  crates/gourgeist/src/activator/activate
  crates/gourgeist/src/activator/activate.csh
  crates/gourgeist/src/activator/activate.fish
  crates/gourgeist/src/activator/activate.nu
  crates/gourgeist/src/activator/activate.ps1
  crates/gourgeist/src/activator/activate_this.py
Labels: documentation

#1614 Allow URL requirements in editable installs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/pip_compile.rs
  scripts/editable-installs/hatchling_editable/README.md
  scripts/editable-installs/hatchling_editable/hatchling_editable/__init__.py
  scripts/editable-installs/hatchling_editable/pyproject.toml
  scripts/editable-installs/poetry_editable/pyproject.toml
Labels: bug

#1523 Add CMD support
  crates/gourgeist/src/activator/.gitattributes
  crates/gourgeist/src/activator/activate.bat
  crates/gourgeist/src/activator/deactivate.bat
  crates/gourgeist/src/activator/pydoc.bat
  crates/gourgeist/src/bare.rs
  crates/uv-trampoline/src/bounce.rs
  crates/uv-trampoline/trampolines/uv-trampoline-aarch64-console.exe
  crates/uv-trampoline/trampolines/uv-trampoline-aarch64-gui.exe
  crates/uv-trampoline/trampolines/uv-trampoline-x86_64-console.exe
  crates/uv-trampoline/trampolines/uv-trampoline-x86_64-gui.exe
Labels: windows, compatibility

#1629 Add brew to readme
  README.md
Labels: documentation

#1649 Do not remove uv itself on pip sync
  crates/uv-installer/src/plan.rs
Labels: bug

#1653 Add `CACHEDIR.TAG` to uv-created virtualenvs
  Cargo.lock
  crates/gourgeist/Cargo.toml
  crates/gourgeist/src/bare.rs
Labels: enhancement

#1664 Minimal markdown nits
  BENCHMARKS.md
  CONTRIBUTING.md
Labels: documentation

#1628 Build source distributions in the cache directory instead of the global temporary directory
  crates/uv-build/src/lib.rs
Labels: bug

#1613 Remove setuptools & wheel from seed packages (#1602)
  crates/uv/src/commands/venv.rs
  crates/uv/tests/venv.rs
Labels: compatibility, virtualenv

#1667 Ensure we retain existing environment variables during `python -m uv`
  python/uv/__main__.py
Labels: bug

#1611 Add smoke test to CI
  .github/workflows/ci.yml
Labels: testing

#1668 fix: use --override rather than -o to specify overrides in README.md
  README.md
Labels: documentation

#1669 Add yank warnings at end of messages
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/tests/pip_install_scenarios.rs
  crates/uv/tests/pip_sync.rs
Labels: error messages

#1670 Document RUST_LOG=trace for additional logging verbosity
  CONTRIBUTING.md
Labels: documentation

#1672 Document local testing instructions
  CONTRIBUTING.md
Labels: documentation

#1675 Add shell completions generation
  Cargo.lock
  Cargo.toml
  crates/uv/Cargo.toml
  crates/uv/src/main.rs
Labels: cli

#1622 Support dotted function paths for script entrypoints
  crates/install-wheel-rs/src/script.rs
  crates/install-wheel-rs/src/wheel.rs
  crates/uv/tests/pip_sync.rs
Labels: bug

#1570 Support `venv --prompt`
  crates/gourgeist/src/activator/activate
  crates/gourgeist/src/activator/activate.bat
  crates/gourgeist/src/activator/activate.csh
  crates/gourgeist/src/activator/activate.fish
  crates/gourgeist/src/activator/activate.nu
  crates/gourgeist/src/activator/activate.ps1
  crates/gourgeist/src/bare.rs
  crates/gourgeist/src/lib.rs
  crates/gourgeist/src/main.rs
  crates/uv-build/src/lib.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/main.rs
Labels: enhancement

#1716 fix: remove uv version from uv pip compile header
  README.md
  crates/uv/src/commands/pip_compile.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_compile_scenarios.rs
  scripts/bench/requirements.txt
  scripts/requirements/compiled/all-kinds.txt
  scripts/requirements/compiled/black.txt
  scripts/requirements/compiled/boto3.txt
  scripts/requirements/compiled/dtlssocket.txt
  scripts/requirements/compiled/flyte.txt
  scripts/requirements/compiled/jupyter.txt
  scripts/requirements/compiled/pdm_2193.txt
  scripts/requirements/compiled/scispacy.txt
  scripts/requirements/compiled/trio.txt
Labels: compatibility

#1720 Preserve trailing slash for `--find-links` URLs
  crates/uv-client/src/flat_index.rs
Labels: bug

#1605 Update the scenarios to use vendored build dependencies
  crates/uv/tests/pip_compile_scenarios.rs
  crates/uv/tests/pip_install_scenarios.rs
  scripts/scenarios/templates/compile.mustache
  scripts/scenarios/templates/install.mustache
  scripts/scenarios/update.py
Labels: testing

#1721 Add Insta's pending snapshots to .gitignore
  .gitignore
Labels: internal

#1719 Respect `--index-url` provided via requirements.txt
  Cargo.lock
  crates/distribution-types/Cargo.toml
  crates/distribution-types/src/index_url.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-dev/src/resolve_cli.rs
  crates/uv/src/main.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#1650 Add warning when dependencies are empty with Poetry metadata
  crates/uv/src/requirements.rs
  crates/uv/tests/pip_compile.rs
Labels: error messages

#1725 Add support for absolute paths on Windows
  crates/distribution-types/src/error.rs
  crates/distribution-types/src/index_url.rs
  crates/distribution-types/src/lib.rs
  crates/pep508-rs/src/lib.rs
  crates/pep508-rs/src/verbatim_url.rs
  crates/requirements-txt/src/lib.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#1729 Support recursive extras for URL dependencies
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#1730 Improve Poetry warning
  crates/uv/src/requirements.rs
  crates/uv/tests/pip_compile.rs
Labels: error messages

#1731 Ignore invalid extras from PyPI
  crates/pypi-types/src/lenient_requirement.rs
  crates/pypi-types/src/metadata.rs
Labels: compatibility

#1727 Ensure extras trigger an install
  crates/uv-installer/src/site_packages.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#1732 Use `httpx` instead of `anyio` for reinstall test
  crates/uv/tests/pip_install.rs
Labels: internal

#1733 Move `uv clean` to `uv cache clean`
  README.md
  crates/uv/src/main.rs
Labels: cli

#1734 Implement `uv cache dir`
  crates/uv/src/commands/cache_clean.rs
  crates/uv/src/commands/cache_dir.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/pip_freeze.rs
  crates/uv/src/main.rs
Labels: enhancement, cli

#1694 Control pip timeout duration via environment variable
  Cargo.lock
  crates/uv-client/Cargo.toml
  crates/uv-client/src/registry_client.rs
Labels: configuration

#1735 Allow `-f` alias for `--find-links`
  crates/uv/src/main.rs
Labels: compatibility

#1751 Clarify Windows install command in README.md
  README.md
Labels: documentation

#1755 Set index URLs for seeding venv
  crates/uv/src/commands/venv.rs
Labels: bug

#1745 feat: allow passing in a custom reqwest Client
  crates/uv-client/src/registry_client.rs
Labels: enhancement

#1742 Fix typos configuration
  _typos.toml
  crates/uv-client/src/flat_index.rs
  crates/uv/tests/pip_install_scenarios.rs
Labels: bug

#1749 Don't preserve timestamp in streaming unzip
  crates/uv-extract/src/stream.rs
  crates/uv/tests/pip_sync.rs
Labels: bug

#1728 Expose find_uv_bin and declare typing support
  python/uv/__init__.py
  python/uv/__main__.py
  python/uv/py.typed
Labels: enhancement

#1765 docs(readme): add instructions for installing on Arch Linux
  README.md
Labels: documentation

#1756 Skip compile_html test on musl
  .gitignore
  crates/uv/tests/pip_compile.rs
Labels: musl

#1746 Better error message for missing space before semicolon in requirements
  crates/pep508-rs/src/lib.rs
Labels: error messages

#1762 feat: add installer to `InstalledDist`
  crates/distribution-types/src/installed.rs
Labels: internal

#1770 If-let instead of unwrap (PR #1746 follow-up)
  crates/pep508-rs/src/lib.rs
Labels: internal

#1739 Backport changes from publish crates
  Cargo.lock
  Cargo.toml
  crates/pep440-rs/Cargo.toml
  crates/pep440-rs/Readme.md
  crates/pep440-rs/src/lib.rs
  crates/pep440-rs/src/version.rs
  crates/pep440-rs/src/version_specifier.rs
  crates/pep508-rs/Cargo.toml
  crates/pep508-rs/src/lib.rs
  crates/pep508-rs/src/marker.rs
  crates/pep508-rs/src/verbatim_url.rs
  crates/requirements-txt/Cargo.toml
  crates/uv-normalize/Cargo.toml
  crates/uv-normalize/src/extra_name.rs
  crates/uv-normalize/src/lib.rs
  crates/uv-normalize/src/package_name.rs
Labels: internal

#1778 Fix pep508-rs tests without features
  crates/pep508-rs/src/lib.rs
Labels: internal

#1776 Add support for `>dev` specifier
  crates/pypi-types/src/lenient_requirement.rs
Labels: bug

#1717 Retain passwords in Git URLs
  Cargo.lock
  crates/cache-key/src/canonical_url.rs
  crates/uv-git/src/lib.rs
  crates/uv/Cargo.toml
  crates/uv/tests/common/mod.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#1780 Support setting request timeout with `UV_HTTP_TIMEOUT` and `HTTP_TIMEOUT`
  crates/uv-client/src/registry_client.rs
Labels: enhancement

#1679 feat: Implement `--annotation-style` parameter for `uv pip compile`
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/compat/mod.rs
  crates/uv/src/main.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/pip_compile.rs
Labels: configuration

#1792 Stream zip archive when fetching non-range-request metadata
  crates/install-wheel-rs/src/lib.rs
  crates/uv-client/src/error.rs
  crates/uv-client/src/registry_client.rs
Labels: enhancement

#1772 Configurable bootstrap dir
  CONTRIBUTING.md
  crates/uv/tests/common/mod.rs
  scripts/bootstrap/install.py
Labels: internal

#1809 Use async unzip for local source distributions
  Cargo.lock
  Cargo.toml
  crates/uv-build/src/lib.rs
  crates/uv-extract/Cargo.toml
  crates/uv-extract/src/sync.rs
Labels: internal

#1790 Preserve executable bit when untarring archives
  crates/uv-extract/src/lib.rs
  crates/uv-extract/src/stream.rs
  crates/uv-extract/src/tar.rs
Labels: bug

#1812 Wait for distribution metadata with `--no-deps`
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#1816 Use redirected URL as base for relative paths
  crates/uv-client/src/flat_index.rs
  crates/uv-client/src/registry_client.rs
Labels: bug

#1817 Normalize `VIRTUAL_ENV` path in activation scripts
  Cargo.lock
  crates/gourgeist/Cargo.toml
  crates/gourgeist/src/bare.rs
Labels: bug, windows

#1820 Upgrade to Rust 1.76
  crates/uv-resolver/tests/resolver.rs
  rust-toolchain.toml
Labels: internal

#1822 Sort output when installing seed packages
  crates/uv/src/commands/venv.rs
  crates/uv/tests/venv.rs
Labels: bug

#1781 Use `git` command to fetch repositories instead of `libgit2` for robust SSH support
  crates/uv-git/src/git.rs
  crates/uv-git/src/source.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#1825 Add fixup for `prefect<1.0.0`
  crates/pypi-types/src/lenient_requirement.rs
Labels: bug

#1826 Improve error message when git ref cannot be fetched
  crates/uv-git/src/git.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/pip_install.rs
Labels: error messages

#1843 Treat ARM wheels as higher-priority than universal
  crates/platform-tags/src/lib.rs
Labels: bug

#1806 [docs] Update README.md to include extras example
  README.md
Labels: documentation

#1796 Move conflicting dependencies into PubGrub
  Cargo.lock
  Cargo.toml
  crates/uv-dev/src/resolve_cli.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-resolver/src/constraints.rs
  crates/uv-resolver/src/editables.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/overrides.rs
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/pubgrub/package.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv-resolver/src/resolver/allowed_urls.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/urls.rs
  crates/uv-resolver/tests/resolver.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_install_scenarios.rs
Labels: bug

#1844 Add docs for git authentication
  README.md
Labels: documentation

#1847 Don't expect pinned packages for editables with non-existent extras
  crates/uv-resolver/src/resolution.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#1773 Linker copies files as a fallback when ref-linking fails
  crates/install-wheel-rs/src/linker.rs
Labels: bug, installer

#1711 Search `PATH` when `python` can't be found with `py`
  crates/uv-interpreter/src/interpreter.rs
  crates/uv-interpreter/src/lib.rs
  crates/uv-interpreter/src/python_query.rs
  crates/uv-interpreter/src/virtual_env.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/venv.rs
Labels: compatibility

#1811 Use more universal windows install instructions
  README.md
Labels: documentation

#1862 fix: expose types to implement custom `ResolverProvider`
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv-resolver/src/version_map.rs
Labels: rustlib

#1877 Allow duplicate URLs that resolve to the same canonical URL
  crates/uv-resolver/src/resolver/urls.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#1874 Retain authentication attached to URLs when making requests to the same host
  crates/uv-client/src/auth.rs
  crates/uv-client/src/flat_index.rs
  crates/uv-client/src/lib.rs
  crates/uv-client/src/registry_client.rs
Labels: bug

#1852 feat: allow passing extra config k,v pairs for pyvenv.cfg when creating a venv
  crates/gourgeist/src/bare.rs
  crates/gourgeist/src/lib.rs
  crates/gourgeist/src/main.rs
  crates/uv-build/src/lib.rs
  crates/uv/src/commands/venv.rs
  crates/uv/tests/venv.rs
Labels: enhancement, virtualenv

#1882 Allow skipping binary builds with `no-build` label
  .github/workflows/build-binaries.yml
Labels: no-build

#1881 Add changelog
  CHANGELOG.md
  CONTRIBUTING.md
  crates/uv/Cargo.toml
  pyproject.toml
  scripts/release/bump.sh
  scripts/release/requirements.in
  scripts/release/requirements.txt
Labels: documentation, no-build

#1887 Disable fail-fast during CI jobs
  .github/workflows/ci.yml
Labels: internal

#1888 Use `rustls-tls-native-roots` in `uv` crate
  crates/uv/Cargo.toml
Labels: bug

#1835 Hide index URLs from header if not emitted
  crates/uv/src/commands/pip_compile.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_compile_scenarios.rs
Labels: compatibility

#1894 Add #1835 to the changelog
  CHANGELOG.md
Labels: documentation

#1892 Write to stdout when `--output-file` is present
  crates/uv/src/commands/pip_compile.rs
  crates/uv/tests/pip_compile.rs
Labels: compatibility, cli

#1898 Omit `--find-links` from annotation header unless requested
  crates/uv/src/commands/pip_compile.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_compile_scenarios.rs
Labels: bug, compatibility

#1905 Ignore Python 2 installations when querying for interpreters
  crates/uv-interpreter/src/get_interpreter_info.py
  crates/uv-interpreter/src/interpreter.rs
  crates/uv-interpreter/src/lib.rs
  crates/uv-interpreter/src/python_query.rs
Labels: bug

#1885 Fix windows py spurious stderr failure
  crates/uv-interpreter/src/python_query.rs
Labels: bug, windows

#1908 Fix uv-created venv detection
  crates/uv-installer/src/plan.rs
  crates/uv-interpreter/src/cfg.rs
  crates/uv-interpreter/src/lib.rs
  crates/uv-interpreter/src/virtual_env.rs
Labels: bug

#1923 Bump version to 0.1.10
  CHANGELOG.md
  Cargo.lock
  crates/uv/Cargo.toml
  pyproject.toml
Labels: internal

#1918 Generate versioned pip launchers
  crates/install-wheel-rs/src/linker.rs
  crates/install-wheel-rs/src/script.rs
  crates/install-wheel-rs/src/wheel.rs
  crates/uv/tests/pip_sync.rs
Labels: bug, compatibility

#1909 Improve interpreter discovery logging
  crates/gourgeist/src/interpreter.rs
  crates/gourgeist/src/lib.rs
  crates/gourgeist/src/main.rs
  crates/uv-interpreter/src/interpreter.rs
  crates/uv-interpreter/src/python_query.rs
  crates/uv-interpreter/src/python_version.rs
  crates/uv/src/confirm.rs
  crates/uv/src/main.rs
Labels: enhancement, windows

#1889 Add support for pip-compile's `--unsafe-package` flag
  crates/uv-resolver/src/resolution.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/compat/mod.rs
  crates/uv/src/main.rs
  crates/uv/tests/pip_compile.rs
Labels: enhancement, compatibility

#1893 Gracefully handle virtual environments with conflicting packages
  crates/distribution-types/src/lib.rs
  crates/uv-installer/src/plan.rs
  crates/uv-installer/src/site_packages.rs
  crates/uv/src/commands/pip_freeze.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/src/commands/pip_uninstall.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/pip_freeze.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_uninstall.rs
Labels: bug

#1926 Add dependabot config
  .github/dependabot.yml
Labels: internal

#1930 Add long-form version output
  Cargo.lock
  crates/uv/Cargo.toml
  crates/uv/build.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/version.rs
  crates/uv/src/main.rs
  crates/uv/src/version.rs
Labels: cli

#1933 Add compatibility for deprecated `python_implementation` marker
  crates/pep508-rs/src/marker.rs
Labels: bug, compatibility

#1944 Avoid erroring for source distributions with symlinks in archive
  Cargo.lock
  crates/uv-extract/Cargo.toml
  crates/uv-extract/src/stream.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#1955 Invalidate dependencies when editables are updated
  crates/uv-cache/src/lib.rs
  crates/uv-installer/src/site_packages.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#1956 Properly apply constraints in venv audit
  crates/uv-installer/src/site_packages.rs
Labels: bug

#1954 docs: clarify lowest vs lowest-direct resolutions
  README.md
Labels: documentation

#1878 Make < exclusive for non-prerelease markers
  crates/pep440-rs/src/version.rs
  crates/uv-cache/src/lib.rs
  crates/uv-resolver/src/prerelease_mode.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/pubgrub/specifier.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_compile_scenarios.rs
  crates/uv/tests/pip_install_scenarios.rs
  requirements.in
  scripts/scenarios/update.py
Labels: bug

#1960 Expand scope of archive timestamping
  crates/uv-cache/src/lib.rs
Labels: bug
