Repository astral-sh/uv, pull requests merged in 2024-07, with the labels that each got.

#4684 Log when we start solving a fork
  crates/uv-resolver/src/resolver/mod.rs
Labels: preview

#4686 Fix tool dist-info directory normalization
  crates/uv-tool/src/lib.rs
Labels: bug, preview

#4656 Add PEP 723 support to uv run
  Cargo.lock
  Cargo.toml
  crates/uv-requirements/src/specification.rs
  crates/uv-scripts/Cargo.toml
  crates/uv-scripts/src/lib.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/run.rs
Labels: preview

#4662 Set fork solution as preference when resolving
  crates/uv-resolver/src/preferences.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/lock_scenarios.rs
Labels: performance, preview

#4658 DRY up some project interpreter validation and discovery
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/run.rs
Labels: internal, preview

#4690 Use a single mutable preferences for forks
  crates/uv-resolver/src/resolver/mod.rs
Labels: internal

#4697 Reinstall entrypoints with `--force`
  crates/uv/src/commands/tool/install.rs
  crates/uv/tests/tool_install.rs
Labels: bug, preview

#4695 Add `tool dir` and `toolchain dir` commands
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/cache_dir.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/tool/dir.rs
  crates/uv/src/commands/tool/mod.rs
  crates/uv/src/commands/toolchain/dir.rs
  crates/uv/src/commands/toolchain/mod.rs
  crates/uv/src/main.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/tool_dir.rs
  crates/uv/tests/toolchain_dir.rs
Labels: cli, preview

#4693 Respect data scripts in `uv tool install`
  Cargo.lock
  crates/install-wheel-rs/src/lib.rs
  crates/install-wheel-rs/src/linker.rs
  crates/install-wheel-rs/src/record.rs
  crates/install-wheel-rs/src/script.rs
  crates/install-wheel-rs/src/wheel.rs
  crates/uv-tool/Cargo.toml
  crates/uv-tool/src/lib.rs
  crates/uv/tests/tool_uninstall.rs
Labels: bug, preview

#4694 Show dedicated message for tools with no entrypoints
  crates/uv/src/commands/tool/install.rs
  crates/uv/tests/tool_install.rs
Labels: cli, preview

#4683 Remove `SolveState` to `ForkState`
  crates/uv-resolver/src/resolver/mod.rs
Labels: internal

#4621 implement `--invert` for `pip tree`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/pip/tree.rs
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
  crates/uv/tests/pip_tree.rs
Labels: cli

#4698 Fix implementation of `GitDatabase::contains`
  crates/uv-git/src/git.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#4701 Use `requires-python` semantics for `--universal`
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/python_requirement.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/tests/lock.rs
Labels: internal

#4704 Simplify `OnceMap::wait_blocking`
  crates/once-map/src/lib.rs
Labels: internal

#4702 More `uv pip tree` cleanup
  crates/uv-installer/src/site_packages.rs
  crates/uv/src/commands/pip/tree.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/pip_tree.rs
Labels: internal

#4703 Replace `map_or(false, ..)` uses with `is_some_and` and `is_ok_and`
  crates/requirements-txt/src/lib.rs
  crates/uv-client/src/httpcache/control.rs
  crates/uv-fs/src/lib.rs
  crates/uv-installer/src/site_packages.rs
  crates/uv-toolchain/src/managed.rs
  crates/uv/src/commands/project/run.rs
Labels: internal

#4565 Enable projects to opt-out of workspace management
  crates/uv-distribution/src/pyproject.rs
  crates/uv-distribution/src/workspace.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/run.rs
  crates/uv/tests/workspace.rs
  scripts/workspaces/albatross-project-in-excluded/packages/seeds/pyproject.toml
  scripts/workspaces/albatross-project-in-excluded/packages/seeds/src/seeds/__init__.py
  uv.schema.json
Labels: preview

#4713 Add lockfile snapshots for branching URL tests
  crates/uv/tests/branching_urls.rs
Labels: testing

#4715 Shared Git and in-memory index across operations
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
Labels: internal

#4716 Support unnamed requirements in `uv tool install`
  Cargo.lock
  crates/uv-requirements/src/specification.rs
  crates/uv-tool/Cargo.toml
  crates/uv-tool/src/tool.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/main.rs
  crates/uv/tests/tool_install.rs
Labels: enhancement, preview

#4632 Add `uvx` alias for `uv tool run`
  crates/uv/src/bin/uvx.rs
Labels: cli, preview

#4601 Allow configuring the toolchain fetch strategy
  crates/uv-cli/src/lib.rs
  crates/uv-settings/src/combine.rs
  crates/uv-settings/src/settings.rs
  crates/uv-toolchain/src/discovery.rs
  crates/uv-toolchain/src/downloads.rs
  crates/uv-toolchain/src/lib.rs
  crates/uv-toolchain/src/toolchain.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/commands/toolchain/install.rs
  crates/uv/src/commands/toolchain/list.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/pip_tree.rs
  crates/uv/tests/show_settings.rs
  uv.schema.json
Labels: configuration, preview

#4602 Drop `prefer` prefix from `toolchain-preference` values
  crates/uv-toolchain/src/discovery.rs
  crates/uv-toolchain/src/toolchain.rs
  crates/uv/tests/common/mod.rs
  uv.schema.json
Labels: configuration, preview

#4717 Fetch managed toolchains if necessary in `uv tool install` and `uv tool run`
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
Labels: enhancement, preview

#4646 Add `uv toolchain uninstall`
  crates/uv-cli/src/lib.rs
  crates/uv-toolchain/src/implementation.rs
  crates/uv-toolchain/src/managed.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/toolchain/install.rs
  crates/uv/src/commands/toolchain/mod.rs
  crates/uv/src/commands/toolchain/uninstall.rs
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
Labels: cli, preview

#4727 Omit pythonX.Y segment in stdlib on managed Windows
  crates/uv-toolchain/src/managed.rs
Labels: bug, windows

#4586 Restructure documentation sections to focus on new user experience
  docs/SUMMARY.md
  docs/guides/install-python.md
  docs/guides/project.md
  docs/guides/projects.md
  docs/guides/scripts.md
  docs/guides/tools.md
  docs/pip/environments.md
  docs/preview/toolchains.md
  docs/python/discovery.md
  docs/style.css
Labels: documentation, preview

#4725 Show when we retried requests
  Cargo.lock
  Cargo.toml
  crates/uv-client/src/error.rs
  crates/uv-client/src/lib.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution/src/error.rs
  crates/uv-toolchain/src/downloads.rs
  crates/uv/src/commands/self_update.rs
Labels: error messages, network

#4733 Lock the toolchains directory during toolchain operations
  crates/uv-toolchain/src/managed.rs
  crates/uv-toolchain/src/toolchain.rs
  crates/uv/src/commands/toolchain/install.rs
  crates/uv/src/commands/toolchain/uninstall.rs
Labels: enhancement, preview

#4737 Accept package names in the tool API
  crates/uv-cli/src/lib.rs
  crates/uv-tool/src/lib.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/uninstall.rs
  crates/uv/src/settings.rs
Labels: internal

#4736 Respect tool upgrades in `uv tool install`
  Cargo.lock
  crates/pypi-types/src/requirement.rs
  crates/uv-tool/Cargo.toml
  crates/uv-tool/src/tool.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/tool_install.rs
Labels: preview

#4740 Remove dangling environments in `tool uninstall`
  crates/uv/src/commands/tool/uninstall.rs
  crates/uv/tests/tool_uninstall.rs
Labels: preview

#4738 Bump version to 0.2.19
  CHANGELOG.md
  Cargo.lock
  PREVIEW-CHANGELOG.md
  README.md
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: release

#4743 Add `uvx` to binary artifacts
  .github/workflows/build-binaries.yml
Labels: release

#4745 Bump version to 0.2.20
  CHANGELOG.md
  Cargo.lock
  PREVIEW-CHANGELOG.md
  README.md
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: release

#4746 Replace tool environments on updated Python request
  crates/uv-tool/src/lib.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/tests/tool_install.rs
Labels: enhancement, preview

#4744 Add test cases for `uvx` in binary build workflow
  .github/workflows/build-binaries.yml
Labels: testing, release

#4751 Differentiate `freeze` and `list` help text
  crates/uv-cli/src/lib.rs
Labels: documentation, cli

#4756 Add `uvx.exe` binary to Windows artifacts
  .github/workflows/build-binaries.yml
Labels: release

#4757 Bump version to 0.2.21
  CHANGELOG.md
  Cargo.lock
  PREVIEW-CHANGELOG.md
  README.md
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: release

#4761 Reactivate python 3.13 in CI
  .github/workflows/ci.yml
Labels: internal

#4767 Make `path_with_trailing_space_gives_proper_error` language independent
  crates/uv/tests/venv.rs
Labels: internal, windows

#4771 Avoid resetting dispatch and in-flight state with reinstalls
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/mod.rs
Labels: internal

#4778 Make in-flight part of shared state struct
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/commands/venv.rs
Labels: internal

#4775 Use optimized versions of managed Python on Linux
  crates/uv-python/download-metadata.json
  crates/uv-python/fetch-download-metadata.py
  crates/uv-python/src/downloads.inc
Labels: bug, preview

#4773 Drop the crate description from the `uv` help menu
  crates/uv-cli/src/lib.rs
Labels: cli

#4750 Use already-installed tools in `uv tool run`
  Cargo.lock
  crates/uv/Cargo.toml
  crates/uv/src/commands/tool/common.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/mod.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/tool_run.rs
Labels: preview

#4782 Update "about" in help menu
  crates/uv-cli/src/lib.rs
Labels: cli

#4780 Improvements to the Python metadata fetch script
  crates/uv-python/fetch-download-metadata.py
Labels: internal

#4770 Add dedicated help menu for `uvx`
  crates/uv-cli/src/lib.rs
  crates/uv/src/bin/uvx.rs
  crates/uv/src/main.rs
Labels: cli, preview

#4768 Box clap commands to avoid windows debug clap stack overflow
  crates/uv-cli/src/lib.rs
  crates/uv/src/main.rs
Labels: internal, windows

#4785 Add `--exclude-newer` to installer arguments
  crates/uv-cli/src/lib.rs
  crates/uv-cli/src/options.rs
  crates/uv-settings/src/settings.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/settings.rs
Labels: cli

#4783 Fix misleading description contains docstring
  crates/pep440-rs/src/version_specifier.rs
Labels: documentation

#4790 Always use exact semantics in `update_environment`
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
Labels: internal

#4792 Upgrade to cargo-dist v0.18.0
  .github/workflows/release.yml
  Cargo.toml
Labels: release

#4784 Cache tool environments in `uv tool run`
  Cargo.lock
  crates/cache-key/src/lib.rs
  crates/uv-cache/src/lib.rs
  crates/uv-python/src/interpreter.rs
  crates/uv-state/src/lib.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/project/ephemeral.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/tool_run.rs
Labels: enhancement, preview

#4793 Avoid hangs before exiting CLI
  crates/uv/src/main.rs
Labels: bug

#4798 Document the `RequiresPython` fields
  crates/uv-resolver/src/requires_python.rs
Labels: internal

#4788 Resolve requirements prior to nuking tool environments
  crates/uv/src/commands/tool/install.rs
  crates/uv/tests/tool_install.rs
Labels: bug, preview

#4804 Rename `EphemeralEnvironment` to `CachedEnvironment`
  crates/uv/src/commands/cache_dir.rs
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/python/dir.rs
  crates/uv/src/commands/python/find.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/src/commands/python/uninstall.rs
  crates/uv/src/commands/self_update.rs
  crates/uv/src/commands/tool/dir.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/commands/tool/uninstall.rs
  crates/uv/src/version.rs
  crates/uv/tests/python_dir.rs
  crates/uv/tests/tool_dir.rs
  crates/uv/tests/tool_install.rs
  crates/uv/tests/tool_list.rs
  crates/uv/tests/tool_uninstall.rs
Labels: internal

#4807 Remove installed python for force installation
  crates/uv/src/commands/python/install.rs
Labels: bug

#4729 Enable Registry Client Builder to be created from Base Client Builder
  crates/uv-client/src/registry_client.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/venv.rs
Labels: internal

#4796 Box clap args some more for `uv init`
  crates/uv-cli/src/lib.rs
  crates/uv/src/main.rs
Labels: internal

#4805 Always use base interpreter for cached environments
  crates/uv-python/src/interpreter.rs
  crates/uv/src/commands/project/environment.rs
Labels: enhancement, preview

#4806 Check hash of downloaded python toolchain
  crates/uv-python/src/downloads.rs
Labels: enhancement, security

#4799 Remove incompatible wheels from `uv.lock`
  crates/distribution-filename/src/wheel.rs
  crates/uv-resolver/src/lock.rs
  crates/uv/tests/edit.rs
  crates/uv/tests/lock.rs
Labels: enhancement, preview

#4794 Always use release-only comparisons for `requires-python`
  PIP_COMPATIBILITY.md
  crates/pep440-rs/src/version.rs
  crates/uv-resolver/src/marker.rs
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/pubgrub/specifier.rs
  crates/uv-resolver/src/python_requirement.rs
  crates/uv-resolver/src/requires_python.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_compile_scenarios.rs
Labels: bug

#4811 Tweak installation language in toolchain install
  crates/uv-python/src/downloads.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/src/commands/python/uninstall.rs
Labels: cli, preview

#4820 Require at least one target for toolchain uninstalls
  crates/uv-cli/src/lib.rs
Labels: cli, preview

#4836 Add `UV_OVERRIDE` environment variable for `--override`
  README.md
  crates/uv-cli/src/lib.rs
  crates/uv/src/settings.rs
Labels: configuration

#4837 Fix some ephemeral-to-cached comments
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/commands/tool/run.rs
Labels: internal, no-build

#4810 Fill Python requests with platform information during automatic fetches
  crates/uv-python/src/installation.rs
Labels: bug

#4838 Preserve verbatim URLs for `--find-links`
  crates/distribution-types/src/index_url.rs
  crates/requirements-txt/src/lib.rs
  crates/uv-client/src/flat_index.rs
  crates/uv-distribution/src/index/registry_wheel_index.rs
  crates/uv-requirements/src/specification.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/show_settings.rs
Labels: bug

#4818 Bold durations in CLI messages
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/pip/check.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/uninstall.rs
Labels: bug, cli

#4841 Deduplicate when install or uninstall python
  crates/uv-python/src/implementation.rs
  crates/uv-python/src/installation.rs
  crates/uv-python/src/managed.rs
  crates/uv-python/src/platform.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/src/commands/python/uninstall.rs
Labels: bug, preview

#4849 Create empty environment for `uv run --isolated`
  crates/uv/src/commands/project/run.rs
Labels: bug, preview

#4845 `uv cache prune` removes all cached environments
  crates/uv-cache/src/lib.rs
  crates/uv/tests/cache_prune.rs
  crates/uv/tests/common/mod.rs
Labels: enhancement, preview

#4850 Update trampolines
  crates/uv-trampoline/trampolines/uv-trampoline-aarch64-console.exe
  crates/uv-trampoline/trampolines/uv-trampoline-aarch64-gui.exe
  crates/uv-trampoline/trampolines/uv-trampoline-i686-console.exe
  crates/uv-trampoline/trampolines/uv-trampoline-i686-gui.exe
  crates/uv-trampoline/trampolines/uv-trampoline-x86_64-console.exe
  crates/uv-trampoline/trampolines/uv-trampoline-x86_64-gui.exe
Labels: windows

#4856 Remove dead code from tests
  crates/uv/tests/pip_install.rs
Labels: internal

#4859 Rename `Workspace.root` to `Workspace.install_path`
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-distribution/src/workspace.rs
  crates/uv-requirements/src/upgrade.rs
  crates/uv-resolver/src/lock.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/main.rs
Labels: internal

#4862 Bump version to v0.2.22
  CHANGELOG.md
  Cargo.lock
  PREVIEW-CHANGELOG.md
  README.md
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: release

#4863 Ignore `compile_invalid_pyc_invalidation_mode` on all platforms
  crates/uv/tests/pip_sync.rs
Labels: internal

#4840 Add progress bar when downloading python
  Cargo.lock
  crates/uv-python/Cargo.toml
  crates/uv-python/src/downloads.rs
  crates/uv-python/src/installation.rs
  crates/uv-python/src/lib.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/src/commands/reporters.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/commands/venv.rs
Labels: cli, preview

#4866 Fix always-plural message in uv python install
  crates/uv/src/commands/python/install.rs
Labels: cli, preview

#4868 Avoid creating cache directories in tool directory
  crates/uv/src/commands/tool/list.rs
  crates/uv/src/main.rs
Labels: bug

#4864 Update windows binaries, again
  crates/uv-trampoline/trampolines/uv-trampoline-aarch64-console.exe
  crates/uv-trampoline/trampolines/uv-trampoline-aarch64-gui.exe
  crates/uv-trampoline/trampolines/uv-trampoline-i686-console.exe
  crates/uv-trampoline/trampolines/uv-trampoline-i686-gui.exe
  crates/uv-trampoline/trampolines/uv-trampoline-x86_64-console.exe
  crates/uv-trampoline/trampolines/uv-trampoline-x86_64-gui.exe
Labels: enhancement, windows

#4851 `Box::pin(run())` and 2MB test stack
  crates/uv/src/main.rs
  crates/uv/tests/common/mod.rs
Labels: internal, windows

#4879 Skip installing `--with` requirements if present in base environment
  crates/uv-installer/src/site_packages.rs
  crates/uv-python/src/environment.rs
  crates/uv-python/src/interpreter.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/run.rs
Labels: enhancement, preview

#4884 Ensure Pythons are aligned in `uv python list`
  crates/uv/src/commands/python/list.rs
Labels: cli, preview

#4881 Add user-facing output to indicate PEP 723 script
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/run.rs
Labels: cli, preview

#4865 Add some decoration to tool CLI
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/list.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/commands/tool/uninstall.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/tool_install.rs
  crates/uv/tests/tool_list.rs
  crates/uv/tests/tool_uninstall.rs
Labels: cli, preview

#4880 Show user-facing warning when falling back to copy installs
  Cargo.lock
  crates/install-wheel-rs/Cargo.toml
  crates/install-wheel-rs/src/linker.rs
  crates/uv/tests/pip_sync.rs
Labels: error messages

#4894 Small forking log improvements
  crates/uv-resolver/src/resolver/mod.rs
Labels: tracing

#4882 Add some text decoration to toolchain CLI
  crates/uv/src/commands/python/install.rs
  crates/uv/src/commands/python/list.rs
  crates/uv/src/commands/python/uninstall.rs
Labels: cli, preview

#4897 Sort dependencies before wheels and source distributions
  crates/uv-resolver/src/lock.rs
  crates/uv/tests/branching_urls.rs
  crates/uv/tests/edit.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/lock_scenarios.rs
Labels: preview, lock

#4900 Respect `requires-python` when prefetching
  crates/uv-resolver/src/resolver/batch_prefetch.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/pip_compile.rs
Labels: bug, resolver

#4902 uv-resolver: partially revert Requires-Python version narrowing
  _typos.toml
  crates/uv-resolver/src/python_requirement.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#4903 Bump version to 0.2.23
  CHANGELOG.md
  Cargo.lock
  PREVIEW-CHANGELOG.md
  README.md
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: release

#4708 Implement `uv tree`
  Cargo.lock
  crates/uv-cli/src/lib.rs
  crates/uv-resolver/src/lock.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/pip/tree.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/tree.rs
Labels: preview

#4913 Avoid debug error for `uv run` with unknown Python version
  crates/uv-python/src/installation.rs
Labels: error messages, preview

#4916 Add command-separation for Python discovery display
  crates/uv-python/src/discovery.rs
Labels: error messages, preview

#4904 Add test cases for the CLI help menu
  crates/uv/tests/common/mod.rs
  crates/uv/tests/help.rs
Labels: testing

#4911 Avoid AND-ing multi-term specifiers in marker normalization
  crates/uv-resolver/src/marker.rs
Labels: bug

#4927 Upgrade `clap`
  Cargo.lock
  Cargo.toml
Labels: internal, cli

#4912 Filter out markers based on Python requirement
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/marker.rs
  crates/uv-resolver/src/requires_python.rs
  crates/uv-resolver/src/resolution/display.rs
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/edit.rs
  crates/uv/tests/pip_compile.rs
Labels: enhancement, preview

#4772 Display short help menu when `--help` is used
  crates/uv-cli/src/lib.rs
  crates/uv/tests/help.rs
Labels: cli

#4928 Avoid inferring package name for GitHub Archives
  crates/uv-requirements/src/unnamed.rs
Labels: bug

#4906 Implement `uv help` manually instead of using Clap default
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/help.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/main.rs
  crates/uv/tests/help.rs
Labels: cli

#4930 Respect resolver settings in `uv remove`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/list.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
Labels: bug, preview

#4929 Remove confusing punctuation in readme
  README.md
Labels: documentation

#4932 Enable `--all` to uninstall all managed Pythons
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/python/uninstall.rs
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
Labels: preview

#4935 Reinstall and recreate environments when interpreter is removed
  crates/uv-tool/src/lib.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/tests/tool_install.rs
Labels: enhancement, preview

#4937 Enable `--all` to uninstall all managed tools
  crates/uv-cli/src/lib.rs
  crates/uv-tool/src/lib.rs
  crates/uv/src/commands/tool/uninstall.rs
  crates/uv/src/settings.rs
Labels: enhancement, preview

#4936 Do not use pager for root `uv help` and improve after help hint
  crates/uv/src/commands/help.rs
  crates/uv/tests/help.rs
Labels: cli

#4945 Avoid serializing if lockfile does not change
  crates/uv-requirements/src/upgrade.rs
  crates/uv-resolver/src/lock.rs
  crates/uv/src/commands/project/lock.rs
Labels: performance

#4934 Switch to Current-Thread Tokio Runtime
  .github/workflows/ci.yml
  Cargo.toml
  crates/bench/benches/uv.rs
  crates/uv-dev/src/main.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-installer/src/installer.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/main.rs
Labels: performance

#4942 Add Python installation guide
  docs/guides/install-python.md
Labels: documentation, preview

#4952 Allow constraints to be provided in `--upgrade-package`
  Cargo.lock
  crates/pep508-rs/Cargo.toml
  crates/pep508-rs/src/lib.rs
  crates/uv-cli/Cargo.toml
  crates/uv-cli/src/lib.rs
  crates/uv-configuration/Cargo.toml
  crates/uv-configuration/src/constraints.rs
  crates/uv-configuration/src/package_options.rs
  crates/uv-requirements/src/upgrade.rs
  crates/uv-resolver/src/exclusions.rs
  crates/uv-settings/src/settings.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/settings.rs
  crates/uv/tests/pip_compile.rs
  uv.schema.json
Labels: enhancement, compatibility

#4947 Avoid reparsing wheel URLs
  crates/distribution-types/src/file.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__hash_optional_missing.snap
Labels: performance

#4955 Fix `index_strategy` doc
  crates/uv-cli/src/lib.rs
Labels: documentation

#4940 Improve 'any' search message during `uv python install`
  crates/uv/src/commands/python/install.rs
  crates/uv/src/main.rs
Labels: cli, preview

#4960 Retry on connection reset network errors
  crates/uv-client/src/base_client.rs
Labels: bug, network

#4787 Add standard filters for virtual environment bin directories and python executables
  crates/uv/tests/common/mod.rs
  crates/uv/tests/tool_list.rs
Labels: internal, testing

#4948 Add support for any Python requests
  crates/uv-python/src/discovery.rs
Labels: enhancement

#4951 Warn if tool binary directory is not on path
  Cargo.lock
  crates/uv/Cargo.toml
  crates/uv/src/commands/tool/install.rs
  crates/uv/tests/tool_install.rs
  crates/uv/tests/tool_uninstall.rs
Labels: error messages, preview

#4949 Add support for serializing `PythonRequest` to a canonical string
  crates/uv-python/src/discovery.rs
Labels: internal

#4938 Respect `--isolated` in `uv python install`
  crates/uv-python/src/lib.rs
  crates/uv-python/src/version_files.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/tests/venv.rs
Labels: cli, preview

#4962 Add some references to more details in the Python install guide
  docs/guides/install-python.md
Labels: documentation, preview

#4720 Lock for the duration of tool commands
  crates/uv-tool/src/lib.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/list.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/commands/tool/uninstall.rs
Labels: enhancement, preview

#4965 Add `manylinux_2_31` to supported `--python-platform`
  crates/uv-configuration/src/target_triple.rs
  uv.schema.json
Labels: compatibility

#4950 Add `uv python pin`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/python/mod.rs
  crates/uv/src/commands/python/pin.rs
  crates/uv/src/main.rs
  crates/uv/src/settings.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/help.rs
  crates/uv/tests/python_pin.rs
Labels: cli, preview

#4642 Allow `uv` crate to be used as a library
  crates/uv/src/bin/uv.rs
  crates/uv/src/lib.rs
Labels: rustlib

#4974 Bump version to 0.2.24
  CHANGELOG.md
  Cargo.lock
  PREVIEW-CHANGELOG.md
  README.md
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: release

#4964 Improve missing `wheel` error message with `--no-build-isolation`
  crates/uv-build/src/lib.rs
Labels: error messages

#4977 Remove extra "project" docs files
  docs/guides/project.md
  docs/preview/projects.md
Labels: internal

#4978 Lock directories to synchronize wheel-install copies
  crates/install-wheel-rs/src/linker.rs
  crates/uv-installer/src/installer.rs
Labels: bug

#5000 Fall back to streaming wheel when `Content-Length` header is absent
  crates/uv-client/src/error.rs
Labels: compatibility

#4999 Rename `python install --force` parameter to `--reinstall`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/help.rs
Labels: cli, preview

#5002 Allow URL dependencies in tool run `--from`
  crates/uv/src/commands/project/environment.rs
  crates/uv/tests/tool_run.rs
Labels: bug, preview

#4997 `uv tool run` suggest valid commands when command is not found
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/tool_run.rs
Labels: enhancement, cli, preview

#5005 Unhide `--isolated` global argument
  crates/uv-cli/src/lib.rs
  crates/uv/tests/help.rs
Labels: cli

#5011 uv: fix doc test
  crates/uv/src/shell.rs
Labels: internal

#4998 Fix substring marker expression disjointness checks
  crates/uv-resolver/src/marker.rs
Labels: bug

#5015 Fix `CONTRIBUTING.md` instructions to install multiple Python versions
  CONTRIBUTING.md
Labels: documentation

#5007 Add `--no-pager` option in `help` command
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/help.rs
  crates/uv/src/lib.rs
  crates/uv/tests/help.rs
Labels: cli

#5014 `uv tool run` error messages references `uvx` when appropriate
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/lib.rs
Labels: cli, preview

#5024 Update SchemaStore script
  scripts/update_schemastore.py
Labels: bug, internal

#5025 Warn when unused `pyproject.toml` configuration is detected
  crates/uv-settings/src/lib.rs
  crates/uv/src/lib.rs
  crates/uv/tests/show_settings.rs
Labels: error messages, configuration

#5023 Fix benchmarks CI job
  .github/workflows/ci.yml
Labels: internal
