Repository astral-sh/uv, pull requests merged in 2024-12, with the labels that each got.

#9525 Build backend: Revamp include/exclude
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/metadata.rs
  crates/uv-globfilter/src/glob_dir_filter.rs
  crates/uv-globfilter/src/portable_glob.rs
  crates/uv-settings/src/settings.rs
  crates/uv/src/commands/build_backend.rs
  crates/uv/tests/it/show_settings.rs
  scripts/packages/built-by-uv/data-dir/build-script.py
  scripts/packages/built-by-uv/pyproject.toml
  scripts/packages/built-by-uv/src/built_by_uv/build-only.h
  scripts/packages/built-by-uv/src/built_by_uv/not-packaged.txt
Labels: preview

#9552 Build backend: Default excludes
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/metadata.rs
  scripts/packages/built-by-uv/pyproject.toml
Labels: preview

#9540 Avoid adding non-extra package with extra dependencies
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/resolver/mod.rs
Labels: performance

#9557 RFC: Add `--dry-run` to `uv pip uninstall`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/pip/uninstall.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/pip_uninstall.rs
  docs/reference/cli.md
Labels: enhancement

#9558 Build backend: Refactoring before list
  crates/uv-build-backend/src/lib.rs
  crates/uv/src/commands/build_frontend.rs
Labels: preview

#9586 Mention `uv pip` behavior in build system note
  docs/concepts/projects/config.md
Labels: documentation

#9585 Include base installation directory in uv run PATH
  crates/uv/src/commands/project/run.rs
Labels: bug, windows

#9570 Omit origin when comparing requirements
  crates/uv-pypi-types/src/requirement.rs
  crates/uv/tests/it/tool_install.rs
Labels: bug

#8650 Add `uv python install --default`
  crates/uv-cli/src/lib.rs
  crates/uv-python/src/installation.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/src/commands/python/uninstall.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/help.rs
  crates/uv/tests/it/python_install.rs
  docs/reference/cli.md
Labels: preview

#9547 Allow `--constraints` and `--overrides` in `uv tool install`
  crates/uv-cli/src/lib.rs
  crates/uv-tool/src/tool.rs
  crates/uv/src/commands/tool/common.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/upgrade.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/show_settings.rs
  crates/uv/tests/it/tool_install.rs
  docs/reference/cli.md
Labels: cli

#9459 Display removed Python executables on uninstall
  crates/uv/src/commands/python/install.rs
  crates/uv/src/commands/python/uninstall.rs
  crates/uv/tests/it/python_install.rs
Labels: enhancement, preview

#9388 Include Git member information when getting metadata from cache
  crates/uv-distribution/src/source/mod.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#9594 Respect path dependencies within Git dependencies
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#9595 Normalize paths when lowering Git dependencies
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-resolver/src/resolver/urls.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#9599 Split build backend into modules
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/source_dist.rs
  crates/uv-build-backend/src/wheel.rs
Labels: internal, preview

#9600 Build backend: Rename `--no-fast-path` to `--force-pep517`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  docs/reference/cli.md
Labels: internal, preview

#9602 Build backend: Add functions to collect file list
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/source_dist.rs
  crates/uv-build-backend/src/wheel.rs
Labels: preview

#9584 Update build failures document
  docs/reference/build_failures.md
  mkdocs.template.yml
Labels: documentation

#9607 Fix Python executable installation when multiple patch versions are requested
  crates/uv/src/commands/python/install.rs
  crates/uv/tests/it/python_install.rs
Labels: preview

#9367 Add policies reference section and license document
  docs/concepts/resolution.md
  docs/reference/index.md
  docs/reference/policies/index.md
  docs/reference/policies/license.md
  docs/reference/policies/platforms.md
  docs/reference/policies/versioning.md
  mkdocs.template.yml
Labels: documentation

#9612 Bump version to 0.5.6
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#9616 Add `Cargo.toml` to triggers for binary test builds
  .github/workflows/build-binaries.yml
Labels: internal

#9620 Disable freebsd test until we resolve the upstream problem
  .github/workflows/ci.yml
Labels: internal

#9624 Implement `Ord` and `PartialOrd` without origin for `Requirement`
  crates/uv-pypi-types/src/requirement.rs
Labels: bug

#9093 Docs(GitLab): add entrypoint for distroless image
  docs/guides/integration/gitlab.md
Labels: documentation

#9545 Model groups as a property of requirements
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-pypi-types/src/requirement.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/source_tree.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/manifest.rs
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/pubgrub/package.rs
  crates/uv-resolver/src/resolver/groups.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/lock_conflict.rs
  crates/uv/tests/it/workspace.rs
Labels: internal

#9487 Improve message when updater receipt is for a different uv executable
  Cargo.lock
  Cargo.toml
  crates/uv/src/commands/self_update.rs
Labels: error messages

#8548 add helper script to download the needed files to mirror for UV_PYTHON_INSTALL_MIRROR
  scripts/create-python-mirror.py
Labels: internal

#9628 Fix FreeBSD test by avoiding expensive copy of the uv binary
  .github/workflows/ci.yml
Labels: internal

#9610 Build backend: Add `--list` option
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/build.rs
  crates/uv/tests/it/python_install.rs
Labels: enhancement, preview

#9611 Improve build frontend error handling
  Cargo.lock
  crates/uv/Cargo.toml
  crates/uv/src/commands/build_frontend.rs
Labels: enhancement

#9635 Build backend: Add integration test for scripts
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/wheel.rs
  crates/uv/tests/it/build.rs
  crates/uv/tests/it/build_backend.rs
  scripts/packages/built-by-uv/pyproject.toml
  scripts/packages/built-by-uv/src/built_by_uv/cli.py
Labels: preview

#9633 uv build: Catch version mismatch between sdist and wheel
  crates/uv-distribution-filename/src/lib.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/tests/it/build.rs
Labels: enhancement

#9621 Build backend: Add direct builds to the resolver and installer
  Cargo.lock
  crates/uv-bench/benches/uv.rs
  crates/uv-build-backend/Cargo.toml
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/metadata.rs
  crates/uv-build-frontend/src/lib.rs
  crates/uv-dispatch/Cargo.toml
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-types/Cargo.toml
  crates/uv-types/src/traits.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/commands/tool/upgrade.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/lib.rs
Labels: preview

#9641 Add `build-essentials` note to build failures doc
  docs/reference/build_failures.md
Labels: documentation

#9642 Un-hide `uv build --no-build-logs` option
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: cli

#9631 docs: add docs to `uv python pin` without a REQUEST argument
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: documentation

#9648 Create missing dir for `uv export`/ `uv pip compile`
  crates/uv/src/commands/mod.rs
  crates/uv/tests/it/export.rs
Labels: bug

#9644 Include more sources to avoid lowest bound warning
  crates/uv-resolver/src/resolution/output.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#9661 Build backend: Add template to uv init
  crates/uv-configuration/src/project_build_backend.rs
  crates/uv-dev/src/generate_cli_reference.rs
  crates/uv/src/commands/project/init.rs
  crates/uv/src/lib.rs
  crates/uv/tests/it/init.rs
Labels: preview

#9659 Unify dist error handling
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution-types/src/dist_error.rs
  crates/uv-distribution-types/src/lib.rs
  crates/uv-installer/src/preparer.rs
  crates/uv-requirements/src/lib.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/src/commands/diagnostics.rs
  crates/uv/src/commands/pip/operations.rs
Labels: internal

#9665 Test `venv` in 3.13t integration test
  .github/workflows/ci.yml
Labels: internal

#9677 Respect build tag priority in `uv.lock`
  crates/uv-resolver/src/lock/mod.rs
Labels: bug

#9676 Use `thiserror` in `InstalledDist`
  crates/uv-distribution-types/src/installed.rs
  crates/uv-resolver/src/error.rs
Labels: error messages

#9678 Remove derivation chain special casing
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution-types/src/dist_error.rs
  crates/uv-installer/src/preparer.rs
  crates/uv-requirements/src/lib.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/resolver/derivation.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/src/commands/diagnostics.rs
  crates/uv/src/commands/pip/operations.rs
Labels: internal

#9670 Disable checkout during FreeBSD tests
  .github/workflows/ci.yml
Labels: internal

#9669 Fix missing display of non-freethreaded Python 3.13 in `python list`
  crates/uv-python/src/installation.rs
  crates/uv/src/commands/python/list.rs
Labels: bug

#9680 Add test coverage for build tag prioritization
  crates/uv-client/src/flat_index.rs
  crates/uv-distribution-filename/src/lib.rs
  crates/uv-distribution-filename/src/source_dist.rs
  crates/uv-distribution-filename/src/wheel.rs
  crates/uv-resolver/src/flat_index.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/sync.rs
  scripts/links/build_tag-1.0.0-1-py2.py3-none-any.whl
  scripts/links/build_tag-1.0.0-3-py2.py3-none-any.whl
  scripts/links/build_tag-1.0.0-5-py2.py3-none-any.whl
Labels: testing

#9691 Add hint on build backend import with preview disabled
  python/uv/__init__.py
Labels: preview

#9698 Bump version to 0.5.7
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#9444 Encode mutually-incompatible pairs of markers
  crates/uv-pep508/src/marker/algebra.rs
  crates/uv-pep508/src/marker/lowering.rs
  crates/uv-pep508/src/marker/simplify.rs
  crates/uv-pep508/src/marker/tree.rs
  crates/uv/tests/it/export.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/snapshots/it__ecosystem__black-lock-file.snap
  crates/uv/tests/it/snapshots/it__ecosystem__home-assistant-core-lock-file.snap
  crates/uv/tests/it/snapshots/it__ecosystem__transformers-lock-file.snap
  crates/uv/tests/it/snapshots/it__ecosystem__warehouse-lock-file.snap
Labels: bug, enhancement

#9704 Eagerly error when parsing `pyproject.toml` requirements
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-requirements/src/source_tree.rs
  crates/uv/tests/it/pip_compile.rs
Labels: performance

#9708 Fix projects's typo in resolver error messages
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv/tests/it/lock_conflict.rs
Labels: bug

#9709 Normalize relative paths when `--project` is specified
  crates/uv-fs/src/path.rs
  crates/uv/src/lib.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#9710 Use copy-on-write when normalizing paths
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-fs/src/path.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/src/lib.rs
Labels: performance

#9712 Run `cargo update`
  Cargo.lock
Labels: internal

#9705 Enforce correctness of self-dependencies
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#9714 Respect self-constraints on recursive extras
  crates/uv-pypi-types/src/requirement.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#9662 Reframe `--locked` and `--frozen` as `--check` operations for `uv lock`
  crates/uv-cli/src/lib.rs
  crates/uv/src/settings.rs
  docs/concepts/projects/sync.md
  docs/reference/cli.md
Labels: cli

#9720 Avoid treating non-existent `--find-links` as relative URLs
  crates/uv-client/src/flat_index.rs
  crates/uv-distribution-types/src/index_url.rs
  crates/uv/tests/it/pip_install.rs
Labels: error messages

#9740 Fix build failure links
  docs/reference/build_failures.md
Labels: documentation

#9718 Allow users to specify URLs in `project.dependencies` and `tool.uv.sources`
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-distribution/src/metadata/requires_dist.rs
  crates/uv/tests/it/lock.rs
Labels: enhancement

#9736 Don't filter non-patch registry version
  crates/uv-python/src/discovery.rs
Labels: bug

#9751 Avoid enforcing non-conflicts in `uv export`
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/requirements_txt.rs
  crates/uv/tests/it/export.rs
Labels: bug

#9750 Avoid 403 error hint for PyTorch URLs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
Labels: error messages

#9760 Don't read metadata from stale `.egg-info` files
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#9761 Show a dedicated error for missing subdirectories
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv/tests/it/pip_install.rs
Labels: error messages

#9759 Allow execution of pyw files on Unix
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/it/run.rs
Labels: enhancement

#9679 Omit Windows Store `python3.13.exe` et al
  crates/uv-python/src/discovery.rs
Labels: windows

#9766 Filter out commit since last tag in tests
  crates/uv/tests/it/common/mod.rs
Labels: internal

#9753 Retry on tar extraction errors
  crates/uv-client/src/base_client.rs
Labels: bug, network

#9756 Rename Python install scratch directory from `.cache` -> `.temp`
  crates/uv-python/src/downloads.rs
  crates/uv-python/src/installation.rs
  crates/uv-python/src/managed.rs
  crates/uv/src/commands/python/install.rs
Labels: enhancement

#9717 Show 'depends on itself' for proxy packages
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv/tests/it/lock.rs
Labels: error messages

#9716 Improve self-dependency hint to make shadowing clear
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv/tests/it/lock.rs
Labels: error messages

#9370 add conflict markers to the lock file
  crates/uv-pypi-types/src/conflicts.rs
  crates/uv-resolver/src/graph_ops.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/requirements_txt.rs
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_source_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_source_version_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_version_unambiguous.snap
  crates/uv-resolver/src/lock/target.rs
  crates/uv-resolver/src/lock/tree.rs
  crates/uv-resolver/src/preferences.rs
  crates/uv-resolver/src/resolution/display.rs
  crates/uv-resolver/src/resolution/output.rs
  crates/uv-resolver/src/resolution/requirements_txt.rs
  crates/uv-resolver/src/resolver/environment.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/universal_marker.rs
  crates/uv/tests/it/lock_conflict.rs
Labels: bug, lock

#7920 :wrench: add `--install-dir` arg to `uv python` commands
  crates/uv-cli/src/lib.rs
  crates/uv-python/src/discovery.rs
  crates/uv-python/src/installation.rs
  crates/uv-python/src/managed.rs
  crates/uv/src/commands/python/dir.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/src/commands/python/uninstall.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/help.rs
  crates/uv/tests/it/python_install.rs
  docs/reference/cli.md
Labels: cli

#8963 Enable `uv tool uninstall uv` on Windows
  Cargo.lock
  crates/uv-tool/src/lib.rs
  crates/uv-virtualenv/src/virtualenv.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/tool/common.rs
  crates/uv/src/commands/tool/uninstall.rs
Labels: windows

#8062 Add `--show-urls` and `--only-downloads` to `uv python list`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/python/list.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  docs/reference/cli.md
Labels: enhancement

#8086 Improve handling of invalid virtual environments during interpreter discovery
  crates/uv-python/src/discovery.rs
  crates/uv/tests/it/python_find.rs
Labels: bug

#9780 uv-resolver: deduplicate resolution markers
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/it/lock_conflict.rs
Labels: bug, lock

#9784 Don't drop comments between items in TOML tables
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv/tests/it/edit.rs
Labels: bug

#9782 Add `uv python list --all-arches`
  crates/uv-cli/src/lib.rs
  crates/uv-python/src/downloads.rs
  crates/uv/src/commands/python/list.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  docs/reference/cli.md
Labels: enhancement

#9785 Don't fail with `--no-build` when static metadata is available
  crates/uv-distribution/src/distribution_database.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#9786 Ignore `.` prefixed directories during managed Python installation discovery
  crates/uv-python/src/managed.rs
Labels: bug

#9781 Allow download of Python distribution variants with newer CPU instruction sets
  crates/uv-python/download-metadata.json
  crates/uv-python/fetch-download-metadata.py
  crates/uv-python/src/downloads.inc
  crates/uv-python/src/downloads.inc.mustache
  crates/uv-python/src/platform.rs
  crates/uv-python/template-download-metadata.py
Labels: enhancement

#9152 Add --gui-script flag for running Python scripts with pythonw.exe on …
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/run.rs
  docs/reference/cli.md
Labels: windows

#9723 Preserve directory-level standalone build symlinks
  crates/uv-virtualenv/src/virtualenv.rs
Labels: enhancement

#9787 Allow `--gui-script` on Unix
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/it/run.rs
Labels: enhancement

#9694 Publish: Support --index <name>
  crates/uv-cli/src/lib.rs
  crates/uv-distribution-types/src/index.rs
  crates/uv-static/src/env_vars.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/publish.rs
  crates/uv/tests/it/show_settings.rs
  docs/configuration/environment.md
  docs/guides/publish.md
  docs/reference/cli.md
  scripts/publish/test_publish.py
  uv.schema.json
Labels: enhancement

#9789 Show a dedicated hint for missing `git+` prefixes
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-pep508/src/lib.rs
  crates/uv-pep508/src/verbatim_url.rs
  crates/uv-pypi-types/src/parsed_url.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_install.rs
Labels: error messages

#9706 Replace executables with broken symlinks during `uv python install`
  crates/uv/src/commands/python/install.rs
  crates/uv/tests/it/python_install.rs
Labels: preview

#9792 Test binary builds on `Cargo.lock` changes
  .github/workflows/build-binaries.yml
Labels: internal

#9773 Resolver module improvements
  crates/uv-resolver/src/resolver/batch_prefetch.rs
  crates/uv-resolver/src/resolver/mod.rs
Labels: internal

#9791 Bump version to 0.5.8
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: no-build, releases

#9808 Fix local packse workflow
  crates/uv/tests/it/common/mod.rs
  scripts/scenarios/generate.py
Labels: internal

#9795 Add support for `UV_OFFLINE`
  crates/uv-cli/src/lib.rs
  crates/uv-static/src/env_vars.rs
  crates/uv/tests/it/help.rs
  docs/configuration/environment.md
  docs/reference/cli.md
Labels: enhancement

#9815 Upgrade minimum Rust version to 1.83
  Cargo.toml
  crates/uv-cache/src/wheel.rs
  crates/uv-client/src/httpcache/mod.rs
  crates/uv-client/src/remote_metadata.rs
  crates/uv-configuration/src/name_specifiers.rs
  crates/uv-distribution-types/src/buildable.rs
  crates/uv-distribution-types/src/hash.rs
  crates/uv-distribution-types/src/lib.rs
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-extract/src/hash.rs
  crates/uv-install-wheel/src/linker.rs
  crates/uv-options-metadata/src/lib.rs
  crates/uv-pep440/src/version.rs
  crates/uv-pep508/src/marker/tree.rs
  crates/uv-pypi-types/src/conflicts.rs
  crates/uv-pypi-types/src/metadata/metadata23.rs
  crates/uv-python/src/discovery.rs
  crates/uv-python/src/installation.rs
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-scripts/src/lib.rs
  crates/uv-settings/src/lib.rs
  crates/uv-types/src/builds.rs
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/tool/uninstall.rs
  rust-toolchain.toml
Labels: rustlib

#9820 Fix suggestion to use `uv help python` on invalid install requests
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/tests/it/python_install.rs
  docs/reference/cli.md
Labels: bug

#9823 Skip root when assessing prefix viability
  crates/uv-virtualenv/src/virtualenv.rs
Labels: bug

#9824 Simplify requires-python check in resolver
  crates/uv-resolver/src/resolver/mod.rs
Labels: internal

#9846 Avoid reusing interpreter metadata when running under Rosetta
  crates/uv-cache/src/lib.rs
  crates/uv-python/src/interpreter.rs
Labels: bug

#9848 Avoid trailing slash when deserializing from lockfile
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#9870 Avoid spurious 'Upgraded tool environment' in `uv tool upgrade`
  crates/uv/src/commands/tool/upgrade.rs
  crates/uv/tests/it/tool_upgrade.rs
Labels: bug, cli

#9879 Avoid lookaheads in `sysconfig` parser
  crates/uv-python/src/sysconfig/parser.rs
Labels: performance

#9880 Install `liblzma-dev` in CI
  .github/workflows/ci.yml
Labels: internal

#9881 Remove use of `.previous()` in sysconfig parser
  crates/uv-python/src/sysconfig/parser.rs
Labels: bug, internal

#9827 Fork version selection based on `requires-python` requirements
  crates/uv-distribution-types/src/prioritized_distribution.rs
  crates/uv-resolver/src/python_requirement.rs
  crates/uv-resolver/src/requires_python.rs
  crates/uv-resolver/src/resolver/availability.rs
  crates/uv-resolver/src/resolver/environment.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/snapshots/it__ecosystem__black-lock-file.snap
  crates/uv/tests/it/snapshots/it__ecosystem__black-uv-lock-output.snap
Labels: enhancement

#9868 Introduce a `--fork-strategy` preference mode
  crates/uv-cli/src/lib.rs
  crates/uv-cli/src/options.rs
  crates/uv-python/src/python_version.rs
  crates/uv-resolver/src/fork_strategy.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_optional_missing.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_optional_present.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_required_present.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_source_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_source_version_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_version_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_direct_has_subdir.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_direct_no_subdir.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_directory.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_editable.snap
  crates/uv-resolver/src/options.rs
  crates/uv-resolver/src/requires_python.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-settings/src/combine.rs
  crates/uv-settings/src/settings.rs
  crates/uv-static/src/env_vars.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/show_settings.rs
  docs/configuration/environment.md
  docs/reference/cli.md
  docs/reference/settings.md
  uv.schema.json
Labels: configuration

#9877 Fix bug in terms when collapsing unavailable versions in resolver errors
  crates/uv-resolver/src/error.rs
  crates/uv/tests/it/cache_prune.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/tool_list.rs
Labels: bug

#9887 Document the `--fork-strategy` setting
  crates/uv-cli/src/lib.rs
  crates/uv-settings/src/settings.rs
  docs/concepts/resolution.md
  docs/reference/settings.md
Labels: documentation

#9876 Avoid `panic!()` when current directory does not exist
  crates/uv-fs/src/path.rs
Labels: bug

#9888 Add lzma to benchmark install
  .github/workflows/ci.yml
Labels: internal

#9889 Bump version to v0.5.9
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#9893 Allow multiple disjoint URLs in overrides
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/urls.rs
  crates/uv/tests/it/pip_compile.rs
Labels: bug

#9862 Show terms in derivation tree debug output
  crates/uv-resolver/src/error.rs
Labels: tracing

#9896 Remove `pypy` from top-level pin example
  README.md
  docs/index.md
Labels: documentation

#9913 Skip `--native-tls` in `pip compile` header
  crates/uv/src/commands/pip/compile.rs
Labels: compatibility

#9912 Show a concise error message for missing version field
  crates/uv-pypi-types/src/metadata/mod.rs
  crates/uv-pypi-types/src/metadata/pyproject_toml.rs
  crates/uv-workspace/src/pyproject.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/run.rs
Labels: error messages

#9905 Patch additional `sysconfig` values such as AR at install time
  crates/uv-python/src/sysconfig/mod.rs
Labels: bug, compatibility

#9903 change example so it works as is on powershell and cmd
  docs/guides/install-python.md
Labels: documentation

#9914 Clear environment in settings tests
  crates/uv/tests/it/show_settings.rs
Labels: testing

#9843 Change backtracking when packages conflict too much
  Cargo.lock
  Cargo.toml
  crates/uv-resolver/src/dependency_provider.rs
  crates/uv-resolver/src/pubgrub/priority.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/snapshots/it__ecosystem__transformers-lock-file.snap
  crates/uv/tests/it/snapshots/it__ecosystem__warehouse-lock-file.snap
  docs/reference/resolver-internals.md
Labels: enhancement, performance, resolver

#9932 Include explicit indexes in publish index choice
  crates/uv-distribution-types/src/index_url.rs
  crates/uv/src/lib.rs
  crates/uv/tests/it/publish.rs
Labels: bug

#9363 Add a note to say that dependencies between workspace members are editable
  docs/concepts/projects/workspaces.md
Labels: documentation

#9931 Correctly document default value of `fork-strategy` setting
  crates/uv-settings/src/settings.rs
  docs/reference/settings.md
Labels: documentation

#9884 Add test case for redundant enumeration of no versions
  crates/uv/tests/it/pip_compile.rs
Labels: testing

#9454 clarify best practice for python matrix strategy github workflow
  docs/guides/integration/github.md
Labels: documentation

#9885 Fix redundant enumeration of all package versions in some resolver errors
  crates/uv-resolver/src/error.rs
  crates/uv/tests/it/pip_compile.rs
Labels: error messages

#9946 FIX: Dependency documentation with double quotes where required
  docs/concepts/projects/dependencies.md
Labels: documentation, windows

#9948 Add resolver error hint for no-binary and no-build failures
  crates/uv-distribution-types/src/prioritized_distribution.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/pip_install_scenarios.rs
Labels: error messages

#9897 Simplify ranges in the derivation tree before reporting
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/pubgrub/report.rs
Labels: internal

#9956 Remove TODO around dev dependency edges
  crates/uv-resolver/src/resolution/output.rs
Labels: internal

#9954 Add some misc. touch-ups in resolver
  crates/uv-resolver/src/graph_ops.rs
  crates/uv-resolver/src/pubgrub/package.rs
  crates/uv-resolver/src/resolver/environment.rs
  crates/uv-resolver/src/resolver/mod.rs
Labels: internal

#9971 Fix typo "operation system"
  crates/uv-python/src/interpreter.rs
Labels: bug

#9952 Omit trailing zeros on Python requirements inferred from versions
  crates/uv-pep440/src/version.rs
  crates/uv-resolver/src/python_requirement.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_compile_scenarios.rs
Labels: error messages

#9965 Build backend: Fix pre-PEP 639 license files
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/metadata.rs
  crates/uv-build-backend/src/source_dist.rs
  crates/uv-build-backend/src/wheel.rs
Labels: bug, preview

#9957 Collapse redundant Python version incompatibilities in resolver error message
  crates/uv-resolver/src/error.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_install_scenarios.rs
Labels: error messages

#9660 Better build error messages
  Cargo.lock
  crates/uv-build-frontend/Cargo.toml
  crates/uv-build-frontend/src/error.rs
  crates/uv-build-frontend/src/lib.rs
  crates/uv-dispatch/Cargo.toml
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution-types/src/dist_error.rs
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-installer/src/preparer.rs
  crates/uv-requirements/src/lib.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-types/src/traits.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/venv.rs
  crates/uv/tests/it/build.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/pip_sync.rs
  crates/uv/tests/it/sync.rs
  crates/uv/tests/it/tool_install.rs
  docs/reference/build_failures.md
Labels: error messages

#9975 Fix `Cargo.lock` by updating thiserror
  Cargo.lock
Labels: internal

#9944 Improve display of ranges when pre-releases are not allowed
  crates/uv-resolver/src/error.rs
  crates/uv/tests/it/cache_prune.rs
  crates/uv/tests/it/pip_install.rs
Labels: error messages

#9976 Disable Depot runner for macOS
  .github/workflows/ci.yml
Labels: internal

#9950 Use the build options value to improve hints for no wheel / source distribution errors
  crates/uv-dispatch/src/lib.rs
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/options.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/pip_install_scenarios.rs
Labels: error messages

#9916 Patch additional sysconfig values such as clang at install time
  crates/uv-python/src/sysconfig/mod.rs
Labels: enhancement

#9977 Update references to `python-build-standalone` to reflect the transferred project
  crates/uv-cli/src/lib.rs
  crates/uv-python/download-metadata.json
  crates/uv-python/fetch-download-metadata.py
  crates/uv-python/src/downloads.inc
  crates/uv-python/src/downloads.rs
  crates/uv-python/src/interpreter.rs
  crates/uv-settings/src/settings.rs
  crates/uv-static/src/env_vars.rs
  crates/uv/tests/it/help.rs
  docs/concepts/python-versions.md
  docs/configuration/environment.md
  docs/guides/install-python.md
  docs/reference/cli.md
  docs/reference/settings.md
  scripts/create-python-mirror.py
  uv.schema.json
Labels: documentation

#9960 Improve styling of `uv remove` dependency hints
  crates/uv/src/commands/project/remove.rs
  crates/uv/tests/it/edit.rs
Labels: error messages

#9983 Bump version to 0.5.10
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#9984 Add nuance to prefetch logging
  crates/uv-resolver/src/resolver/batch_prefetch.rs
Labels: tracing

#9992 Fix show_settings tests not to be affected by system configs
  crates/uv/tests/it/show_settings.rs
Labels: testing

#10005 `metadata_directory` already contains dist-info directory
  crates/uv-build-backend/src/lib.rs
  pyproject.toml
Labels: bug, preview

#10009 Update packse to 0.3.42 for backtracking test
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/lock_scenarios.rs
  crates/uv/tests/it/pip_compile_scenarios.rs
  crates/uv/tests/it/pip_install_scenarios.rs
  scripts/scenarios/requirements.txt
  scripts/sync_scenarios.sh
Labels: internal
