Repository astral-sh/uv, pull requests merged in 2024-09, with the labels that each got.

#6915 Remove dangling archives in `uv cache clean ${package}`
  crates/uv-cache/src/lib.rs
  crates/uv/tests/cache_clean.rs
  crates/uv/tests/pip_sync.rs
Labels: bug

#6776 fix: replace std::fs::canonicalize with Simplified::simple_canonicaliz…
  crates/uv-fs/src/path.rs
Labels: windows

#6919 Remove some canonicalize calls
  crates/uv-fs/src/path.rs
  crates/uv-virtualenv/src/virtualenv.rs
  crates/uv/src/commands/project/init.rs
Labels: internal

#6929 Avoid panic with missing temporary directory
  crates/uv-client/src/registry_client.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/venv.rs
Labels: bug

#6896 Add source distribution support to `uv-build` crate
  crates/uv-build/src/lib.rs
  crates/uv-configuration/src/build_options.rs
  crates/uv-dev/src/build.rs
Labels: enhancement

#6939 Avoid updating incorrect dependencies for sorted `uv add`
  crates/uv-workspace/src/pyproject.rs
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/tests/edit.rs
Labels: bug

#6882 Use lower-bound semantics for all Python compatibility comparisons
  crates/bench/benches/uv.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_optional_missing.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_optional_present.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_required_present.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_source_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_source_version_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_version_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_direct_has_subdir.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_direct_no_subdir.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_directory.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_editable.snap
  crates/uv-resolver/src/pubgrub/package.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/python_requirement.rs
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv-resolver/src/resolver/batch_prefetch.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_compile_scenarios.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_install_scenarios.rs
  crates/uv/tests/pip_sync.rs
Labels: bug

#6903 Stream build backend output to `debug!`
  crates/uv-build/src/lib.rs
  crates/uv-virtualenv/src/virtualenv.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_sync.rs
Labels: tracing

#6943 Allow `uv sync --package` without copying member `pyproject.toml`
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-workspace/src/lib.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/sync.rs
Labels: enhancement

#6947 Bump version to v0.4.3
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: release

#6949 Avoid canonicalizing cache directory
  crates/uv-cache/src/lib.rs
Labels: bug, windows

#6952 Update URL in structured schema
  docs/.overrides/main.html
Labels: documentation

#6953 Use | for page separator in meta titles
  docs/.overrides/main.html
Labels: documentation

#6950 Support file:// URL for `UV_PYTHON_INSTALL_MIRROR`
  crates/uv-python/src/downloads.rs
Labels: enhancement

#6954 Add `--no-hashes` to `uv export`
  crates/uv-cli/src/lib.rs
  crates/uv-resolver/src/lock/requirements_txt.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/export.rs
  docs/reference/cli.md
Labels: enhancement, configuration

#6957 Move unreachable wheels check
  crates/uv-resolver/src/lock/mod.rs
Labels: internal

#6053 feat: introduce more docker tags for uv
  .github/workflows/build-docker.yml
  docs/guides/integration/docker.md
Labels: release

#6921 docs `docker.md`: example to use bind mounts
  docs/guides/integration/docker.md
Labels: documentation

#6917 Show all PyPy versions in `uv python list --all-versions`
  crates/uv/src/commands/python/list.rs
Labels: bug, uv python

#6863 Show env option in CLI reference documentation
  crates/uv-dev/src/generate_cli_reference.rs
  docs/reference/cli.md
Labels: documentation

#6887 Make headers title case for backward compatibility
  crates/uv-client/src/base_client.rs
Labels: compatibility, network

#6834 Allow customizing the project environment path with `UV_PROJECT_ENVIRONMENT`
  crates/uv-workspace/src/workspace.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/sync.rs
  crates/uv/tests/venv.rs
Labels: configuration

#6976 Remove `VIRTUAL_ENV` from project commmands by default
  crates/uv/tests/common/mod.rs
  crates/uv/tests/pip_check.rs
  crates/uv/tests/pip_compile_scenarios.rs
  crates/uv/tests/pip_freeze.rs
  crates/uv/tests/pip_install_scenarios.rs
  crates/uv/tests/pip_list.rs
  crates/uv/tests/pip_show.rs
  scripts/scenarios/templates/compile.mustache
  scripts/scenarios/templates/install.mustache
Labels: internal, testing

#6835 Improve project handling in `uv venv`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/venv.rs
  docs/reference/cli.md
Labels: cli

#6980 Fix outdated references to the help menu documentation in the first steps page
  docs/getting-started/first-steps.md
Labels: documentation

#6978 Use a consistent pattern for `uv add` and `uv remove` tests
  crates/uv/tests/common/mod.rs
  crates/uv/tests/edit.rs
  crates/uv/tests/workflow.rs
Labels: internal, testing

#6982 Add optional dependencies section to the lockfile document
  docs/concepts/projects.md
Labels: documentation

#6984 Document use of the `file://` scheme in Python installation mirrors
  docs/configuration/environment.md
Labels: documentation

#6869 Pin `.python-version` in `uv init`
  crates/uv-cli/src/lib.rs
  crates/uv-python/src/version_files.rs
  crates/uv/src/commands/project/init.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/init.rs
  docs/reference/cli.md
Labels: enhancement

#6987 Add docs for `UV_PROJECT_ENVIRONMENT`
  docs/concepts/projects.md
  docs/configuration/environment.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
Labels: documentation

#6864 Add warning when `VIRTUAL_ENV` is set but will not be respected in project commands
  Cargo.lock
  crates/uv-workspace/Cargo.toml
  crates/uv-workspace/src/workspace.rs
  crates/uv/tests/init.rs
  crates/uv/tests/run.rs
  crates/uv/tests/sync.rs
  crates/uv/tests/workspace.rs
Labels: cli

#6979 Add instructions for installing from Cargo
  docs/getting-started/installation.md
Labels: documentation

#6988 Bump version to v0.4.4
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: release

#6959 Prune unreachable packages from lockfile
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv/tests/snapshots/ecosystem__transformers-lock-file.snap
Labels: enhancement

#6961 Prune unreachable wheels from lockfile
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/export.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/snapshots/ecosystem__packse-lock-file.snap
  crates/uv/tests/snapshots/ecosystem__transformers-lock-file.snap
  crates/uv/tests/snapshots/workflow__packse_add_remove_existing_package_noop-2.snap
  crates/uv/tests/snapshots/workflow__packse_add_remove_one_package-2.snap
  crates/uv/tests/snapshots/workflow__packse_promote_transitive_to_direct_then_remove-2.snap
  crates/uv/tests/workflow.rs
Labels: enhancement

#6955 fix: adjust close_handles pointer offsets to match distlib cleanup_fds
  crates/uv-trampoline/src/bounce.rs
  crates/uv-trampoline/trampolines/uv-trampoline-aarch64-console.exe
  crates/uv-trampoline/trampolines/uv-trampoline-aarch64-gui.exe
  crates/uv-trampoline/trampolines/uv-trampoline-i686-console.exe
  crates/uv-trampoline/trampolines/uv-trampoline-i686-gui.exe
  crates/uv-trampoline/trampolines/uv-trampoline-x86_64-console.exe
  crates/uv-trampoline/trampolines/uv-trampoline-x86_64-gui.exe
Labels: windows

#6994 Reflect exit code in `uv tool run` and `uv run`
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/run.rs
  crates/uv/tests/tool_run.rs
Labels: bug

#7017 Fix available Docker image rendering and shorten list
  docs/guides/integration/docker.md
Labels: documentation

#7023 Fix handling of inline optional dependencies in `uv add`
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv/tests/edit.rs
Labels: bug

#7026 Redact packse version in all urls
  crates/uv/tests/common/mod.rs
  crates/uv/tests/lock.rs
Labels: internal

#7024 Revert `pyproject.toml` modifications on Ctrl-C
  Cargo.lock
  crates/uv/Cargo.toml
  crates/uv/src/commands/project/add.rs
Labels: bug

#7013 Add note to `extra` and `all-extras` in `uv sync` help
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: documentation

#7021 Use the root project name for the project virtual environment prompt
  crates/uv/src/commands/project/mod.rs
  crates/uv/tests/sync.rs
Labels: enhancement

#6895 Implement `uv build`
  Cargo.lock
  crates/uv-build/src/lib.rs
  crates/uv-cli/src/lib.rs
  crates/uv-cli/src/options.rs
  crates/uv-dev/Cargo.toml
  crates/uv-dev/src/build.rs
  crates/uv-dev/src/main.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/build.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/build.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/help.rs
  docs/reference/cli.md
Labels: enhancement, cli

#6898 Support `uv build --wheel` from source distributions
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/build.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/build.rs
  docs/reference/cli.md
Labels: enhancement, cli

#6912 Show build output by default in `uv build`
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/src/lib.rs
  crates/uv-configuration/src/build_options.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-types/src/traits.rs
  crates/uv/src/commands/build.rs
  crates/uv/tests/build.rs
Labels: enhancement

#6990 Add `--package` support to `uv build`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/build.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/build.rs
  docs/reference/cli.md
Labels: enhancement

#6991 Add documentation for `uv build`
  docs/concepts/projects.md
  docs/guides/projects.md
  docs/guides/publish.md
Labels: documentation

#7031 Use correct ordering semantics for narrowing upper-bounded Python requirements
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_optional_missing.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_optional_present.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_required_present.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_source_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_source_version_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_version_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_direct_has_subdir.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_direct_no_subdir.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_directory.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_editable.snap
  crates/uv-resolver/src/marker.rs
  crates/uv-resolver/src/requires_python.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#6986 docs(configuration): clarify `uv.toml` precedence
  docs/configuration/files.md
Labels: documentation

#7010 Add project docs for `project.scripts`
  docs/concepts/projects.md
Labels: documentation

#7038 Touchup to the project environment config section
  docs/concepts/projects.md
  docs/configuration/environment.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
Labels: documentation

#7046 Make invlaid core-metadata tag non-fatal
  crates/uv-client/src/html.rs
Labels: compatibility

#7044 Bump version to 0.4.5
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: release

#7048 Misc projects docs grammar fixes
  docs/concepts/projects.md
Labels: documentation

#7037 Allow multiple packages for `uv tool upgrade/uninstall`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/tool/uninstall.rs
  crates/uv/src/commands/tool/upgrade.rs
  crates/uv/src/settings.rs
  crates/uv/tests/tool_uninstall.rs
  crates/uv/tests/tool_upgrade.rs
  docs/reference/cli.md
Labels: cli

#6918 Sort by implementation in `uv python list`
  crates/uv/src/commands/python/list.rs
Labels: cli

#7051 Update docs on `.python-version` file
  docs/concepts/projects.md
  docs/concepts/python-versions.md
  docs/guides/projects.md
Labels: documentation

#7054 ci(docker)!: adjust entrypoint and cmd for inherited images
  .github/workflows/build-docker.yml
Labels: release

#7060 Use distribution hash over registry hash
  crates/uv-resolver/src/resolution/graph.rs
Labels: bug

#7061 Strip fragments from direct source URLs in lockfile
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/lock.rs
Labels: bug

#7050 Implement `--show-version-specifiers` for `tool list`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/tool/list.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/tool_list.rs
  docs/reference/cli.md
Labels: enhancement, cli

#7063 fix inverted log message
  crates/uv/src/commands/build.rs
  crates/uv/tests/build.rs
Labels: bug

#7077 Accept vec of packages in uv tool uninstall
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/tool/uninstall.rs
  crates/uv/src/settings.rs
Labels: internal

#7086 Don't include registry hashes for URL distributions
  crates/uv-resolver/src/resolution/graph.rs
Labels: internal

#7090 Document how to disable path modifications during install
  docs/getting-started/installation.md
Labels: documentation

#7083 Document how to manually update locked package version
  docs/concepts/projects.md
Labels: documentation

#7076 Remove propagate_markers
  crates/uv-resolver/src/graph_ops.rs
  crates/uv-resolver/src/lock/requirements_txt.rs
  crates/uv-resolver/src/resolution/display.rs
  crates/uv-resolver/src/resolution/requirements_txt.rs
Labels: internal

#7084 Use astral-sh/setup-uv action
  .github/workflows/sync-python-releases.yml
Labels: internal

#7056 Document official `setup-uv` action
  .github/workflows/sync-python-releases.yml
  docs/guides/integration/github.md
Labels: documentation

#7093 Respect hashes in constraints files
  crates/bench/benches/uv.rs
  crates/distribution-types/src/specified_requirement.rs
  crates/pypi-types/src/requirement.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-installer/src/site_packages.rs
  crates/uv-requirements/src/specification.rs
  crates/uv-types/src/hash.rs
  crates/uv/src/commands/build.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/venv.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_sync.rs
Labels: enhancement, security

#7092 Upgrade to the latest cargo-dist version
  .github/workflows/release.yml
  Cargo.toml
Labels: release

#7085 Accept `--build-constraints` in `uv build`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/build.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/build.rs
  docs/concepts/projects.md
  docs/reference/cli.md
Labels: enhancement, cli

#7094 Add `--require-hashes` and `--verify-hashes` to `uv build`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/build.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/build.rs
  docs/reference/cli.md
Labels: enhancement, cli

#7098 Remove timestamp exact vs. approximate enum
  crates/uv-cache/src/lib.rs
Labels: internal

#7100 Support `--no-build` and `--no-binary` in `uv sync` et al
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/sync.rs
Labels: bug

#7102 Invalidate lockfile when member versions change
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-workspace/src/pyproject.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/sync.rs
Labels: bug

#7103 Bump version to 0.4.6
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: release

#7108 Take intersection of constraint and requirements hashes
  crates/uv-types/src/hash.rs
  crates/uv/tests/pip_install.rs
Labels: enhancement

#7106 Add `-ExecutionPolicy ByPass` to Windows installer recommendations
  docs/getting-started/installation.md
Labels: documentation, internal

#7109 Add `--output-file` to `uv export`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/export.rs
  docs/reference/cli.md
Labels: enhancement, cli

#7110 Add `--no-emit-project` and friends to `uv export`
  crates/uv-cli/src/lib.rs
  crates/uv-configuration/src/install_options.rs
  crates/uv-resolver/src/lock/requirements_txt.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/export.rs
  docs/reference/cli.md
Labels: enhancement, cli

#7111 Fixup comment for `export --output-file`
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: documentation, internal

#7112 Prune unused source distributions from the cache
  Cargo.lock
  crates/uv-cache/src/lib.rs
  crates/uv-cache/src/removal.rs
  crates/uv-distribution/Cargo.toml
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/lib.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-distribution/src/source/revision.rs
  crates/uv/src/commands/cache_prune.rs
  crates/uv/tests/cache_prune.rs
Labels: enhancement, cache

#7114 Add distinctive logging for cache prune phases
  crates/uv-cache/src/lib.rs
  crates/uv/tests/cache_prune.rs
Labels: tracing

#7104 Put CLI changes in "Enhancements" section
  pyproject.toml
Labels: documentation, internal

#7122 chore: Fix typo in docs
  docs/pip/environments.md
Labels: documentation

#7120 (doc) Fix wrong examples for locking
  docs/pip/compile.md
Labels: documentation

#7133 chore: Remove dep on derivative
  Cargo.lock
  Cargo.toml
  crates/uv-resolver/Cargo.toml
  crates/uv-resolver/src/pubgrub/report.rs
Labels: internal

#7140 Write trailing newline to `.python-version` files
  crates/uv-python/src/version_files.rs
Labels: bug

#7131 Avoid panicking when encountering an invalid Python version during `uv python list`
  crates/uv-python/src/downloads.rs
  crates/uv-python/src/installation.rs
  crates/uv-python/src/managed.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/src/commands/python/list.rs
  crates/uv/src/commands/python/uninstall.rs
Labels: bug

#7141 Fix typo `aaarch64->aarch64`
  CHANGELOG.md
  crates/uv-cli/src/lib.rs
  crates/uv-settings/src/settings.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/sync.rs
  docs/reference/cli.md
  docs/reference/settings.md
  uv.schema.json
Labels: documentation

#7127 Skip metadata fetch for `--no-deps` and `pip sync`
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv-resolver/src/resolution/mod.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/cache_clean.rs
  crates/uv/tests/cache_prune.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_sync.rs
Labels: performance

#7151 Avoid removing entries during `read_dir`
  crates/uv-distribution/src/source/mod.rs
Labels: bug

#7150 Bump version to v0.4.7
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: release

#7169 Add build isolation logging to build operations
  crates/uv-build/src/lib.rs
Labels: tracing

#7138 installation.md: update shell syntax for setting env vars
  docs/getting-started/installation.md
Labels: documentation

#7107 Document support for `UV_INSTALL_DIR`
  docs/getting-started/installation.md
Labels: documentation

#7174 Avoid extra newlines in debug logging for source builds
  crates/uv-build/src/lib.rs
Labels: bug, tracing

#7168 docs: list supported sdist formats
  README.md
  crates/uv-cli/src/lib.rs
  crates/uv-settings/src/settings.rs
  docs/concepts/dependencies.md
  docs/concepts/projects.md
  docs/concepts/resolution.md
  docs/reference/cli.md
  docs/reference/settings.md
  uv.schema.json
Labels: documentation

#7178 Clearer registry Python sort
  crates/uv-python/src/py_launcher.rs
Labels: internal

#7187 Bump Rust toolchain to 1.81
  Cargo.toml
  crates/pep440-rs/src/version.rs
  crates/uv/tests/edit.rs
  crates/uv/tests/lock_scenarios.rs
  rust-toolchain.toml
Labels: internal

#7194 DRY up exclusion checks in selector
  crates/uv-resolver/src/candidate_selector.rs
Labels: performance, internal

#7189 docs(concepts): mention PEP 625
  docs/concepts/resolution.md
Labels: documentation

#7200 ignore macOS .DS_Store files
  .gitignore
Labels: internal

#7198 Improve error message for uv init already init-ed
  crates/uv/src/commands/project/init.rs
  crates/uv/tests/init.rs
Labels: error messages

#7188 Direct users towards `uv venv` to create a virtual environment
  crates/uv-python/src/environment.rs
  crates/uv/tests/pip_sync.rs
Labels: error messages

#7201 treat .tgz the same as .tar.gz
  crates/distribution-filename/src/extension.rs
  crates/uv/tests/build.rs
  docs/concepts/resolution.md
Labels: compatibility

#7209 Prune unreachable packages from `--universal` output
  crates/uv-resolver/src/graph_ops.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/resolution/display.rs
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv-resolver/src/resolution/mod.rs
  crates/uv-resolver/src/resolution/requirements_txt.rs
  crates/uv/tests/lock_scenarios.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/snapshots/ecosystem__transformers-uv-lock-output.snap
Labels: bug

#7210 Avoid distribution clones in `requirements.txt` graph
  crates/uv-resolver/src/resolution/display.rs
  crates/uv-resolver/src/resolution/requirements_txt.rs
Labels: internal

#7195 Avoid iteration for singleton selections
  crates/pep440-rs/src/version.rs
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/version_map.rs
Labels: performance

#7217 Fix typo in name normalization
  crates/uv-normalize/src/dist_info_name.rs
  crates/uv-normalize/src/group_name.rs
Labels: internal

#7175 Respect exclusion when collecting workspace members
  Cargo.lock
  crates/uv-workspace/Cargo.toml
  crates/uv-workspace/src/workspace.rs
Labels: bug

#7226 Avoid batch prefetching for un-optimized registries
  Cargo.lock
  crates/bench/benches/uv.rs
  crates/distribution-types/Cargo.toml
  crates/distribution-types/src/index_url.rs
  crates/distribution-types/src/prioritized_distribution.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-client/tests/remote_metadata.rs
  crates/uv-dev/src/wheel_metadata.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-resolver/src/resolver/batch_prefetch.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv-types/src/traits.rs
  crates/uv/src/commands/build.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/venv.rs
Labels: performance

#7136 Add support for dynamic cache keys
  Cargo.lock
  Cargo.toml
  crates/distribution-types/Cargo.toml
  crates/distribution-types/src/cached.rs
  crates/distribution-types/src/installed.rs
  crates/install-wheel-rs/Cargo.toml
  crates/install-wheel-rs/Readme.md
  crates/install-wheel-rs/src/linker.rs
  crates/install-wheel-rs/src/wheel.rs
  crates/uv-cache-info/Cargo.toml
  crates/uv-cache-info/src/cache_info.rs
  crates/uv-cache-info/src/commit_info.rs
  crates/uv-cache-info/src/lib.rs
  crates/uv-cache-info/src/timestamp.rs
  crates/uv-cache/Cargo.toml
  crates/uv-cache/src/by_timestamp.rs
  crates/uv-cache/src/lib.rs
  crates/uv-configuration/Cargo.toml
  crates/uv-configuration/src/config_settings.rs
  crates/uv-configuration/src/package_options.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/Cargo.toml
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/download.rs
  crates/uv-distribution/src/index/built_wheel_index.rs
  crates/uv-distribution/src/index/cached_wheel.rs
  crates/uv-distribution/src/source/built_wheel_metadata.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-git/Cargo.toml
  crates/uv-installer/Cargo.toml
  crates/uv-installer/src/installer.rs
  crates/uv-installer/src/plan.rs
  crates/uv-installer/src/satisfies.rs
  crates/uv-python/Cargo.toml
  crates/uv-python/src/interpreter.rs
  crates/uv-settings/Cargo.toml
  crates/uv-settings/src/settings.rs
  crates/uv-types/src/traits.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/lib.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_sync.rs
  docs/concepts/cache.md
  docs/reference/settings.md
  uv.schema.json
Labels: enhancement, cache

#7218 Surface dedicated errors for `.python-version` conflict with `requires-python`
  crates/uv-python/src/version_files.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/run.rs
  crates/uv/tests/sync.rs
Labels: error messages

#7233 Bump version to v0.4.8
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#7238 Break up `uv-build/src/lib.rs`
  crates/uv-build/src/error.rs
  crates/uv-build/src/lib.rs
Labels: internal

#7139 Invalidate cache when `--config-settings` change
  Cargo.lock
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/Cargo.toml
  crates/uv-distribution/src/index/built_wheel_index.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-installer/src/plan.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/pip_install.rs
Labels: bug, cache

#7239 Add a dedicated error for packages that fail due to `distutils` deprecation
  crates/uv-build/src/error.rs
  crates/uv-build/src/lib.rs
  crates/uv-dispatch/src/lib.rs
Labels: error messages

#7254 Remove workspace root for single-member workspace with `uv export`
  crates/uv-configuration/src/install_options.rs
  crates/uv/tests/export.rs
Labels: bug

#7231 Extract METADATA reading into a crate
  Cargo.lock
  Cargo.toml
  crates/install-wheel-rs/src/lib.rs
  crates/uv-client/Cargo.toml
  crates/uv-client/src/error.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-client/src/remote_metadata.rs
  crates/uv-distribution/Cargo.toml
  crates/uv-distribution/src/download.rs
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-extract/Cargo.toml
  crates/uv-metadata/Cargo.toml
  crates/uv-metadata/src/lib.rs
  crates/uv-resolver/Cargo.toml
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv/tests/pip_sync.rs
Labels: internal

#7252 Allow setting a target version for `uv self update`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/self_update.rs
  crates/uv/src/lib.rs
Labels: enhancement

#7262 Avoid updating `pyproject.toml` offsets on non-add edits
  crates/uv/src/commands/project/add.rs
  crates/uv/tests/edit.rs
Labels: bug

#5927 Run benchmarks with `--profile profiling`
  .github/workflows/ci.yml
  Cargo.lock
  crates/bench/Cargo.toml
Labels: internal

#7267 Deduplicate implementation for `python_installation_from_directory`
  crates/uv-python/src/discovery.rs
Labels: internal

#7265 Add test cases for finding unsupported versions
  crates/uv/tests/python_find.rs
Labels: testing

#7269 Improve error message when requested Python version is unsupported
  crates/uv-python/src/discovery.rs
  crates/uv/tests/python_find.rs
Labels: error messages

#7263 Add support for managed Python 3.13 and update CPython versions
  crates/pep440-rs/src/version.rs
  crates/uv-python/download-metadata.json
  crates/uv-python/fetch-download-metadata.py
  crates/uv-python/src/downloads.inc
  crates/uv-python/src/downloads.inc.mustache
  crates/uv-python/src/downloads.rs
  crates/uv-python/src/installation.rs
  crates/uv-python/src/interpreter.rs
  crates/uv-python/src/managed.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/src/commands/python/list.rs
  crates/uv/src/commands/python/uninstall.rs
Labels: enhancement

#7266 Block Python <3.7 not only on linux
  crates/uv-python/python/get_interpreter_info.py
Labels: enhancement

#7232 Create `py.typed` files during `uv init --lib`
  crates/uv/src/commands/project/init.rs
  crates/uv/tests/init.rs
  docs/concepts/projects.md
Labels: enhancement

#7276 Revert `Cargo.lock` changes
  Cargo.lock
Labels: internal

#7192 Add `uv run --no-sync`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/run.rs
  docs/concepts/projects.md
  docs/reference/cli.md
Labels: cli

#7274 Bump version to 0.4.9
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#7278 Avoid selecting pre-releases for Python downloads without a version request
  crates/uv-python/src/downloads.rs
Labels: bug

#7277 Apply `--no-install` options when constructing resolution
  Cargo.lock
  crates/uv-configuration/Cargo.toml
  crates/uv-configuration/src/install_options.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/requirements_txt.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/sync.rs
Labels: bug

#7301 Support relative paths in `uv add --script`
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/edit.rs
Labels: bug

#7305 Avoid enforcing platform compatibility when validating lockfile
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/sync.rs
Labels: bug, error messages

#7302 Add Python 3.13 system test for Linux
  .github/workflows/ci.yml
Labels: testing

#7268 Support globs as cache keys in `tool.uv.cache-keys`
  Cargo.lock
  crates/uv-cache-info/Cargo.toml
  crates/uv-cache-info/src/cache_info.rs
  crates/uv-settings/src/settings.rs
  crates/uv/tests/pip_install.rs
  docs/concepts/cache.md
  docs/reference/settings.md
  uv.schema.json
Labels: enhancement, configuration

#7304 Show verbose output during system install in test
  scripts/check_system_python.py
Labels: internal, testing

#7306 Allow explicitly requesting an system interpreter version in `check_system_python`
  .github/workflows/ci.yml
  scripts/check_system_python.py
Labels: testing

#7290 Include pre-release Python versions in `uv python list`
  crates/uv-python/src/downloads.rs
  crates/uv/src/commands/python/list.rs
  crates/uv/src/commands/python/uninstall.rs
Labels: bug

#7307 Add dedicated lock errors for wheel-only distributions
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/sync.rs
Labels: error messages

#7300 Avoid selecting prerelease Python installations without opt-in
  .github/workflows/ci.yml
  crates/uv-python/src/discovery.rs
  docs/concepts/python-versions.md
Labels: bug

#7318 Avoid installing transitive dev dependencies
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/sync.rs
Labels: bug

#7337 Use `globwalk` for `cache-keys` matching
  Cargo.lock
  Cargo.toml
  crates/uv-cache-info/Cargo.toml
  crates/uv-cache-info/src/cache_info.rs
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/index/built_wheel_index.rs
  crates/uv-distribution/src/source/mod.rs
Labels: performance

#7330 Fix documentation typos for `uv build --build-constraint` flag
  CHANGELOG.md
  crates/uv-cli/src/lib.rs
  docs/concepts/projects.md
  docs/reference/cli.md
Labels: documentation

#7338 Avoid clobbering existing `py.typed` files contents in `uv init`
  crates/uv/src/commands/project/init.rs
  crates/uv/tests/init.rs
Labels: bug

#7339 Clarify Python requirement source for script incompatibilities
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/run.rs
Labels: error messages
