Repository astral-sh/uv, pull requests merged in 2024-08, with the labels that each got.

#5678 Avoid unwrap when serializing receipts
  crates/uv-tool/src/lib.rs
  crates/uv-tool/src/receipt.rs
  crates/uv-tool/src/tool.rs
  crates/uv/tests/tool_install.rs
Labels: internal

#5657 Add transformers `pyproject.toml` to test requirements
  scripts/requirements/.gitignore
  scripts/requirements/transformers/pyproject.toml
Labels: internal, preview

#5665 Grouping `GlobalArgs` to dedicated heading
  crates/uv-cache/src/cli.rs
  crates/uv-cli/src/lib.rs
  crates/uv/tests/help.rs
Labels: cli

#5685 Generate CLI reference for documentation
  Cargo.lock
  crates/uv-cli/Cargo.toml
  crates/uv-dev/Cargo.toml
  crates/uv-dev/src/generate_cli_reference.rs
  crates/uv-dev/src/main.rs
  docs/reference/cli.md
  docs/stylesheets/extra.css
  mkdocs.template.yml
Labels: documentation, preview

#5689 Move settings reference to reference section
  crates/uv-dev/src/generate_options_reference.rs
  docs/configuration/files.md
  docs/configuration/index.md
  docs/reference/settings.md
  mkdocs.template.yml
Labels: documentation, preview

#5694 Fixup settings reference
  mkdocs.template.yml
Labels: internal

#5686 Include newly-added optional dependencies in lockfile
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/tests/edit.rs
Labels: bug, preview

#5679 Support legacy tool receipts with PEP 508 requirements
  crates/uv-tool/src/tool.rs
  crates/uv/tests/tool_list.rs
Labels: bug, preview

#5691 Move `--python` and `--python-version` into the "Python options" help
  crates/uv-cli/src/lib.rs
Labels: cli

#5688 Set lower bounds in `uv add`
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/tests/edit.rs
Labels: enhancement, preview

#5701 Add CLI reference to `generate-all`
  crates/uv-dev/src/generate_all.rs
Labels: internal

#5700 Unhide the experimental top-level commands
  crates/uv-cli/src/lib.rs
  crates/uv/tests/help.rs
  docs/reference/cli.md
Labels: preview

#5704 Don't use equals signs for cli args with value
  STYLE.md
  docs/concepts/resolution.md
  docs/pip/compatibility.md
  docs/pip/environments.md
Labels: documentation

#5705 Limit sync after `uv add`
  crates/uv/src/commands/project/add.rs
Labels: cli, preview

#5706 Update top-level command descriptions
  crates/uv-cli/src/lib.rs
  crates/uv/tests/help.rs
  docs/reference/cli.md
Labels: cli

#5697 Use "pre-release" in prose and `Prerelease` in code
  CHANGELOG.md
  STYLE.md
  crates/pep440-rs/Readme.md
  crates/pep440-rs/python/Readme.md
  crates/pep440-rs/src/lib.rs
  crates/pep440-rs/src/version.rs
  crates/pep440-rs/src/version_specifier.rs
  crates/uv-cli/src/lib.rs
  crates/uv-cli/src/options.rs
  crates/uv-python/src/python_version.rs
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/options.rs
  crates/uv-resolver/src/prerelease.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/pubgrub/specifier.rs
  crates/uv-settings/src/combine.rs
  crates/uv-settings/src/settings.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/settings.rs
  crates/uv/tests/pip_compile.rs
  uv.schema.json
Labels: documentation

#5709 Support dev dependencies in virtual workspace roots
  crates/uv-distribution/src/lib.rs
  crates/uv-distribution/src/metadata/mod.rs
  crates/uv-distribution/src/metadata/requires_dist.rs
  crates/uv-normalize/src/group_name.rs
  crates/uv-normalize/src/lib.rs
  crates/uv-resolver/src/lock.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/sync.rs
Labels: enhancement, preview

#5695 Add a dedicated error for members with mismatched Python requirements
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/tests/sync.rs
  scripts/workspaces/albatross-root-workspace/packages/bird-feeder/pyproject.toml
Labels: error messages, preview

#5712 Bump version to 0.2.33
  CHANGELOG.md
  Cargo.lock
  PREVIEW-CHANGELOG.md
  README.md
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: no-build, release

#5717 Install Python versions with previous uv release
  .github/workflows/ci.yml
Labels: testing

#5639 Support build constraints
  PIP_COMPATIBILITY.md
  README.md
  crates/bench/benches/uv.rs
  crates/uv-cli/src/lib.rs
  crates/uv-dev/src/build.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-resolver/src/manifest.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/help.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_sync.rs
  crates/uv/tests/show_settings.rs
  docs/reference/cli.md
Labels: enhancement

#5722 Fix CLI reference URLs to subcommands
  crates/uv-dev/src/generate_cli_reference.rs
  docs/reference/cli.md
Labels: documentation, preview

#5720 Show default and possible options in CLI reference documentation
  crates/uv-dev/src/generate_cli_reference.rs
  docs/reference/cli.md
Labels: documentation, preview

#5708 Use prettier to format the documentation
  .github/workflows/ci.yml
  .prettierignore
  BENCHMARKS.md
  CHANGELOG.md
  CONTRIBUTING.md
  PIP_COMPATIBILITY.md
  README.md
  STYLE.md
  crates/README.md
  crates/install-wheel-rs/Readme.md
  crates/pep440-rs/CHANGELOG.md
  crates/pep440-rs/Readme.md
  crates/pep440-rs/python/Readme.md
  crates/pep508-rs/Readme.md
  crates/uv-trampoline/README.md
  docs/concepts/cache.md
  docs/concepts/dependencies.md
  docs/concepts/projects.md
  docs/concepts/python-versions.md
  docs/concepts/resolution.md
  docs/concepts/tools.md
  docs/concepts/workspaces.md
  docs/configuration/authentication.md
  docs/configuration/environment.md
  docs/configuration/index.md
  docs/features.md
  docs/first-steps.md
  docs/guides/index.md
  docs/guides/install-python.md
  docs/guides/integration/alternative-indexes.md
  docs/guides/integration/github.md
  docs/guides/projects.md
  docs/guides/scripts.md
  docs/guides/tools.md
  docs/index.md
  docs/installation.md
  docs/pip/compatibility.md
  docs/pip/compile.md
  docs/pip/dependencies.md
  docs/pip/environments.md
  docs/platforms.md
  scripts/packages/README.md
Labels: documentation, internal

#5735 Skip files when detecting workspace members
  crates/uv-workspace/src/workspace.rs
  scripts/workspaces/albatross-root-workspace/packages/.gitignore
Labels: bug, preview

#5738 Remove double-proxy nodes in error reporting
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/pubgrub/package.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/pip_compile.rs
Labels: bug, error messages

#5741 Respect `.python-version` in `--isolated` runs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/run.rs
Labels: bug, preview

#5736 Respect pre-release preferences from input files
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/requires_python.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#5745 Always strip in release mode
  Cargo.toml
Labels: enhancement

#5718 Improvements to the documentation
  CONTRIBUTING.md
  STYLE.md
  docs/concepts/projects.md
  docs/concepts/python-versions.md
  docs/features.md
  docs/first-steps.md
  docs/guides/install-python.md
  docs/guides/integration/alternative-indexes.md
  docs/guides/integration/docker.md
  docs/guides/projects.md
  docs/guides/scripts.md
  docs/guides/tools.md
  docs/index.md
  docs/installation.md
  docs/pip/compile.md
  docs/pip/environments.md
  docs/pip/inspection.md
  docs/pip/packages.md
  mkdocs.template.yml
Labels: documentation, preview

#5723 Rewrite resolver docs
  BENCHMARKS.md
  README.md
  docs/concepts/resolution.md
  docs/index.md
  docs/reference/resolution-internals.md
  mkdocs.template.yml
Labels: documentation, preview

#5728 Better workspace documentation
  docs/concepts/workspaces.md
Labels: documentation, preview

#5753 Omit local segments when adding uv add bounds
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/tests/edit.rs
Labels: bug, preview

#5743 Avoid monomorphization of `untar`
  crates/uv-extract/src/stream.rs
Labels: internal

#5755 Fix the default value of python-preference in docs/reference/settings.md
  crates/uv-settings/src/settings.rs
  docs/reference/settings.md
Labels: documentation

#5756 Respect malformed `.dist-info` directories in tool installs
  crates/uv-installer/src/site_packages.rs
  crates/uv-tool/src/lib.rs
  crates/uv/src/commands/tool/common.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/tool_install.rs
Labels: bug, preview

#5761 Use lockfile directly in `uv tree`
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/lock.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/tree.rs
Labels: bug, preview

#5766 Avoid lingering dev and optional dependencies in `uv tree`
  crates/uv-resolver/src/lock.rs
  crates/uv/tests/tree.rs
Labels: bug, preview

#5770 Remove lock from `TreeDisplay`
  crates/uv-resolver/src/lock.rs
Labels: internal

#5769 Fix broken anchor links in docs about dependencies
  docs/concepts/dependencies.md
Labels: documentation

#5787 Use cache for Python install temporary directories
  crates/uv-python/src/downloads.rs
  crates/uv-python/src/installation.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/src/lib.rs
Labels: preview

#5788 Remove top-level bar from Python installs
  crates/uv/src/commands/reporters.rs
Labels: cli, preview

#5786 Make some minor tweaks to the docs
  docs/concepts/dependencies.md
  docs/first-steps.md
  docs/guides/install-python.md
  docs/guides/integration/github.md
  docs/guides/projects.md
  docs/guides/tools.md
  docs/index.md
  docs/installation.md
Labels: documentation, preview

#5795 Use `uvx` in docs serve contributing command
  CONTRIBUTING.md
Labels: documentation

#5696 Collapse policies section into reference
  docs/reference/resolver-internals.md
  mkdocs.template.yml
Labels: documentation, preview

#5763 Filter `uv tree` to current platform by default
  crates/uv-cli/src/lib.rs
  crates/uv-resolver/src/lock.rs
  crates/uv/src/commands/pip/tree.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/tree.rs
Labels: enhancement, cli, preview

#5764 Support `--python-platform` in `uv tree`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/pip/mod.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/tree.rs
  docs/reference/cli.md
Labels: enhancement, cli, preview

#5768 Show extras and dev dependencies in `uv tree`
  crates/uv-resolver/src/lock.rs
  crates/uv/tests/tree.rs
Labels: enhancement, preview

#5800 Remove interpreter from `BuildContext` trait
  crates/uv-dev/src/build.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-types/src/traits.rs
Labels: internal

#5798 Don't show deprecated warning in `uvx --isolated`
  crates/uv/src/lib.rs
Labels: bug, preview

#5799 Avoid using already-installed tools on `--upgrade` or `--reinstall`
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/tool_run.rs
Labels: cli, preview

#5794 Add a guide for publishing packages
  docs/guides/projects.md
  docs/guides/publish.md
  docs/guides/scripts.md
  docs/guides/tools.md
  mkdocs.template.yml
Labels: documentation, preview

#5693 Create help sections for build, install, resolve, and index
  crates/uv-cli/src/lib.rs
  crates/uv/tests/common/mod.rs
Labels: cli

#5803 Redact registry credentials in lockfile
  crates/uv-resolver/src/lock.rs
  crates/uv/tests/lock.rs
Labels: enhancement, preview

#5805 Strip URL fragments from lockfile
  crates/distribution-types/src/file.rs
  crates/distribution-types/src/lib.rs
  crates/uv-resolver/src/lock.rs
  crates/uv/tests/edit.rs
  crates/uv/tests/lock_scenarios.rs
Labels: internal

#5801 Add `--no-sources` to avoid reading from `tool.uv.sources`
  crates/bench/benches/uv.rs
  crates/uv-cli/src/lib.rs
  crates/uv-cli/src/options.rs
  crates/uv-configuration/src/lib.rs
  crates/uv-configuration/src/sources.rs
  crates/uv-dev/src/build.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/src/metadata/mod.rs
  crates/uv-distribution/src/metadata/requires_dist.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-settings/src/settings.rs
  crates/uv-types/src/traits.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/show_settings.rs
  docs/concepts/dependencies.md
  docs/reference/settings.md
  uv.schema.json
Labels: cli, preview

#5812 Support overlapping local and non-local requirements in forks
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/pip_compile.rs
Labels: bug, resolver

#5813 Update the resolution concept documentation
  docs/concepts/resolution.md
Labels: documentation, preview

#5821 Support uv add `--dev` in virtual workspaces
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/tests/edit.rs
Labels: bug, preview

#5707 Allow downloading wheels for metadata with `--no-binary`
  PIP_COMPATIBILITY.md
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/error.rs
  crates/uv-installer/src/preparer.rs
  crates/uv/src/commands/pip/operations.rs
Labels: bug

#5823 Update resolver reference documentation
  docs/concepts/resolution.md
  docs/reference/resolver-internals.md
Labels: documentation, preview

#5826 Fix some console blocks in the environment doc
  docs/pip/environments.md
Labels: documentation, preview

#5825 Add "next steps" to some early documentation pages
  docs/concepts/dependencies.md
  docs/features.md
  docs/installation.md
Labels: documentation, preview

#5824 Update documentation index
  docs/index.md
Labels: documentation, preview

#5827 Address some feedback in the tools documentation
  docs/concepts/tools.md
  docs/guides/tools.md
Labels: documentation, preview

#5820 Update the override section with some content from the README
  docs/concepts/resolution.md
Labels: documentation, preview

#5828 Link to the GitHub integration guide from the cache concept
  docs/concepts/cache.md
Labels: documentation, preview

#5829 Add `--no-build-isolation` to uv lock et al
  crates/uv-cli/src/lib.rs
  crates/uv-cli/src/options.rs
  crates/uv-settings/src/settings.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/settings.rs
  crates/uv/tests/sync.rs
  docs/reference/settings.md
  uv.schema.json
Labels: configuration, preview

#5830 Improve display order of top-level commands
  crates/uv-cli/src/lib.rs
  crates/uv/tests/help.rs
  docs/reference/cli.md
Labels: cli

#5833 Add help heading for `--no-sources`
  crates/uv-cli/src/lib.rs
Labels: cli

#5842 Reject `pyproject.toml` in `--config-file`
  crates/uv-settings/src/combine.rs
  crates/uv-settings/src/settings.rs
  crates/uv-workspace/src/pyproject.rs
  crates/uv/src/lib.rs
  crates/uv/tests/show_settings.rs
  uv.schema.json
Labels: bug

#5843 Minor improvements to benchmarking setup
  scripts/benchmark/pyproject.toml
  scripts/benchmark/src/benchmark/__init__.py
  scripts/benchmark/src/benchmark/resolver.py
  scripts/benchmark/src/benchmark/tools.py
  scripts/benchmark/uv.lock
  scripts/requirements/transformers-extras.in
Labels: internal, benchmarks

#5845 Avoid reusing incompatible distributions across lock and sync
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/tests/sync.rs
Labels: bug

#5844 Add `--python` argument to benchmark script
  scripts/benchmark/src/benchmark/resolver.py
Labels: internal, benchmarks

#5834 Improve CLI documentation for global options
  crates/uv-cli/src/lib.rs
  crates/uv/tests/help.rs
  docs/reference/cli.md
Labels: cli

#5847 Fix GitHub cache integration link
  docs/concepts/cache.md
Labels: internal

#5846 Reuse existing virtualenvs with `--no-project`
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/run.rs
Labels: bug, preview

#5849 Ensure `python`-to-`pythonX.Y` symlink exists in downloaded Pythons
  crates/uv-python/src/downloads.rs
Labels: bug, preview

#5850 Resolver internals docs touchups
  .prettierignore
  docs/reference/resolver-internals.md
Labels: documentation, preview

#5857 Replace unreachable `todo!()` with `unreachable!()` in locking
  crates/uv-resolver/src/lock.rs
Labels: preview

#5854 Use uv installer during build
  docs/guides/publish.md
Labels: documentation, preview

#5841 Improve CLI documentation for `uv run`
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: documentation

#5864 Support empty dependencies in PEP 723 scripts
  crates/uv-scripts/src/lib.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/run.rs
Labels: bug, preview

#5863 Avoid panic when re-locking with precise commit
  crates/pypi-types/src/parsed_url.rs
  crates/pypi-types/src/requirement.rs
  crates/uv-git/src/git.rs
  crates/uv-git/src/lib.rs
  crates/uv-git/src/resolver.rs
  crates/uv-installer/src/plan.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-resolver/src/lock.rs
  crates/uv/tests/lock.rs
Labels: bug, preview

#5868 Assume `git+` prefix when URLs end in `.git`
  crates/pypi-types/src/parsed_url.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/tests/edit.rs
  crates/uv/tests/pip_install.rs
Labels: enhancement

#5862 Improve documentation for `uv init` CLI
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: documentation, cli, preview

#5869 Improve `--python` CLI documentation
  clippy.toml
  crates/uv-cli/src/lib.rs
  crates/uv/tests/help.rs
  docs/reference/cli.md
Labels: documentation, cli

#5870 Improve CLI documentation for `uv tree`
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: documentation, preview

#5871 Replace `uv help python` references in CLI documentation with links
  crates/uv-dev/src/generate_cli_reference.rs
  docs/reference/cli.md
Labels: documentation, preview

#5873 Use a larger runner for Windows test jobs
  .github/workflows/ci.yml
Labels: testing

#5874 Use a larger runner for macOS test jobs
  .github/workflows/ci.yml
Labels: testing

#5880 Add `--locked` coverage to lock tests
  crates/uv/tests/lock.rs
Labels: testing

#5881 Add `uv add --no-sync` and `uv remove --no-sync`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/edit.rs
Labels: cli, preview

#5853 Group resolver options in lockfile
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__hash_optional_missing.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__hash_optional_present.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__hash_required_present.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__missing_dependency_source_unambiguous.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__missing_dependency_source_version_unambiguous.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__missing_dependency_version_unambiguous.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__source_direct_has_subdir.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__source_direct_no_subdir.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__source_directory.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__source_editable.snap
  crates/uv/tests/branching_urls.rs
  crates/uv/tests/edit.rs
  crates/uv/tests/lock.rs
Labels: preview, lock

#5883 Use a larger runner for Linux test jobs
  .github/workflows/ci.yml
Labels: testing

#5885 Fix lock test cases
  crates/uv/tests/lock.rs
Labels: internal

#5889 Bump version to v0.2.34
  CHANGELOG.md
  Cargo.lock
  PREVIEW-CHANGELOG.md
  README.md
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: release

#5892 Setup Rust after restoring the cache
  .github/workflows/ci.yml
Labels: testing

#5897 Use cached environments for `--with` layers
  crates/uv/src/commands/project/run.rs
Labels: preview

#5895 Avoid requires-python warning in virtual-only workspace
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/edit.rs
  crates/uv/tests/sync.rs
Labels: cli, preview

#5719 Enable mirror for `python-build-standalone` downloads
  README.md
  crates/uv-python/src/downloads.rs
  crates/uv/src/commands/python/install.rs
  docs/configuration/environment.md
Labels: configuration, preview

#5894 Support `no-build-isolation-package`
  crates/uv-build/src/lib.rs
  crates/uv-cli/src/lib.rs
  crates/uv-cli/src/options.rs
  crates/uv-settings/src/settings.rs
  crates/uv-types/src/builds.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/show_settings.rs
  crates/uv/tests/sync.rs
  docs/reference/cli.md
  docs/reference/settings.md
  uv.schema.json
Labels: configuration

#5904 Enable LTO optimizations in release builds to reduce binary size
  Cargo.toml
Labels: performance

#5906 Docs: Fix link to tools concept page
  docs/guides/tools.md
Labels: documentation

#5908 Fix reuse of Git commits in lockfile
  crates/uv-git/src/resolver.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/lock.rs
Labels: bug, preview

#5907 Respect `--upgrade-package` when resolving from lockfile
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/lock.rs
Labels: bug, preview

#5810 Only textwrap json packse scenarios with packse 0.3.32
  crates/uv/tests/common/mod.rs
  crates/uv/tests/lock_scenarios.rs
  crates/uv/tests/pip_compile_scenarios.rs
  crates/uv/tests/pip_install_scenarios.rs
  scripts/scenarios/.gitignore
  scripts/scenarios/generate.py
  scripts/scenarios/requirements.in
  scripts/scenarios/requirements.txt
  scripts/scenarios/templates/compile.mustache
  scripts/scenarios/templates/install.mustache
  scripts/scenarios/templates/lock.mustache
Labels: internal

#5910 Add missing "git" feature to various tests
  crates/uv/tests/edit.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_sync.rs
  crates/uv/tests/pip_tree.rs
Labels: testing

#5861 Rename `distribution` to `packages` in lockfile
  crates/uv-requirements/src/upgrade.rs
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/preferences.rs
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__hash_optional_missing.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__hash_optional_present.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__hash_required_present.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__missing_dependency_source_ambiguous.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__missing_dependency_source_unambiguous.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__missing_dependency_source_version_ambiguous.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__missing_dependency_source_version_unambiguous.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__missing_dependency_version_ambiguous.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__missing_dependency_version_unambiguous.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__source_direct_has_subdir.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__source_direct_no_subdir.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__source_directory.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__source_editable.snap
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/branching_urls.rs
  crates/uv/tests/edit.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/lock_scenarios.rs
  crates/uv/tests/workspace.rs
  scripts/benchmark/uv.lock
Labels: preview, lock

#5899 Show build and install summaries in `uv run` and `uv tool run`
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/loggers.rs
  crates/uv/src/commands/pip/mod.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/printer.rs
  crates/uv/tests/run.rs
  crates/uv/tests/tool_run.rs
Labels: tracing, cli, preview

#5891 Skip git tests on Windows
  .github/workflows/ci.yml
Labels: testing

#5914 Improve the CLI documentation for `uv add`
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: documentation, cli, preview

#5918 Prefetch metadata in `--no-deps` mode
  crates/uv-resolver/src/resolver/mod.rs
Labels: performance

#5919 Fix failing lockfile tests
  crates/uv/tests/lock.rs
  crates/uv/tests/lock_scenarios.rs
Labels: internal

#5922 Make repeated `uv add` operations simpler
  crates/uv-workspace/src/pyproject.rs
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/tests/edit.rs
Labels: cli, preview

#5916 Improve the CLI documentation for `uv remove`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  docs/reference/cli.md
Labels: documentation, cli, preview

#5917 Improve the `uv tree` CLI documentation
  crates/uv-cli/src/lib.rs
Labels: documentation, cli, preview

#5923 Ignore local configuration in tool commands
  crates/uv/src/lib.rs
  crates/uv/tests/show_settings.rs
  docs/configuration/files.md
Labels: configuration, preview

#5925 Deprecate `--system` and `--no-system` in `uv venv`
  crates/uv-cli/src/lib.rs
  crates/uv/src/lib.rs
Labels: cli

#5926 Add CLI flags to reference documentation
  crates/uv-dev/src/generate_cli_reference.rs
  docs/reference/cli.md
Labels: documentation, preview

#5931 Search beyond workspace root when discovering configuration
  crates/uv-settings/src/lib.rs
  crates/uv/src/lib.rs
  crates/uv/tests/show_settings.rs
  docs/configuration/files.md
Labels: bug, configuration, preview

#5940 Add caveat about pip interface name
  docs/pip/index.md
Labels: documentation, preview

#5941 Respect `--upgrade-package` in tool install
  crates/uv/src/commands/tool/upgrade.rs
  crates/uv/src/settings.rs
  crates/uv/tests/tool_upgrade.rs
Labels: cli, preview

#5943 Make `--upgrade` imply `--refresh`
  crates/uv-cache/src/lib.rs
  crates/uv-cli/src/lib.rs
  crates/uv-configuration/src/package_options.rs
  crates/uv/src/lib.rs
  docs/reference/cli.md
Labels: cli

#5944 Respect subdirectories when locating Git workspaces
  crates/uv-distribution/src/source/mod.rs
  crates/uv/tests/lock.rs
Labels: bug

#5888 Enforce extension validity at parse time
  Cargo.lock
  crates/distribution-filename/src/extension.rs
  crates/distribution-filename/src/lib.rs
  crates/distribution-filename/src/source_dist.rs
  crates/distribution-types/src/buildable.rs
  crates/distribution-types/src/lib.rs
  crates/distribution-types/src/resolution.rs
  crates/pep508-rs/src/lib.rs
  crates/pypi-types/Cargo.toml
  crates/pypi-types/src/parsed_url.rs
  crates/pypi-types/src/requirement.rs
  crates/requirements-txt/src/lib.rs
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-whitespace.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-whitespace.txt.snap
  crates/requirements-txt/test-data/requirements-txt/whitespace.txt
  crates/uv-cache/src/lib.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-extract/Cargo.toml
  crates/uv-extract/src/stream.rs
  crates/uv-installer/src/plan.rs
  crates/uv-installer/src/satisfies.rs
  crates/uv-python/Cargo.toml
  crates/uv-python/src/downloads.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/flat_index.rs
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv/tests/cache_clean.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_install.rs
Labels: internal

#5954 Update packse to 0.3.34
  crates/uv/tests/common/mod.rs
  crates/uv/tests/lock_scenarios.rs
  crates/uv/tests/pip_compile_scenarios.rs
  crates/uv/tests/pip_install_scenarios.rs
  scripts/scenarios/requirements.in
  scripts/scenarios/requirements.txt
Labels: internal

#5905 Discard forks when using `--upgrade`
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/lock.rs
Labels: bug, preview

#5955 cargo: straighten out LTO configuration
  Cargo.toml
Labels: release

#5948 Add `update` alias for `uv tool upgrade`
  crates/uv-cli/src/lib.rs
Labels: cli, preview

#5932 Improve the `uv lock` CLI documentation
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: documentation, cli, preview

#5956 Display portable paths in posix venv activation commands
  crates/uv/src/commands/venv.rs
Labels: bug, windows

#5938 Add basic universal benchmarks to CI
  .github/workflows/ci.yml
  Cargo.lock
  crates/bench/Cargo.toml
  crates/bench/benches/uv.rs
Labels: internal, benchmarks

#5963 Improve the `uv venv` CLI documentation
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: documentation, cli

#5968 Move some documents to relevant sections
  docs/getting-started/features.md
  docs/getting-started/first-steps.md
  docs/getting-started/installation.md
  docs/index.md
  docs/reference/platforms.md
  docs/reference/versioning.md
  mkdocs.template.yml
Labels: documentation, preview

#5960 Run `cargo update`
  Cargo.lock
Labels: internal

#5898 Implement marker trees using algebraic decision diagrams
  Cargo.lock
  Cargo.toml
  crates/pep440-rs/src/version_specifier.rs
  crates/pep508-rs/Cargo.toml
  crates/pep508-rs/src/lib.rs
  crates/pep508-rs/src/marker/algebra.rs
  crates/pep508-rs/src/marker/mod.rs
  crates/pep508-rs/src/marker/parse.rs
  crates/pep508-rs/src/marker/simplify.rs
  crates/pep508-rs/src/marker/tree.rs
  crates/pep508-rs/src/unnamed.rs
  crates/pypi-types/src/requirement.rs
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-poetry-with-hashes.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-poetry-with-hashes.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-unix-editable.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-windows-editable.txt.snap
  crates/uv-configuration/src/constraints.rs
  crates/uv-configuration/src/overrides.rs
  crates/uv-pubgrub/Cargo.toml
  crates/uv-pubgrub/src/lib.rs
  crates/uv-requirements/src/source_tree.rs
  crates/uv-resolver/Cargo.toml
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/marker.rs
  crates/uv-resolver/src/pubgrub/mod.rs
  crates/uv-resolver/src/pubgrub/package.rs
  crates/uv-resolver/src/requires_python.rs
  crates/uv-resolver/src/resolution/display.rs
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv-resolver/src/resolution/requirements_txt.rs
  crates/uv-resolver/src/resolver/fork_map.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/resolver_markers.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/lock_scenarios.rs
  crates/uv/tests/pip_compile.rs
Labels: lock

#5953 Warn when there are missing bounds on transitive deps in lowest
  crates/distribution-types/src/resolution.rs
  crates/pep440-rs/src/version_specifier.rs
  crates/pypi-types/src/requirement.rs
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/lock.rs
Labels: enhancement

#5936 Update the interface for declaring Python download preferences
  crates/uv-cli/src/lib.rs
  crates/uv-python/src/discovery.rs
  crates/uv-python/src/installation.rs
  crates/uv-python/src/lib.rs
  crates/uv-settings/src/combine.rs
  crates/uv-settings/src/settings.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/init.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/src/commands/python/list.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/help.rs
  crates/uv/tests/lock.rs
  crates/uv/tests/show_settings.rs
  docs/concepts/python-versions.md
  docs/reference/cli.md
  docs/reference/settings.md
  uv.schema.json
Labels: configuration, preview

#5965 Document virtual environment discovery
  docs/concepts/python-versions.md
Labels: documentation, preview

#5937 Retain and respect settings in tool upgrades
  Cargo.lock
  crates/distribution-types/Cargo.toml
  crates/distribution-types/src/index_url.rs
  crates/install-wheel-rs/src/linker.rs
  crates/pep508-rs/src/verbatim_url.rs
  crates/uv-cli/src/lib.rs
  crates/uv-cli/src/options.rs
  crates/uv-configuration/src/authentication.rs
  crates/uv-configuration/src/build_options.rs
  crates/uv-configuration/src/config_settings.rs
  crates/uv-configuration/src/package_options.rs
  crates/uv-configuration/src/sources.rs
  crates/uv-resolver/src/prerelease.rs
  crates/uv-settings/src/settings.rs
  crates/uv-tool/Cargo.toml
  crates/uv-tool/src/receipt.rs
  crates/uv-tool/src/tool.rs
  crates/uv/src/commands/tool/common.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/upgrade.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/show_settings.rs
  crates/uv/tests/tool_install.rs
  crates/uv/tests/tool_list.rs
  crates/uv/tests/tool_upgrade.rs
  docs/reference/cli.md
Labels: enhancement, preview

#5971 Add hint for long help to `uvx`
  crates/uv-cli/src/lib.rs
Labels: cli, preview

#5961 Improve the `uv python` CLI documentation
  clippy.toml
  crates/uv-cli/src/lib.rs
  crates/uv/tests/help.rs
  docs/reference/cli.md
Labels: documentation, cli, preview

#5930 Improve the `uv sync` CLI documentation
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: documentation, cli, preview

#5976 Remove unnecessary optional from `uv run`
  crates/uv/src/commands/project/run.rs
Labels: internal

#5969 Support relative path wheels
  crates/distribution-types/src/lib.rs
  crates/distribution-types/src/resolution.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-installer/src/plan.rs
  crates/uv-resolver/src/lock.rs
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__hash_optional_missing.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__hash_optional_present.snap
  crates/uv-resolver/src/snapshots/uv_resolver__lock__tests__hash_required_present.snap
  crates/uv/tests/sync.rs
Labels: enhancement, preview

#5977 Warn when project-specific settings are passed to non-project `uv run` commands
  crates/uv/src/commands/project/init.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/init.rs
  crates/uv/tests/run.rs
Labels: cli, preview

#5984 Bump version to 0.2.35
  .github/workflows/build-binaries.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  PREVIEW-CHANGELOG.md
  README.md
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: release

#5989 Drop empty section from the changelog
  CHANGELOG.md
Labels: documentation, internal

#5987 Remove `editable: false` support
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-workspace/src/pyproject.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/tests/edit.rs
  docs/concepts/dependencies.md
  uv.schema.json
Labels: preview
