Repository astral-sh/uv, pull requests merged in 2024-04, with the labels that each got.

#2746 Add `pyproject.toml` et al to list of prompted packages
  crates/uv-requirements/src/sources.rs
Labels: enhancement

#2749 Remove `Cache` argument from `DistributionDatabase`
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-installer/src/downloader.rs
  crates/uv-resolver/src/resolver/mod.rs
Labels: internal

#2750 Rename to `SourceDistributionBuilder`
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/lib.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/resolver.rs
  crates/uv-requirements/src/source_tree.rs
Labels: internal

#2697 Don't use exclude newer manually in test functions
  crates/uv/tests/common/mod.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/venv.rs
Labels: internal, testing

#2736 Add Homebrew system check test
  .github/workflows/ci.yml
Labels: testing

#2758 Bump version to v0.1.27
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: release

#2684 Recursively resolve direct URL references upfront
  PIP_COMPATIBILITY.md
  crates/uv-requirements/src/lookahead.rs
  crates/uv-resolver/src/manifest.rs
  crates/uv-types/src/requirements.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/tests/pip_compile.rs
Labels: enhancement

#2762 Rename `resolver.rs` to `unnamed.rs` in `uv-requirements`
  crates/uv-requirements/src/lib.rs
  crates/uv-requirements/src/unnamed.rs
Labels: internal

#2764 Use canonical URL to key redirect map
  crates/uv-resolver/src/resolution.rs
  crates/uv-resolver/src/resolver/index.rs
  crates/uv-resolver/src/resolver/mod.rs
Labels: bug

#2761 Populate the in-memory index when resolving lookahead URLs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-resolver/src/resolver/index.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/tests/pip_compile.rs
Labels: performance

#2765 Split `get_or_build_wheel_metadata` into distinct methods
  crates/distribution-types/src/lib.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/git.rs
Labels: internal

#2766 Use distribution database and index for all pre-resolution phases
  crates/distribution-types/src/buildable.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/source_tree.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#2768 Use `user_display` for source tree error
  crates/uv-requirements/src/source_tree.rs
Labels: internal

#2780 Resolve non-determistic behavior in preferences due to site-packages ordering
  crates/uv-installer/src/site_packages.rs
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/preferences.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#2781 Detect Fish via `FISH_VERSION`
  crates/uv/src/shell.rs
Labels: bug

#2783 Bump `cargo-dist` to 0.13.0-prerelease.3
  .github/workflows/release.yml
  Cargo.toml
Labels: release

#2785 Bump version to 0.1.28
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: release

#2786 Use `cargo update -p uv` for release instead of `cargo check`
  scripts/release/bump.sh
Labels: release

#2788 Move scenario sync script to top-level scripts
  crates/uv/tests/pip_compile_scenarios.rs
  crates/uv/tests/pip_install_scenarios.rs
  scripts/scenarios/generate.py
  scripts/scenarios/templates/compile.mustache
  scripts/scenarios/templates/install.mustache
  scripts/sync_scenarios.sh
Labels: internal

#2769 Allow conflicting Git URLs that refer to the same commit SHA
  crates/cache-key/src/canonical_url.rs
  crates/uv-distribution/src/git.rs
  crates/uv-distribution/src/lib.rs
  crates/uv-git/src/lib.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/resolver/urls.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_sync.rs
Labels: enhancement

#2789 Preserve `.git` suffixes and casing in Git dependencies
  crates/cache-key/src/canonical_url.rs
  crates/distribution-types/src/direct_url.rs
  crates/uv-distribution/src/git.rs
  crates/uv-git/src/git.rs
  crates/uv-git/src/lib.rs
  crates/uv-git/src/source.rs
  crates/uv/tests/pip_sync.rs
Labels: bug

#2707 fixed uv can't create .venv for cpython-x86 on Windows
  .github/workflows/ci.yml
  crates/uv-interpreter/python/get_interpreter_info.py
Labels: bug

#2790 Fixups to `release.sh` and `sync_scenarios.sh`
  scripts/release.sh
  scripts/sync_scenarios.sh
Labels: internal

#2791 Fix references to "WerkZeug" in "anyio" tests
  crates/uv/tests/pip_compile.rs
Labels: testing

#2793 Remove unused `download_and_extract_archive` method
  crates/uv-distribution/src/lib.rs
  crates/uv-distribution/src/source/mod.rs
Labels: internal

#2792 Remove redirects from the resolver
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/git.rs
  crates/uv-distribution/src/lib.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/source_tree.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv-resolver/src/redirect.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv-resolver/src/resolver/index.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
Labels: internal

#2782 Simplify sorting of site package entries
  crates/uv-installer/src/site_packages.rs
Labels: internal

#2800 Fix windows lock race: Lock exclusive after all try lock errors
  crates/uv-fs/src/lib.rs
Labels: bug

#2811 Avoid unused extras check in `pip install` for source trees
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#2816 Allow no-op `--no-compile` flag on CLI
  crates/uv/src/main.rs
Labels: compatibility

#2815 Allow package lookups across multiple indexes via explicit opt-in
  Cargo.lock
  PIP_COMPATIBILITY.md
  README.md
  crates/uv-client/Cargo.toml
  crates/uv-client/src/registry_client.rs
  crates/uv-dev/src/resolve_many.rs
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv-types/Cargo.toml
  crates/uv-types/src/build_options.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/logging.rs
  crates/uv/src/main.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/pip_compile.rs
Labels: enhancement, compatibility

#2795 Respect Git tags and branches that look like short commits
  crates/uv-git/src/git.rs
  crates/uv-git/src/lib.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#2818 Document that uv is safe to run concurrently
  README.md
Labels: documentation

#2820 Deduplicate editables during install commands
  crates/distribution-types/src/editable.rs
  crates/uv-installer/src/downloader.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#2825 Bump version to v0.1.29
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: release

#2826 Respect `--no-build` and `--no-binary` in `--find-links`
  crates/uv-client/src/flat_index.rs
  crates/uv-dev/src/resolve_cli.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/src/commands/venv.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_sync.rs
  scripts/links/maturin-1.4.0-py3-none-any.whl
  scripts/links/maturin-2.0.0-py3-none-linux_x86_64.whl
  scripts/links/simple_launcher-0.1.0-py3-none-any.whl
  scripts/links/tqdm-1000.0.0-py3-none-any.whl
  scripts/links/tqdm-4.66.1-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.musllinux_1_1_x86_64.whl
  scripts/links/tqdm-999.0.0.tar.gz
Labels: bug

#2829 Show resolution diagnostics after `pip install`
  crates/uv/src/commands/pip_install.rs
  crates/uv/tests/pip_install_scenarios.rs
Labels: enhancement

#2832 Refactor candidate selector for batch prefetching
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/version_map.rs
Labels: internal

#2836 Fix a typo in source_tree.rs
  crates/uv-requirements/src/source_tree.rs
Labels: internal

#2837 Add a test for `--offline` direct URLs
  crates/uv/tests/pip_compile.rs
Labels: testing

#2839 Add backtracking tests for distribution incompatibilities
  crates/uv/tests/pip_compile.rs
  scripts/links/validation-1.0.0-py3-none-any.whl
  scripts/links/validation-2.0.0-py3-none-any.whl
  scripts/links/validation-3.0.0-py3-none-any.whl
Labels: testing

#2838 Update `fetch-version-metadata` to only require the stdlib
  scripts/bootstrap/fetch-version-metadata.py
Labels: internal

#2834 Backtrack on distributions with invalid metadata
  Cargo.lock
  crates/uv-client/src/error.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-client/src/remote_metadata.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/source_tree.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv-resolver/Cargo.toml
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv-resolver/src/resolver/index.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_sync.rs
Labels: bug

#2848 Use `miette` when printing `pip sync` resolution failures
  crates/uv/src/commands/pip_sync.rs
  crates/uv/tests/pip_sync.rs
Labels: error messages

#2849 Remove additional 'because'
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/pip_compile.rs
  scripts/packages/dependent_editables/second_editable/.gitignore
Labels: error messages

#2854 Turn off text wrapping in non-scenario fixtures
  crates/uv/tests/cache_prune.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/pip_check.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_freeze.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_list.rs
  crates/uv/tests/pip_show.rs
  crates/uv/tests/pip_sync.rs
  crates/uv/tests/pip_uninstall.rs
  crates/uv/tests/venv.rs
Labels: testing

#2856 Only ignore `bin` directory at repo root
  .gitignore
Labels: internal

#2855 Include LICENSE files in source distribution
  pyproject.toml
Labels: bug

#2857 DRY up request builer in wheel download
  crates/uv-distribution/src/distribution_database.rs
Labels: internal

#2858 Sort and expand target triples in Cargo.toml
  Cargo.toml
Labels: internal

#2859 PIP_COMPATIBILITY.md: typo fixes
  PIP_COMPATIBILITY.md
Labels: documentation

#2860 Fix base client builder docstring reference
  crates/uv-client/src/base_client.rs
Labels: internal

#2875 Expand documentation in `scripts/bench/__main__.py`
  scripts/bench/__main__.py
Labels: documentation

#2876 Expand some documentation around identifier traits
  crates/distribution-types/src/id.rs
  crates/distribution-types/src/traits.rs
Labels: documentation

#2452 Speed up cold cache urllib3/boto3/botocore with batched prefetching
  crates/distribution-types/src/prioritized_distribution.rs
  crates/distribution-types/src/resolved.rs
  crates/uv-resolver/src/resolver/batch_prefetch.rs
  crates/uv-resolver/src/resolver/mod.rs
Labels: performance

#2901 DRY up local wheel path in distribution database
  crates/uv-distribution/src/distribution_database.rs
  scripts/requirements/all-kinds.in
Labels: internal

#2902 DRY up HTTP request builder in source database
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/source/mod.rs
Labels: internal

#2903 Suppress MultipleHandlers from ctrlc in confirm
  crates/uv-requirements/src/confirm.rs
Labels: bug

#2905 Always return unzipped wheels from the distribution database
  crates/uv-distribution/src/distribution_database.rs
Labels: internal

#2906 Remove unused local wheel types
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/download.rs
  crates/uv-distribution/src/lib.rs
  crates/uv-distribution/src/unzip.rs
  crates/uv-installer/src/downloader.rs
Labels: internal

#2907 Respect cached local `--find-links` in install plan
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/index/registry_wheel_index.rs
  crates/uv/tests/pip_sync.rs
Labels: bug

#2909 Add a layer of indirection to the local path-based wheel cache
  crates/uv-cache/src/lib.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv/tests/pip_sync.rs
Labels: internal

#2861 Add extract support for zstd
  Cargo.lock
  crates/uv-extract/Cargo.toml
  crates/uv-extract/src/seek.rs
  crates/uv-extract/src/stream.rs
Labels: internal

#2904 Use scheme parsing to determine absolute vs. relative URLs
  crates/distribution-types/src/file.rs
  crates/pypi-types/src/base_url.rs
Labels: bug

#2889 Group `pyo3` dependency updates
  .github/renovate.json5
  Cargo.lock
Labels: internal

#2914 Restore lockfile
  Cargo.lock
Labels: internal

#2916 Disable CentOS system check
  .github/workflows/ci.yml
Labels: internal

#2919 Reduce visibility of some methods in source database
  crates/uv-distribution/src/source/mod.rs
Labels: internal

#2920 Rebrand `Manifest` as `Revision` in wheel database
  crates/uv-distribution/src/index/built_wheel_index.rs
  crates/uv-distribution/src/index/registry_wheel_index.rs
  crates/uv-distribution/src/source/built_wheel_metadata.rs
  crates/uv-distribution/src/source/manifest.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-distribution/src/source/revision.rs
Labels: internal

#2921 DRY up source distribution fetching between wheel and metadata routes
  crates/uv-distribution/src/source/mod.rs
Labels: internal

#2922 Separate local archive vs. local source tree paths in source database
  crates/uv-distribution/src/source/mod.rs
  crates/uv/tests/pip_sync.rs
Labels: performance, internal

#2932 Skip scenario tests on Windows
  crates/uv/tests/pip_compile_scenarios.rs
  crates/uv/tests/pip_install_scenarios.rs
  scripts/scenarios/templates/compile.mustache
  scripts/scenarios/templates/install.mustache
Labels: internal, testing

#2930 Add filtering of patch Python versions unless explicitly requested
  crates/uv/tests/common/mod.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_compile_scenarios.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_install_scenarios.rs
  crates/uv/tests/pip_sync.rs
  crates/uv/tests/venv.rs
Labels: internal, testing

#2934 Bump version to v0.1.30
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: release

#2918 Improve operating system and architecture types in `uv-toolchain`
  Cargo.lock
  crates/uv-dev/src/fetch_python.rs
  crates/uv-toolchain/Cargo.toml
  crates/uv-toolchain/fetch-version-metadata.py
  crates/uv-toolchain/python-version-metadata.json
  crates/uv-toolchain/src/downloads.rs
  crates/uv-toolchain/src/find.rs
  crates/uv-toolchain/src/lib.rs
  crates/uv-toolchain/src/python_versions.inc
Labels: internal

#2925 Replace PyPI-internal Hashes representation with flat vector
  crates/distribution-types/src/file.rs
  crates/distribution-types/src/lib.rs
  crates/distribution-types/src/prioritized_distribution.rs
  crates/pypi-types/src/simple_json.rs
  crates/uv-cache/src/lib.rs
  crates/uv-client/src/flat_index.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-resolver/src/preferences.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv-resolver/src/version_map.rs
Labels: internal

#2939 Store common fields on `BuiltWheelIndex` struct
  crates/uv-distribution/src/index/built_wheel_index.rs
  crates/uv-distribution/src/index/registry_wheel_index.rs
  crates/uv-installer/src/plan.rs
Labels: internal

#2943 Ignore direct URL distributions in prefetcher
  crates/uv-resolver/src/resolver/batch_prefetch.rs
Labels: bug

#2942 Add ecosystem test for Prefect
  .github/workflows/ci.yml
Labels: testing

#2850 Surface invalid metadata as hints in error reports
  Cargo.lock
  crates/uv-resolver/Cargo.toml
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/pip_compile.rs
  crates/uv/tests/pip_sync.rs
Labels: error messages

#2954 Enforce and backtrack on invalid versions in source metadata
  crates/distribution-types/src/buildable.rs
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
Labels: enhancement

#2959 Remove rust 1.75 workaround
  crates/uv-dispatch/src/lib.rs
Labels: internal

#2931 Add discovery of Python versions installed with `uv-toolchain`
  Cargo.lock
  crates/uv-interpreter/Cargo.toml
  crates/uv-interpreter/src/find_python.rs
  crates/uv-interpreter/src/interpreter.rs
  crates/uv-interpreter/src/lib.rs
  crates/uv-toolchain/Cargo.toml
  crates/uv-toolchain/src/downloads.rs
  crates/uv-toolchain/src/find.rs
  crates/uv-toolchain/src/lib.rs
  crates/uv-toolchain/src/python_version.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/main.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/pip_compile_scenarios.rs
  crates/uv/tests/pip_sync.rs
  crates/uv/tests/venv.rs
  scripts/scenarios/templates/compile.mustache
Labels: internal

#2940 Add `python-patch` feature to isolate tests that require Python patch versions to match our suite
  crates/uv/Cargo.toml
  crates/uv/tests/pip_compile_scenarios.rs
  crates/uv/tests/pip_install_scenarios.rs
  crates/uv/tests/venv.rs
  scripts/scenarios/generate.py
  scripts/scenarios/templates/compile.mustache
  scripts/scenarios/templates/install.mustache
Labels: testing

#2961 Strip query string when parsing filename from HTML index
  crates/uv-client/src/html.rs
Labels: bug

#2966 Update hashes without `--upgrade` if not present
  crates/uv-resolver/src/resolution.rs
  crates/uv/tests/pip_compile.rs
Labels: bug

#2817 Upgrade `reqwest` to v0.12.3
  Cargo.lock
  Cargo.toml
  crates/uv-auth/Cargo.toml
  crates/uv-auth/src/middleware.rs
  crates/uv-client/Cargo.toml
  crates/uv-client/src/base_client.rs
  crates/uv-client/src/lib.rs
  crates/uv-client/src/middleware.rs
  crates/uv-client/src/tls.rs
  crates/uv-client/tests/netrc_auth.rs
  crates/uv-client/tests/user_agent_version.rs
  crates/uv/Cargo.toml
Labels: internal

#2971 Add ecosystem test for flask
  .github/workflows/ci.yml
Labels: testing

#2824 Add a `--require-hashes` command-line setting
  crates/uv-resolver/src/options.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/src/main.rs
Labels: enhancement, no-build

#2974 Remove unused `task-local-extensions` dependency
  Cargo.lock
  Cargo.toml
  crates/uv-client/Cargo.toml
  crates/uv-configuration/Cargo.toml
  crates/uv-dev/Cargo.toml
Labels: internal

#2975 Remove unused `--output-file` from `pip install`
  crates/uv/src/main.rs
Labels: bug

#2945 Add hash-checking support to `install` and `sync`
  Cargo.lock
  Cargo.toml
  PIP_COMPATIBILITY.md
  crates/distribution-types/src/cached.rs
  crates/distribution-types/src/hashed.rs
  crates/distribution-types/src/lib.rs
  crates/distribution-types/src/prioritized_distribution.rs
  crates/pep508-rs/src/lib.rs
  crates/uv-cache/src/lib.rs
  crates/uv-client/Cargo.toml
  crates/uv-client/src/cached_client.rs
  crates/uv-client/src/flat_index.rs
  crates/uv-dev/src/resolve_cli.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/Cargo.toml
  crates/uv-distribution/src/archive.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/download.rs
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/index/built_wheel_index.rs
  crates/uv-distribution/src/index/cached_wheel.rs
  crates/uv-distribution/src/index/registry_wheel_index.rs
  crates/uv-distribution/src/lib.rs
  crates/uv-distribution/src/source/built_wheel_metadata.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-distribution/src/source/revision.rs
  crates/uv-extract/Cargo.toml
  crates/uv-extract/src/hash.rs
  crates/uv-extract/src/lib.rs
  crates/uv-extract/src/stream.rs
  crates/uv-installer/Cargo.toml
  crates/uv-installer/src/downloader.rs
  crates/uv-installer/src/plan.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/source_tree.rs
  crates/uv-requirements/src/specification.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/flat_index.rs
  crates/uv-resolver/src/hash_checking_mode.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/options.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv-resolver/tests/resolver.rs
  crates/uv-types/Cargo.toml
  crates/uv-types/src/hashes.rs
  crates/uv-types/src/lib.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/src/commands/venv.rs
  crates/uv/tests/cache_prune.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_sync.rs
Labels: enhancement

#2949 Fall back to distributions without hashes in resolver
  crates/distribution-types/src/prioritized_distribution.rs
  crates/uv-resolver/src/flat_index.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_sync.rs
Labels: enhancement

#2951 Return computed hashes from metadata requests
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/lib.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/source_tree.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
Labels: internal

#2952 Add support for URL requirements in `--generate-hashes`
  crates/distribution-types/src/cached.rs
  crates/distribution-types/src/hash.rs
  crates/distribution-types/src/hashed.rs
  crates/distribution-types/src/lib.rs
  crates/uv-dev/src/resolve_cli.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/index/built_wheel_index.rs
  crates/uv-distribution/src/index/registry_wheel_index.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-installer/src/downloader.rs
  crates/uv-installer/src/plan.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/source_tree.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv-resolver/src/flat_index.rs
  crates/uv-resolver/src/hash_checking_mode.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/options.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv-resolver/tests/resolver.rs
  crates/uv-types/src/hash.rs
  crates/uv-types/src/lib.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/src/commands/venv.rs
  crates/uv/tests/pip_compile.rs
Labels: enhancement

#2977 Create dedicated abstractions for `.rev` and `.http` pointers
  crates/uv-cache/src/lib.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/index/built_wheel_index.rs
  crates/uv-distribution/src/index/cached_wheel.rs
  crates/uv-distribution/src/index/registry_wheel_index.rs
  crates/uv-distribution/src/lib.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-installer/src/plan.rs
Labels: internal

#2981 Remove unnecessary `touch` calls from tests
  crates/uv/tests/pip_check.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_list.rs
  crates/uv/tests/pip_show.rs
  crates/uv/tests/pip_sync.rs
  crates/uv/tests/pip_uninstall.rs
Labels: internal, testing

#2985 Store IDs rather than paths in the cache
  crates/uv-cache/src/archive.rs
  crates/uv-cache/src/lib.rs
  crates/uv-distribution/src/archive.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/index/cached_wheel.rs
  crates/uv-distribution/src/index/registry_wheel_index.rs
  crates/uv-distribution/src/source/revision.rs
  crates/uv-installer/src/plan.rs
Labels: internal

#2986 Add `--find-links` source distributions to the registry cache
  crates/distribution-types/src/index_url.rs
  crates/uv-client/src/flat_index.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution/src/index/cached_wheel.rs
  crates/uv-distribution/src/index/registry_wheel_index.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv/tests/pip_sync.rs
Labels: bug

#2987 Remove editable field from `RequirementEntry`
  crates/requirements-txt/src/lib.rs
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-basic.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-constraints-a.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-constraints-b.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-editable.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-for-poetry.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-include-a.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-include-b.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-poetry-with-hashes.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-small.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__line-endings-whitespace.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-basic.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-constraints-a.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-constraints-b.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-for-poetry.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-include-a.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-include-b.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-poetry-with-hashes.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-small.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-unix-bare-url.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-whitespace.txt.snap
  crates/requirements-txt/src/snapshots/requirements_txt__test__parse-windows-bare-url.txt.snap
  crates/uv-requirements/src/upgrade.rs
Labels: internal

#2970 Bump packse to 0.3.14
  crates/uv/tests/common/mod.rs
  crates/uv/tests/pip_compile_scenarios.rs
  crates/uv/tests/pip_install_scenarios.rs
  scripts/scenarios/requirements.txt
Labels: internal

#2969 Unify packse find links urls
  crates/uv-git/src/source.rs
  crates/uv/tests/common/mod.rs
  crates/uv/tests/pip_compile_scenarios.rs
  crates/uv/tests/pip_install.rs
  crates/uv/tests/pip_install_scenarios.rs
  scripts/scenarios/generate.py
  scripts/scenarios/requirements.txt
Labels: internal

#2923 feat: convert linehaul tests to use snapshots
  Cargo.lock
  crates/uv-client/Cargo.toml
  crates/uv-client/tests/user_agent_version.rs
Labels: internal

#2989 Silence lint false positive
  crates/uv-configuration/src/config_settings.rs
Labels: internal

#2992 Add a few more `--generate-hashes` cases to compile tests
  crates/uv/tests/pip_compile.rs
Labels: testing

#2993 Support unnamed requirements in `--require-hashes`
  Cargo.lock
  crates/distribution-types/src/id.rs
  crates/distribution-types/src/traits.rs
  crates/uv-build/src/lib.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/src/index/built_wheel_index.rs
  crates/uv-distribution/src/index/registry_wheel_index.rs
  crates/uv-installer/src/downloader.rs
  crates/uv-installer/src/plan.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/source_tree.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv-resolver/src/flat_index.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv-resolver/src/resolver/batch_prefetch.rs
  crates/uv-resolver/src/resolver/index.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv-types/Cargo.toml
  crates/uv-types/src/hash.rs
  crates/uv-types/src/traits.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/tests/pip_sync.rs
Labels: enhancement

#2994 Add additional coverage for `--require-hashes` in `install`
  crates/uv/tests/pip_install.rs
Labels: testing

#2995 Add `UV_BREAK_SYSTEM_PACKAGES` environment variable
  README.md
  crates/uv/src/main.rs
Labels: compatibility, configuration

#2996 Remove outdated comment on `IndexLocations`
  crates/distribution-types/src/index_url.rs
Labels: documentation

#2997 Make hash-checking failure mode stricter and safer
  crates/uv-distribution/src/error.rs
  crates/uv-types/src/hash.rs
Labels: error messages

#2999 Allow unnamed requirements for overrides
  crates/requirements-txt/src/lib.rs
  crates/uv-installer/src/site_packages.rs
  crates/uv-requirements/src/specification.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv-types/src/hash.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/src/commands/pip_uninstall.rs
  crates/uv/tests/pip_compile.rs
Labels: enhancement

#2998 Remove unnecessary hashing from IDs
  crates/distribution-types/src/id.rs
  crates/distribution-types/src/lib.rs
Labels: internal

#3003 Replace `unwrap` with `?` in hash generation
  crates/pypi-types/src/simple_json.rs
  crates/uv-types/src/hash.rs
  crates/uv/tests/pip_sync.rs
Labels: internal

#3005 ci: re-enable centos compatible testing
  .github/workflows/ci.yml
Labels: testing

#2805 Support freethreading python
  crates/platform-tags/src/tags.rs
  crates/uv-cache/Cargo.toml
  crates/uv-cache/src/lib.rs
  crates/uv-interpreter/Cargo.toml
  crates/uv-interpreter/python/get_interpreter_info.py
  crates/uv-interpreter/src/interpreter.rs
  crates/uv-resolver/tests/resolver.rs
  crates/uv/src/commands/pip_compile.rs
Labels: enhancement

#3008 Split Clap arguments into separate module
  crates/uv/src/cli.rs
  crates/uv/src/main.rs
Labels: internal

#3015 Log hardlink failures
  crates/install-wheel-rs/src/linker.rs
Labels: enhancement

#3013 Avoid calling `normalize_path` with relative paths that extend beyond the current directory
  Cargo.lock
  Cargo.toml
  crates/pep508-rs/src/verbatim_url.rs
  crates/uv-fs/Cargo.toml
  crates/uv-fs/src/path.rs
  crates/uv-interpreter/src/find_python.rs
  crates/uv-interpreter/src/interpreter.rs
  req.txt
Labels: bug

#3001 Remove some Clap-level conflicts in argument groups
  crates/uv/src/cli.rs
Labels: bug, cli

#3018 Allow comments after all requirements.txt entries
  crates/requirements-txt/src/lib.rs
Labels: bug

#3002 Deduplicate symbolic links between `purelib` and `platlib`
  .github/workflows/ci.yml
  crates/uv-interpreter/src/python_environment.rs
  scripts/check_system_python.py
Labels: bug

#3020 Remove accidental file
  req.txt
Labels: internal

#3010 Avoid cache invalidation on credentials renewal
  crates/cache-key/src/canonical_url.rs
  crates/uv/tests/pip_install.rs
Labels: bug

#3032 Force color for build error messages
  crates/uv-build/src/lib.rs
Labels: error messages

#3038 Minor improvements to renovate config
  .github/renovate.json5
Labels: internal

#3039 Bump version to 0.1.32
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: no-build, release

#3041 Move `ExcludeNewer` into its own type
  crates/uv-dev/src/resolve_cli.rs
  crates/uv-resolver/src/exclude_newer.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/options.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv-resolver/tests/resolver.rs
  crates/uv/src/cli.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/venv.rs
  crates/uv/tests/pip_compile.rs
Labels: internal

#3042 Move global CLI flags into separate struct
  crates/uv/src/cli.rs
  crates/uv/src/main.rs
Labels: internal

#3043 Make the junction crate dependency Windows-only
  crates/uv-fs/Cargo.toml
Labels: internal

#3044 Use the larger runner for Windows clippy runs
  .github/workflows/ci.yml
Labels: internal

#3056 Show package name in no version for direct dependency error
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv/tests/pip_compile.rs
Labels: error messages

#3058 Enable auto-wrapping of `--help` output
  Cargo.lock
  crates/uv-dev/Cargo.toml
  crates/uv/Cargo.toml
Labels: cli

#3055 Add compatibility arguments for pip list
  crates/uv/src/cli.rs
  crates/uv/src/compat/mod.rs
  crates/uv/src/main.rs
Labels: compatibility

#2976 Rewrite `uv-auth`
  Cargo.lock
  crates/uv-auth/Cargo.toml
  crates/uv-auth/src/cache.rs
  crates/uv-auth/src/credentials.rs
  crates/uv-auth/src/keyring.rs
  crates/uv-auth/src/lib.rs
  crates/uv-auth/src/middleware.rs
  crates/uv-auth/src/netloc.rs
  crates/uv-auth/src/store.rs
  crates/uv-client/src/base_client.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-configuration/Cargo.toml
  crates/uv-configuration/src/authentication.rs
  crates/uv-configuration/src/lib.rs
  crates/uv/Cargo.toml
  crates/uv/src/cli.rs
  crates/uv/src/commands/pip_compile.rs
  crates/uv/src/commands/pip_install.rs
  crates/uv/src/commands/pip_sync.rs
  crates/uv/src/commands/pip_uninstall.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/main.rs
Labels: breaking

#3007 Add `uv-workspace` crate with settings discovery and deserialization
  Cargo.lock
  Cargo.toml
  crates/install-wheel-rs/src/linker.rs
  crates/uv-auth/Cargo.toml
  crates/uv-configuration/src/authentication.rs
  crates/uv-configuration/src/build_options.rs
  crates/uv-configuration/src/config_settings.rs
  crates/uv-configuration/src/name_specifiers.rs
  crates/uv-resolver/Cargo.toml
  crates/uv-resolver/src/exclude_newer.rs
  crates/uv-resolver/src/prerelease_mode.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv-resolver/src/resolution_mode.rs
  crates/uv-toolchain/Cargo.toml
  crates/uv-toolchain/src/python_version.rs
  crates/uv-workspace/Cargo.toml
  crates/uv-workspace/src/lib.rs
  crates/uv-workspace/src/settings.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/Cargo.toml
  crates/uv/src/main.rs
Labels: configuration

#3070 Skip HEAD requests for Pypicloud with Private S3
  crates/uv-client/src/error.rs
Labels: compatibility

#3072 Remove invalid `serde` reference in `uv-configuration`
  crates/uv-configuration/src/config_settings.rs
Labels: bug, internal

#3071 Add filter for install_registry_source_dist_cached on Gentoo
  crates/uv/tests/pip_sync.rs
Labels: testing

#3079 Flatten settings into a single struct
  crates/uv-workspace/src/settings.rs
Labels: configuration

#3080 Use kebab-case for serde enums
  crates/install-wheel-rs/src/linker.rs
  crates/uv-configuration/src/authentication.rs
  crates/uv-configuration/src/build_options.rs
  crates/uv-resolver/src/prerelease_mode.rs
  crates/uv-resolver/src/resolution.rs
  crates/uv-resolver/src/resolution_mode.rs
Labels: bug

#3083 Fix reference to `pyproject.toml` path in workspace discovery
  crates/uv-workspace/src/workspace.rs
Labels: bug

#3084 Add some tracing to workspace discovery
  Cargo.lock
  crates/uv-workspace/Cargo.toml
  crates/uv-workspace/src/workspace.rs
Labels: internal

#3085 Avoid `#[clap]` macro
  crates/uv/src/cli.rs
Labels: internal

#3090 Log versions tried from batch prefetch
  crates/uv-resolver/src/resolver/batch_prefetch.rs
  crates/uv-resolver/src/resolver/mod.rs
Labels: performance, internal

#3092 Skip configuration loading while unused
  crates/uv/src/main.rs
Labels: internal

#3093 Un-hide `--require-hashes` CLI argument
  crates/uv/src/cli.rs
Labels: cli

#3087 Incorporate heuristics to improve package prioritization
  crates/uv-resolver/src/dependency_provider.rs
  crates/uv-resolver/src/pubgrub/priority.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/pip_install_scenarios.rs
Labels: performance

#3094 Bump version to 0.1.33
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  pyproject.toml
Labels: release

#3074 Add `uv run` command
  crates/uv/src/cli.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/run.rs
  crates/uv/src/main.rs
Labels: internal, cli

#3075 Create ephemeral virtual environments for `uv run`
  crates/uv-interpreter/src/python_environment.rs
  crates/uv/src/cli.rs
  crates/uv/src/commands/run.rs
  crates/uv/src/main.rs
Labels: internal, cli
