Repository astral-sh/uv, pull requests merged in 2024-11, with the labels that each got.

#8736 Include member groups when locking workspace
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#8740 Docs: fix env var name in providing credentials section
  docs/configuration/indexes.md
Labels: documentation

#8703 Run `cargo update`
  Cargo.lock
  Cargo.toml
  crates/uv-performance-flate2-backend/Cargo.lock
  crates/uv-performance-flate2-backend/Cargo.toml
  crates/uv-performance-memory-allocator/Cargo.lock
  crates/uv-performance-memory-allocator/Cargo.toml
Labels: internal

#8756 Fix `add httpx` example with real git branch
  docs/concepts/dependencies.md
Labels: documentation

#8739 Add support for `uv sync --all-packages`
  crates/uv-cli/src/lib.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/build.rs
  crates/uv/tests/it/sync.rs
  docs/reference/cli.md
Labels: enhancement

#8741 Add support for `uv run --all-packages`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/run.rs
  docs/reference/cli.md
Labels: enhancement

#8742 Add support for `uv export --all-packages`
  crates/uv-cli/src/lib.rs
  crates/uv-resolver/src/lock/requirements_txt.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/export.rs
  docs/reference/cli.md
Labels: enhancement

#8760 Enable `--all-packages --frozen` in `uv sync` and `uv export`
  Cargo.lock
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/requirements_txt.rs
  crates/uv-resolver/src/lock/target.rs
  crates/uv-resolver/src/lock/tree.rs
  crates/uv-workspace/Cargo.toml
  crates/uv-workspace/src/lib.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/tests/it/export.rs
  crates/uv/tests/it/sync.rs
Labels: enhancement

#8753 Show full error chain on tool upgrade failures
  crates/uv/src/commands/tool/upgrade.rs
  crates/uv/tests/it/tool_upgrade.rs
Labels: error messages

#8772 Fix indentation in `projects.md`
  docs/concepts/projects.md
Labels: documentation

#8493 Generate environment variables doc from code
  .prettierignore
  Cargo.lock
  crates/uv-dev/src/generate_all.rs
  crates/uv-dev/src/generate_cli_reference.rs
  crates/uv-dev/src/generate_env_vars_reference.rs
  crates/uv-dev/src/generate_env_vars_reference/tests.rs
  crates/uv-dev/src/generate_json_schema.rs
  crates/uv-dev/src/generate_options_reference.rs
  crates/uv-dev/src/main.rs
  crates/uv-macros/src/lib.rs
  crates/uv-static/Cargo.toml
  crates/uv-static/src/env_vars.rs
  docs/configuration/environment.md
Labels: documentation

#8776 Fix no_binary_only_binary test
  crates/uv/tests/it/pip_compile.rs
Labels: internal

#8777 docs: env var doc improvements
  crates/uv-dev/src/generate_env_vars_reference.rs
  crates/uv-static/src/env_vars.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/init.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
  docs/configuration/environment.md
Labels: documentation

#8768 Allow incompatible `requires-python` for source distributions with static metadata
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution-types/src/buildable.rs
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/resolver/availability.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv-types/src/traits.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_compile_scenarios.rs
Labels: bug

#8784 Retrying parsing in test_publish.py
  scripts/publish/test_publish.py
Labels: internal

#8785 Fix indentation level in test publish script
  scripts/publish/test_publish.py
Labels: internal

#8800 Add `From` for `FlatDistributions` struct
  crates/uv-resolver/src/flat_index.rs
Labels: enhancement

#8807 Extend BaseClient to accept extra middleware
  crates/uv-client/src/base_client.rs
  crates/uv-client/src/registry_client.rs
Labels: enhancement, rustlib

#8808 Allow managed downloads with `--python-preference system`
  crates/uv-python/src/discovery.rs
Labels: bug

#8816 Fix test case on `main`
  crates/uv/tests/it/lock.rs
Labels: internal

#8733 Improve interactions with existing Python executables during install
  Cargo.lock
  crates/uv-cli/src/lib.rs
  crates/uv-python/src/managed.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/python/install.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/help.rs
  crates/uv/tests/it/python_install.rs
  docs/reference/cli.md
Labels: preview

#8795 Update Packse snapshots
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/lock_scenarios.rs
  crates/uv/tests/it/pip_compile_scenarios.rs
  crates/uv/tests/it/pip_install_scenarios.rs
  scripts/scenarios/generate.py
  scripts/scenarios/requirements.in
  scripts/scenarios/requirements.txt
Labels: testing

#8803 Publish: Hint at `--skip-existing` -> `--check-url` transition
  crates/uv-cli/src/lib.rs
  crates/uv/src/lib.rs
  crates/uv/tests/it/publish.rs
Labels: enhancement, preview

#8820 Bump version to 0.4.30
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#8822 Update pip-and-uv strictness example
  docs/pip/compatibility.md
Labels: documentation

#8769 Enable support for arbitrary git transports
  crates/uv-pep508/src/verbatim_url.rs
Labels: enhancement

#8829 Warn on failure to query system configuration file
  crates/uv-settings/src/lib.rs
Labels: error messages, tracing

#8834 uv-pep440: DRY up VersionSmall implementation
  crates/uv-pep440/src/version.rs
Labels: rustlib

#8835 Show dedicated error for trailing ; on URL and path requirements
  crates/uv-pep508/src/lib.rs
  crates/uv-pep508/src/tests.rs
  crates/uv-pep508/src/unnamed.rs
  crates/uv/tests/it/pip_install.rs
Labels: error messages

#8837 Using `--build-backend` in `uv init` implies `--package`
  crates/uv/src/commands/project/init.rs
Labels: bug

#8836 Allow semicolons directly after direct URLs
  crates/uv-pep508/src/lib.rs
  crates/uv-pep508/src/tests.rs
  crates/uv-pep508/src/unnamed.rs
  crates/uv-requirements-txt/src/snapshots/uv_requirements_txt__test__parse-unix-editable.txt.snap
  crates/uv-requirements-txt/src/snapshots/uv_requirements_txt__test__parse-unix-hash.txt.snap
  crates/uv-requirements-txt/src/snapshots/uv_requirements_txt__test__parse-unix-semicolon.txt.snap
  crates/uv-requirements-txt/src/snapshots/uv_requirements_txt__test__parse-windows-editable.txt.snap
  crates/uv-requirements-txt/test-data/requirements-txt/editable.txt
  crates/uv-requirements-txt/test-data/requirements-txt/semicolon.txt
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/pip_sync.rs
Labels: compatibility

#8839 Respect fork markers in `--resolution-mode=lowest-direct`
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/resolution_mode.rs
  crates/uv-resolver/src/resolver/batch_prefetch.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/it/pip_compile.rs
Labels: bug

#8850 Revert "Using `--build-backend` in `uv init` implies `--package` (#8837)"
  crates/uv/src/commands/project/init.rs
Labels: internal

#8797 Implement PEP 440-compliant local version semantics
  crates/uv-pep440/src/lib.rs
  crates/uv-pep440/src/version.rs
  crates/uv-pep440/src/version/tests.rs
  crates/uv-pep440/src/version_ranges.rs
  crates/uv-pep440/src/version_specifier.rs
  crates/uv-pep440/src/version_specifier/tests.rs
  crates/uv-python/src/discovery.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/it/lock_scenarios.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_install_scenarios.rs
  crates/uv/tests/it/snapshots/it__ecosystem__transformers-lock-file.snap
  crates/uv/tests/it/snapshots/it__ecosystem__transformers-uv-lock-output.snap
  scripts/scenarios/generate.py
Labels: enhancement, compatibility

#8818 Remove all special-casing for local version identifiers
  crates/uv-requirements/src/lookahead.rs
  crates/uv-resolver/src/manifest.rs
  crates/uv-resolver/src/resolver/locals.rs
  crates/uv-resolver/src/resolver/locals/tests.rs
  crates/uv-resolver/src/resolver/mod.rs
  docs/pip/compatibility.md
Labels: internal

#8843 Incorporate `[max]` local version into `VersionSmall`
  crates/uv-cache/src/lib.rs
  crates/uv-pep440/src/version.rs
  crates/uv/tests/it/cache_clean.rs
  crates/uv/tests/it/cache_prune.rs
Labels: performance

#8844 Use a + for the visual max local
  crates/uv-pep440/src/version.rs
Labels: internal

#8852 Use cache in windows clippy job
  .github/workflows/ci.yml
Labels: internal

#8867 Respect dynamic version updates in `uv lock`
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#8859 Add `docs/configuration/environment.md` to code change list
  .github/workflows/ci.yml
Labels: testing

#8868 Use no reporter by default in `cache clean`
  crates/uv-cache/src/lib.rs
  crates/uv-cache/src/removal.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv/src/commands/cache_clean.rs
  crates/uv/src/commands/reporters.rs
Labels: internal

#8869 Add dedicated tests for the max local version sentinel
  crates/uv-pep440/src/version/tests.rs
Labels: testing

#8872 Add support for `pip list --outdated`
  Cargo.lock
  crates/uv-cli/src/compat.rs
  crates/uv-cli/src/lib.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/pip/list.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/pip_list.rs
  docs/reference/cli.md
Labels: enhancement, compatibility

#8873 Upgrade to cargo-dist v0.25.1
  .github/workflows/release.yml
  Cargo.toml
Labels: releases

#8874 Add installer variables to environment reference
  crates/uv-static/src/env_vars.rs
  docs/configuration/environment.md
Labels: documentation

#8886 Build basic source distributions
  Cargo.lock
  Cargo.toml
  crates/uv-build-backend/Cargo.toml
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/tests.rs
  crates/uv/src/commands/build_backend.rs
Labels: preview

#8894 Only report Python pins as updated if its the same file
  crates/uv/src/commands/python/pin.rs
  crates/uv/tests/it/python_find.rs
Labels: cli

#8890 Improve Python discovery source messages
  crates/uv-cli/src/lib.rs
  crates/uv-python/src/discovery.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/help.rs
  crates/uv/tests/it/python_find.rs
  crates/uv/tests/it/python_pin.rs
  crates/uv/tests/it/venv.rs
  docs/reference/cli.md
Labels: tracing

#8893 Add `uv tree --outdated`
  crates/uv-cli/src/lib.rs
  crates/uv-distribution-filename/src/lib.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/lock/map.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/tree.rs
  crates/uv/src/commands/pip/latest.rs
  crates/uv/src/commands/pip/list.rs
  crates/uv/src/commands/pip/mod.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/tree.rs
  docs/reference/cli.md
Labels: enhancement

#8900 Add project boundary note
  docs/concepts/python-versions.md
Labels: documentation

#8899 Bump version to 0.5.0
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/gitlab.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: no-build, releases

#8853 [UX] Split README's install code block into 3
  README.md
Labels: documentation

#8905 Build source distributions at top-level of cache
  crates/uv-build-frontend/src/lib.rs
  crates/uv-distribution/src/source/mod.rs
Labels: cache

#8907 Remove source distribution filename from cache
  crates/uv-distribution/src/source/mod.rs
Labels: bug, windows, cache

#8910 Add dedicated cache method for creating build directories
  crates/uv-build-frontend/src/lib.rs
  crates/uv-cache/src/lib.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/commands/project/run.rs
Labels: internal

#8914 Enable uv to replace and delete itself on Windows
  Cargo.lock
  Cargo.toml
  crates/uv-install-wheel/Cargo.toml
  crates/uv-install-wheel/src/uninstall.rs
Labels: bug, windows

#8937 Add uninstall note for previous versions
  docs/getting-started/installation.md
Labels: documentation

#8936 Remove some missed references to `~/.cargo/bin`
  crates/uv-static/src/env_vars.rs
  docs/configuration/environment.md
  docs/guides/integration/docker.md
Labels: documentation

#8938 Fix `prune_unzipped` test on `main`
  crates/uv/tests/it/cache_prune.rs
Labels: internal

#8939 Allow non-registry dependencies in `uv pip list --outdated`
  crates/uv/src/commands/pip/latest.rs
  crates/uv/tests/it/pip_list.rs
Labels: bug

#8942 Respect `--index-url` in `uv pip list`
  crates/uv-cli/src/lib.rs
  crates/uv-cli/src/options.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/pip_list.rs
  docs/reference/cli.md
Labels: bug

#8950 Wait longer for index updates in publish test
  scripts/publish/test_publish.py
Labels: internal

#8955 Compute superset of existing and required hashes when healing cache
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/source/mod.rs
Labels: bug, cache

#8946 Respect comma-separated extras in `--with`
  crates/uv-cli/src/comma.rs
  crates/uv-cli/src/comma/tests.rs
  crates/uv-cli/src/lib.rs
  crates/uv/src/settings.rs
Labels: bug

#8906 Move "from PyPI" install message to above the relevant code block
  README.md
Labels: documentation

#8960 Support multiple extras in universal pip compile output
  crates/uv-resolver/src/resolution/display.rs
  crates/uv-resolver/src/resolution/requirements_txt.rs
  crates/uv/tests/it/pip_compile.rs
Labels: bug

#8961 Prefer compatible to incompatible distributions when packages exist on multiple indexes
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv/tests/it/pip_compile.rs
Labels: bug, resolver

#8943 Update uv development status classifier to "Stable" on PyPI
  pyproject.toml
Labels: releases

#8968 Fix reference to `--resolution` in docs
  docs/concepts/resolution.md
Labels: documentation

#8971 Fix references to `--resolution-strategy` in error message output
  crates/uv-distribution-types/src/resolution.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
Labels: bug, error messages

#8975 Some minor copy-edits for the 0.5.0 introduction
  CHANGELOG.md
Labels: internal

#8980 Avoid creating `.venv in `uv add --frozen` and `uv add --no-sync`
  crates/uv/src/commands/project/add.rs
  crates/uv/tests/it/edit.rs
Labels: bug

#8987 Fix prune unzipped snapshot
  crates/uv/tests/it/cache_prune.rs
Labels: internal

#8951 Pin publish test to 3.12
  .github/workflows/ci.yml
  scripts/publish/test_publish.py
Labels: internal

#8992 Use `[N]` in lieu of exact prune counts
  crates/uv/tests/it/cache_prune.rs
Labels: testing

#8990 Allow default indexes to be marked as explicit
  crates/uv-distribution-types/src/index_url.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv/tests/it/lock.rs
  docs/configuration/indexes.md
Labels: bug

#8993 Remove some unused public methods
  crates/uv-distribution-types/src/resolution.rs
  crates/uv-distribution/src/error.rs
  crates/uv-resolver/src/resolution/graph.rs
Labels: internal

#8994 Consistent colon usage in build failure errors
  crates/uv-requirements/src/lib.rs
  crates/uv/tests/it/export.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/workspace.rs
Labels: error messages

#8972 docs(tools): mention how to use extras
  docs/guides/tools.md
Labels: documentation

#9022 Avoid retraversing filesystem when testing exact glob matches
  crates/uv-workspace/src/workspace.rs
Labels: performance

#9025 Add an error case for `--no-binary` sync failures
  crates/uv/tests/it/sync.rs
Labels: testing

#9024 Allow `--no-build` to validate lock
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#9038 Consistently box distributions in fetch and build errors
  Cargo.lock
  crates/uv-installer/Cargo.toml
  crates/uv-installer/src/preparer.rs
  crates/uv-requirements/src/extras.rs
  crates/uv-requirements/src/lib.rs
  crates/uv-requirements/src/lookahead.rs
Labels: internal

#9039 Rename `Fetch` to `Download` in build errors
  crates/uv-installer/src/preparer.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/src/commands/diagnostics.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
Labels: internal

#9040 Hide `--no-system` from `uv pip tree` CLI
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: cli

#8933 Handle sigterm calls, fixes #6724
  Cargo.lock
  Cargo.toml
  crates/uv/Cargo.toml
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/tool/run.rs
Labels: bug

#9041 Use rich diagnostic formatting for early build failures
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_install.rs
Labels: error messages

#9042 Rename `fetch_and_build` to `download_and_build`
  crates/uv/src/commands/diagnostics.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
Labels: internal

#9030 Revert `uv.lock` changes when `uv add` fails
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/it/edit.rs
Labels: bug

#9043 Use rich diagnostic formatting for install failures
  crates/uv-dispatch/src/lib.rs
  crates/uv-installer/src/lib.rs
  crates/uv-installer/src/preparer.rs
  crates/uv/src/commands/diagnostics.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/it/build.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/pip_sync.rs
  crates/uv/tests/it/sync.rs
Labels: error messages

#9058 Use crates.io reqwest-middleware
  Cargo.lock
  Cargo.toml
Labels: internal, rustlib

#9044 DRY up diagnostic reporting for resolution failures
  crates/uv/src/commands/diagnostics.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/it/export.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/run.rs
  crates/uv/tests/it/tool_install.rs
  crates/uv/tests/it/tool_run.rs
  crates/uv/tests/it/workspace.rs
Labels: internal

#9037 Make diagnostic methods dynamic on error
  crates/uv/src/commands/diagnostics.rs
Labels: internal

#9064 Fix `.env` file example in docs
  docs/configuration/files.md
Labels: documentation

#9065 Use `[[index]]` API in configuration example
  docs/configuration/files.md
Labels: documentation

#9075 Ignore virtual environments in parent directories when choosing Python version for new projects
  crates/uv/src/commands/project/init.rs
  crates/uv/tests/it/init.rs
Labels: bug

#8986 Publish: Ignore non-matching files
  crates/uv-publish/src/lib.rs
  crates/uv/tests/it/publish.rs
  scripts/publish/test_publish.py
Labels: bug

#9066 Prefer Python executable names that match the request over default names
  crates/uv-python/src/discovery.rs
  crates/uv-python/src/discovery/tests.rs
  crates/uv-python/src/implementation.rs
  crates/uv-python/src/tests.rs
  crates/uv/tests/it/python_pin.rs
Labels: bug

#8695 Make Python and PyPy install mirrors configurable in uv.toml
  crates/uv-cli/src/lib.rs
  crates/uv-python/src/downloads.rs
  crates/uv-python/src/installation.rs
  crates/uv-settings/src/settings.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/init.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/commands/tool/upgrade.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/help.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/show_settings.rs
  crates/uv/tests/it/sync.rs
  docs/reference/cli.md
  docs/reference/settings.md
  uv.schema.json
Labels: enhancement

#9089 Split after specifiers in `--with` requirements
  crates/uv-cli/src/comma.rs
  crates/uv-cli/src/comma/tests.rs
Labels: bug

#8630 Add wget instructions for systems without curl
  docs/getting-started/installation.md
Labels: documentation

#9097 Sort by name, then specifiers in `uv add`
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv/tests/it/edit.rs
Labels: bug

#9098 Defer reporting of build failures in resolver
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
Labels: bug

#9102 Add `version` to `ResolvedDist`
  crates/uv-distribution-types/src/prioritized_distribution.rs
  crates/uv-distribution-types/src/resolution.rs
  crates/uv-distribution-types/src/resolved.rs
  crates/uv-installer/src/plan.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/target.rs
  crates/uv-resolver/src/resolution/graph.rs
  crates/uv-resolver/src/resolution/mod.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/src/commands/project/sync.rs
Labels: internal

#9109 Avoid duplicating first-entry comments in `uv add`
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv/tests/it/edit.rs
Labels: bug

#9085 Minimal wheel settings
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/tests.rs
  crates/uv/src/commands/build_backend.rs
Labels: preview

#9103 Rename `ResolutionGraph` to `ResolverOutput`
  crates/uv-bench/benches/uv.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/resolution/display.rs
  crates/uv-resolver/src/resolution/mod.rs
  crates/uv-resolver/src/resolution/output.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
Labels: internal

#9118 Show link we failed on parsing index pages
  crates/uv-client/src/html.rs
  crates/uv-client/src/html/tests.rs
Labels: error messages

#9099 Show file extensions on available commands when not `.exe`
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/it/run.rs
Labels: bug

#9124 Support `copy_dir_all` in unit tests too
  crates/uv-fs/src/lib.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/pip_freeze.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/pip_sync.rs
  crates/uv/tests/it/pip_uninstall.rs
  crates/uv/tests/it/run.rs
  crates/uv/tests/it/tool_install.rs
  crates/uv/tests/it/tool_run.rs
Labels: internal

#9127 Remove end-of-line whitespace in snapshots
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/pip_freeze.rs
  crates/uv/tests/it/pip_install.rs
Labels: internal

#9091 Build backend: Add source tree -> source dist -> wheel tests
  Cargo.lock
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/tests.rs
  crates/uv-globfilter/src/glob_dir_filter.rs
  crates/uv/Cargo.toml
  crates/uv/tests/it/build_backend.rs
  scripts/packages/built-by-uv/.gitignore
  scripts/packages/built-by-uv/README.md
  scripts/packages/built-by-uv/data-dir/dont-include-me.txt
  scripts/packages/built-by-uv/pyproject.toml
  scripts/packages/built-by-uv/src/built_by_uv/__init__.py
  scripts/packages/built-by-uv/src/built_by_uv/arithmetic/__init__.py
  scripts/packages/built-by-uv/src/built_by_uv/arithmetic/circle.py
  scripts/packages/built-by-uv/src/built_by_uv/arithmetic/pi.txt
  scripts/packages/built-by-uv/test.sh
  scripts/packages/built-by-uv/tests/test_package.py
  scripts/packages/built-by-uv/uv.lock
  scripts/packages/uv_backend/.gitignore
  scripts/packages/uv_backend/README.md
  scripts/packages/uv_backend/pyproject.toml
  scripts/packages/uv_backend/src/uv_backend/__init__.py
Labels: preview

#9106 Refactor `Resolution` type to retain dependency graph
  Cargo.lock
  crates/uv-distribution-types/Cargo.toml
  crates/uv-distribution-types/src/resolution.rs
  crates/uv-resolver/src/lock/requirements_txt.rs
  crates/uv-resolver/src/lock/target.rs
  crates/uv-resolver/src/resolution/display.rs
  crates/uv-resolver/src/resolution/output.rs
  crates/uv-types/src/hash.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/project/sync.rs
Labels: internal

#9108 Show full derivation chain when encountering build failures
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution-types/src/derivation.rs
  crates/uv-distribution-types/src/file.rs
  crates/uv-distribution-types/src/lib.rs
  crates/uv-installer/src/preparer.rs
  crates/uv-requirements/src/extras.rs
  crates/uv-requirements/src/lib.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/resolver/derivation.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/src/commands/diagnostics.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/sync.rs
Labels: error messages

#9131 Misc. touch-ups to target-to-resolution routine
  crates/uv-resolver/src/lock/target.rs
Labels: internal

#9110 Add support for async unzipping with ZIP64 archives
  Cargo.lock
  Cargo.toml
Labels: bug

#9133 Bump version to 0.5.2
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#9136 Show derivation markers for resolutions with project name
  crates/uv-resolver/src/resolver/derivation.rs
  crates/uv/tests/it/pip_compile.rs
Labels: bug

#9094 Detect nested workspace inside the current workspace and members with identical names
  crates/uv-workspace/src/lib.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv-workspace/src/workspace/tests.rs
Labels: bug

#9055 Refactor shell quoting
  Cargo.lock
  Cargo.toml
  crates/uv-install-wheel/Cargo.toml
  crates/uv-install-wheel/src/wheel.rs
  crates/uv-shell/src/lib.rs
  crates/uv-shell/src/shlex.rs
  crates/uv/src/commands/venv.rs
Labels: enhancement

#8984 Allow apostrophe in venv name
  Cargo.lock
  crates/uv-virtualenv/Cargo.toml
  crates/uv-virtualenv/src/virtualenv.rs
  crates/uv/tests/it/venv.rs
Labels: bug

#9149 Build backend: Include readme and license files
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/metadata.rs
  crates/uv-build-backend/src/tests.rs
  crates/uv/tests/it/build_backend.rs
  scripts/packages/built-by-uv/LICENSE-APACHE
  scripts/packages/built-by-uv/LICENSE-MIT
  scripts/packages/built-by-uv/pyproject.toml
  scripts/packages/built-by-uv/third-party-licenses/PEP-401.txt
Labels: preview

#9139 Add `--index <name>=<url>` syntax to index documentation
  docs/configuration/indexes.md
Labels: documentation

#9112 Include version constraints in derivation chains
  Cargo.lock
  crates/uv-distribution-types/Cargo.toml
  crates/uv-distribution-types/src/derivation.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/resolver/derivation.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/diagnostics.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/sync.rs
Labels: error messages

#9113 Include extras and dependency groups in derivation chains
  crates/uv-distribution-types/src/derivation.rs
  crates/uv-resolver/src/resolver/derivation.rs
  crates/uv/src/commands/diagnostics.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/sync.rs
Labels: error messages

#9155 Include cyan for prefix on versions
  crates/uv/src/commands/diagnostics.rs
Labels: bug

#9095 Update styles to support collapsible nav
  docs/stylesheets/extra.css
Labels: internal

#9154 Use Depot runners instead of GitHub larger runners for Unix
  .github/workflows/ci.yml
Labels: internal

#9162 Support overrides and constraints in PEP 723 scripts
  crates/uv-requirements/src/specification.rs
  crates/uv-scripts/src/lib.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/lib.rs
  crates/uv/tests/it/run.rs
Labels: enhancement

#9173 Add a dedicated error for `include = "dev"` with `tool.uv.dev-dependencies`
  crates/uv-distribution/src/metadata/requires_dist.rs
  crates/uv-resolver/src/lock/target.rs
  crates/uv-workspace/src/dependency_groups.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/tests/it/lock.rs
Labels: error messages

#9172 Include trampolines in sdist on Windows
  pyproject.toml
Labels: windows, releases

#9169 Avoid showing disjoint marker error with `true`
  crates/uv-workspace/src/pyproject.rs
  crates/uv/tests/it/lock.rs
Labels: error messages

#9170 Turn `--verify-hashes` on by default
  crates/uv-cli/src/lib.rs
  crates/uv-configuration/src/hash.rs
  crates/uv-settings/src/settings.rs
  crates/uv-static/src/env_vars.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/build.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/show_settings.rs
  docs/configuration/environment.md
  docs/reference/cli.md
  docs/reference/settings.md
Labels: security

#9185 Sort distributions when computing hash
  crates/uv/src/commands/project/environment.rs
Labels: bug

#9186 Fix typo in environment variable name
  crates/uv-static/src/env_vars.rs
  crates/uv/tests/it/show_settings.rs
  docs/reference/cli.md
Labels: internal

#9198 Fix flaky failure in `verify_hashes_mismatch`
  crates/uv/tests/it/pip_install.rs
Labels: testing

#9184 Migrate to `zlib-rs`
  Cargo.lock
  crates/uv-performance-flate2-backend/Cargo.toml
Labels: internal

#9202 Enable `zlib-rs` on all platforms
  .github/workflows/build-binaries.yml
Labels: performance, releases

#9206 Better error message when `git` is not found
  crates/uv-git/src/git.rs
Labels: error messages

#6523 docs: Add PyTorch installation guide
  docs/guides/integration/pytorch.md
  mkdocs.template.yml
Labels: documentation

#9160 Allow conflicting extras in explicit index assignments
  crates/uv-distribution-types/src/resolution.rs
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-distribution/src/metadata/mod.rs
  crates/uv-distribution/src/metadata/requires_dist.rs
  crates/uv-pep508/src/marker/tree.rs
  crates/uv-pypi-types/src/requirement.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/resolver/indexes.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-workspace/src/dependency_groups.rs
  crates/uv-workspace/src/pyproject.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/sync.rs
  docs/concepts/dependencies.md
  uv.schema.json
Labels: enhancement

#9210 Add documentation for using uv with PyTorch
  docs/guides/index.md
  docs/guides/integration/index.md
  docs/guides/integration/pytorch.md
  mkdocs.template.yml
Labels: documentation

#9074 Update `uv tool install --force` to imply `--reinstall-package <name>`
  crates/uv-configuration/src/package_options.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/tests/it/tool_install.rs
Labels: cli

#9215 Only install the specified project with `--frozen --package` in legacy non-`[project]` workspaces
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#9213 Automatically retry body errors when processing response
  crates/uv-client/src/base_client.rs
  crates/uv-client/src/cached_client.rs
  crates/uv-client/src/flat_index.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-publish/src/lib.rs
  crates/uv-resolver/src/bare.rs
  crates/uv-resolver/src/lib.rs
Labels: bug

#9222 Typo
  crates/uv-cli/src/lib.rs
Labels: documentation

#9223 Update generate-all
  docs/reference/cli.md
Labels: documentation, internal

#9229 Bump version to v0.5.3
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#9238 Use existing index field in PEP 723 scripts
  Cargo.lock
  crates/uv-scripts/Cargo.toml
  crates/uv-scripts/src/lib.rs
  crates/uv/src/commands/project/run.rs
Labels: internal

#9237 Sort hashes in `uv export` output
  crates/uv-resolver/src/lock/requirements_txt.rs
  crates/uv/tests/it/export.rs
Labels: bug
