Repository astral-sh/uv, pull requests merged in 2025-09, with the labels that each got.

#15626 Add error trace to invalid package format
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/resolver/availability.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/it/pip_sync.rs
Labels: error messages

#15617 Add test case for status code retries
  crates/uv-client/src/base_client.rs
Labels: internal

#15641 Add test cases for URL matching with the native keyring
  crates/uv/tests/it/auth.rs
Labels: testing

#15645 Add zstandard support for wheels
  Cargo.lock
  Cargo.toml
  crates/uv-client/src/flat_index.rs
  crates/uv-distribution-types/src/file.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-extract/Cargo.toml
  crates/uv-extract/src/stream.rs
  crates/uv-pypi-types/src/simple_json.rs
  crates/uv-resolver/src/lock/export/pylock_toml.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_optional_missing.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_optional_present.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_required_present.snap
Labels: enhancement

#15648 Bump version to v0.8.15
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/concepts/build-backend.md
  docs/concepts/projects/init.md
  docs/concepts/projects/workspaces.md
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#15649 Make `uv auth dir` service-aware
  crates/uv-auth/src/pyx.rs
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/auth/dir.rs
  crates/uv/src/lib.rs
  docs/reference/cli.md
Labels: enhancement

#15687 Add test coverage of x86-64 Python from `setup-python` on arm64 macOS
  .github/workflows/ci.yml
Labels: testing

#15272 fix: refresh activation scripts from upstream virtualenv
  .github/workflows/ci.yml
  crates/uv-virtualenv/README.md
  crates/uv-virtualenv/src/activator/activate
  crates/uv-virtualenv/src/activator/activate.bat
  crates/uv-virtualenv/src/activator/activate.fish
  crates/uv-virtualenv/src/activator/activate.nu
  crates/uv-virtualenv/src/activator/deactivate.bat
  crates/uv-virtualenv/src/activator/pydoc.bat
Labels: bug

#15710 Don't trace logs all architectures
  crates/uv-platform/src/lib.rs
Labels: internal

#15708 Allow `editable = false` for workspace sources
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-workspace/src/lib.rs
  crates/uv-workspace/src/pyproject.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/lock_target.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/version.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/sync.rs
  uv.schema.json
Labels: enhancement

#15712 Allow `--editable` to override `editable = false` annotations
  crates/uv-cli/src/lib.rs
  crates/uv-configuration/src/editable.rs
  crates/uv-resolver/src/lock/export/pylock_toml.rs
  crates/uv-resolver/src/lock/export/requirements_txt.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/version.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/sync.rs
Labels: cli

#15706 Improve the CLI help for options that accept requirements files
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: documentation

#15738 Use workspace dependencies in uv-keyring
  Cargo.toml
  crates/uv-keyring/Cargo.toml
Labels: internal

#15744 Remove cmake from our Docker image build
  Dockerfile
Labels: internal

#15748 Show a dedicated error for venvs in source trees
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/metadata.rs
  crates/uv-build-backend/src/source_dist.rs
  crates/uv-build-backend/src/wheel.rs
  crates/uv/tests/it/build_backend.rs
Labels: enhancement, error messages, build-backend

#15759 Use token store credentials for `uv publish`
  crates/uv/src/commands/publish.rs
Labels: bug

#15735 Build backend error message style consistency
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/metadata.rs
  crates/uv-build-backend/src/source_dist.rs
  crates/uv-build-backend/src/wheel.rs
  crates/uv/tests/it/build.rs
  crates/uv/tests/it/build_backend.rs
Labels: error messages

#15761 Bump version to v0.8.16
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/concepts/build-backend.md
  docs/concepts/projects/init.md
  docs/concepts/projects/workspaces.md
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#15768 Improve error message for HTTP validation in auth services
  crates/uv-auth/src/service.rs
  crates/uv/tests/it/auth.rs
Labels: error messages

#15772 Do not search for a password for requests with a token attached already
  crates/uv-auth/src/cache.rs
  crates/uv-auth/src/credentials.rs
  crates/uv-auth/src/middleware.rs
Labels: bug

#15773 Avoid initiating login flow for invalid API keys
  crates/uv-auth/src/pyx.rs
  crates/uv/src/commands/auth/token.rs
Labels: bug

#15774 Respect `PYX_API_URL` when suggesting `uv auth login` on 401
  crates/uv-auth/src/middleware.rs
Labels: error messages

#15828 Log when the cache is disabled
  crates/uv/src/lib.rs
Labels: cli

#15827 Allow cached environment reuse with `@latest`
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/tool_run.rs
Labels: bug

#15831 Error when `pyproject.toml` target does not exist for dependency groups
  crates/uv-distribution/src/metadata/dependency_groups.rs
  crates/uv-distribution/src/metadata/mod.rs
  crates/uv/tests/it/pip_compile.rs
Labels: error messages

#15829 Improve BSD tag construction
  crates/uv-platform-tags/src/platform.rs
  crates/uv-platform-tags/src/tags.rs
Labels: bug

#15868 Remove windows-sys 0.48 by updating miow
  Cargo.lock
Labels: internal

#15872 Propagate preview flag to client for `native-auth` feature
  crates/uv-client/src/base_client.rs
  crates/uv/src/lib.rs
Labels: bug, preview

#15877 Add tests for realm-level authentication
  crates/uv/tests/it/auth.rs
Labels: testing

#15879 Store native credentials for realms with the https scheme stripped
  crates/uv-auth/src/keyring.rs
  crates/uv/tests/it/auth.rs
Labels: bug, preview

#15795 Add `--no-clear` to `uv venv` to disable removal prompts
  crates/uv-cli/src/lib.rs
  crates/uv-virtualenv/src/virtualenv.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/venv.rs
Labels: cli

#15881 fix misleading debug message in uv sync
  crates/uv-build-frontend/src/lib.rs
  crates/uv-tool/src/lib.rs
  crates/uv-virtualenv/src/lib.rs
  crates/uv-virtualenv/src/virtualenv.rs
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
Labels: tracing

#15679 Invert the logic for determining if a path is a base conda environment
  crates/uv-python/src/lib.rs
  crates/uv-python/src/virtualenv.rs
Labels: bug

#15898 Better warning for no direct build
  crates/uv-build-backend/src/metadata.rs
Labels: tracing

#15234 Fix `uv sync --no-sources` not switching from editable to registry installations
  crates/uv-dispatch/src/lib.rs
  crates/uv-installer/src/lib.rs
  crates/uv-installer/src/plan.rs
  crates/uv-installer/src/satisfies.rs
  crates/uv-installer/src/site_packages.rs
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#15911 Add PyG packages to torch backend
  crates/uv-torch/src/backend.rs
Labels: enhancement

#15681 Add handling for unnamed conda environments in base environment detection
  crates/uv-python/src/lib.rs
  crates/uv-python/src/virtualenv.rs
Labels: enhancement

#15888 Make `uv cache clean` parallel process safe
  crates/uv-cache/src/lib.rs
  crates/uv-cache/src/removal.rs
  crates/uv-fs/src/lib.rs
  crates/uv/src/commands/cache_clean.rs
  crates/uv/src/commands/cache_prune.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/lib.rs
  crates/uv/tests/it/cache_clean.rs
  crates/uv/tests/it/cache_prune.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#15962 Document pyodide support
  docs/concepts/python-versions.md
Labels: documentation

#15964 Tweak title for viewing version in project guide
  docs/guides/projects.md
Labels: documentation

#15961 Document support for free-threaded and debug Python versions
  crates/uv-cli/src/lib.rs
  crates/uv/tests/it/help.rs
  docs/concepts/python-versions.md
  docs/reference/cli.md
Labels: documentation

#15963 Add `package` level conflicts to the conflicting dependencies docs
  docs/concepts/resolution.md
Labels: documentation

#15985 Hide freethreaded+debug Python downloads in `uv python list`
  crates/uv/src/commands/python/list.rs
Labels: bug

#15990 Retain the cache lock and temporary caches during `uv run` and `uvx`
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/tool/run.rs
Labels: bug

#15993 Revert "Refresh lockfile when `--refresh` is provided (#15991)"
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/lib.rs
  crates/uv/tests/it/lock.rs
Labels: internal

#16045 Re-order lock validation checks by severity
  crates/uv/src/commands/project/lock.rs
Labels: bug

#16062 Group pubgrub/version-ranges updates
  .github/renovate.json5
Labels: internal

#16027 Windows arm64 and Linux RISC-V64 are Tier 2 supported
  docs/reference/policies/platforms.md
Labels: documentation

#16046 Add `UV_SKIP_WHEEL_FILENAME_CHECK` to allow installing invalid wheels
  Cargo.lock
  crates/uv-install-wheel/Cargo.toml
  crates/uv-install-wheel/src/install.rs
  crates/uv-install-wheel/src/lib.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-settings/src/lib.rs
  crates/uv-static/src/env_vars.rs
  crates/uv-static/src/lib.rs
  crates/uv/tests/it/pip_sync.rs
  crates/uv/tests/it/sync.rs
  docs/pip/compatibility.md
  docs/reference/environment.md
Labels: compatibility

#16047 Use a global flags instance for wheel check
  Cargo.lock
  Cargo.toml
  crates/uv-flags/Cargo.toml
  crates/uv-flags/src/lib.rs
  crates/uv-install-wheel/Cargo.toml
  crates/uv-install-wheel/src/install.rs
  crates/uv-resolver/Cargo.toml
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-settings/Cargo.toml
  crates/uv-settings/src/lib.rs
  crates/uv-static/src/lib.rs
  crates/uv/Cargo.toml
  crates/uv/src/lib.rs
Labels: internal
