Repository astral-sh/uv, pull requests merged in 2025-05, with the labels that each got.

#13227 Use base client pattern in more sites
  crates/uv-requirements/src/lib.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/pip/list.rs
  crates/uv/src/commands/pip/tree.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
Labels: internal

#13241 Update "Viewing the version" docs
  docs/getting-started/help.md
Labels: documentation

#13259 Update add_warn_index_url snapshot
  crates/uv/tests/it/edit.rs
Labels: internal

#13260 Check nested IO errors for retries
  crates/uv-client/src/base_client.rs
Labels: enhancement, network

#13265 Move static feature out of perf features
  .github/workflows/ci.yml
  crates/uv-bench/Cargo.toml
  crates/uv-dev/Cargo.toml
  crates/uv-distribution/Cargo.toml
  crates/uv-extract/Cargo.toml
  crates/uv/Cargo.toml
Labels: internal

#13281 Retry streaming downloads on broken pipe errors
  crates/uv-client/src/base_client.rs
  crates/uv-client/src/cached_client.rs
Labels: bug, network

#13283 Respect locked script preferences in `uv run --with`
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/it/run.rs
Labels: bug

#13285 Support more zip compression formats: bzip2, lzma, xz, zstd
  Cargo.toml
Labels: enhancement, compatibility

#9829 Add `--dry-run` support to `uv self update`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/self_update.rs
  crates/uv/src/lib.rs
  docs/reference/cli.md
Labels: enhancement

#13284 Treat already-installed base environment packages as preferences in `uv run --with`
  crates/uv-resolver/src/preferences.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/it/run.rs
Labels: bug

#13289 Accept `musllinux_1_0` as a valid platform tag
  crates/uv-platform-tags/src/tags.rs
Labels: compatibility

#12804 Build backend: Make preview default and add configuration docs
  crates/uv-configuration/src/project_build_backend.rs
  crates/uv/src/commands/project/init.rs
  crates/uv/tests/it/init.rs
  docs/concepts/projects/init.md
  docs/configuration/build-backend.md
  docs/configuration/index.md
  mkdocs.template.yml
  pyproject.toml
Labels: documentation, preview

#13287 Avoid re-creating virtual environment with `--no-sync`
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/commands/python/find.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/run.rs
Labels: error messages

#13303 Use `fs_err` for paths in symlinking errors
  clippy.toml
  crates/uv-cache/src/lib.rs
  crates/uv-fs/src/lib.rs
  crates/uv-install-wheel/src/linker.rs
  crates/uv-python/src/downloads.rs
  crates/uv-virtualenv/src/virtualenv.rs
  crates/uv/tests/it/build.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/python_find.rs
Labels: error messages

#13311 Move portable glob parsing to struct
  crates/uv-build-backend/src/metadata.rs
  crates/uv-build-backend/src/source_dist.rs
  crates/uv-build-backend/src/wheel.rs
  crates/uv-globfilter/src/glob_dir_filter.rs
  crates/uv-globfilter/src/lib.rs
  crates/uv-globfilter/src/main.rs
  crates/uv-globfilter/src/portable_glob.rs
Labels: internal

#13171 Reproducible uv build backend across operating systems
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/metadata.rs
  crates/uv-build-backend/src/source_dist.rs
  crates/uv-build-backend/src/wheel.rs
  crates/uv-globfilter/src/glob_dir_filter.rs
  crates/uv-globfilter/src/main.rs
  crates/uv/tests/it/build.rs
Labels: enhancement, windows, preview

#13264 Add `--show-with` to `uv tool list` to list packages included by `--with`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/tool/list.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/tool_install.rs
  crates/uv/tests/it/tool_list.rs
  docs/reference/cli.md
Labels: cli

#13326 Remove outdated description of index strategy
  docs/configuration/indexes.md
Labels: documentation

#12168 Improve error message when a virtual environment Python symlink is broken
  crates/uv-python/src/discovery.rs
  crates/uv-python/src/interpreter.rs
  crates/uv-python/src/lib.rs
  crates/uv-tool/src/lib.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/tests/it/pip_compile.rs
Labels: error messages

#13335 Avoid enumerating sources in errors for path Python requests
  crates/uv-python/src/discovery.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/python_find.rs
Labels: error messages

#13305 Suggest `uv self update` if required version is newer
  crates/uv-configuration/src/required_version.rs
  crates/uv/src/lib.rs
Labels: enhancement

#13340 Show 'Downgraded' when self update is used to install an older version
  crates/uv/src/commands/self_update.rs
Labels: cli

#13339 Fix display of HTTP responses in trace logs for retry of errors
  crates/uv-client/src/base_client.rs
Labels: tracing

#13348 Rename `--raw-sources` to `--raw`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/edit.rs
  docs/reference/cli.md
Labels: cli

#13379 Retain dot-separated wheel tags during cache prune
  Cargo.lock
  crates/uv-cache/Cargo.toml
  crates/uv-cache/src/lib.rs
Labels: bug, cache

#13382 Fix `.tgz` parsing to respect true extension
  crates/uv-distribution-filename/src/extension.rs
  crates/uv-distribution-filename/src/source_dist.rs
  crates/uv-extract/src/stream.rs
Labels: bug

#13384 Avoid erroring on `pylock.toml` dependency entries
  crates/uv-resolver/src/lock/export/pylock_toml.rs
  crates/uv/tests/it/pip_install.rs
Labels: bug

#13401 Fix ecosystem checks by pinning Git refs
  .github/workflows/ci.yml
Labels: internal

#13351 Add more context to errors in high level crates.
  crates/uv-install-wheel/Cargo.toml
  crates/uv-installer/src/site_packages.rs
  crates/uv-python/Cargo.toml
  crates/uv-requirements-txt/Cargo.toml
  crates/uv-requirements/src/sources.rs
  crates/uv-trampoline-builder/Cargo.toml
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/init.rs
  crates/uv/src/commands/run.rs
  crates/uv/src/commands/tool/run.rs
Labels: enhancement, error messages

#13406 Avoid panics for cannot-be-a-base URLs
  crates/uv-cache-key/src/canonical_url.rs
  crates/uv-python/src/downloads.rs
Labels: bug

#13366 Fix double self-dependency
  Cargo.lock
  Cargo.toml
  crates/uv/tests/it/pip_compile.rs
Labels: bug

#13421 Reject `pylock.toml` in `uv add -r`
  crates/uv/src/commands/project/add.rs
Labels: bug, error messages

#13423 Add comma after "i.e." in Conda environment error
  crates/uv-requirements/src/specification.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/pip_install.rs
Labels: error messages

#13422 Remove unused source tree variant
  crates/uv-requirements/src/sources.rs
  crates/uv-requirements/src/specification.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/project/add.rs
Labels: internal

#13426 Be more precise in unpinned packages warning
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
Labels: error messages

#13430 uv export docs: "export" instead of "install"
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: documentation

#13390 feat(docker): add 3.14 beta images to uv docker
  .github/workflows/build-docker.yml
  docs/guides/integration/docker.md
Labels: enhancement

#13460 Retain trailing comments after PEP 723 metadata block
  crates/uv-scripts/src/lib.rs
  crates/uv/tests/it/edit.rs
Labels: bug

#13266 ProgressReporter: align progress bars by largest name length
  crates/uv/src/commands/reporters.rs
Labels: cli

#13461 Remove extra newline
  crates/uv-python/src/interpreter.rs
Labels: error messages

#13463 Ensure cached realm credentials are applied if no password is found for index URL
  crates/uv-auth/src/middleware.rs
  crates/uv/tests/it/pip_install.rs
Labels: bug

#13451 Issue template: Please include the complete error message
  .github/ISSUE_TEMPLATE/1_bug_report.yaml
Labels: internal

#13462 Reinstall local packages in `uv add`
  crates/uv/src/lib.rs
  crates/uv/tests/it/edit.rs
Labels: enhancement

#13473 Bump version to 0.7.4
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/configuration/build-backend.md
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#13477 Mask `gen` as `r#gen` for the 2024 edition
  crates/uv-distribution-types/src/status_code_strategy.rs
Labels: internal

#13483 cli: adjust grammar in “script not supported” error
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/it/tool_run.rs
Labels: error messages

#13479 Apply some Edition 2024 fixes
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-python/src/discovery.rs
  crates/uv-python/src/downloads.rs
  crates/uv-python/src/managed.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/pubgrub/package.rs
  crates/uv-resolver/src/resolution/output.rs
  crates/uv-resolver/src/resolver/batch_prefetch.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/python/pin.rs
  crates/uv/src/commands/run.rs
  crates/uv/src/commands/tool/common.rs
  crates/uv/src/commands/tool/install.rs
Labels: internal

#13468 Build backend: Case sensitive module discovery
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/source_dist.rs
  crates/uv-build-backend/src/wheel.rs
  crates/uv-globfilter/src/portable_glob.rs
  crates/uv/tests/it/build_backend.rs
  docs/configuration/build-backend.md
Labels: bug

#13488 Don't error when the script is too short for the buffer
  crates/uv-install-wheel/src/wheel.rs
Labels: bug

#13498 Bump simple cache bucket to v16
  crates/uv-cache/src/lib.rs
  crates/uv/tests/it/cache_clean.rs
Labels: bug

#13501 Fix VIRTUAL_ENV_PROMPT value in activator/activate
  crates/uv-virtualenv/src/activator/activate
Labels: compatibility

#13511 Fix PowerShell code blocks
  docs/configuration/installer.md
  docs/getting-started/installation.md
  docs/guides/integration/jupyter.md
  docs/guides/projects.md
  docs/index.md
  docs/pip/environments.md
Labels: documentation

#13380 Respect default extras in uv remove
  crates/uv/src/commands/project/remove.rs
  crates/uv/tests/it/edit.rs
Labels: bug

#12850 Add missing git feature dep to preserve_executable_bit test
  crates/uv/tests/it/build_backend.rs
Labels: bug, internal

#13517 Update pre-release hint
  crates/uv/tests/it/lock.rs
Labels: testing

#13518 Remove `av` pin in `transformers`
  crates/uv/tests/it/snapshots/it__ecosystem__transformers-lock-file.snap
  ecosystem/transformers/pyproject.toml
Labels: testing

#13530 Use `AsyncFn` traits for cached client
  crates/uv-client/src/cached_client.rs
Labels: internal

#13537 Bump version to 0.7.6
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/configuration/build-backend.md
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
  rust-toolchain.toml
Labels: releases

#13533 [docs] Fix Publishing Packages, Next = "Index"
  mkdocs.template.yml
Labels: documentation

#13534 Clarify adding SSH Git dependencies
  docs/concepts/projects/dependencies.md
Labels: documentation

#13317 make `uv version` lock and sync
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/version.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/help.rs
  crates/uv/tests/it/version.rs
  docs/reference/cli.md
Labels: bug

#13563 Build backend: Support stubs packages
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/settings.rs
  docs/configuration/build-backend.md
  docs/reference/settings.md
  uv.schema.json
Labels: enhancement, build-backend

#13599 No GHA token for cross arch tests
  .github/workflows/build-binaries.yml
Labels: internal, releases

#13611 Remove misleading line in pin documentation
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: documentation

#13623 Fix tests due to yanked configargparse
  crates/uv/tests/it/lock_conflict.rs
Labels: internal

#13635 Unwire PackageMetadata fields
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#13656 Stack traces from Windows CI crashes
  .github/workflows/ci.yml
Labels: internal, windows

#13576 Extend use of safe URL logging types to `uv-auth` crate
  Cargo.lock
  crates/uv-auth/Cargo.toml
  crates/uv-auth/src/cache.rs
  crates/uv-auth/src/credentials.rs
  crates/uv-auth/src/index.rs
  crates/uv-auth/src/keyring.rs
  crates/uv-auth/src/lib.rs
  crates/uv-auth/src/middleware.rs
  crates/uv-distribution-types/src/index.rs
  crates/uv-distribution-types/src/index_url.rs
  crates/uv-git/src/source.rs
  crates/uv-redacted/src/lib.rs
  crates/uv/src/commands/publish.rs
Labels: security

#13669 Reduce number of reference-checks for `uv cache clean`
  crates/uv-cache/src/lib.rs
Labels: performance

#13663 Exit early on `self update` if global `--offline` is set
  crates/uv/src/commands/self_update.rs
  crates/uv/src/lib.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/self_update.rs
Labels: bug

#13678 Avoid reinstalling dependency group members with `--all-packages`
  crates/uv-resolver/src/lock/installable.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#13598 Write the path of the parent environment to an `extends-environment` key in the `pyvenv.cfg` file of an ephemeral environment
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/run.rs
Labels: virtualenv

#13645 Include pre-release versions in `uv python install --reinstall`
  crates/uv-python/src/downloads.rs
Labels: bug

#13661 Increase deadsnake timeout to 15min
  .github/workflows/ci.yml
Labels: internal

#13680 Avoid using 3.8 in tests when feasible
  crates/uv/Cargo.toml
  crates/uv/tests/it/build.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/init.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/pip_sync.rs
  crates/uv/tests/it/python_find.rs
  crates/uv/tests/it/run.rs
  crates/uv/tests/it/sync.rs
  crates/uv/tests/it/tool_install.rs
  crates/uv/tests/it/tool_run.rs
  crates/uv/tests/it/venv.rs
Labels: testing

#13690 Update dependabot support status
  docs/guides/integration/dependency-bots.md
Labels: documentation

#13691 docs: integration with marimo guide
  docs/guides/integration/index.md
  docs/guides/integration/marimo.md
  mkdocs.template.yml
Labels: documentation

#13696 Use ref-cast for `DisplaySafeUrl`
  Cargo.lock
  Cargo.toml
  crates/uv-auth/src/credentials.rs
  crates/uv-auth/src/keyring.rs
  crates/uv-auth/src/middleware.rs
  crates/uv-redacted/Cargo.toml
  crates/uv-redacted/src/lib.rs
  crates/uv/src/commands/publish.rs
Labels: internal

#13688 Update packse scenarios
  .python-versions
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/lock_scenarios.rs
  crates/uv/tests/it/pip_compile_scenarios.rs
  crates/uv/tests/it/pip_install_scenarios.rs
  scripts/scenarios/generate.py
  scripts/scenarios/requirements.txt
  scripts/scenarios/templates/compile.mustache
  scripts/scenarios/templates/install.mustache
  scripts/sync_scenarios.sh
Labels: internal

#13700 Use only a single 3.13t Linux integration test
  .github/workflows/ci.yml
Labels: internal

#13706 Fix `exclude-newer` date format in docs
  crates/uv-settings/src/settings.rs
  docs/reference/settings.md
  uv.schema.json
Labels: documentation

#13549 make the error message clearer when running distroless containers
  crates/uv-python/src/discovery.rs
  crates/uv-python/src/downloads.rs
  crates/uv-python/src/libc.rs
  crates/uv-python/src/managed.rs
Labels: error messages

#13732 update python build standalone, unblocklist linux updates
  crates/uv-python/download-metadata.json
  crates/uv-python/fetch-download-metadata.py
  crates/uv/tests/it/python_install.rs
Labels: internal

#13736 Don't fail direct URL hash checking with dependency metadata
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/metadata/mod.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#13739 Bump version to 0.7.9
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/configuration/build-backend.md
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases
