Repository astral-sh/uv, pull requests merged in 2025-01, with the labels that each got.

#10258 Detect cyclic dependencies during builds
  crates/uv-build-frontend/src/error.rs
  crates/uv-build-frontend/src/lib.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-installer/src/preparer.rs
  crates/uv-types/src/traits.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/venv.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_install.rs
Labels: bug, error messages

#10257 Fix small typo in editable packages docs
  docs/pip/packages.md
Labels: documentation

#10259 Parse URLs lazily in resolver
  crates/uv-client/src/error.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution-types/src/file.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-requirements/src/upgrade.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/requirements_txt.rs
Labels: performance

#10266 Use `BTreeMap::range` to avoid iterating over unnecessary versions
  crates/uv-resolver/src/version_map.rs
Labels: performance

#10271 Fix `lock_pytorch_cpu`
  crates/uv/tests/it/lock.rs
Labels: internal

#10268 Fix musl cdylib warning
  crates/uv-pep508/Cargo.toml
Labels: internal

#10274 Avoid forking on version in non-universal resolutions
  crates/uv-resolver/src/resolver/mod.rs
Labels: bug

#10277 Gate performance feature on cfg
  crates/uv/src/bin/uv.rs
Labels: internal

#10276 Ignore empty or missing hrefs in Simple HTML
  crates/uv-client/src/html.rs
Labels: bug, compatibility

#10279 Bump version to v0.5.14
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#10291 Visit source distributions before wheels
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution-types/src/prioritized_distribution.rs
Labels: performance

#10179 Extract supported architectures from wheel tags
  crates/uv-distribution-types/src/prioritized_distribution.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
Labels: bug

#10297 Update copyright year
  LICENSE-APACHE
  LICENSE-MIT
Labels: documentation

#10298 Rename CI runners and use Windows 2025 preview on large runners
  .github/workflows/build-binaries.yml
  .github/workflows/ci.yml
Labels: internal

#10307 Avoid generating unused hashes during `uv lock`
  crates/uv-distribution-types/src/hash.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-requirements/src/source_tree.rs
  crates/uv-types/src/hash.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/sync.rs
Labels: performance

#10315 Respect `FORCE_COLOR` environment variable
  crates/uv-cli/src/lib.rs
  crates/uv/tests/it/help.rs
  docs/reference/cli.md
Labels: bug, cli

#9135 Clarify exclude-newer only allows full timestamps in settings docs
  crates/uv-settings/src/settings.rs
  docs/reference/settings.md
  uv.schema.json
Labels: documentation

#10086 Use dynamic dispatch to simplify reporters
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/reporter.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-git/src/resolver.rs
  crates/uv-git/src/source.rs
  crates/uv-installer/src/installer.rs
  crates/uv-installer/src/preparer.rs
  crates/uv-requirements/src/extras.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/source_tree.rs
  crates/uv-requirements/src/unnamed.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv-resolver/src/resolver/reporter.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/reporters.rs
Labels: internal

#10331 Tweak script `--no-project` comment
  docs/guides/scripts.md
Labels: documentation

#10332 docs: installation.md add info about installing with Scoop
  docs/getting-started/installation.md
Labels: documentation

#10097 Avoid downgrading packages when `--upgrade` is provided
  crates/uv-configuration/src/package_options.rs
  crates/uv-installer/src/plan.rs
  crates/uv-requirements/src/upgrade.rs
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/exclusions.rs
  crates/uv/tests/it/pip_install.rs
Labels: bug

#10337 Bump version to 0.5.15
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#10352 Add `Send + 'static` bounds to cache deserialization
  crates/uv-client/src/cached_client.rs
Labels: performance, internal

#10338 Accept requirements in `uv remove`
  crates/uv-cli/src/lib.rs
  crates/uv-settings/src/settings.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/edit.rs
Labels: compatibility

#10347 Simplify `requirements_for_extra`
  crates/uv-resolver/src/resolver/mod.rs
Labels: internal

#10346 Speed up file pins
  crates/uv-resolver/src/pins.rs
Labels: performance

#10349 Refactor batch prefetch
  Cargo.lock
  crates/uv-resolver/Cargo.toml
  crates/uv-resolver/src/resolver/batch_prefetch.rs
Labels: internal

#10348 Optimize `requirements_for_extra`
  crates/uv-configuration/src/overrides.rs
  crates/uv-resolver/src/resolver/mod.rs
Labels: performance

#10345 Remove `[u64; 4]` from small version to move `Arc` to full version
  crates/uv-distribution-types/src/lib.rs
  crates/uv-pep440/src/version.rs
  crates/uv-pep440/src/version_ranges.rs
  crates/uv-pep440/src/version_specifier.rs
  crates/uv-pep508/src/marker/algebra.rs
  crates/uv-pep508/src/marker/simplify.rs
  crates/uv-python/src/discovery.rs
  crates/uv/src/commands/python/list.rs
  crates/uv/src/lib.rs
Labels: performance

#10371 Fix ruff linting warnings from generated template files for extension modules
  crates/uv/src/commands/project/init.rs
  crates/uv/tests/it/init.rs
  docs/concepts/projects/init.md
Labels: bug

#10370 Re-enable zlib-ng on all platforms (except s390x, PowerPC, and FreeBSD)
  crates/uv-performance-flate2-backend/Cargo.lock
  crates/uv-performance-flate2-backend/Cargo.toml
Labels: performance

#10374 Avoid enforcing project-level required version for `uv self`
  crates/uv/src/lib.rs
Labels: bug

#10388 Fix `invalid_platform` test on main
  crates/uv/tests/it/pip_compile.rs
Labels: internal

#10387 Improve file pinning comments
  crates/uv-resolver/src/pins.rs
Labels: internal

#10385 Force a niche into `VersionSmall`
  crates/uv-pep440/src/version.rs
Labels: performance

#10395 Bump version to v0.5.16
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#10401 Respect `requires-python` when installing tools
  crates/uv-requirements/src/specification.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/requires_python.rs
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/tool/common.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/lib.rs
Labels: bug

#10397 improve shell compatibility of venv activate scripts
  .github/workflows/ci.yml
  crates/uv-virtualenv/src/activator/activate
Labels: bug

#10135 Add support for locking PEP 723 scripts
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/lock_target.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/lock.rs
  docs/reference/cli.md
Labels: enhancement

#10400 Avoid Docker rate limits by logging into DockerHub
  .github/workflows/build-docker.yml
Labels: internal

#10136 Respect PEP 723 script lockfiles in uv run
  crates/uv-configuration/src/dev.rs
  crates/uv-scripts/src/lib.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/commands/project/install_target.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/it/run.rs
Labels: enhancement

#10145 Update PEP 723 lockfile in `uv add --script`
  crates/uv-cli/src/lib.rs
  crates/uv-scripts/src/lib.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock_target.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/tests/it/edit.rs
Labels: enhancement

#10159 Add `--script` support to `uv tree` for PEP 723 scripts
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/tree.rs
  docs/reference/cli.md
Labels: enhancement

#10160 Add `--script` support to `uv export` for PEP 723 scripts
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/export.rs
  docs/reference/cli.md
Labels: enhancement

#10162 Update PEP 723 lockfile in `uv remove --script`
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/tests/it/edit.rs
Labels: enhancement

#10411 Add Lambda layer instructions to AWS Lambda guide
  docs/guides/integration/aws-lambda.md
Labels: documentation

#10416 Remove duplicated comment
  crates/uv-resolver/src/resolver/mod.rs
Labels: internal

#10419 Remove unnecessary `.to_string()` call
  crates/uv-platform-tags/src/tags.rs
Labels: internal

#10414 Add `uv lock --script` to the docs
  docs/guides/scripts.md
Labels: documentation

#10423 Use `matches` rather than `contains` in `requirements.txt` parsing
  crates/uv-requirements-txt/src/lib.rs
Labels: performance

#10433 Upgrade to the latest Ruff version
  scripts/benchmark/src/benchmark/resolver.py
  scripts/popular_packages/pypi_10k_most_dependents.ipynb
  scripts/publish/test_publish.py
  scripts/scenarios/generate.py
Labels: internal

#10421 Add meta descriptions for some guides
  docs/guides/integration/docker.md
  docs/guides/integration/fastapi.md
  docs/guides/integration/jupyter.md
  docs/guides/integration/pre-commit.md
Labels: documentation

#10261 docs: Clarify build system specific features usage.
  docs/concepts/projects/config.md
Labels: documentation

#10432 Fetch concurrently for non-first-match index strategies
  crates/uv-client/src/registry_client.rs
Labels: performance

#10439 Use faster disjointness check for markers
  crates/uv-pep508/src/marker/algebra.rs
Labels: performance

#10441 Visit proxy packages eagerly
  crates/uv-resolver/src/pubgrub/priority.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv/tests/it/lock_conflict.rs
  crates/uv/tests/it/lock_scenarios.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/pip_install_scenarios.rs
  crates/uv/tests/it/snapshots/it__ecosystem__transformers-lock-file.snap
  crates/uv/tests/it/snapshots/it__ecosystem__transformers-uv-lock-output.snap
Labels: bug

#10442 replace backoff with backon
  Cargo.lock
  Cargo.toml
  crates/uv-fs/Cargo.toml
  crates/uv-fs/src/lib.rs
Labels: internal

#10443 Respect sentinels in prioritization
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/pubgrub/priority.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv/tests/it/pip_install_scenarios.rs
  crates/uv/tests/it/snapshots/it__ecosystem__transformers-lock-file.snap
Labels: performance

#10409 Improve tool list output when tool environment is broken
  crates/uv/src/commands/tool/list.rs
  crates/uv/tests/it/tool_list.rs
Labels: bug

#10450 Add meta descriptions for remaining guides
  docs/guides/integration/alternative-indexes.md
  docs/guides/integration/dependency-bots.md
  docs/guides/integration/github.md
  docs/guides/integration/gitlab.md
  docs/guides/integration/pytorch.md
Labels: documentation

#10447 Allow reading `--with-requirements` from stdin in `uv add` and `uv run`
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/run.rs
Labels: enhancement, cli

#10449 De-duplicate result handling in Simple API responses
  crates/uv-client/src/registry_client.rs
Labels: internal

#10456 Remove `get_with_version` methods
  crates/uv-resolver/src/version_map.rs
Labels: internal

#10457 Only track markers for compatible versions
  crates/uv-distribution-types/src/prioritized_distribution.rs
  crates/uv-pep440/src/version.rs
  crates/uv/tests/it/pip_compile.rs
Labels: bug

#10463 Add second apache airflow test case
  scripts/requirements/airflow2-constraints.txt
  scripts/requirements/airflow2-req.in
Labels: performance, internal

#10472 uv-resolver: pre-compute PEP 508 markers from universal markers
  crates/uv-resolver/src/universal_marker.rs
Labels: performance

#10477 Fix `UV_FIND_LINKS` delimiter to split on commas
  crates/uv-cli/src/lib.rs
Labels: bug

#10476 Avoid allocating for names in the PEP 508 parser
  crates/uv-pep508/src/lib.rs
Labels: performance

#10453 Use `ArcStr` for marker values
  Cargo.lock
  crates/uv-distribution-types/Cargo.toml
  crates/uv-distribution-types/src/prioritized_distribution.rs
  crates/uv-pep508/Cargo.toml
  crates/uv-pep508/src/lib.rs
  crates/uv-pep508/src/marker/algebra.rs
  crates/uv-pep508/src/marker/parse.rs
  crates/uv-pep508/src/marker/simplify.rs
  crates/uv-pep508/src/marker/tree.rs
  crates/uv-resolver/Cargo.toml
  crates/uv-resolver/src/resolution/output.rs
  crates/uv-resolver/src/resolver/mod.rs
Labels: performance

#10480 Bump version to v0.5.17
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#10484 Fixes bug in `uv remove` when only comments exist
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv/tests/it/edit.rs
Labels: bug

#10490 Avoid forking for identical markers
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/lock_scenarios.rs
  crates/uv/tests/it/pip_compile.rs
Labels: bug

#10496 Avoid prompting on terminals during publish tests
  crates/uv/src/commands/publish.rs
Labels: bug, testing

#10497 Revert "improve shell compatibility of venv activate scripts (#10397)"
  .github/workflows/ci.yml
  crates/uv-virtualenv/src/activator/activate
Labels: bug

#10499 Bump version to v0.5.18
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#10526 Remove resolved build tag TODO
  crates/uv-distribution-filename/src/wheel.rs
Labels: internal

#10528 Fix typo in `version_map.rs`
  crates/uv-resolver/src/version_map.rs
Labels: internal

#10531 Update packse to include `--python-platform`
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/lock_scenarios.rs
  crates/uv/tests/it/pip_compile_scenarios.rs
  crates/uv/tests/it/pip_install_scenarios.rs
  scripts/scenarios/requirements.txt
  scripts/scenarios/templates/install.mustache
Labels: testing

#10500 Fix git-tag cache-key reader in case of slashes (#10467)
  Cargo.lock
  crates/uv-cache-info/Cargo.toml
  crates/uv-cache-info/src/git_info.rs
Labels: bug

#10538 typo
  docs/guides/tools.md
Labels: documentation

#10544 Upgrade packse to v0.3.44
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/lock_scenarios.rs
  crates/uv/tests/it/pip_compile_scenarios.rs
  crates/uv/tests/it/pip_install_scenarios.rs
  scripts/scenarios/requirements.txt
Labels: testing

#10545 Add a shared `uv-small-str` crate
  Cargo.lock
  Cargo.toml
  crates/uv-normalize/Cargo.toml
  crates/uv-normalize/src/extra_name.rs
  crates/uv-normalize/src/group_name.rs
  crates/uv-normalize/src/lib.rs
  crates/uv-normalize/src/package_name.rs
  crates/uv-small-str/Cargo.toml
  crates/uv-small-str/src/lib.rs
Labels: internal

#10572 Don't treat `setuptools` and `wheel` as seed packages in uv sync on Python 3.12
  crates/uv-installer/src/plan.rs
  crates/uv/src/commands/venv.rs
Labels: bug

#10553 Provide `pyproject.toml` path for parse errors in `uv venv`
  crates/uv/src/commands/venv.rs
  crates/uv/tests/it/venv.rs
Labels: error messages

#10578 Read cached registry distributions when `--config-settings` are present
  crates/uv-distribution/src/index/registry_wheel_index.rs
  crates/uv-installer/src/plan.rs
  crates/uv/tests/it/pip_install.rs
Labels: bug, cache

#10488 Pip freeze path
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/pip/freeze.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/pip_freeze.rs
  docs/reference/cli.md
Labels: enhancement, compatibility, cli

#10532 chore: update windows-registry and windows-result crates
  Cargo.lock
  Cargo.toml
Labels: internal, dependencies

#10525 Use structured types for parsing and formatting language and ABI tags
  crates/uv-distribution-filename/src/wheel.rs
  crates/uv-platform-tags/src/abi_tag.rs
  crates/uv-platform-tags/src/language_tag.rs
  crates/uv-platform-tags/src/lib.rs
  crates/uv-platform-tags/src/tags.rs
Labels: internal

#10527 Show expected and available ABI tags in resolver errors
  Cargo.lock
  crates/uv-distribution-types/Cargo.toml
  crates/uv-distribution-types/src/prioritized_distribution.rs
  crates/uv-platform-tags/src/tags.rs
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/requires_python.rs
  crates/uv-resolver/src/resolver/availability.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_install_scenarios.rs
Labels: error messages, no-build

#10542 Use structured wheel tags everywhere
  Cargo.lock
  crates/uv-bench/benches/distribution_filename.rs
  crates/uv-build-backend/Cargo.toml
  crates/uv-build-backend/src/wheel.rs
  crates/uv-cache/src/lib.rs
  crates/uv-distribution-filename/Cargo.toml
  crates/uv-distribution-filename/src/lib.rs
  crates/uv-distribution-filename/src/snapshots/uv_distribution_filename__wheel__tests__ok_build_tag.snap
  crates/uv-distribution-filename/src/snapshots/uv_distribution_filename__wheel__tests__ok_multiple_tags.snap
  crates/uv-distribution-filename/src/snapshots/uv_distribution_filename__wheel__tests__ok_single_tags.snap
  crates/uv-distribution-filename/src/wheel.rs
  crates/uv-distribution-types/src/lib.rs
  crates/uv-distribution-types/src/prioritized_distribution.rs
  crates/uv-platform-tags/Cargo.toml
  crates/uv-platform-tags/src/abi_tag.rs
  crates/uv-platform-tags/src/language_tag.rs
  crates/uv-platform-tags/src/lib.rs
  crates/uv-platform-tags/src/platform.rs
  crates/uv-platform-tags/src/platform_tag.rs
  crates/uv-platform-tags/src/tags.rs
  crates/uv-publish/src/lib.rs
  crates/uv-python/src/platform.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_optional_missing.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_optional_present.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_required_present.snap
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/requires_python.rs
  crates/uv/tests/it/cache_clean.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_install_scenarios.rs
  crates/uv/tests/it/pip_sync.rs
  crates/uv/tests/it/snapshots/it__ecosystem__warehouse-lock-file.snap
Labels: internal, no-build

#10580 Correct Pyston tag format
  crates/uv-platform-tags/src/abi_tag.rs
  crates/uv-platform-tags/src/language_tag.rs
  crates/uv-platform-tags/src/tags.rs
  crates/uv-resolver/src/requires_python.rs
Labels: bug

#10546 Shrink size of platform tag enum
  Cargo.lock
  crates/uv-distribution-filename/src/lib.rs
  crates/uv-distribution-types/src/lib.rs
  crates/uv-platform-tags/Cargo.toml
  crates/uv-platform-tags/src/platform_tag.rs
  crates/uv-platform-tags/src/tags.rs
Labels: performance

#10584 Filter wheels from lockfile based on architecture
  crates/uv-platform-tags/src/platform_tag.rs
  crates/uv-platform-tags/src/tags.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/lock_scenarios.rs
  crates/uv/tests/it/pip_compile_scenarios.rs
  crates/uv/tests/it/pip_install_scenarios.rs
  crates/uv/tests/it/snapshots/it__ecosystem__transformers-lock-file.snap
  scripts/scenarios/requirements.txt
Labels: enhancement

#10583 Reduce `WheelFilename` to 48 bytes
  crates/uv-build-backend/src/wheel.rs
  crates/uv-distribution-filename/src/lib.rs
  crates/uv-distribution-filename/src/snapshots/uv_distribution_filename__wheel__tests__ok_build_tag.snap
  crates/uv-distribution-filename/src/snapshots/uv_distribution_filename__wheel__tests__ok_multiple_tags.snap
  crates/uv-distribution-filename/src/snapshots/uv_distribution_filename__wheel__tests__ok_single_tags.snap
  crates/uv-distribution-filename/src/wheel.rs
  crates/uv-distribution-types/src/lib.rs
  crates/uv-distribution-types/src/prioritized_distribution.rs
  crates/uv-publish/src/lib.rs
  crates/uv-resolver/src/flat_index.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_optional_missing.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_optional_present.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_required_present.snap
  crates/uv-resolver/src/requires_python.rs
  crates/uv-resolver/src/version_map.rs
Labels: performance

#10599 Include build tag in rendered wheel filenames
  Cargo.lock
  crates/uv-distribution-filename/Cargo.toml
  crates/uv-distribution-filename/src/build_tag.rs
  crates/uv-distribution-filename/src/wheel.rs
Labels: bug, no-build

#10601 Reduce distribution size to 200 bytes
  crates/uv-distribution-types/src/lib.rs
  crates/uv-resolver/src/lock/mod.rs
Labels: performance

#10605 Recommend `--native-tls` on SSL errors
  crates/uv-client/src/error.rs
  crates/uv/src/commands/diagnostics.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
Labels: error messages

#10607 Show resolver hints for packages with markers
  crates/uv-resolver/src/pubgrub/package.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv/tests/it/pip_compile.rs
Labels: bug, error messages

#10611 Use script locking for publish test script
  scripts/publish/test_publish.py
  scripts/publish/test_publish.py.lock
Labels: internal

#10625 Avoid allocating when stripping source distribution extension
  crates/uv-distribution-filename/src/extension.rs
  crates/uv-distribution-filename/src/source_dist.rs
Labels: performance

#10479 Always spawn a main2 thread to normalize main stack size issues
  .github/workflows/ci.yml
  CONTRIBUTING.md
  crates/uv-static/src/env_vars.rs
  crates/uv/src/lib.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/ecosystem.rs
  crates/uv/tests/it/show_settings.rs
  docs/configuration/environment.md
Labels: internal

#10623 Make `version` an optional field on installable distribution type
  crates/uv-distribution-types/src/dist_error.rs
  crates/uv-distribution-types/src/resolution.rs
  crates/uv-distribution-types/src/resolved.rs
  crates/uv-resolver/src/lock/installable.rs
  crates/uv-resolver/src/resolution/output.rs
  crates/uv-resolver/src/resolver/derivation.rs
  crates/uv/src/commands/diagnostics.rs
Labels: internal

#10620 Use `memchr` for wheel parsing
  Cargo.lock
  crates/uv-distribution-filename/Cargo.toml
  crates/uv-distribution-filename/src/lib.rs
  crates/uv-distribution-filename/src/splitter.rs
  crates/uv-distribution-filename/src/wheel.rs
Labels: performance

#10622 Omit dynamic versions from the lockfile
  crates/uv-distribution-types/src/dependency_metadata.rs
  crates/uv-distribution/src/metadata/mod.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-pypi-types/src/metadata/metadata12.rs
  crates/uv-pypi-types/src/metadata/metadata_resolver.rs
  crates/uv-pypi-types/src/metadata/pyproject_toml.rs
  crates/uv-requirements/src/upgrade.rs
  crates/uv-resolver/src/lock/installable.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/requirements_txt.rs
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_optional_missing.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_optional_present.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_required_present.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_source_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_source_version_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_version_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_direct_has_subdir.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_direct_no_subdir.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_directory.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_editable.snap
  crates/uv-resolver/src/lock/tree.rs
  crates/uv-resolver/src/preferences.rs
  crates/uv-workspace/src/pyproject.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/snapshots/it__ecosystem__black-lock-file.snap
Labels: enhancement

#10627 Remove `import re` from entrypoint wrapper scripts
  crates/uv-install-wheel/src/wheel.rs
  crates/uv/tests/it/tool_install.rs
Labels: performance

#10588 Silence log message to debug for uv run
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/it/run.rs
Labels: needs-decision, cli

#10582 Show target Python version in error messages
  crates/uv-platform-tags/src/abi_tag.rs
  crates/uv-platform-tags/src/language_tag.rs
  crates/uv-platform-tags/src/platform_tag.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_install_scenarios.rs
Labels: error messages

#10629 Patch embedded install path for Python dylib on macOS during `python install`
  crates/uv-python/src/installation.rs
  crates/uv-python/src/lib.rs
  crates/uv-python/src/macos_dylib.rs
  crates/uv-python/src/managed.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/tests/it/python_install.rs
Labels: bug

#10539 Add meta titles to documents in guides, excluding integration documents.
  docs/guides/install-python.md
  docs/guides/projects.md
  docs/guides/publish.md
  docs/guides/scripts.md
  docs/guides/tools.md
Labels: documentation

#10639 Avoid reading symlinks during `uv python install` on Windows
  crates/uv/src/commands/python/install.rs
Labels: bug

#10643 Bump version to 0.5.19
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: no-build, releases

#10650 Fix outdated comment in `Cargo.toml` for `performance` feature
  crates/uv/Cargo.toml
Labels: internal, no-build

#10652 Drop expensive package `boltons` from `tool_uv_sources` test
  crates/uv/tests/it/pip_install.rs
Labels: testing

#10655 Avoid failing when deserializing unknown tags
  crates/uv-distribution-filename/src/lib.rs
  crates/uv-distribution-types/src/lib.rs
  crates/uv-distribution-types/src/prioritized_distribution.rs
  crates/uv-platform-tags/src/abi_tag.rs
  crates/uv-platform-tags/src/language_tag.rs
  crates/uv-platform-tags/src/platform_tag.rs
  crates/uv-platform-tags/src/tags.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/snapshots/it__ecosystem__warehouse-lock-file.snap
Labels: bug

#10658 Add `win_ia64` tag
  crates/uv-platform-tags/src/platform_tag.rs
Labels: enhancement

#10659 Bump version to v0.5.20
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#10660 Add support for `pypy_73`-style tags
  crates/uv-platform-tags/src/abi_tag.rs
  crates/uv-platform-tags/src/tags.rs
  crates/uv-resolver/src/requires_python.rs
Labels: enhancement

#10647 Drop expensive packages `numpy` and `boltons` from `sync_editable` test
  crates/uv/tests/it/pip_sync.rs
Labels: testing

#10675 docs: fix a few typos
  crates/uv-cli/src/lib.rs
  crates/uv-pep508/src/marker/algebra.rs
  crates/uv-python/src/discovery.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-workspace/src/pyproject.rs
  crates/uv/src/commands/python/pin.rs
  docs/reference/cli.md
  docs/reference/settings.md
  uv.schema.json
Labels: documentation

#10672 Log source file on compile timeout
  crates/uv-installer/src/compile.rs
Labels: error messages

#10642 Simplify `valid_link` determination in `python install`
  crates/uv/src/commands/python/install.rs
Labels: internal

#10649 Add feature-gate to ecosystem tests and disable on Windows CI
  crates/uv/Cargo.toml
  crates/uv/tests/it/main.rs
Labels: testing

#10651 Improve performance of our test drive in Windows CI
  .github/workflows/ci.yml
  .github/workflows/setup-dev-drive.ps1
Labels: internal, testing

#10690 Respect preferences for explicit index dependencies from `requirements.txt`
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv/tests/it/pip_compile.rs
Labels: bug

#10692 Improve the styling of collapsible nav items
  docs/stylesheets/extra.css
Labels: documentation

#10701 Add SyntaxWarning compatibility note to bytecode compilation docs
  docs/pip/compatibility.md
Labels: documentation

#10703 Avoid building dynamic versions when validating lockfile
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/it/lock.rs
Labels: enhancement

#10665 Store unsupported tags in wheel filename
  crates/uv-distribution-filename/src/lib.rs
  crates/uv-distribution-filename/src/snapshots/uv_distribution_filename__wheel__tests__ok_build_tag.snap
  crates/uv-distribution-filename/src/snapshots/uv_distribution_filename__wheel__tests__ok_multiple_tags.snap
  crates/uv-distribution-filename/src/wheel.rs
  crates/uv-distribution-filename/src/wheel_tag.rs
  crates/uv-distribution-types/src/lib.rs
  crates/uv-distribution-types/src/prioritized_distribution.rs
  crates/uv-platform-tags/src/abi_tag.rs
  crates/uv-platform-tags/src/language_tag.rs
  crates/uv-platform-tags/src/platform_tag.rs
  crates/uv-platform-tags/src/tags.rs
  crates/uv-resolver/src/pubgrub/report.rs
Labels: performance

#10704 Avoid narrowing `requires-python` marker with disjunctions
  Cargo.lock
  crates/uv-resolver/Cargo.toml
  crates/uv-resolver/src/marker.rs
  crates/uv/tests/it/pip_compile.rs
Labels: bug

#10705 Avoid returning `Some` for narrowing no-ops
  crates/uv-resolver/src/python_requirement.rs
  crates/uv-resolver/src/requires_python.rs
  crates/uv-resolver/src/resolver/environment.rs
Labels: internal

#10715 Add `UV_VENV_SEED` environment variable
  crates/uv-cli/src/lib.rs
  crates/uv-static/src/env_vars.rs
  docs/configuration/environment.md
  docs/reference/cli.md
Labels: configuration

#10700 Sort preferences by environment, then index
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/preferences.rs
Labels: bug

#10697 fix: ignore permission errors too when looking for user file
  crates/uv-settings/src/lib.rs
Labels: bug

#10710 fix: links in `configuring projects` doc
  .gitignore
  docs/concepts/projects/config.md
Labels: documentation

#10698 Add `MACOSX_DEPLOYMENT_TARGET` to the `--python-platform` documentation
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: documentation

#10720 Fix typo
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: internal

#10688 Respect environment variable credentials for indexes outside root
  crates/uv/src/commands/project/install_target.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/lock_target.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#10721 Avoid attempting to patch macOS dylib for non-macOS installs
  crates/uv-python/src/managed.rs
Labels: bug

#10180 Use `D:` drive for Windows CI
  .github/workflows/ci.yml
  .github/workflows/setup-dev-drive.ps1
Labels: internal

#10723 Bump version to v0.5.21
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#10725 Avoid using NumPy, Pandas, etc. in tool tests
  crates/uv/tests/it/tool_run.rs
Labels: testing

#10734 Use iterators rather than eagerly collecting tags
  crates/uv-distribution-types/src/prioritized_distribution.rs
  crates/uv-resolver/src/pubgrub/report.rs
Labels: internal

#10735 Correct documentation for wheel tag hints
  crates/uv-resolver/src/pubgrub/report.rs
Labels: documentation, internal

#10736 Use colors for lock errors
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_source_ambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_source_version_ambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_version_ambiguous.snap
  crates/uv/tests/it/sync.rs
Labels: error messages

#10741 Remove unnecessary clone on package name
  crates/uv-resolver/src/resolver/mod.rs
Labels: internal

#10740 Remove trailing commas before brackets
  crates/uv-cli/src/comma.rs
  crates/uv-client/src/httpcache/control.rs
  crates/uv-distribution-types/src/dependency_metadata.rs
  crates/uv-pep440/src/version.rs
  crates/uv-pep508/src/marker/tree.rs
  crates/uv-publish/src/lib.rs
  crates/uv-python/src/sysconfig/parser.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv/src/commands/diagnostics.rs
  crates/uv/src/commands/python/install.rs
Labels: internal

#10754 Remove unused Git resolver methods
  crates/uv-git/src/resolver.rs
  crates/uv-git/src/source.rs
Labels: internal

#10757 Remove URL conversions in Git path
  crates/uv-git/src/git.rs
Labels: internal

#10758 Remove TOCTOU errors in Git clone
  crates/uv-git/src/git.rs
Labels: bug

#10775 Ignore lockfile in ecosystem tests
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/ecosystem.rs
Labels: internal
