Repository astral-sh/uv, pull requests merged in 2025-08, with the labels that each got.

#15016 chore(ci): pin some lingering actions by hash
  .github/workflows/build-binaries.yml
  .github/workflows/ci.yml
Labels: internal

#15018 chore(ci): address findings in publish-docs workflow
  .github/workflows/publish-docs.yml
Labels: internal

#15026 Gracefully handle entrypoint permission errors
  crates/uv/src/commands/project/run.rs
Labels: bug

#15033 Remove some arguments from `install`
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
Labels: internal

#15031 Use consistent workspace inheritance
  crates/uv-build-backend/Cargo.toml
  crates/uv-build/Cargo.toml
  crates/uv-console/Cargo.toml
  crates/uv-globfilter/Cargo.toml
  crates/uv-macros/Cargo.toml
  crates/uv-metadata/Cargo.toml
  crates/uv-normalize/Cargo.toml
  crates/uv-publish/Cargo.toml
  crates/uv-requirements/Cargo.toml
  crates/uv-torch/Cargo.toml
Labels: internal

#15054 Fix compile_exclude_newer_package test
  crates/uv/tests/it/pip_compile.rs
Labels: internal

#15059 Fix handling of `python-preference = system` when managed interpreters are on the PATH
  crates/uv-python/src/discovery.rs
  crates/uv/tests/it/python_find.rs
Labels: bug

#15038 Preserve lowered extra build dependencies
  Cargo.lock
  crates/uv-bench/benches/uv.rs
  crates/uv-build-frontend/src/lib.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution-filename/src/extension.rs
  crates/uv-distribution-types/src/build_requires.rs
  crates/uv-distribution-types/src/lib.rs
  crates/uv-distribution-types/src/requirement.rs
  crates/uv-distribution/src/index/built_wheel_index.rs
  crates/uv-distribution/src/lib.rs
  crates/uv-distribution/src/metadata/build_requires.rs
  crates/uv-distribution/src/metadata/mod.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-installer/Cargo.toml
  crates/uv-installer/src/plan.rs
  crates/uv-normalize/src/group_name.rs
  crates/uv-types/src/traits.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/upgrade.rs
  crates/uv/src/commands/venv.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#15066 Show wheel tag hints in install plan
  Cargo.lock
  crates/uv-installer/Cargo.toml
  crates/uv-installer/src/plan.rs
  crates/uv/tests/it/pip_sync.rs
Labels: error messages

#15088 Remove duplicate `extra-build-dependencies` warnings for `uv pip`
  crates/uv/src/lib.rs
Labels: error messages, preview

#15089 Use "option" instead of "setting" in `pylock` warning
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
Labels: error messages

#15090 Take a build constraints reference in `BuildDispatch`
  crates/uv-bench/benches/uv.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/venv.rs
Labels: internal

#15067 Improve HTTP response caching log messages
  crates/uv-client/src/cached_client.rs
  crates/uv-client/src/httpcache/mod.rs
Labels: tracing

#15087 Support `match-runtime = true` in the `uv pip` CLI
  crates/uv-distribution-types/src/build_requires.rs
  crates/uv-workspace/src/pyproject.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/tests/it/pip_install.rs
Labels: enhancement, preview

#15041 Avoid invalid simplification with conflict markers
  crates/uv-pep508/src/marker/tree.rs
  crates/uv-pypi-types/src/conflicts.rs
  crates/uv-resolver/src/graph_ops.rs
  crates/uv-resolver/src/resolver/environment.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/universal_marker.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/lock_conflict.rs
  crates/uv/tests/it/lock_scenarios.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#15107 Support `UV_NO_EDITABLE` where `--no-editable` is supported
  crates/uv-cli/src/lib.rs
  crates/uv-static/src/env_vars.rs
  crates/uv/tests/it/export.rs
  docs/reference/cli.md
  docs/reference/environment.md
Labels: bug

#15019 Address linter findings in build-binaries.yml
  .github/workflows/build-binaries.yml
Labels: internal

#15114 Upgrade `cargo-dist` to add `UV_INSTALLER_URL` to PowerShell installer
  .github/workflows/release.yml
  dist-workspace.toml
Labels: bug

#15120 Fix warnings when running tests with a subset of features
  crates/uv/tests/it/export.rs
  crates/uv/tests/it/lock.rs
Labels: internal

#15126 Ensure symlink warning is shown
  crates/uv-cli/src/lib.rs
  crates/uv-install-wheel/src/linker.rs
  crates/uv-settings/src/settings.rs
  docs/reference/cli.md
  docs/reference/settings.md
  uv.schema.json
Labels: documentation

#15136 Harden ZIP streaming to reject repeated entries and other malformed ZIP files
  Cargo.lock
  Cargo.toml
  crates/uv-dev/Cargo.toml
  crates/uv-dev/src/lib.rs
  crates/uv-dev/src/validate_zip.rs
  crates/uv-extract/Cargo.toml
  crates/uv-extract/src/error.rs
  crates/uv-extract/src/stream.rs
  crates/uv-metadata/src/lib.rs
  crates/uv-static/src/env_vars.rs
  crates/uv/Cargo.toml
  crates/uv/tests/it/extract.rs
  crates/uv/tests/it/main.rs
  crates/uv/tests/it/pip_install.rs
  docs/reference/environment.md
Labels: security

#15134 Consider pythonw when copying entrypoints in uv run
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/it/run.rs
Labels: bug

#14181 Update `find_uv_bin` to locate uv in the base prefix
  crates/uv/tests/it/python_module.rs
  python/uv/_find_uv.py
Labels: enhancement

#15145 chore(ci): fix lint findings in build-docker
  .github/workflows/build-docker.yml
Labels: internal

#15147 Add a regression test for `--require-hashes` with unpinned build requirements
  crates/uv/tests/it/pip_install.rs
Labels: testing

#14182 Refactor `find_uv_bin` and add a better error message
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/python_module.rs
  python/uv/_find_uv.py
Labels: enhancement

#15148 chore(ci): add zizmor workflow
  .github/workflows/zizmor.yml
Labels: internal

#15138 Add missing periods (`.`) to list elements in `Features` docs page
  docs/getting-started/features.md
Labels: documentation

#15007 replace manual venv removal with remove_virtualenv
  Cargo.lock
  crates/uv-tool/Cargo.toml
  crates/uv-tool/src/lib.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/tool/uninstall.rs
Labels: internal

#15013 Ignore GraalPy devtag
  .github/workflows/ci.yml
  crates/uv-python/python/get_interpreter_info.py
Labels: bug

#15153 Fix regression where `--require-hashes` applied to build dependencies in `uv pip install`
  crates/uv/src/commands/pip/install.rs
  crates/uv/tests/it/pip_install.rs
Labels: bug

#14184 Add support for `--prefix` and `--with` installations in `find_uv_bin`
  crates/uv/tests/it/python_module.rs
  python/uv/_find_uv.py
Labels: enhancement

#14191 Search in the user scheme scripts directory last in `find_uv_bin`
  crates/uv/tests/it/python_module.rs
  python/uv/_find_uv.py
Labels: bug

#15157 Update Rust toolchain to 1.89
  clippy.toml
  crates/uv-client/src/base_client.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-configuration/src/dependency_groups.rs
  crates/uv-configuration/src/extras.rs
  crates/uv-distribution-types/src/any.rs
  crates/uv-distribution-types/src/cached.rs
  crates/uv-distribution-types/src/dist_error.rs
  crates/uv-distribution-types/src/installed.rs
  crates/uv-distribution-types/src/lib.rs
  crates/uv-distribution-types/src/prioritized_distribution.rs
  crates/uv-distribution-types/src/requested.rs
  crates/uv-distribution-types/src/resolved.rs
  crates/uv-distribution-types/src/traits.rs
  crates/uv-distribution/src/index/registry_wheel_index.rs
  crates/uv-fs/src/path.rs
  crates/uv-git/src/resolver.rs
  crates/uv-pep440/src/version.rs
  crates/uv-pep440/src/version_specifier.rs
  crates/uv-pep508/src/marker/tree.rs
  crates/uv-pep508/src/verbatim_url.rs
  crates/uv-pypi-types/src/supported_environments.rs
  crates/uv-python/src/environment.rs
  crates/uv-python/src/interpreter.rs
  crates/uv-python/src/sysconfig/parser.rs
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/lock/export/pylock_toml.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/pubgrub/distribution.rs
  crates/uv-resolver/src/resolution/mod.rs
  crates/uv-resolver/src/resolution/requirements_txt.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv-types/src/hash.rs
  crates/uv-workspace/src/dependency_groups.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/self_update.rs
  rust-toolchain.toml
Labels: internal

#15154 Do not update `uv.lock` when using `--isolated`
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/it/run.rs
Labels: enhancement

#15010 Add `UV_DEV` and `UV_NO_DEV` environment variables
  crates/uv-cli/src/lib.rs
  crates/uv-static/src/env_vars.rs
  docs/reference/cli.md
  docs/reference/environment.md
Labels: configuration

#15181 Add `find_uv_bin` test cases by Python version
  crates/uv/tests/it/python_module.rs
Labels: testing

#15182 Add a test requirement on Python 3.14
  .python-versions
Labels: testing

#15221 Respect system proxies on macOS and Windows
  Cargo.lock
  Cargo.toml
Labels: bug

#15225 Include build settings in cache key for registry source distribution lookups
  crates/uv-distribution/src/index/registry_wheel_index.rs
  crates/uv-installer/src/plan.rs
  crates/uv/tests/it/pip_install.rs
Labels: bug

#15161 Fix settings rendering for `extra-build-dependencies`
  crates/uv-settings/src/settings.rs
  crates/uv-workspace/src/pyproject.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/tests/it/sync.rs
  docs/reference/settings.md
  uv.schema.json
Labels: documentation

#15223 Add the Rust toolchain to Renovate
  .github/renovate.json5
Labels: internal

#15247 chore(🧹): cleanup env var usage
  crates/uv-installer/src/compile.rs
  crates/uv-static/src/env_vars.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/tests/it/build.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/export.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/pip_sync.rs
  crates/uv/tests/it/python_install.rs
  crates/uv/tests/it/python_list.rs
  crates/uv/tests/it/python_pin.rs
  crates/uv/tests/it/run.rs
  crates/uv/tests/it/show_settings.rs
  crates/uv/tests/it/sync.rs
  crates/uv/tests/it/tool_install.rs
  crates/uv/tests/it/tool_upgrade.rs
  docs/reference/environment.md
Labels: documentation, internal

#15253 Move warnings for conflicting modules into preview
  Cargo.lock
  crates/uv-configuration/src/preview.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-install-wheel/Cargo.toml
  crates/uv-install-wheel/src/linker.rs
  crates/uv-installer/src/installer.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/show_settings.rs
Labels: preview

#15263 Fix missing uv version in Docker image tags
  .github/workflows/build-docker.yml
Labels: bug

#15269 Add Debian 13 trixie to published Docker images
  .github/workflows/build-docker.yml
  docs/guides/integration/docker.md
Labels: enhancement

#15291 Force cache indexes to set hash digests and cache info
  crates/uv-distribution/src/index/built_wheel_index.rs
  crates/uv-distribution/src/index/cached_wheel.rs
  crates/uv-distribution/src/index/registry_wheel_index.rs
Labels: internal

#15292 Reject `match-runtime = true` for dynamic packages
  crates/uv-build-frontend/src/error.rs
  crates/uv-build-frontend/src/lib.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv/tests/it/sync.rs
Labels: error messages

#15299 Avoid `&String` in installer
  crates/uv-installer/src/installer.rs
Labels: internal

#15305 Move python bin filtering into test that needs it
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/python_module.rs
Labels: testing

#15319 Move `--no-build-isolation-package` into `pyproject.toml` in tests
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/sync.rs
Labels: testing

#15322 Add retries to tests that download from R2
  Cargo.lock
  crates/uv/Cargo.toml
  crates/uv/tests/it/extract.rs
Labels: testing

#15374 Block `tokio::fs` symbols
  clippy.toml
  crates/uv-distribution/src/distribution_database.rs
  crates/uv/tests/it/common/mod.rs
Labels: internal

#15377 Initialize Git prior to reading author
  crates/uv/src/commands/project/init.rs
Labels: enhancement

#15393 Add tests to track `upgrade` and `upgrade-package` interactions
  crates/uv/tests/it/show_settings.rs
Labels: testing

#15388 Retain IO error source in extraction
  crates/uv-extract/src/error.rs
Labels: error messages

#15396 Add `uv sync` tests for upgrade CLI interaction
  crates/uv/tests/it/show_settings.rs
Labels: testing

#15017 Add an experimental `uv format` command
  Cargo.lock
  Cargo.toml
  crates/uv-bin-install/Cargo.toml
  crates/uv-bin-install/src/lib.rs
  crates/uv-cache/src/lib.rs
  crates/uv-cli/src/lib.rs
  crates/uv-configuration/src/preview.rs
  crates/uv-platform/src/lib.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/project/format.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/reporters.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/format.rs
  crates/uv/tests/it/help.rs
  crates/uv/tests/it/main.rs
  crates/uv/tests/it/show_settings.rs
  docs/concepts/preview.md
  docs/reference/cli.md
Labels: preview

#15405 Add `triton` to `torch-backend` manifest
  crates/uv-torch/src/backend.rs
Labels: bug

#15434 fix(tests): Ensure show_settings tests don't load user config
  crates/uv/tests/it/show_settings.rs
Labels: internal

#15441 Bump MSRV to 1.87
  Cargo.toml
  crates/uv-install-wheel/src/wheel.rs
Labels: internal

#15449 Avoid introducing unnecessary system dependency on CUDA
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-torch/src/backend.rs
Labels: bug

#15453 Include cycle error message in `uv pip` CLI
  crates/uv/src/commands/pip/operations.rs
  crates/uv/tests/it/pip_install.rs
Labels: error messages

#15438 feat: uv format should read project dir
  crates/uv/src/commands/project/format.rs
  crates/uv/src/lib.rs
  crates/uv/tests/it/format.rs
Labels: preview

#15481 Cache PyTorch wheels by default
  crates/uv-distribution-types/src/index.rs
  crates/uv-distribution-types/src/index_url.rs
Labels: enhancement

#15487 Move wheel tag methods to `WheelTag`
  crates/uv-distribution-filename/src/wheel.rs
  crates/uv-distribution-filename/src/wheel_tag.rs
Labels: internal

#15486 Add `--python-platform` to `uv pip check`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/pip/check.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/pip_check.rs
  docs/reference/cli.md
Labels: cli

#15511 Remove redundant STOPSHIPs
  crates/uv-distribution/src/source/mod.rs
Labels: internal, no-build, no-test

#15527 Fix format of {version} on `uv format` failure
  crates/uv/src/commands/project/format.rs
Labels: preview

#15530 Rename some Simple API structs
  crates/uv-client/src/html.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution-types/src/file.rs
  crates/uv-pypi-types/src/simple_json.rs
Labels: internal

#15532 Add `rkyv` implementation for Core Metadata
  Cargo.lock
  crates/uv-normalize/src/extra_name.rs
  crates/uv-normalize/src/group_name.rs
  crates/uv-pep508/Cargo.toml
  crates/uv-pep508/src/lib.rs
  crates/uv-pypi-types/Cargo.toml
  crates/uv-pypi-types/src/metadata/metadata_resolver.rs
  crates/uv-pypi-types/src/simple_json.rs
Labels: internal

#15538 Refuse to remove non-virtual environments in `uv venv`
  crates/uv-virtualenv/src/virtualenv.rs
  crates/uv/tests/it/venv.rs
Labels: bug

#15552 Treat a 203 error on credential removal as a missing entry on Windows
  crates/uv-keyring/src/windows.rs
Labels: bug, internal

#15551 Lock during installs in `uv format` to prevent races
  crates/uv-bin-install/src/lib.rs
Labels: bug, preview

#15556 Tweak some documentation headings
  docs/concepts/projects/config.md
  docs/concepts/projects/dependencies.md
  docs/concepts/projects/layout.md
  docs/concepts/projects/run.md
  docs/concepts/projects/sync.md
  docs/concepts/resolution.md
  docs/js/extra.js
  mkdocs.template.yml
Labels: documentation

#15564 Ensure we get the last error from Windows on the same thread
  crates/uv-keyring/src/windows.rs
Labels: bug, internal, windows

#15561 Use `thiserror` for keyring error type
  Cargo.lock
  crates/uv-keyring/Cargo.toml
  crates/uv-keyring/src/error.rs
Labels: internal

#15546 Make `cache_index_credentials()` misuse resistant
  crates/uv-client/src/registry_client.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/list.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/pip/tree.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/commands/publish.rs
  crates/uv/src/commands/venv.rs
Labels: internal

#15548 Use a global `BaseClientBuilder`
  crates/uv-bench/benches/uv.rs
  crates/uv-client/src/base_client.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-client/tests/it/remote_metadata.rs
  crates/uv-client/tests/it/user_agent_version.rs
  crates/uv-dev/src/validate_zip.rs
  crates/uv-dev/src/wheel_metadata.rs
  crates/uv-publish/src/lib.rs
  crates/uv-requirements-txt/src/lib.rs
  crates/uv-requirements/src/lib.rs
  crates/uv-requirements/src/upgrade.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/list.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/pip/tree.rs
  crates/uv/src/commands/pip/uninstall.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/format.rs
  crates/uv/src/commands/project/init.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/commands/project/version.rs
  crates/uv/src/commands/publish.rs
  crates/uv/src/commands/python/find.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/src/commands/python/pin.rs
  crates/uv/src/commands/self_update.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/commands/tool/upgrade.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/lib.rs
  crates/uv/tests/it/common/mod.rs
Labels: internal

#15594 Improve publish test error when no versions are found
  scripts/publish/test_publish.py
Labels: testing

#15608 Skip non-existent directories in bytecode compilation
  crates/uv/src/commands/mod.rs
Labels: bug
