Repository astral-sh/uv, pull requests merged in 2025-04, with the labels that each got.

#12592 fix parsing of `python-platform` in settings tomls
  crates/uv-configuration/src/target_triple.rs
  crates/uv/tests/it/show_settings.rs
Labels: bug

#12598 Update dependencies.md
  docs/concepts/projects/dependencies.md
Labels: documentation

#12610 Add `Bearer` support to `Credentials`
  crates/uv-auth/src/cache.rs
  crates/uv-auth/src/credentials.rs
  crates/uv-auth/src/keyring.rs
  crates/uv-auth/src/middleware.rs
Labels: internal

#12623 enforce crc32 checks when using async-zip
  crates/uv-extract/src/error.rs
  crates/uv-extract/src/stream.rs
  crates/uv-metadata/src/lib.rs
  crates/uv/tests/it/pip_install.rs
Labels: bug

#12627 improve archive error messages
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-extract/src/error.rs
  crates/uv-metadata/src/lib.rs
  crates/uv/tests/it/pip_install.rs
Labels: error messages

#12498 Add qualification to authenticate always documentation
  docs/configuration/indexes.md
Labels: documentation

#12631 Include explicit indexes in URL auth policies list
  crates/uv-distribution-types/src/index_url.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#12628 Report the queried executable path in `uv python list`
  crates/uv-python/src/interpreter.rs
  crates/uv/src/commands/python/list.rs
Labels: enhancement, cli

#12637 Bump to 0.6.12
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#12376 Add `--show-version` to `uv python find`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/python/find.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/python_find.rs
  docs/reference/cli.md
Labels: enhancement

#12367 Skip repeated directories in `PATH` when searching for Python interpreters
  Cargo.lock
  crates/uv-python/Cargo.toml
  crates/uv-python/src/discovery.rs
  crates/uv/tests/it/python_list.rs
Labels: enhancement

#12659 use astral-sh/cargo-dist instead
  .github/workflows/release.yml
  Cargo.toml
Labels: internal

#12682 Use `Credentials` abstraction in `uv-publish`
  Cargo.lock
  crates/uv-auth/src/credentials.rs
  crates/uv-publish/Cargo.toml
  crates/uv-publish/src/lib.rs
  crates/uv/src/commands/publish.rs
Labels: internal, no-build

#12722 only warn if CRC appears to be missing
  Cargo.lock
  crates/uv-extract/src/stream.rs
  crates/uv-metadata/Cargo.toml
  crates/uv-metadata/src/lib.rs
Labels: bug

#12672 Unset `SCRIPT_PATH` in relocatable activation script
  crates/uv-virtualenv/src/activator/activate
Labels: enhancement

#12726 Avoid infinite loop in `uv export` with conflicts
  CHANGELOG.md
  crates/uv-resolver/src/lock/requirements_txt.rs
  crates/uv/tests/it/export.rs
Labels: bug

#12683 Extend the reference documentation for `uv pip sync`
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: documentation

#12732 Add lockfile note about PEP 751
  docs/concepts/projects/layout.md
Labels: documentation

#12669 Emit dedicated error message for Conda environment.yml files
  crates/uv-requirements/src/sources.rs
  crates/uv-requirements/src/specification.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/pip_install.rs
Labels: error messages

#12736 Update maturin-action to v1.48.1
  .github/workflows/build-binaries.yml
Labels: internal

#12756 Split workspace members onto their own lines in `uv init`
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv/tests/it/init.rs
Labels: bug

#12757 Error when `tool.uv.sources` is set in system-level configuration file
  crates/uv-settings/src/lib.rs
Labels: error messages

#12640 Fix mismatched pip interface header / nav titles
  docs/pip/environments.md
  mkdocs.template.yml
Labels: documentation

#12767 Avoid querying GitHub on repeated install invocations
  crates/uv-distribution/src/source/mod.rs
  crates/uv-git-types/src/oid.rs
  crates/uv-git/src/resolver.rs
Labels: performance

#12779 Build backend: Check module dir exists for sdist build
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/source_dist.rs
  crates/uv-build-backend/src/wheel.rs
  crates/uv/tests/it/build_backend.rs
Labels: bug, preview

#12786 Bump to 0.6.14
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#12717 Use index-level instead of realm-level credential caching for known indexes
  crates/uv-auth/src/cache.rs
  crates/uv-auth/src/index.rs
  crates/uv-auth/src/middleware.rs
  docs/configuration/authentication.md
Labels: network

#12793 Fix lockfile note
  docs/concepts/projects/layout.md
Labels: documentation

#12807 Fix CLI reference with code block
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: documentation

#12820 Split UV_INDEX on all whitespace
  crates/uv-cli/src/lib.rs
  crates/uv-cli/src/options.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/edit.rs
Labels: bug, compatibility

#12811 feat: Error on dependency object specifier
  crates/uv-workspace/src/dependency_groups.rs
  crates/uv/tests/it/lock.rs
Labels: internal

#12825 Refine lack of musl distributions to ARM-only
  docs/concepts/python-versions.md
  docs/guides/integration/docker.md
Labels: documentation

#12824 display aliases for long and short args in the cli reference
  crates/uv-dev/src/generate_cli_reference.rs
  docs/reference/cli.md
Labels: documentation

#12471 Add integration test for GitHub provided free-threaded Python
  .github/workflows/ci.yml
Labels: testing

#12840 Revert "feat: Error on dependency object specifier (#12811)"
  crates/uv-workspace/src/dependency_groups.rs
  crates/uv/tests/it/lock.rs
Labels: internal

#12841 Error on unknown dependency object specifiers
  crates/uv-workspace/src/dependency_groups.rs
  crates/uv/tests/it/lock.rs
Labels: internal

#12836 Fix pre-release exclusive comparison operator in uv-pep440
  crates/uv-pep440/src/version_specifier.rs
Labels: bug

#12873 Address #12836 review comment
  crates/uv-pep440/src/version_specifier.rs
Labels: internal

#12858 Fix typo in a reference
  docs/js/extra.js
Labels: documentation

#12778 Enable `--dry-run` with `--locked` / `--frozen` for `uv sync`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/it/sync.rs
Labels: enhancement, cli

#12878 Fix tests on non-English Windows
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/ecosystem.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/pip_sync.rs
  crates/uv/tests/it/run.rs
Labels: internal, windows

#12879 fix cargo-dist config
  Cargo.toml
Labels: internal

#12882 Respect build constraints for `uv run --with` dependencies
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/it/run.rs
Labels: enhancement

#12885 make distability opt-in
  Cargo.toml
  crates/uv/Cargo.toml
Labels: internal

#12892 Remove `if if`
  crates/uv/src/commands/project/run.rs
Labels: internal

#12893 Cache `which git` in `uv init`
  Cargo.lock
  crates/uv-configuration/Cargo.toml
  crates/uv-configuration/src/vcs.rs
Labels: enhancement

#12884 Ensure virtual environment is compatible with interpreter on sync
  crates/uv-python/src/environment.rs
  crates/uv-python/src/virtualenv.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#12839 Set 4MB stack size for all threads, introduce `UV_STACK_SIZE`
  crates/uv-configuration/src/lib.rs
  crates/uv-configuration/src/rayon.rs
  crates/uv-configuration/src/threading.rs
  crates/uv-static/src/env_vars.rs
  crates/uv/src/lib.rs
  docs/configuration/environment.md
Labels: bug, windows

#12239 Patch `CC` and `CCX` entries in sysconfig for cross-compiled `aarch64` Python distributions
  crates/uv-python/src/sysconfig/mod.rs
Labels: bug

#11553 [docs] Add shebang section for scripts
  docs/guides/scripts.md
Labels: documentation

#12916 Improve docs for `uv python list --only-downloads` and `--only-installed`
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: documentation

#12923 Use suffix on uvx binary when searching for uv binary
  crates/uv/src/bin/uvx.rs
Labels: enhancement

#12941 Add test for install from remote requirements.txt
  Cargo.lock
  crates/uv/Cargo.toml
  crates/uv/tests/it/pip_install.rs
Labels: testing

#12947 Align supported Config-settings with example in docs
  crates/uv-configuration/src/config_settings.rs
  uv.schema.json
Labels: bug

#12943 fix(ui): update version formatting to use cyan color
  crates/uv/src/commands/self_update.rs
Labels: bug, cli

#12915 Show PyPy downloads during `uv python list`
  crates/uv-python/src/downloads.rs
  crates/uv/src/commands/python/list.rs
Labels: bug

#12949 update cargo-dist and enable ci checks
  .github/workflows/release.yml
  Cargo.toml
Labels: internal, releases

#12956 Separate `requirements.txt` export logic from graph construction
  crates/uv-resolver/src/lock/export/mod.rs
  crates/uv-resolver/src/lock/export/requirements_txt.rs
  crates/uv-resolver/src/lock/mod.rs
Labels: internal

#12957 Accept `requirements.txt` (verbatim) as a format on the CLI
  crates/uv-configuration/src/export_format.rs
  docs/reference/cli.md
Labels: cli

#12925 Fix `PythonDownloadRequest` parsing for partial keys
  crates/uv-python/src/discovery.rs
  crates/uv-python/src/downloads.rs
  crates/uv/tests/it/python_find.rs
Labels: bug

#12951 Add debug logs for version file search
  crates/uv-python/src/version_files.rs
  crates/uv/tests/it/lock.rs
Labels: tracing

#12909 Ignore arbitrary Python requests in version files
  crates/uv-python/src/version_files.rs
  crates/uv/src/commands/python/pin.rs
  crates/uv/tests/it/python_find.rs
Labels: breaking

#11603 Require the command in `uvx <name>` to be available in the Python environment
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/it/tool_run.rs
Labels: breaking

#12944 Obfuscate password in credentials debug messages
  crates/uv-auth/src/credentials.rs
Labels: security

#12651 Use index URL instead of package URL for keyring credential lookups
  crates/uv-auth/src/cache.rs
  crates/uv-auth/src/index.rs
  crates/uv-auth/src/lib.rs
  crates/uv-auth/src/middleware.rs
  crates/uv-client/src/base_client.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution-types/src/index_url.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/list.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/pip/tree.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/commands/publish.rs
  crates/uv/src/commands/venv.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/publish.rs
  docs/configuration/authentication.md
  scripts/packages/keyring_test_plugin/keyrings/test_keyring.py
Labels: network, breaking

#12969 Obfuscate username in tracing URL
  Cargo.lock
  Cargo.toml
  crates/uv-auth/Cargo.toml
  crates/uv-auth/src/credentials.rs
  crates/uv-auth/src/middleware.rs
Labels: security

#12968 Add upload time to `uv.lock`
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_optional_missing.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_optional_present.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_required_present.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_source_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_source_version_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_version_dynamic.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_version_unambiguous.snap
  crates/uv/tests/it/branching_urls.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/export.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/lock_conflict.rs
  crates/uv/tests/it/lock_scenarios.rs
  crates/uv/tests/it/run.rs
  crates/uv/tests/it/snapshots/it__ecosystem__black-lock-file.snap
  crates/uv/tests/it/snapshots/it__ecosystem__github-wikidata-bot-lock-file.snap
  crates/uv/tests/it/snapshots/it__ecosystem__home-assistant-core-lock-file.snap
  crates/uv/tests/it/snapshots/it__ecosystem__packse-lock-file.snap
  crates/uv/tests/it/snapshots/it__ecosystem__saleor-lock-file.snap
  crates/uv/tests/it/snapshots/it__ecosystem__transformers-lock-file.snap
  crates/uv/tests/it/snapshots/it__ecosystem__warehouse-lock-file.snap
  crates/uv/tests/it/snapshots/it__workflow__jax_instability-2.snap
  crates/uv/tests/it/snapshots/it__workflow__packse_add_remove_existing_package_noop-2.snap
  crates/uv/tests/it/snapshots/it__workflow__packse_add_remove_one_package-2.snap
  crates/uv/tests/it/snapshots/it__workflow__packse_promote_transitive_to_direct_then_remove-2.snap
  crates/uv/tests/it/sync.rs
  crates/uv/tests/it/tree.rs
  crates/uv/tests/it/workflow.rs
  crates/uv/tests/it/workspace.rs
Labels: enhancement

#12897 Allow updating Git sources by name
  crates/uv-workspace/src/pyproject.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/tests/it/edit.rs
Labels: enhancement

#12945 Refactor adding bounds to dependencies in `pyproject.toml`
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv/src/commands/project/add.rs
Labels: internal

#12803 Build backend: Add reference docs and schema
  Cargo.lock
  crates/uv-build-backend/Cargo.toml
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/metadata.rs
  crates/uv-build-backend/src/settings.rs
  crates/uv-build-backend/src/source_dist.rs
  crates/uv-build-backend/src/wheel.rs
  crates/uv-globfilter/README.md
  crates/uv-globfilter/src/portable_glob.rs
  crates/uv-macros/src/options_metadata.rs
  crates/uv-pypi-types/src/identifier.rs
  crates/uv-settings/src/settings.rs
  crates/uv-workspace/Cargo.toml
  crates/uv-workspace/src/pyproject.rs
  crates/uv-workspace/src/workspace.rs
  docs/reference/settings.md
  pyproject.toml
  uv.schema.json
Labels: documentation, preview

#13017 Forward additional signals to the child process in `uv run`
  crates/uv/src/commands/run.rs
Labels: bug

#13018 Add a brief sleep before sending SIGINT to children
  crates/uv/src/commands/run.rs
Labels: enhancement

#12955 Add `uv export` support for PEP 751
  crates/uv-cli/src/lib.rs
  crates/uv-configuration/src/export_format.rs
  crates/uv-pypi-types/src/simple_json.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/lock/export/mod.rs
  crates/uv-resolver/src/lock/export/pylock_toml.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/tests/it/export.rs
  docs/reference/cli.md
Labels: enhancement

#12958 Infer output type in `uv export`
  crates/uv-cli/src/lib.rs
  crates/uv-requirements/src/sources.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/export.rs
  docs/reference/cli.md
Labels: cli

#13026 Retry on deadsnake repo add failure
  .github/workflows/ci.yml
Labels: internal

#12992 Add `pylock.toml` to `uv pip install` and `uv pip sync`
  crates/uv-distribution-types/src/resolution.rs
  crates/uv-requirements/src/sources.rs
  crates/uv-requirements/src/specification.rs
  crates/uv-resolver/src/lock/export/pylock_toml.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/pip_sync.rs
Labels: enhancement

#13025 Refactor environment validity check into separate function
  crates/uv/src/commands/project/mod.rs
  crates/uv/tests/it/lock.rs
Labels: internal

#12993 Validate that PEP 751 entries don't include multiple sources
  crates/uv-resolver/src/lock/export/pylock_toml.rs
  crates/uv/tests/it/pip_install.rs
Labels: error messages

#13019 Add PEP 751 support to `uv pip compile`
  crates/uv-cli/src/lib.rs
  crates/uv-requirements/src/upgrade.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/lock/export/mod.rs
  crates/uv-resolver/src/lock/export/pylock_toml.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/preferences.rs
  crates/uv-settings/src/combine.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/show_settings.rs
  docs/reference/cli.md
Labels: enhancement

#13028 Clean up TOML-to-Jiff conversion
  crates/uv-resolver/src/lock/export/pylock_toml.rs
Labels: internal

#13030 Omit PEP 751 version for source trees
  crates/uv-resolver/src/lock/export/pylock_toml.rs
  crates/uv/tests/it/export.rs
  crates/uv/tests/it/pip_compile.rs
Labels: bug

#13034 Bump version to 0.6.15
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-publish/src/lib.rs
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/concepts/projects/layout.md
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#13036 Add `crates/uv-publish/src/lib.rs` to version patch files
  pyproject.toml
Labels: internal

#13041 Revert "Properly handle authentication for 302 redirect URLs"
  Cargo.lock
  crates/uv-client/Cargo.toml
  crates/uv-client/src/base_client.rs
  crates/uv-client/src/cached_client.rs
  crates/uv-client/src/lib.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-git/src/resolver.rs
  crates/uv-publish/src/lib.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/edit.rs
Labels: bug

#13042 Bump verison to 0.6.16
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#13047 Apply context filter to PEP 751 tests
  crates/uv/tests/it/pip_compile.rs
Labels: internal

#13053 Fix several occurrences of the phrase “This options”
  crates/uv-build/python/uv_build/__init__.py
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: documentation

#12917 Check dist name to handle bogus redirect
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/it/pip_install.rs
Labels: bug

#13072 Add PyTorch v2.7.0 to GPU backend
  crates/uv-torch/src/backend.rs
  docs/reference/cli.md
  uv.schema.json
Labels: preview

#13076 Temporarily remove bogus redirect test
  crates/uv/tests/it/pip_install.rs
Labels: testing

#13077 Avoid panic for invalid Python versions
  crates/uv-python/src/python_version.rs
  crates/uv/tests/it/pip_install.rs
Labels: bug, error messages

#13066 Update pubgrub to a3b4db3
  Cargo.lock
  Cargo.toml
Labels: enhancement

#13088 Check for mismatched package and distribution names on resolver thread
  crates/uv-distribution-types/src/lib.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/it/pip_install.rs
Labels: bug

#12349 change `uv version` to be an interface for project version reads and edits
  crates/uv-cli/src/lib.rs
  crates/uv-cli/src/version.rs
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/version.rs
  crates/uv/src/lib.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/help.rs
  crates/uv/tests/it/main.rs
  crates/uv/tests/it/version.rs
  docs/reference/cli.md
Labels: enhancement, breaking

#12671 Make `--frozen` and `--no-sources` conflicting options
  crates/uv-cli/src/lib.rs
Labels: error messages, breaking

#13051 Block scripts from overwriting `python`
  crates/uv-install-wheel/src/lib.rs
  crates/uv-install-wheel/src/wheel.rs
  crates/uv/tests/it/pip_install.rs
Labels: bug

#13086 Reject requires python even if not listed on the index page
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/it/pip_compile.rs
Labels: bug

#13105 Fix panic with invalid last char in PEP 508 name
  crates/uv-pep508/src/lib.rs
  crates/uv-pep508/src/verbatim_url.rs
Labels: bug

#12742 Test publishing with pypa/gh-action-pypi-publish
  .github/workflows/ci.yml
Labels: internal

#13022 Omit Python 3.7 downloads from managed versions
  crates/uv-python/download-metadata.json
  crates/uv-python/fetch-download-metadata.py
  crates/uv-python/src/download-metadata-minified.json
Labels: breaking

#13027 Report Python versions in `pyvenv.cfg` version mismatch
  crates/uv-python/src/environment.rs
  crates/uv-python/src/interpreter.rs
  crates/uv-python/src/python_version.rs
  crates/uv-python/src/virtualenv.rs
  crates/uv/src/commands/project/mod.rs
Labels: error messages, tracing

#13121 Loosen `github.repository` match in `ci.yml`
  .github/workflows/ci.yml
Labels: internal

#13132 Avoid erroring on omitted wheel-only packages in `pylock.toml`
  crates/uv-resolver/src/lock/export/pylock_toml.rs
  crates/uv/tests/it/pip_sync.rs
Labels: bug

#13134 Respect build options (`--no-binary` et al) in `pylock.toml`
  crates/uv-resolver/src/lock/export/pylock_toml.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/tests/it/pip_sync.rs
Labels: bug

#13136 Show tag hints when failing to find a compatible wheel in `pylock.toml`
  crates/uv-requirements/src/upgrade.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/lock/export/mod.rs
  crates/uv-resolver/src/lock/export/pylock_toml.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/it/pip_sync.rs
Labels: error messages

#13140 Don't run CodSpeed benchmarks outside of `astral-sh/uv`
  .github/workflows/ci.yml
Labels: internal

#13130 [docs] Changed fish completions append `>>` to overwrite `>`
  docs/getting-started/installation.md
Labels: documentation

#13050 Implement RFC 7231 compliant relative URI and fragment handling in redirects
  Cargo.lock
  crates/uv-client/Cargo.toml
  crates/uv-client/src/base_client.rs
  crates/uv-client/src/cached_client.rs
  crates/uv-client/src/lib.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-git/src/resolver.rs
  crates/uv-publish/src/lib.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/edit.rs
Labels: bug, error messages

#12175 Optional managed Python archive download cache
  crates/uv-cache/src/lib.rs
  crates/uv-python/src/downloads.rs
  crates/uv-static/src/env_vars.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/src/commands/reporters.rs
  crates/uv/tests/it/python_install.rs
  docs/configuration/environment.md
Labels: enhancement

#13108 Remove `--version` from subcommands
  crates/uv-cli/src/lib.rs
  crates/uv/src/lib.rs
  crates/uv/tests/it/help.rs
  crates/uv/tests/it/run.rs
  crates/uv/tests/it/tool_run.rs
  docs/reference/cli.md
Labels: cli, breaking

#13181 Remove flyte-short-incompatible benchmark for too many false positives
  crates/uv-bench/benches/distribution_filename.rs
Labels: internal

#13109 Fix display name for `uvx --version`
  crates/uv-cli/src/lib.rs
Labels: bug

#12964 Refactor `ExtraSpecification` to support `default-extras`
  crates/uv-configuration/src/extras.rs
  crates/uv-normalize/src/extra_name.rs
  crates/uv-normalize/src/lib.rs
  crates/uv-resolver/src/lock/export/mod.rs
  crates/uv-resolver/src/lock/export/pylock_toml.rs
  crates/uv-resolver/src/lock/export/requirements_txt.rs
  crates/uv-resolver/src/lock/installable.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/install_target.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/show_settings.rs
Labels: internal

#13119 Reject non-PEP 751 filenames in `uv pip compile` and `uv export`
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/tests/it/export.rs
  crates/uv/tests/it/pip_compile.rs
Labels: error messages, breaking

#13199 Upgrade PyTorch guide to CUDA 12.8 and PyTorch 2.7
  docs/guides/integration/pytorch.md
Labels: documentation

#13200 Add ROCm example to the PyTorch guide
  docs/guides/integration/pytorch.md
Labels: documentation

#13202 Stylize version warning with bold, yellow, etc.
  crates/uv/src/commands/version.rs
  crates/uv/tests/it/version.rs
Labels: internal

#13218 Bump version to 0.7.1
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#13219 Fix changelog indentation level
  CHANGELOG.md
Labels: internal

#13220 Fix PR links in CHANGELOG
  CHANGELOG.md
Labels: internal

#13234 Fix incorrect venv invalidation for pre-release Python versions
  crates/uv-python/src/environment.rs
Labels: bug

#13230 Respect `--project` in `uv version`
  crates/uv/src/commands/version.rs
  crates/uv/tests/it/version.rs
Labels: bug

#13237 Fix patching of `clang` in managed Python sysconfig
  crates/uv-python/src/sysconfig/mod.rs
Labels: bug

#13229 Use "error" instead of "warning" for self-update message
  crates/uv/src/commands/self_update.rs
Labels: error messages

#13228 Improve trace log for retryable errors
  crates/uv-client/src/base_client.rs
Labels: tracing

#13203 hard error `uv version` for more cli flags
  crates/uv/src/lib.rs
Labels: error messages

#13240 Bump version to 0.7.2
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#12974 Add `python-downloads-json-url` option for `uv.toml` to configure custom Python installations via JSON URL
  crates/uv-cli/src/lib.rs
  crates/uv-python/src/downloads.rs
  crates/uv-python/src/installation.rs
  crates/uv-settings/src/settings.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/project/init.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/src/commands/python/list.rs
  crates/uv/src/commands/tool/common.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/commands/tool/upgrade.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/help.rs
  crates/uv/tests/it/show_settings.rs
  docs/reference/cli.md
  docs/reference/settings.md
  uv.schema.json
Labels: configuration
