Repository astral-sh/uv, pull requests merged in 2025-07, with the labels that each got.

#14396 Remove unnecessary codspeed deps
  Cargo.lock
  crates/uv-bench/Cargo.toml
Labels: internal

#14379 Use the insiders requirements when building docs in CI
  .github/workflows/ci.yml
Labels: testing

#14378 Keep track of retries in `ManagedPythonDownload::fetch_with_retry`
  crates/uv-python/src/downloads.rs
Labels: enhancement

#14338 Reuse build (virtual) environments across resolution and installation
  Cargo.lock
  crates/uv-build-frontend/src/lib.rs
  crates/uv-configuration/src/build_options.rs
  crates/uv-configuration/src/sources.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-types/Cargo.toml
  crates/uv-types/src/builds.rs
  crates/uv-types/src/traits.rs
Labels: enhancement

#14368 Workaround for panic due to missing global validation in clap
  crates/uv-cli/src/options.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/pip_install.rs
Labels: bug

#14402 Bump version to 0.7.18
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/concepts/build-backend.md
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#14335 Update the tilde version specifier warning to include more context
  crates/uv-distribution-types/src/requires_python.rs
  crates/uv-pep440/src/lib.rs
  crates/uv-pep440/src/version_specifier.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/tests/it/lock.rs
Labels: enhancement

#14404 Make project and interpreter lock acquisition non-fatal
  crates/uv-build-frontend/src/lib.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/pip/uninstall.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#14427 Add linux aarch64 smoke tests
  .github/workflows/ci.yml
Labels: testing

#14432 Finish incomplete sentence in pip migration guide
  docs/guides/migration/pip-to-project.md
Labels: documentation

#14310 Add a test for `--force-pep517`
  crates/uv/tests/it/build.rs
Labels: internal

#14444 make `ErrorTree` for `NoSolutionError` externally accessible
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/pubgrub/mod.rs
  crates/uv-resolver/src/pubgrub/package.rs
  crates/uv-resolver/src/resolver/availability.rs
Labels: rustlib

#14450 Remove transparent variants in `uv-extract` to enable retries
  crates/uv-extract/src/error.rs
Labels: bug

#14456 Document that `VerbatimUrl` does not preserve original string after serialization
  crates/uv-pep508/src/verbatim_url.rs
Labels: internal

#14480 Move fragment preservation test to directly test our redirect handling logic
  crates/uv-client/src/base_client.rs
  crates/uv-client/src/registry_client.rs
Labels: testing

#14493 Remove `cache-dependency-glob` examples for `setup-uv`
  docs/guides/integration/github.md
Labels: documentation

#14498 Fix handling of pre-releases in preferences
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/preferences.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
Labels: bug

#14519 Drop trailing arguments when writing shebangs
  crates/uv-install-wheel/src/wheel.rs
  crates/uv/tests/it/pip_install.rs
Labels: bug, compatibility

#14460 Multiple modules in namespace packages
  Cargo.lock
  crates/uv-build-backend/Cargo.toml
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/settings.rs
  crates/uv-build-backend/src/source_dist.rs
  crates/uv-build-backend/src/wheel.rs
  docs/concepts/build-backend.md
  docs/reference/settings.md
  uv.schema.json
Labels: enhancement, build-backend

#14449 Simplify relative URL handling
  crates/uv-client/src/error.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution-types/src/file.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-pypi-types/src/base_url.rs
Labels: internal

#14539 Add nesting groups documentation for dependency groups
  docs/concepts/projects/dependencies.md
Labels: documentation

#14541 Only run macOS tests on `main` without opt-in
  .github/workflows/ci.yml
Labels: internal

#14522 Add hint when Python downloads are disabled
  crates/uv-python/src/installation.rs
  crates/uv-python/src/lib.rs
  crates/uv/src/commands/python/pin.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/python_find.rs
  crates/uv/tests/it/python_install.rs
  crates/uv/tests/it/python_pin.rs
  crates/uv/tests/it/tool_run.rs
Labels: error messages

#14530 feature: shorthand for --with (-w) in uvx and uv tool run
  crates/uv-cli/src/lib.rs
  crates/uv/tests/it/tool_run.rs
  docs/concepts/tools.md
  docs/reference/cli.md
Labels: cli

#14552 Use `astral-sh` fork of `rs-async-zip`
  Cargo.lock
  Cargo.toml
Labels: internal

#14551 Fix `if` on macos test job
  .github/workflows/ci.yml
Labels: internal

#14320 Add `--python-platform` to `uv sync`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/version.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/sync.rs
  docs/reference/cli.md
Labels: enhancement

#14554 Fix repeated word in Pyodide doc
  crates/uv-configuration/src/target_triple.rs
  docs/reference/cli.md
  uv.schema.json
Labels: documentation

#14529 Default to `--workspace` when adding subdirectories
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/edit.rs
  docs/reference/cli.md
Labels: cli, breaking

#14197 Support conflicting editable settings across groups
  crates/uv-distribution-types/src/buildable.rs
  crates/uv-distribution-types/src/lib.rs
  crates/uv-distribution-types/src/requirement.rs
  crates/uv-distribution/src/index/built_wheel_index.rs
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-installer/src/satisfies.rs
  crates/uv-pypi-types/src/parsed_url.rs
  crates/uv-requirements-txt/src/lib.rs
  crates/uv-requirements-txt/src/requirement.rs
  crates/uv-requirements-txt/src/snapshots/uv_requirements_txt__test__parse-unix-bare-url.txt.snap
  crates/uv-requirements-txt/src/snapshots/uv_requirements_txt__test__parse-unix-editable.txt.snap
  crates/uv-requirements-txt/src/snapshots/uv_requirements_txt__test__parse-windows-bare-url.txt.snap
  crates/uv-requirements-txt/src/snapshots/uv_requirements_txt__test__parse-windows-editable.txt.snap
  crates/uv-requirements/src/source_tree.rs
  crates/uv-resolver/src/lock/export/pylock_toml.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/urls.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/sync.rs
Labels: bug, breaking

#14546 Tear miette out of the `uv venv` command
  crates/uv/src/commands/venv.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/venv.rs
Labels: cli, breaking

#14322 Add missing validations for disallowed `uv.toml` fields
  crates/uv-settings/src/lib.rs
  crates/uv-settings/src/settings.rs
Labels: error messages, breaking

#14567 Isolate `install_git_public_rate_limited...` test from `UV_HTTP_RETRIES`
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/pip_install.rs
Labels: internal

#14565 Increase the number of retries during test runs in CI
  .github/workflows/ci.yml
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/network.rs
Labels: internal

#14605 Add test case for `uv tool` Python re-resolves
  crates/uv/tests/it/tool_run.rs
Labels: testing

#14606 Do not re-resolve with a new Python version in `uv tool` if it is incompatible with `--python`
  crates/uv/src/commands/tool/common.rs
  crates/uv/tests/it/tool_run.rs
Labels: bug

#14582 Add an exception handler on Windows
  Cargo.lock
  Cargo.toml
  crates/uv/Cargo.toml
  crates/uv/src/lib.rs
  crates/uv/src/windows_exception.rs
Labels: windows

#14620 Allow users to override index `cache-control` headers
  crates/uv-client/src/cached_client.rs
  crates/uv-client/src/error.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution-types/src/index.rs
  crates/uv-distribution-types/src/index_url.rs
  crates/uv/tests/it/show_settings.rs
  docs/concepts/indexes.md
  uv.schema.json
Labels: configuration, network

#14636 Skip Windows Python interpreters that return a broken MSIX package code
  crates/uv-python/src/discovery.rs
  crates/uv-python/src/interpreter.rs
Labels: bug, windows

#14633 Move "Conflicting dependencies" to the "Resolution" page
  docs/concepts/projects/config.md
  docs/concepts/resolution.md
Labels: documentation

#14656 Display `sys.executable` names in check system jobs
  scripts/check_system_python.py
Labels: testing

#14658 Fix doctests
  crates/uv-pep508/src/lib.rs
  crates/uv-requirements-txt/src/shquote.rs
Labels: internal

#14661 `uv init`: Make `uv_build` the default build backend (from `hatchling`)
  crates/uv-build-backend/src/metadata.rs
  crates/uv/src/commands/project/init.rs
  crates/uv/tests/it/build.rs
  crates/uv/tests/it/build_backend.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/init.rs
  docs/concepts/build-backend.md
Labels: enhancement, breaking

#14413 Build `path` sources without build systems by default
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-workspace/src/pyproject.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/sync.rs
  docs/concepts/projects/config.md
  docs/concepts/projects/dependencies.md
Labels: enhancement, breaking

#14677 Fix typo in #14619
  crates/uv/src/windows_exception.rs
Labels: windows

#14369 Add UV_COMPILE_BYTECODE_TIMEOUT environment variable
  crates/uv-installer/src/compile.rs
  crates/uv-static/src/env_vars.rs
  docs/reference/environment.md
Labels: configuration

#14685 Bump version to 0.7.22
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/concepts/build-backend.md
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#14662 Add support for toggling Python bin and registry install options via env vars
  crates/uv-cli/src/lib.rs
  crates/uv-settings/src/lib.rs
  crates/uv-static/src/env_vars.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/help.rs
  crates/uv/tests/it/python_install.rs
  docs/reference/cli.md
  docs/reference/environment.md
Labels: configuration, preview

#14690 Add release notes and bump version for 0.8.0
  CHANGELOG.md
  Cargo.lock
  crates/uv-build-backend/src/lib.rs
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/concepts/build-backend.md
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  scripts/packages/built-by-uv/pyproject.toml
Labels: no-build, no-test

#14696 CHANGELOG: manylinux_2_28 is more like 2019
  CHANGELOG.md
Labels: no-build, no-test

#14697 Bump version to 0.8.0
  pyproject.toml
Labels: no-build, no-test

#14712 Add a reusable path-or-URL parser
  crates/uv-distribution-types/src/index_url.rs
  crates/uv-pep508/src/verbatim_url.rs
Labels: internal

#14733 Fix tests requiring patch-level Python
  crates/uv/tests/it/sync.rs
Labels: testing, codex

#14756 Fix comment on `extra_names`
  crates/uv-configuration/src/extras.rs
Labels: internal

#14753 Support `extras` and `dependency_groups` markers in PEP 508 grammar
  crates/uv-pep508/src/marker/algebra.rs
  crates/uv-pep508/src/marker/lowering.rs
  crates/uv-pep508/src/marker/parse.rs
  crates/uv-pep508/src/marker/simplify.rs
  crates/uv-pep508/src/marker/tree.rs
  crates/uv-resolver/src/marker.rs
  crates/uv-resolver/src/resolution/output.rs
Labels: compatibility

#14757 Move dependency group normalization into specification
  crates/uv-normalize/src/group_name.rs
  crates/uv-requirements/src/specification.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/lib.rs
Labels: internal

#14763 Add missing `the` in concept link
  docs/getting-started/features.md
Labels: codex

#14762 Fix kebab casing of README variants in build backend
  crates/uv-build-backend/src/metadata.rs
Labels: bug

#14765 Implement `PartialEq` for `OptionSet`
  crates/uv-options-metadata/src/lib.rs
Labels: internal

#14703 Retry request on invalid data error
  crates/uv-client/src/base_client.rs
Labels: bug

#14779 Use sha256 checksum from GitHub API for GraalPy releases
  crates/uv-python/fetch-download-metadata.py
Labels: internal

#14782 Collect contains markers in enum
  crates/uv-pep508/src/marker/parse.rs
  crates/uv-pep508/src/marker/tree.rs
Labels: internal

#14571 Update `toml` to v0.9
  Cargo.lock
  Cargo.toml
  crates/uv-build-frontend/src/lib.rs
  crates/uv-distribution/src/metadata/requires_dist.rs
  crates/uv-pypi-types/src/metadata/pyproject_toml.rs
  crates/uv-workspace/src/pyproject.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/show_settings.rs
  crates/uv/tests/it/venv.rs
Labels: internal

#14764 Create (e.g.) `python3.13t` executables in `uv venv`
  crates/uv-virtualenv/src/virtualenv.rs
  crates/uv/tests/it/python_install.rs
Labels: compatibility

#14801 Error on unknown fields in `dependency-metadata`
  crates/uv-distribution-types/src/dependency_metadata.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/sync.rs
  uv.schema.json
Labels: error messages

#12259 Disallow writing symlinks outside the source distribution target directory
  Cargo.lock
  Cargo.toml
  crates/uv-extract/src/stream.rs
  crates/uv/tests/it/build.rs
Labels: compatibility

#14812 Allow removal of virtual environments with missing interpreters
  crates/uv/src/commands/project/mod.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#14824 Add derivation chains for dependency errors
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/urls.rs
  crates/uv/src/commands/diagnostics.rs
  crates/uv/tests/it/branching_urls.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
Labels: error messages

#14831 Preserve index URL priority order when writing to pyproject.toml
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#14830 Avoid reading files in the environment bin that are not entrypoints
  crates/uv/src/commands/project/run.rs
Labels: bug

#14816 expose `tls_built_in_root_certs` from reqwest client
  crates/uv-client/src/base_client.rs
  crates/uv-client/src/registry_client.rs
Labels: rustlib

#14854 Use `cache_index_credentials` in `uv venv`
  crates/uv/src/commands/venv.rs
Labels: internal

#14855 Avoid writing redacted credentials to tool receipt
  crates/uv-distribution-types/src/index_url.rs
  crates/uv-redacted/src/lib.rs
  crates/uv/tests/it/tool_install.rs
Labels: bug

#14863 Respect `--with` versions over base environment versions
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/it/run.rs
Labels: bug

#14867 uv_build: Allow non-standard entrypoint names
  crates/uv-build-backend/src/metadata.rs
Labels: enhancement, build-backend

#14864 Consolidate environment hash filtering
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/python_find.rs
  crates/uv/tests/it/run.rs
  crates/uv/tests/it/sync.rs
Labels: testing

#14879 Add test cases for dependent conflicting extras
  crates/uv/tests/it/lock_conflict.rs
Labels: testing

#14880 Remove redundant `let Some`
  crates/uv-resolver/src/resolver/mod.rs
Labels: internal

#14881 Fix snapshot for GitHub message
  crates/uv/tests/it/pip_install.rs
Labels: internal

#14887 Remove prioritized dist duplication
  crates/uv-distribution-types/src/prioritized_distribution.rs
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/resolver/mod.rs
Labels: internal

#14823 Split preview mode into separate feature flags
  Cargo.lock
  crates/uv-bench/benches/uv.rs
  crates/uv-build-frontend/src/lib.rs
  crates/uv-cli/src/lib.rs
  crates/uv-configuration/Cargo.toml
  crates/uv-configuration/src/preview.rs
  crates/uv-dev/src/compile.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-python/src/discovery.rs
  crates/uv-python/src/environment.rs
  crates/uv-python/src/installation.rs
  crates/uv-python/src/lib.rs
  crates/uv-python/src/managed.rs
  crates/uv-static/src/env_vars.rs
  crates/uv-tool/src/lib.rs
  crates/uv-virtualenv/src/lib.rs
  crates/uv-virtualenv/src/virtualenv.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/pip/check.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/freeze.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/list.rs
  crates/uv/src/commands/pip/show.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/pip/tree.rs
  crates/uv/src/commands/pip/uninstall.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/init.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/commands/project/version.rs
  crates/uv/src/commands/python/find.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/src/commands/python/list.rs
  crates/uv/src/commands/python/pin.rs
  crates/uv/src/commands/python/uninstall.rs
  crates/uv/src/commands/tool/common.rs
  crates/uv/src/commands/tool/dir.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/commands/tool/upgrade.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/python_install.rs
  crates/uv/tests/it/show_settings.rs
  docs/reference/environment.md
Labels: configuration, preview

#14905 Update validation for `enviroments` and `required-environments` in `uv.toml`
  crates/uv-settings/src/lib.rs
  crates/uv/tests/it/pip_compile.rs
Labels: bug

#14912 Remove resolved TODO in `allowed_indexes`
  crates/uv-distribution-types/src/index_url.rs
Labels: internal

#14326 Cache Python downloads by default in `python install` tests
  crates/uv-cache/src/lib.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/python_install.rs
Labels: testing

#14938 Clarify messaging when a new resolution needs to be performed
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/sync.rs
Labels: tracing

#14964 Add `UV_` prefix to installer environment variables
  .github/workflows/release.yml
  crates/uv-static/src/env_vars.rs
  dist-workspace.toml
  docs/getting-started/installation.md
  docs/reference/environment.md
  docs/reference/installer.md
Labels: documentation

#14968 Show uv_build in projects documentation
  docs/concepts/projects/init.md
  docs/concepts/projects/workspaces.md
  pyproject.toml
Labels: documentation

#14976 Perform wheel lockfile filtering based on platform and OS intersection
  crates/uv-platform-tags/src/platform_tag.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/it/lock.rs
Labels: enhancement

#14978 Implement `CacheKey` for all `Pep508Url` variants
  Cargo.lock
  crates/uv-pep508/src/lib.rs
  crates/uv-pep508/src/verbatim_url.rs
  crates/uv-pypi-types/Cargo.toml
  crates/uv-pypi-types/src/parsed_url.rs
Labels: internal

#14970 Copy entrypoints that have a shebang that differs in `python` vs `python3`
  crates/uv/src/commands/project/run.rs
Labels: bug

#14987 Improve visibility of copy and line separator in dark mode
  docs/stylesheets/extra.css
Labels: documentation

#14933 Fix symlink preservation in virtual environment creation
  crates/uv-virtualenv/src/virtualenv.rs
  crates/uv/tests/it/venv.rs
Labels: bug

#14972 Skip`cargo dev generate-all` test case in CI
  crates/uv-dev/src/generate_options_reference.rs
Labels: internal

#14458 Log the debug error trace
  crates/uv-dev/src/main.rs
  crates/uv/src/commands/publish.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/src/commands/tool/upgrade.rs
  crates/uv/src/lib.rs
Labels: internal

#14996 Remove retry wrapper when matching on error kind
  crates/uv-client/src/cached_client.rs
  crates/uv-client/src/error.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-publish/src/lib.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv/src/commands/pip/latest.rs
Labels: bug
