Repository astral-sh/uv, pull requests merged in 2025-02, with the labels that each got.

#11142 Don't expand self-referential extras in the build backend
  crates/uv-build-backend/src/metadata.rs
Labels: bug, preview

#11155 Set `UV_PYTHON` in Jupyter kernels
  docs/guides/integration/jupyter.md
Labels: documentation

#11158 Optimize exclusion computation for markers
  crates/uv-pep508/src/marker/algebra.rs
Labels: performance

#11166 uv-install-wheel: Split installation logic and link logic
  crates/uv-bench/benches/uv.rs
  crates/uv-cli/src/lib.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-install-wheel/src/install.rs
  crates/uv-install-wheel/src/lib.rs
  crates/uv-install-wheel/src/linker.rs
  crates/uv-installer/src/installer.rs
  crates/uv-settings/src/combine.rs
  crates/uv-settings/src/settings.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/settings.rs
Labels: internal

#11177 Fix relative paths in bytecode compilation
  crates/uv-installer/src/compile.rs
  crates/uv/src/commands/mod.rs
Labels: bug

#11169 Update pubgrub to set-based outdated priority tracking
  Cargo.lock
  Cargo.toml
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/tests/it/pip_install_scenarios.rs
Labels: enhancement, performance

#11015 Use dev drive for trampoline CI to avoid timeout
  .github/workflows/ci.yml
Labels: internal

#11174 Use Astral-maintained `tokio-tar` fork
  Cargo.lock
  Cargo.toml
  crates/uv-extract/Cargo.toml
  crates/uv-extract/src/lib.rs
  crates/uv-extract/src/stream.rs
  crates/uv-extract/src/tar.rs
  crates/uv-publish/Cargo.toml
Labels: performance, security

#11191 Avoid setting permissions during tar extraction
  Cargo.lock
  Cargo.toml
  crates/uv-extract/src/stream.rs
Labels: bug, compatibility

#11194 Add best-practice flags to `pip install` example in troubleshooting guide
  docs/reference/troubleshooting/build-failures.md
Labels: documentation

#11196 Use wire JSON schema for conflict items
  crates/uv-pypi-types/src/conflicts.rs
  uv.schema.json
Labels: bug

#11195 Remove warnings for missing lower bounds
  Cargo.lock
  crates/uv-bench/benches/uv.rs
  crates/uv-build-frontend/src/lib.rs
  crates/uv-configuration/src/bounds.rs
  crates/uv-configuration/src/lib.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/Cargo.toml
  crates/uv-distribution/src/metadata/build_requires.rs
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-distribution/src/metadata/mod.rs
  crates/uv-distribution/src/metadata/requires_dist.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-types/src/traits.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/lock_target.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/commands/venv.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/sync.rs
Labels: cli

#11193 Improve error messages for `uv pip install` with `--extra` or `--all-extras` and invalid sources
  crates/uv/src/commands/pip/operations.rs
  crates/uv/tests/it/pip_install.rs
Labels: error messages

#11200 add instructions for deactivating an environment
  docs/pip/environments.md
Labels: documentation

#11211 Fix typo "dependency-group" in error message and comments
  crates/uv-configuration/src/dev.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/sync.rs
Labels: documentation

#11212 Move wheel helper function to wheel module
  crates/uv-install-wheel/src/install.rs
  crates/uv-install-wheel/src/wheel.rs
Labels: internal

#11098 Update resolver internals docs
  docs/reference/resolver-internals.md
Labels: documentation

#11210 Disable SSL in Git commands for `--allow-insecure-host`
  crates/uv-client/src/base_client.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-git/src/git.rs
  crates/uv-git/src/resolver.rs
  crates/uv-git/src/source.rs
  crates/uv-static/src/env_vars.rs
Labels: bug

#11218 Allow discovering virtual environments from the first interpreter found on the `PATH`
  crates/uv-python/src/discovery.rs
  crates/uv-python/src/lib.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/python_find.rs
Labels: bug

#11208 Use base Python for cached environments
  crates/uv-python/src/interpreter.rs
  crates/uv-python/src/lib.rs
  crates/uv-virtualenv/Cargo.toml
  crates/uv-virtualenv/src/virtualenv.rs
  crates/uv/src/commands/project/environment.rs
  crates/uv/tests/it/run.rs
Labels: bug

#11209 Set base executable when returning virtual environment
  crates/uv-python/src/interpreter.rs
  crates/uv-python/src/virtualenv.rs
  crates/uv-virtualenv/src/virtualenv.rs
Labels: bug

#11141 Clear ephemeral overlays when running tools
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/it/run.rs
Labels: bug

#11228 Bump version to v0.5.28
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#11229 Disable wheel testing for `powerpc64le-unknown-linux-gnu`
  .github/workflows/build-binaries.yml
Labels: testing

#11192 Add `--bare` option to `uv init`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/project/init.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/init.rs
  docs/concepts/projects/init.md
  docs/reference/cli.md
Labels: cli

#11246 Move content from the `mkdocs.public.yml` into the template
  .github/workflows/ci.yml
  docs/requirements-insiders.txt
  mkdocs.public.yml
  mkdocs.template.yml
Labels: bug, documentation

#11252 Minor touchups to the Docker provenance docs
  docs/guides/integration/docker.md
Labels: documentation

#11251 Allow the project `VIRTUAL_ENV` warning to be silenced with `--no-active`
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/run.rs
  docs/concepts/projects/config.md
Labels: cli

#11259 Use a flock to avoid concurrent initialization of project environments
  crates/uv/src/commands/project/mod.rs
Labels: bug

#11224 fix handling of `--all-groups` and `--no-default-groups` flags
  crates/uv-cli/src/lib.rs
  crates/uv-configuration/src/dev.rs
  crates/uv-requirements/src/source_tree.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/run.rs
  crates/uv/tests/it/show_settings.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#11260 Migrate to published `astral-tokio-tar` crate
  Cargo.lock
  Cargo.toml
  crates/uv-extract/src/stream.rs
Labels: dependencies

#11264 Avoid using `user_display` for workspace locks
  crates/uv/src/commands/project/mod.rs
Labels: internal

#11265 Allow opt-in to `.python-version` in `uv init` with `--pin-python`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/project/init.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/init.rs
  docs/concepts/projects/init.md
Labels: cli

#11255 Misc. improvements to the documentation
  README.md
  docs/getting-started/features.md
  docs/guides/index.md
  docs/guides/integration/alternative-indexes.md
  docs/guides/package.md
  docs/guides/projects.md
  docs/index.md
  mkdocs.template.yml
Labels: documentation

#11165 Show messages for slow tasks in non-interactive mode
  crates/uv-git/src/source.rs
  crates/uv-static/src/env_vars.rs
  crates/uv/src/commands/reporters.rs
  crates/uv/tests/it/common/mod.rs
Labels: enhancement

#11268 Update 3.12.8 references in Windows Python tests
  crates/uv/tests/it/python_install.rs
Labels: testing, windows

#11267 Bump version to 0.5.29
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#11270 Use consistent 'Registry' prefix for wheel and source distribution logs
  crates/uv-installer/src/plan.rs
Labels: tracing

#11271 add pip install setuptools in flash-attn docs
  docs/concepts/projects/config.md
Labels: documentation

#11286 Add Discord to PyPI project URLs
  pyproject.toml
Labels: documentation

#11299 Add `uv sync --dry-run`
  crates/uv-cli/src/lib.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/sync.rs
  docs/reference/cli.md
Labels: enhancement, cli

#11301 Use an iterator for logging upgrade events
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#11303 Use a `DryRun` enum everywhere
  crates/uv-configuration/src/dry_run.rs
  crates/uv-configuration/src/lib.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/pip/uninstall.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/show_settings.rs
Labels: internal

#11311 Un-nest `satisfies_requires_dist`
  crates/uv-resolver/src/lock/mod.rs
Labels: internal

#11284 cleanup some dependency-group docs
  crates/uv-cli/src/lib.rs
  docs/concepts/projects/dependencies.md
  docs/reference/cli.md
Labels: documentation

#11292 uv-python tests: Use #!/bin/sh instead of #!/bin/bash
  crates/uv-python/src/interpreter.rs
  crates/uv-python/src/lib.rs
Labels: testing

#11320 Typo in `release_specifiers_to_ranges` docs
  crates/uv-pep440/src/version_ranges.rs
Labels: internal

#11327 Correct environment variable expansion in rustdoc
  crates/uv-pep508/src/verbatim_url.rs
Labels: documentation

#11332 Add tests for `uv add` with and without trailing slash
  crates/uv/tests/it/edit.rs
Labels: testing

#11328 Set 777 permissions on locked files
  crates/uv-fs/src/lib.rs
Labels: bug

#11313 Optimize flattening in apache airflow workspace
  crates/uv-distribution/src/metadata/build_requires.rs
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-distribution/src/metadata/requires_dist.rs
  crates/uv-pep508/src/marker/tree.rs
Labels: performance

#11331 Add note about available versions
  crates/uv-cli/src/lib.rs
  crates/uv/tests/it/help.rs
  docs/concepts/python-versions.md
  docs/reference/cli.md
Labels: documentation

#11306 Include archive bucket version in archive pointers
  crates/uv-cache/src/lib.rs
  crates/uv-distribution/src/archive.rs
  crates/uv-distribution/src/index/cached_wheel.rs
  crates/uv/tests/it/cache_prune.rs
Labels: bug

#11334 Use refined specifiers when logging narrowed Python range
  crates/uv-resolver/src/requires_python.rs
Labels: bug, tracing

#11280 Add docs for `uv tool install --editable`
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: documentation

#11269 Use files instead of junctions on Windows
  Cargo.lock
  crates/uv-cache/Cargo.toml
  crates/uv-cache/src/archive.rs
  crates/uv-cache/src/lib.rs
  crates/uv-distribution-filename/src/wheel.rs
  crates/uv-distribution/src/archive.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/index/built_wheel_index.rs
  crates/uv-distribution/src/index/cached_wheel.rs
  crates/uv-distribution/src/index/registry_wheel_index.rs
  crates/uv-fs/src/lib.rs
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/commands/python/uninstall.rs
  crates/uv/tests/it/cache_prune.rs
Labels: windows, no-build

#11335 Support extras in `@` requests for tools
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/mod.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/it/tool_run.rs
Labels: bug

#11333 Respect `no-build` label in Docker image builds
  .github/workflows/build-docker.yml
Labels: internal

#11340 Ignore 'egg' fragment in HTML Simple API response
  crates/uv-client/src/html.rs
Labels: compatibility

#11338 Fix broken anchors in readme and docs index
  README.md
  docs/index.md
Labels: documentation

#11336 Fix credential caching for index roots when URL ends in `simple/`
  crates/uv-distribution-types/src/index.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#11346 Allow sync and update environment methods to take modifications
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/upgrade.rs
Labels: internal

#11359 Upgrade `astral-tokio-tar` to v0.5.1
  Cargo.lock
  Cargo.toml
Labels: bug

#11362 Avoid empty trailing colon for empty requirements
  crates/uv/src/commands/project/mod.rs
Labels: tracing

#11395 Avoid reading metadata from `.egg-info` files
  crates/uv-distribution/src/error.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-install-wheel/src/install.rs
  crates/uv-pypi-types/src/metadata/metadata10.rs
  crates/uv-pypi-types/src/metadata/metadata12.rs
  crates/uv-pypi-types/src/metadata/mod.rs
  crates/uv/tests/it/pip_compile.rs
Labels: bug

#11400 Allow dynamic packages to be overloaded
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_version_dynamic.snap
  crates/uv/tests/it/lock.rs
Labels: bug

#11401 Avoid re-cloning name when populating ambiguous set
  crates/uv-resolver/src/lock/mod.rs
Labels: performance

#11403 Disable pip cache in Windows system test job
  .github/workflows/ci.yml
Labels: internal

#11380 Fix windows installation instructions mismatch
  docs/index.md
Labels: documentation

#11399 Add `NO_BINARY` and `NO_BINARY_PACKAGE` environment variables
  crates/uv-cli/src/lib.rs
  crates/uv-static/src/env_vars.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/sync.rs
  docs/configuration/environment.md
  docs/reference/cli.md
Labels: configuration

#11405 Bump version to v0.5.30
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: no-build, releases

#11396 Catch broken `mac_ver()`
  crates/uv-python/python/get_interpreter_info.py
  crates/uv-python/src/interpreter.rs
Labels: error messages

#11410 Capture intermediary snapshots in `sync_dry_run`
  crates/uv/tests/it/sync.rs
Labels: testing

#11415 Mark `sync::sync_dry_run` test as requiring `python-managed`
  crates/uv/tests/it/sync.rs
Labels: internal

#11429 Allow source distributions to produce wheels with +local suffixes
  crates/uv-distribution/src/source/mod.rs
  crates/uv-installer/src/preparer.rs
Labels: compatibility

#11427 Avoid comparing to system site packages in `--dry-run` mode
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
Labels: bug

#11337 Allow PEP 508 requirements in tool requests
  crates/uv/src/commands/tool/mod.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/it/tool_run.rs
Labels: enhancement, cli

#11345 Bring parity to `uvx` and `uv tool install` requests
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/mod.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/it/tool_install.rs
  crates/uv/tests/it/tool_run.rs
Labels: enhancement

#11421 retry local clones without hardlinks if they fail
  crates/uv-git/src/git.rs
Labels: bug

#11347 Use a stable directory for (local) script virtual environments
  crates/uv-cache/src/lib.rs
  crates/uv-resolver/src/redirect.rs
  crates/uv-scripts/src/lib.rs
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/it/run.rs
Labels: enhancement

#11364 Use stable environments for remote and stdin scripts
  Cargo.lock
  crates/uv-python/src/environment.rs
  crates/uv-scripts/Cargo.toml
  crates/uv-scripts/src/lib.rs
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/lib.rs
Labels: enhancement, no-build

#11449 Optional schemars dependency
  crates/uv-pypi-types/Cargo.toml
  crates/uv-pypi-types/src/conflicts.rs
  crates/uv-workspace/Cargo.toml
Labels: internal

#11431 Prefer running executables in the environment with `<name>` over `<name>/__main__.py`
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/it/run.rs
Labels: bug

#11290 Allow `--python <dir>` requests to match existing environments if `sys.executable` is the same file
  crates/uv-python/src/discovery.rs
Labels: bug

#11459 Bump version to 0.5.31
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#11465 Respect executable name in `uvx --from tool@latest`
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/it/tool_run.rs
Labels: bug

#11468 Omit lockfile version when additional fields are dynamic
  crates/uv-distribution/src/source/mod.rs
  crates/uv-pypi-types/src/metadata/metadata_resolver.rs
  crates/uv-pypi-types/src/metadata/mod.rs
  crates/uv-pypi-types/src/metadata/pyproject_toml.rs
  crates/uv-pypi-types/src/metadata/requires_dist.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#11481 Fix isolation of recursion test
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/pip_compile_scenarios.rs
  crates/uv/tests/it/pip_install_scenarios.rs
  crates/uv/tests/it/run.rs
Labels: testing

#11433 Support `--active` for PEP 723 script environments
  Cargo.lock
  crates/uv-cli/src/lib.rs
  crates/uv-fs/Cargo.toml
  crates/uv-fs/src/lib.rs
  crates/uv-workspace/Cargo.toml
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/tests/it/run.rs
  crates/uv/tests/it/sync.rs
  docs/reference/cli.md
Labels: enhancement, no-build

#11499 Validate dependency groups even when `--frozen` is present
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/install_target.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/tests/it/export.rs
  crates/uv/tests/it/sync.rs
Labels: enhancement

#11500 Use a 'minor' version field (`revision`) in the lockfile
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_optional_missing.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_optional_present.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_required_present.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_source_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_source_version_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_version_dynamic.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_version_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_direct_has_subdir.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_direct_no_subdir.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_directory.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_editable.snap
  crates/uv/src/commands/project/install_target.rs
  crates/uv/tests/it/branching_urls.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/export.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/lock_conflict.rs
  crates/uv/tests/it/lock_scenarios.rs
  crates/uv/tests/it/run.rs
  crates/uv/tests/it/snapshots/it__ecosystem__black-lock-file.snap
  crates/uv/tests/it/snapshots/it__ecosystem__github-wikidata-bot-lock-file.snap
  crates/uv/tests/it/snapshots/it__ecosystem__home-assistant-core-lock-file.snap
  crates/uv/tests/it/snapshots/it__ecosystem__packse-lock-file.snap
  crates/uv/tests/it/snapshots/it__ecosystem__saleor-lock-file.snap
  crates/uv/tests/it/snapshots/it__ecosystem__transformers-lock-file.snap
  crates/uv/tests/it/snapshots/it__ecosystem__warehouse-lock-file.snap
  crates/uv/tests/it/snapshots/it__workflow__jax_instability-2.snap
  crates/uv/tests/it/snapshots/it__workflow__packse_add_remove_existing_package_noop-2.snap
  crates/uv/tests/it/snapshots/it__workflow__packse_add_remove_one_package-2.snap
  crates/uv/tests/it/snapshots/it__workflow__packse_promote_transitive_to_direct_then_remove-2.snap
  crates/uv/tests/it/sync.rs
  crates/uv/tests/it/tree.rs
  crates/uv/tests/it/workflow.rs
  crates/uv/tests/it/workspace.rs
Labels: resolver

#11496 Bump version to v0.6.0
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
  scripts/packages/built-by-uv/pyproject.toml
Labels: no-build, releases, no-test

#11510 Split changelog into separate files
  CHANGELOG.md
  changelogs/0.1.x.md
  changelogs/0.2.x.md
  changelogs/0.3.x.md
  changelogs/0.4.x.md
  changelogs/0.5.x.md
Labels: documentation

#11517 Add tiny change to changelog
  CHANGELOG.md
Labels: internal

#11524 Respect verbatim executable name in uvx
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/it/tool_run.rs
Labels: bug

#11519 Note that main.py used to be hello.py
  docs/concepts/projects/init.md
Labels: documentation

#11535 Add `--all` to `uvx --reinstall` message
  crates/uv/src/settings.rs
Labels: bug, error messages

#11543 Remove redundant index from preference key
  crates/uv-resolver/src/candidate_selector.rs
Labels: internal

#11546 Prefer local variants in preference selection
  crates/uv-resolver/src/candidate_selector.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
Labels: bug

#11539 Fallback to `GET` on HTTP 400 when attempting to use range requests for wheel download
  crates/uv-client/src/error.rs
Labels: bug, network

#11562 Remove clone from marker evaluation
  crates/uv-resolver/src/graph_ops.rs
  crates/uv-resolver/src/universal_marker.rs
Labels: internal

#11571 Accept iterator in universal marker evaluation
  crates/uv-resolver/src/lock/installable.rs
  crates/uv-resolver/src/universal_marker.rs
Labels: internal

#11448 Split uv-git and uv-git-types
  Cargo.lock
  Cargo.toml
  crates/uv-distribution-types/Cargo.toml
  crates/uv-distribution-types/src/buildable.rs
  crates/uv-distribution-types/src/lib.rs
  crates/uv-distribution/Cargo.toml
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-git-types/Cargo.toml
  crates/uv-git-types/src/github.rs
  crates/uv-git-types/src/lib.rs
  crates/uv-git-types/src/oid.rs
  crates/uv-git-types/src/reference.rs
  crates/uv-git/Cargo.toml
  crates/uv-git/src/git.rs
  crates/uv-git/src/lib.rs
  crates/uv-git/src/resolver.rs
  crates/uv-git/src/source.rs
  crates/uv-installer/Cargo.toml
  crates/uv-installer/src/satisfies.rs
  crates/uv-pypi-types/Cargo.toml
  crates/uv-pypi-types/src/parsed_url.rs
  crates/uv-pypi-types/src/requirement.rs
  crates/uv-requirements/Cargo.toml
  crates/uv-requirements/src/lib.rs
  crates/uv-resolver/Cargo.toml
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/requirements_txt.rs
  crates/uv-workspace/Cargo.toml
  crates/uv-workspace/src/pyproject.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/project/add.rs
Labels: internal

#11572 Make fetch python downloads deterministic
  crates/uv-python/download-metadata.json
  crates/uv-python/fetch-download-metadata.py
  crates/uv-python/src/downloads.inc
Labels: internal

#11394 Warn for builds in non-build and workspace root pyproject.toml
  Cargo.lock
  crates/uv-build-frontend/Cargo.toml
  crates/uv-build-frontend/src/lib.rs
  crates/uv/tests/it/build.rs
  crates/uv/tests/it/pip_install.rs
Labels: error messages

#11578 Fix macro typo
  crates/uv/src/lib.rs
Labels: internal

#11542 Add documentation for required environments
  docs/concepts/projects/config.md
  docs/concepts/resolution.md
Labels: documentation

#11580 Bump version to 0.6.1
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#11585 Add `tool.uv.build-constraint-dependencies` to `pyproject.toml`
  crates/uv-scripts/src/lib.rs
  crates/uv-settings/src/settings.rs
  crates/uv-workspace/src/pyproject.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/lock_target.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/show_settings.rs
  docs/pip/compile.md
  docs/reference/settings.md
  docs/reference/troubleshooting/build-failures.md
  uv.schema.json
Labels: enhancement

#11514 Eagerly reject unsupported Git schemes
  Cargo.lock
  crates/uv-distribution-types/src/lib.rs
  crates/uv-distribution-types/src/resolution.rs
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-git-types/src/lib.rs
  crates/uv-installer/src/satisfies.rs
  crates/uv-pypi-types/src/parsed_url.rs
  crates/uv-pypi-types/src/requirement.rs
  crates/uv-requirements/Cargo.toml
  crates/uv-requirements/src/lib.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/requirements_txt.rs
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-workspace/src/pyproject.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/sync.rs
Labels: error messages, no-build

#11586 Use an `Arc` for Index URLs
  crates/uv-distribution-types/src/index_url.rs
Labels: performance

#11590 Revert "Temporarily disable cloudsmith test"
  scripts/publish/test_publish.py
Labels: internal

#11589 Set `COLUMNS` during tests
  crates/uv-static/src/env_vars.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/tool_run.rs
  docs/configuration/environment.md
Labels: internal

#11478 More consistent `build-binaries.yml`
  .github/workflows/build-binaries.yml
Labels: internal

#11579 Move `clone_recursive` documentation
  clippy.toml
  crates/uv-install-wheel/src/linker.rs
Labels: internal

#11604 respect color settings for log messages
  crates/uv/src/logging.rs
Labels: bug, tracing

#11616 Regenerate env var docs
  docs/configuration/environment.md
Labels: documentation

#11625 Allow use of x86-64 Python on ARM Windows
  crates/uv-python/src/downloads.rs
  crates/uv-python/src/managed.rs
  crates/uv-python/src/platform.rs
Labels: bug

#11626 Add emulated test for x86-64 Python on aarch64 Windows
  .github/workflows/ci.yml
Labels: testing

#11630 Bump version to 0.6.2
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#11660 Reduce overhead in converting resolutions
  crates/uv-distribution-types/src/dist_error.rs
  crates/uv-distribution-types/src/resolution.rs
  crates/uv-distribution-types/src/resolved.rs
  crates/uv-installer/src/plan.rs
  crates/uv-installer/src/preparer.rs
  crates/uv-resolver/src/lock/installable.rs
  crates/uv-resolver/src/resolution/mod.rs
  crates/uv-resolver/src/resolution/output.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/src/commands/project/sync.rs
Labels: performance

#11644 Allow quotes around command-line options in `requirement.txt files`
  Cargo.lock
  Cargo.toml
  crates/uv-requirements-txt/Cargo.toml
  crates/uv-requirements-txt/src/lib.rs
  crates/uv/tests/it/pip_install.rs
Labels: compatibility, no-build

#11669 Fix missing a closing bracket in the cache-keys setting
  crates/uv-settings/src/settings.rs
  docs/reference/settings.md
Labels: documentation

#11653 Avoid installing duplicate dependencies across conflicting groups
  crates/uv-resolver/src/lock/installable.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#11633 Skip removed directories during bytecode compilation
  crates/uv-installer/src/compile.rs
Labels: bug

#11643 Support conflict markers in `uv export`
  crates/uv-resolver/src/graph_ops.rs
  crates/uv-resolver/src/lock/requirements_txt.rs
  crates/uv-resolver/src/universal_marker.rs
  crates/uv/tests/it/export.rs
Labels: bug

#11680 Reuse refined interpreter to create tool environment
  crates/uv/src/commands/tool/install.rs
Labels: bug

#11681 Include uppercase platforms for Windows wheels
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#11618 Run uv-dev tests
  crates/uv-dev/Cargo.toml
  crates/uv-dev/src/lib.rs
  crates/uv-dev/src/main.rs
Labels: internal

#11412 Remove in-memory locks from distribution database
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/lib.rs
  crates/uv-distribution/src/locks.rs
  crates/uv-requirements/src/source_tree.rs
Labels: internal

#11687 Re-allow HTTP schemes for Git dependencies
  crates/uv-git-types/src/lib.rs
Labels: compatibility

#11665 Accept multiple `.env` files in `UV_ENV_FILE`
  crates/uv-cli/src/lib.rs
  crates/uv/tests/it/run.rs
Labels: bug, configuration

#11705 Update credential message in snapshot
  crates/uv/tests/it/pip_install.rs
Labels: testing

#11702 Treat lockfile as outdated if (empty) extras are added
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/src/commands/project/install_target.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#11713 Remove unused `thiserror` variants
  Cargo.lock
  Cargo.toml
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-frontend/src/error.rs
  crates/uv-distribution/src/error.rs
  crates/uv-extract/src/error.rs
  crates/uv-install-wheel/Cargo.toml
  crates/uv-install-wheel/src/lib.rs
  crates/uv-tool/src/lib.rs
  crates/uv-virtualenv/Cargo.toml
  crates/uv-virtualenv/src/lib.rs
Labels: internal

#11716 Respect existing PEP 723 script settings in `uv add`
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/lib.rs
  crates/uv/tests/it/edit.rs
Labels: bug

#11719 Check subdirectory existence after cache heal
  crates/uv-distribution/src/source/mod.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#11714 Use boxed slices for hash vector
  crates/uv-client/src/flat_index.rs
  crates/uv-distribution-types/src/cached.rs
  crates/uv-distribution-types/src/file.rs
  crates/uv-distribution-types/src/lib.rs
  crates/uv-distribution-types/src/resolution.rs
  crates/uv-distribution/src/archive.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/download.rs
  crates/uv-distribution/src/index/cached_wheel.rs
  crates/uv-distribution/src/metadata/mod.rs
  crates/uv-distribution/src/source/built_wheel_metadata.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-distribution/src/source/revision.rs
  crates/uv-pypi-types/src/simple_json.rs
  crates/uv-resolver/src/flat_index.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/requirements_txt.rs
  crates/uv-resolver/src/preferences.rs
  crates/uv-resolver/src/resolution/mod.rs
  crates/uv-resolver/src/resolution/output.rs
  crates/uv-resolver/src/resolution/requirements_txt.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv-types/src/hash.rs
Labels: performance

#11717 Initialize PEP 723 script in `uv lock --script`
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/lib.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/lock.rs
Labels: enhancement

#11748 Add link to environment marker specification
  docs/concepts/resolution.md
Labels: documentation

#11715 Use a `SmallString` for the Yanked enum
  Cargo.lock
  crates/uv-client/src/html.rs
  crates/uv-pypi-types/Cargo.toml
  crates/uv-pypi-types/src/simple_json.rs
  crates/uv-resolver/src/resolution/output.rs
  crates/uv-small-str/src/lib.rs
Labels: performance

#11755 Use a `Box` for `Yanked` on `File`
  crates/uv-client/src/html.rs
  crates/uv-distribution-types/src/file.rs
  crates/uv-distribution-types/src/resolved.rs
  crates/uv-pypi-types/src/simple_json.rs
  crates/uv-resolver/src/version_map.rs
Labels: performance

#11756 Use `SmallString` on `Hashes`
  crates/uv-extract/src/hash.rs
  crates/uv-publish/src/lib.rs
  crates/uv-pypi-types/src/simple_json.rs
  crates/uv-small-str/src/lib.rs
Labels: performance

#11722 Fix message when there are no buildable packages
  crates/uv/src/commands/build_frontend.rs
  crates/uv/tests/it/build.rs
Labels: error messages

#11754 Add anchor links to arguments and options in the CLI reference
  crates/uv-dev/src/generate_cli_reference.rs
  docs/reference/cli.md
Labels: documentation

#11766 Use a Boxed slice for version specifiers
  crates/uv-pep440/src/version_specifier.rs
Labels: performance

#11772 Avoid cloning to string when creating cache path
  crates/uv-distribution/src/index/registry_wheel_index.rs
Labels: performance

#11770 Use matches over contains for extra value parsing
  crates/uv-pep508/src/marker/parse.rs
Labels: performance

#11769 Remove stale comment on `MarkerEnvironment`
  crates/uv-pep508/src/marker/environment.rs
Labels: internal

#11768 Avoid using owned `String` for package name constructors
  crates/uv-configuration/src/extras.rs
  crates/uv-normalize/src/extra_name.rs
  crates/uv-normalize/src/group_name.rs
  crates/uv-normalize/src/lib.rs
  crates/uv-normalize/src/package_name.rs
  crates/uv-pep508/src/lib.rs
  crates/uv-pypi-types/src/metadata/metadata10.rs
  crates/uv-pypi-types/src/metadata/metadata_resolver.rs
  crates/uv-resolver/src/universal_marker.rs
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv/src/commands/project/init.rs
Labels: performance
