Repository astral-sh/uv, pull requests merged in 2025-06, with the labels that each got.

#13781 Unify `zip` and `async_zip` compression methods
  Cargo.lock
  Cargo.toml
Labels: enhancement

#13779 Remove winsafe
  Cargo.lock
  Cargo.toml
  crates/uv-fs/Cargo.toml
  crates/uv-fs/src/which.rs
Labels: enhancement, windows

#13441 feat: add dynamically generated sysconfig replacement mappings
  .github/workflows/sync-python-releases.yml
  Cargo.lock
  crates/uv-dev/Cargo.toml
  crates/uv-dev/src/generate_all.rs
  crates/uv-dev/src/generate_sysconfig_mappings.rs
  crates/uv-dev/src/lib.rs
  crates/uv-dev/sync_sysconfig_targets.sh
  crates/uv-python/src/sysconfig/generated_mappings.rs
  crates/uv-python/src/sysconfig/mod.rs
  crates/uv-python/src/sysconfig/replacements.rs
Labels: no-build

#13786 Downgrade firecracker action to v0.3
  .github/workflows/ci.yml
Labels: internal

#13804 Update acj/freebsd-firecracker-action to v0.4.1
  .github/workflows/ci.yml
Labels: internal, ci-flake

#13808 Add test case for HTTPS credentials on direct URL in `uv export`
  crates/uv/tests/it/export.rs
Labels: testing

#13810 Add `uv export` test cases for PEP 751 format with credentials
  crates/uv/tests/it/export.rs
Labels: testing

#13799 Don't redact username `git` for SSH
  crates/uv-redacted/src/lib.rs
Labels: bug

#13809 Retain credentials for direct URLs in `uv export`
  crates/uv-resolver/src/lock/export/requirements_txt.rs
  crates/uv/tests/it/export.rs
Labels: bug

#13806 Display ssh git username in `Debug` implementation
  crates/uv-redacted/src/lib.rs
Labels: bug

#13818 Disable OpenSUSE system test for now
  .github/workflows/ci.yml
Labels: internal

#13816 Remove `python-managed` marker from `sync_dry_run` test
  crates/uv/tests/it/sync.rs
Labels: internal

#13787 Use "terminal driver" instead of "shell" in SIGINT docs
  crates/uv/src/commands/run.rs
  docs/concepts/projects/run.md
Labels: documentation

#13814 Test case: Don't redact username `git` for SSH
  Cargo.lock
  crates/uv/Cargo.toml
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/export.rs
Labels: internal

#13835 Downgrade reqwest and hyper-util
  Cargo.lock
  Cargo.toml
Labels: bug

#13844 Bump version to 0.7.11
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/configuration/build-backend.md
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#13857 Make `requirements_txt_ssh_git_username` not write into homedir
  crates/uv/tests/it/export.rs
Labels: internal

#13858 Switch `sync_dry_run` test to Python 3.9
  crates/uv/tests/it/sync.rs
Labels: internal

#13855 List `.gitignore` in project init files
  docs/guides/projects.md
Labels: documentation

#13860 Add `uv python pin --rm` to remove `.python-version` pins
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/python/pin.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/python_pin.rs
  docs/reference/cli.md
Labels: enhancement

#13842 Remove the configuration section in favor of concepts / reference
  .github/workflows/ci.yml
  .prettierignore
  changelogs/0.4.x.md
  crates/uv-dev/src/generate_env_vars_reference.rs
  docs/concepts/authentication.md
  docs/concepts/build-backend.md
  docs/concepts/configuration-files.md
  docs/concepts/index.md
  docs/concepts/indexes.md
  docs/concepts/projects/dependencies.md
  docs/concepts/python-versions.md
  docs/configuration/index.md
  docs/getting-started/installation.md
  docs/guides/integration/alternative-indexes.md
  docs/guides/projects.md
  docs/guides/scripts.md
  docs/pip/compatibility.md
  docs/pip/packages.md
  docs/reference/environment.md
  docs/reference/installer.md
  mkdocs.template.yml
  pyproject.toml
Labels: documentation

#13866 Fix `lock_requires_python` test case
  crates/uv/tests/it/lock.rs
Labels: internal

#13862 Improve `python pin` error messages
  crates/uv/src/commands/python/pin.rs
  crates/uv/tests/it/python_pin.rs
Labels: error messages

#13882 Change `GlobDirFilter` fallback to `true`
  crates/uv-globfilter/src/glob_dir_filter.rs
Labels: enhancement, preview

#13869 Lock during `uv sync`, `uv add` and `uv remove` to avoid race conditions
  crates/uv-python/src/environment.rs
  crates/uv-python/src/interpreter.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/sync.rs
Labels: bug

#13455 Hint at `tool.uv.environments` on resolution error
  crates/uv-bench/benches/uv.rs
  crates/uv-dispatch/src/lib.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/resolver/environment.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/lock_scenarios.rs
  crates/uv/tests/it/pip_compile.rs
Labels: error messages

#13575 Hint at `tool.uv.required-environments`
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/it/sync.rs
  scripts/links/wheel_tag_test-0.1.0-py3-none-win_amd64.whl
Labels: error messages

#13926 Fix use of deprecated `black_box` function
  crates/uv-bench/benches/uv.rs
Labels: internal

#13917 Check if relative URL is valid directory before treating as index
  crates/uv-pep508/src/verbatim_url.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/tests/it/edit.rs
Labels: bug

#13585 Add basic network error tests
  crates/uv/tests/it/main.rs
  crates/uv/tests/it/network.rs
Labels: internal, error messages, network

#13929 Add an `llms.txt` to uv
  docs/requirements-insiders.txt
  docs/requirements.in
  docs/requirements.txt
  mkdocs.template.yml
Labels: documentation

#13944 Ignore Python discovery errors during `uv python pin`
  crates/uv/src/commands/python/pin.rs
Labels: bug

#13946 Download versions in `uv python pin` if not found
  crates/uv/src/commands/python/pin.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/python_pin.rs
Labels: enhancement

#13531 Support transparently upgradeable Python bin installations
  Cargo.lock
  crates/uv-fs/Cargo.toml
  crates/uv-python/src/managed.rs
  crates/uv-python/src/python_version.rs
  crates/uv-trampoline/src/bounce.rs
  crates/uv-trampoline/trampolines/trampolines/uv-trampoline-aarch64-console.exe
  crates/uv-trampoline/trampolines/trampolines/uv-trampoline-aarch64-gui.exe
  crates/uv-trampoline/trampolines/trampolines/uv-trampoline-i686-console.exe
  crates/uv-trampoline/trampolines/trampolines/uv-trampoline-i686-gui.exe
  crates/uv-trampoline/trampolines/trampolines/uv-trampoline-x86_64-console.exe
  crates/uv-trampoline/trampolines/trampolines/uv-trampoline-x86_64-gui.exe
  crates/uv-trampoline/trampolines/uv-trampoline-aarch64-console.exe
  crates/uv-trampoline/trampolines/uv-trampoline-aarch64-gui.exe
  crates/uv-trampoline/trampolines/uv-trampoline-i686-console.exe
  crates/uv-trampoline/trampolines/uv-trampoline-i686-gui.exe
  crates/uv-trampoline/trampolines/uv-trampoline-x86_64-console.exe
  crates/uv-trampoline/trampolines/uv-trampoline-x86_64-gui.exe
  crates/uv/Cargo.toml
  crates/uv/src/commands/python/install.rs
  crates/uv/src/commands/python/uninstall.rs
  crates/uv/tests/it/pip_compile_scenarios.rs
  crates/uv/tests/it/pip_install_scenarios.rs
  crates/uv/tests/it/python_install.rs
  crates/uv/tests/it/python_upgrade.rs
Labels: enhancement

#13955 Bump timeout on Python download release fetch
  crates/uv-python/fetch-download-metadata.py
Labels: internal

#13980 Simplify Python version link construction in discovery
  crates/uv-python/src/discovery.rs
Labels: internal

#13975 Universal sync_required_environment_hint test
  crates/uv/tests/it/sync.rs
Labels: internal

#13991 Update platform support reference to include Python implementation list
  docs/reference/policies/platforms.md
Labels: documentation

#13993 Add supported macOS version to the platform reference
  docs/reference/policies/platforms.md
Labels: documentation

#13627 Add tests for IO Error retries
  Cargo.lock
  Cargo.toml
  crates/uv/tests/it/network.rs
Labels: internal, network

#14024 Make wiremock filter a default filter
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/pip_install.rs
Labels: internal

#14009 filter out riscv64 wheels before publishing to pypi
  .github/workflows/publish-pypi.yml
Labels: internal

#13735 Add `[tool.uv.dependency-groups].mygroup.requires-python`
  Cargo.lock
  crates/uv-bench/benches/uv.rs
  crates/uv-configuration/src/dependency_groups.rs
  crates/uv-configuration/src/extras.rs
  crates/uv-distribution-types/src/lib.rs
  crates/uv-distribution-types/src/requires_python.rs
  crates/uv-distribution/src/metadata/requires_dist.rs
  crates/uv-resolver/src/lib.rs
  crates/uv-resolver/src/lock/export/pylock_toml.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/marker.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/python_requirement.rs
  crates/uv-resolver/src/resolution/output.rs
  crates/uv-resolver/src/resolution/requirements_txt.rs
  crates/uv-resolver/src/resolver/environment.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv-settings/src/settings.rs
  crates/uv-workspace/Cargo.toml
  crates/uv-workspace/src/dependency_groups.rs
  crates/uv-workspace/src/lib.rs
  crates/uv-workspace/src/pyproject.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/latest.rs
  crates/uv/src/commands/pip/list.rs
  crates/uv/src/commands/pip/tree.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/init.rs
  crates/uv/src/commands/project/install_target.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/lock_target.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/commands/project/version.rs
  crates/uv/src/commands/python/find.rs
  crates/uv/src/commands/python/pin.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/python_find.rs
  crates/uv/tests/it/run.rs
  crates/uv/tests/it/show_settings.rs
  crates/uv/tests/it/sync.rs
  crates/uv/tests/it/venv.rs
  docs/reference/settings.md
  uv.schema.json
Labels: enhancement

#13742 Support reading dependency-groups from pyproject.tomls with no project
  crates/uv-distribution-types/src/annotation.rs
  crates/uv-distribution/src/lib.rs
  crates/uv-distribution/src/metadata/dependency_groups.rs
  crates/uv-distribution/src/metadata/mod.rs
  crates/uv-pep508/src/origin.rs
  crates/uv-requirements/src/source_tree.rs
  crates/uv-requirements/src/specification.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_install.rs
Labels: bug

#14041 Fix implied `platform_machine` marker for `win_amd64` platform tag
  crates/uv-distribution-types/src/prioritized_distribution.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#14101 Refactors to transparent python upgrades
  Cargo.lock
  crates/uv-python/Cargo.toml
  crates/uv-python/src/discovery.rs
  crates/uv-python/src/installation.rs
  crates/uv-python/src/managed.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/python/install.rs
  crates/uv/src/commands/python/uninstall.rs
Labels: enhancement

#14102 Turn off `clippy::struct_excessive_bools` rule
  Cargo.toml
  crates/uv-cli/src/compat.rs
  crates/uv-cli/src/lib.rs
  crates/uv-client/src/httpcache/control.rs
  crates/uv-python/src/virtualenv.rs
  crates/uv-resolver/src/resolution/display.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv/src/settings.rs
Labels: internal

#14119 Remove preview label from `--torch-backend`
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  docs/guides/integration/pytorch.md
Labels: preview

#14109 Serialize Python requests for tools as canonicalized strings
  crates/uv-python/src/discovery.rs
  crates/uv-tool/src/tool.rs
  crates/uv/src/commands/tool/common.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/upgrade.rs
Labels: bug

#13940 Warn on empty index directory
  crates/uv-distribution-types/src/index_url.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/tests/it/edit.rs
Labels: enhancement

#13595 Properly handle authentication when encountering redirects
  Cargo.lock
  crates/uv-client/Cargo.toml
  crates/uv-client/src/base_client.rs
  crates/uv-client/src/cached_client.rs
  crates/uv-client/src/lib.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-git/src/resolver.rs
  crates/uv-publish/src/lib.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/edit.rs
Labels: bug

#14128 Fix benchmark compilation failure: `cannot find attribute clap in this scope`
  crates/uv-torch/src/backend.rs
Labels: bug

#14133 Fix Docker attestations
  .github/workflows/build-docker.yml
Labels: internal

#14141 handle an existing shebang in `uv init --script`
  Cargo.lock
  crates/uv-scripts/Cargo.toml
  crates/uv-scripts/src/lib.rs
  crates/uv-warnings/src/lib.rs
  crates/uv/tests/it/init.rs
  docs/guides/scripts.md
Labels: bug

#14126 Support netrc and same-origin credential propagation on index redirects
  Cargo.lock
  crates/uv-client/Cargo.toml
  crates/uv-client/src/base_client.rs
  crates/uv-client/src/cached_client.rs
  crates/uv-client/src/lib.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-git/src/resolver.rs
  crates/uv-publish/src/lib.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/edit.rs
Labels: bug

#14156 Update cargo-dist
  .github/workflows/release.yml
  Cargo.toml
  dist-workspace.toml
Labels: internal

#14107 Refactor `PythonVersionFile` global loading
  crates/uv-python/src/version_files.rs
  crates/uv/src/commands/python/pin.rs
Labels: internal

#14172 Add XPU to `--torch-backend`
  clippy.toml
  crates/uv-resolver/src/resolver/system.rs
  crates/uv-torch/src/backend.rs
  docs/reference/cli.md
  uv.schema.json
Labels: enhancement

#14175 Use a dedicated type for form metadata
  crates/uv-publish/src/lib.rs
Labels: internal

#14179 Only update existing symlink directories on preview uninstall
  crates/uv/src/commands/python/uninstall.rs
Labels: bug

#14176 Add auto-detection for AMD GPUs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-static/src/env_vars.rs
  crates/uv-torch/src/accelerator.rs
  crates/uv-torch/src/backend.rs
  docs/guides/integration/pytorch.md
Labels: enhancement

#14214 Consolidate logic for checking for a virtual environment
  crates/uv-fs/src/lib.rs
  crates/uv-python/src/discovery.rs
  crates/uv-python/src/interpreter.rs
  crates/uv-python/src/virtualenv.rs
  crates/uv-virtualenv/src/virtualenv.rs
Labels: internal

#14219 Update upgrade tests to use 3.10.17 instead of 3.10.8
  crates/uv/tests/it/python_install.rs
  crates/uv/tests/it/python_upgrade.rs
Labels: internal

#14224 Strip query parameters when parsing source URL
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#14238 Update wiremock to 0.6.4
  Cargo.lock
  Cargo.toml
Labels: enhancement

#14241 Add `"python-eol"` feature to Sphinx tests
  crates/uv/tests/it/sync.rs
Labels: testing

#14235 Don't log GitHub fast path usage if it's cached
  crates/uv-distribution/src/source/mod.rs
  crates/uv-git/src/resolver.rs
Labels: tracing

#14240 Remove wheel filename benchmark
  Cargo.lock
  crates/uv-bench/Cargo.toml
  crates/uv-bench/benches/distribution_filename.rs
Labels: ci-flake

#13033 Skip GitHub fast path when rate-limited
  crates/uv-git/src/git.rs
  crates/uv-git/src/lib.rs
  crates/uv-git/src/rate_limit.rs
  crates/uv-git/src/resolver.rs
  crates/uv-static/src/env_vars.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/pip_install.rs
Labels: enhancement

#13693 Update schemars 1.0.0
  Cargo.lock
  Cargo.toml
  crates/uv-configuration/src/name_specifiers.rs
  crates/uv-configuration/src/required_version.rs
  crates/uv-configuration/src/trusted_host.rs
  crates/uv-dev/src/generate_json_schema.rs
  crates/uv-distribution-types/src/index_url.rs
  crates/uv-distribution-types/src/pip_index.rs
  crates/uv-distribution-types/src/status_code_strategy.rs
  crates/uv-fs/src/path.rs
  crates/uv-pep508/Cargo.toml
  crates/uv-pep508/src/lib.rs
  crates/uv-pep508/src/marker/tree.rs
  crates/uv-pypi-types/src/conflicts.rs
  crates/uv-pypi-types/src/identifier.rs
  crates/uv-python/src/python_version.rs
  crates/uv-resolver/src/exclude_newer.rs
  crates/uv-settings/src/settings.rs
  crates/uv-small-str/src/lib.rs
  crates/uv-workspace/src/pyproject.rs
  uv.schema.json
Labels: enhancement

#14251 GCP Artifact Registry download URLs must have /simple path
  docs/guides/integration/alternative-indexes.md
Labels: documentation

#14274 Restore snapshot for `sync_dry_run`
  crates/uv/tests/it/sync.rs
Labels: testing

#14275 Add verbose output on flake for `run_groups_requires_python`
  crates/uv/tests/it/run.rs
Labels: internal

#14292 Include path or URL when failing to convert in lockfile
  crates/uv-resolver/src/lock/mod.rs
Labels: error messages

#14288 Avoid using path URL for workspace Git dependencies in `requirements.txt`
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-redacted/src/lib.rs
  crates/uv/tests/it/pip_compile.rs
Labels: bug

#14294 Allow local indexes to reference remote files
  crates/uv-resolver/src/lock/mod.rs
Labels: bug

#14303 Bump MSRV and `rust-toolchain` version
  Cargo.toml
  clippy.toml
  crates/uv-fs/src/which.rs
  crates/uv-python/src/discovery.rs
  crates/uv-trampoline-builder/src/lib.rs
  crates/uv/tests/it/ecosystem.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_install.rs
  rust-toolchain.toml
Labels: internal

#14245 Normalize index URLs to remove trailing slash
  crates/uv-distribution-types/src/file.rs
  crates/uv-distribution-types/src/index_url.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/it/edit.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/lock_scenarios.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#14319 Return `Cow` from `UrlString::with_` methods
  crates/uv-distribution-types/src/file.rs
  crates/uv-resolver/src/lock/mod.rs
Labels: internal

#14195 Avoid rendering desugared prefix matches in error messages
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv/tests/it/lock.rs
Labels: bug, error messages

#14334 Bump version to 0.7.16
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/concepts/build-backend.md
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#14340 Apply build constraints when resolving `--with` dependencies
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/upgrade.rs
  crates/uv/tests/it/run.rs
  crates/uv/tests/it/tool_install.rs
  crates/uv/tests/it/tool_run.rs
Labels: bug

#14337 Use the canonical `ImplementationName` -> `&str` implementation
  crates/uv-python/src/implementation.rs
  crates/uv-python/src/managed.rs
Labels: internal

#14330 Update the Python query cache comment
  crates/uv-python/src/interpreter.rs
Labels: internal

#14341 Fix typo
  docs/concepts/projects/dependencies.md
Labels: documentation

#14346 Drop trailing slashes when converting index URL from URL
  crates/uv-distribution-types/src/index_url.rs
  crates/uv-pep508/src/verbatim_url.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#14347 Bump version to 0.7.17
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/concepts/build-backend.md
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#14328 Improve trace message for cached Python interpreter query
  crates/uv-python/src/interpreter.rs
Labels: tracing

#14351 Add an `IntoIterator` for `FormMetadata`
  crates/uv-publish/src/lib.rs
Labels: internal

#14352 Allow `alpha`, `beta`, and `rc` prefixes in tests
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/version.rs
Labels: testing

#14372 Ignore invalid build backend settings when not building
  crates/uv-workspace/src/pyproject.rs
  crates/uv/tests/it/build_backend.rs
Labels: preview

#14331 Include the canonical path in the interpreter query cache key
  crates/uv-python/src/interpreter.rs
Labels: bug

#13724 disfavor aarch64 windows in its own house
  .github/workflows/ci.yml
  crates/uv-python/src/platform.rs
  crates/uv/src/commands/python/install.rs
Labels: internal
