Repository astral-sh/uv, pull requests merged in 2025-10, with the labels that each got.

#15909 Remove tracking of inferred dependency conflicts
  crates/uv-pypi-types/src/conflicts.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/tests/it/lock_conflict.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#16091 Show variants in `uv pip list`
  crates/uv-distribution-types/src/installed.rs
  crates/uv-distribution-types/src/variant_json.rs
  crates/uv/src/commands/pip/list.rs
Labels: enhancement, preview

#16088 Make cache control lookups robust to username
  crates/uv-auth/src/lib.rs
  crates/uv-auth/src/realm.rs
  crates/uv-distribution-types/src/index_url.rs
Labels: bug

#16092 Fix pubgrub grouping in renovate
  .github/renovate.json5
Labels: internal

#16099 Update slab to v0.4.11
  Cargo.lock
Labels: internal

#16114 Fix typo in `_CONDA_ROOT` docs
  crates/uv-macros/src/lib.rs
  docs/reference/environment.md
Labels: documentation

#16080 Confirm that the directory name is a valid Python install key during managed check
  crates/uv-python/src/interpreter.rs
Labels: bug

#16135 Remove unused version.rs
  crates/uv/src/commands/version.rs
Labels: internal

#16159 Fix `uv python upgrade` replacement of installed binaries on pre-release to stable
  crates/uv-python/src/managed.rs
  crates/uv/tests/it/python_upgrade.rs
Labels: bug

#15133 Trim trailing slashes to fix workspace discovery
  crates/uv-workspace/src/workspace.rs
  crates/uv/tests/it/build.rs
Labels: bug, breaking

#15352 Promote trixie and alpine 3.22 as default tags
  .github/workflows/build-docker.yml
  docs/guides/integration/docker.md
Labels: breaking

#16150 Publish Python 3.14 Docker Images
  .github/workflows/build-docker.yml
  docs/guides/integration/docker.md
Labels: enhancement

#16177 Use correct tag comment for Vampire/setup-wsl v6.0.0
  .github/workflows/ci.yml
Labels: internal

#16172 Upgrade reqsign to 0.18.0 to remove chrono deps
  Cargo.lock
  Cargo.toml
Labels: internal
