Repository astral-sh/uv, pull requests merged in 2025-03, with the labels that each got.

#11874 Fix typo in unsatisfiable
  crates/uv-pep508/src/marker/algebra.rs
Labels: internal

#11873 Respect `include-system-site-packages` in layered environments
  crates/uv-python/src/environment.rs
  crates/uv-python/src/virtualenv.rs
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/tool/run.rs
Labels: bug

#11846 Suggest `uv tool update-shell` in PowerShell
  crates/uv-shell/src/lib.rs
  crates/uv/src/commands/python/install.rs
  crates/uv/src/commands/tool/common.rs
  crates/uv/src/commands/tool/update_shell.rs
Labels: bug, windows

#11889 Avoid error on relative paths in `uv tool uninstall`
  crates/uv-tool/src/lib.rs
  crates/uv/src/commands/tool/uninstall.rs
Labels: bug

#11875 Make interpreter caching robust to OS upgrades
  Cargo.lock
  crates/uv-python/Cargo.toml
  crates/uv-python/src/interpreter.rs
Labels: bug

#11898 Document our MSRV policy
  docs/reference/policies/versioning.md
Labels: documentation

#11890 Avoid silently dropping errors in directory enumeration
  crates/uv-cache/src/lib.rs
  crates/uv-distribution/src/index/built_wheel_index.rs
  crates/uv-distribution/src/index/registry_wheel_index.rs
  crates/uv-distribution/src/source/built_wheel_metadata.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-fs/src/lib.rs
  crates/uv-tool/src/lib.rs
  crates/uv/src/commands/python/uninstall.rs
  crates/uv/src/commands/tool/uninstall.rs
Labels: bug

#11895 Docs: Clarify that setting cache-keys overrides defaults
  docs/concepts/cache.md
Labels: documentation

#11115 Avoid fallback to PyPI in mixed CPU/CUDA example
  docs/guides/integration/pytorch.md
Labels: documentation

#10048 Test with custom install dir
  CONTRIBUTING.md
  crates/uv/tests/it/help.rs
Labels: documentation

#11922 Edition 2024 prep: Escape `r#gen` and remove redundant ref
  crates/uv-configuration/src/dev.rs
  crates/uv-configuration/src/name_specifiers.rs
  crates/uv-configuration/src/required_version.rs
  crates/uv-configuration/src/trusted_host.rs
  crates/uv-distribution-types/src/index_url.rs
  crates/uv-distribution-types/src/pip_index.rs
  crates/uv-fs/src/path.rs
  crates/uv-pep440/src/version.rs
  crates/uv-pep508/src/lib.rs
  crates/uv-pep508/src/marker/algebra.rs
  crates/uv-pep508/src/marker/tree.rs
  crates/uv-pypi-types/src/conflicts.rs
  crates/uv-python/src/python_version.rs
  crates/uv-resolver/src/exclude_newer.rs
  crates/uv-small-str/src/lib.rs
  crates/uv-workspace/src/pyproject.rs
Labels: internal

#11801 Discover registry PEP 514 Pythons cross 32/64-bit
  Cargo.toml
  crates/uv-python/src/windows_registry.rs
Labels: bug

#11910 Avoid string allocation when enumerating tool names
  crates/uv-tool/src/lib.rs
Labels: performance

#11894 Migrate to `zlib-rs` (again)
  CONTRIBUTING.md
  Cargo.lock
  Cargo.toml
  crates/uv-dev/Cargo.toml
  crates/uv-performance-flate2-backend/Cargo.lock
  crates/uv-performance-flate2-backend/Cargo.toml
  crates/uv-performance-flate2-backend/src/lib.rs
  crates/uv/Cargo.toml
  pyproject.toml
Labels: performance, no-build

#11928 Fix typo in `no_default_groups` documentation and changelog
  CHANGELOG.md
  crates/uv-cli/src/lib.rs
  docs/reference/cli.md
Labels: documentation

#11934 Bump version to 0.6.4
  .github/workflows/build-binaries.yml
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#11936 Explicitly install the rust toolchain before the target during Docker builds
  Dockerfile
Labels: releases

#10207 Allow `--constraints` and `--overrides` in `uvx`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/tool_run.rs
  docs/reference/cli.md
Labels: enhancement

#11947 Fix error message suggesting `--user` instead of `--username`
  crates/uv/src/commands/publish.rs
Labels: error messages

#11938 Run the Docker build workflow when we touch project or toolchain metadata
  .github/workflows/build-binaries.yml
  .github/workflows/build-docker.yml
Labels: testing

#11957 Remove unused `UV_STACK_SIZE` env vars
  .github/workflows/ci.yml
Labels: internal

#11950 Move `LowerBound` and `UpperBound` structs in `uv-pep440`
  crates/uv-pep440/src/lib.rs
  crates/uv-pep440/src/version_ranges.rs
  crates/uv-resolver/src/error.rs
  crates/uv-resolver/src/marker.rs
  crates/uv-resolver/src/requires_python.rs
  crates/uv-resolver/src/resolver/environment.rs
Labels: internal

#11956 Fix system site packages detection default
  crates/uv-python/src/virtualenv.rs
Labels: bug

#11952 Compare major-minor specifiers when filtering interpreters
  crates/uv-python/src/discovery.rs
  crates/uv/tests/it/python_find.rs
Labels: bug

#11967 Fix `include_system_side_packages` typo
  crates/uv-python/src/virtualenv.rs
  crates/uv/src/commands/project/run.rs
Labels: internal

#11969 Remove `Serialize` implementations from some settings
  crates/uv-settings/src/settings.rs
Labels: internal

#11971 Fix empty constraints in satisfies check
  crates/uv/src/commands/tool/run.rs
Labels: internal

#11968 Add `NO_BUILD` and `NO_BUILD_PACKAGE` environment variables
  crates/uv-cli/src/lib.rs
  crates/uv-static/src/env_vars.rs
  crates/uv/tests/it/sync.rs
  docs/configuration/environment.md
  docs/reference/cli.md
Labels: configuration

#11976 Respect markers on constraints when validating current environment
  crates/uv-installer/src/site_packages.rs
  crates/uv/tests/it/pip_install.rs
Labels: bug, performance

#11888 Add support for Windows legacy scripts via uv run
  crates/uv/src/commands/project/run.rs
  crates/uv/tests/it/run.rs
Labels: windows

#11992 Warn user on `uvx run` command
  crates/uv/src/commands/diagnostics.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/it/edit.rs
Labels: error messages

#11994 Allow overrides in `satisfies` check for `uv tool run`
  crates/uv-installer/src/site_packages.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/it/tool_run.rs
Labels: enhancement

#11995 Allow overrides in all satisfies checks
  crates/uv-installer/src/site_packages.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/tool/run.rs
Labels: performance

#12010 Invalidate lockfile when empty dependency groups are added or removed
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#11446 A minimal build backend for uv: uv_build
  .github/workflows/build-binaries.yml
  .github/workflows/ci.yml
  .github/workflows/publish-pypi.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/metadata.rs
  crates/uv-build-backend/src/serde_verbatim.rs
  crates/uv-build/Cargo.toml
  crates/uv-build/LICENSE-APACHE
  crates/uv-build/LICENSE-MIT
  crates/uv-build/README.md
  crates/uv-build/deny.toml
  crates/uv-build/pyproject.toml
  crates/uv-build/python/uv_build/__init__.py
  crates/uv-build/python/uv_build/__main__.py
  crates/uv-build/python/uv_build/py.typed
  crates/uv-build/src/main.rs
  crates/uv-types/src/traits.rs
  crates/uv/src/commands/build_backend.rs
  crates/uv/src/commands/project/init.rs
  crates/uv/tests/it/init.rs
  pyproject.toml
  python/uv/__init__.py
  scripts/packages/built-by-uv/pyproject.toml
Labels: preview

#12018 Bump version to 0.6.5
  CHANGELOG.md
  Cargo.lock
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#12019 Bump uv-build version to 0.6.5
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
Labels: no-build, releases

#12022 Run the `uv-build` publish sequentially after `uv`
  .github/workflows/publish-pypi.yml
Labels: no-build, releases

#12023 Fix upload name for macOS wheels
  .github/workflows/build-binaries.yml
Labels: no-build, releases

#12024 Revert "Run the `uv-build` publish sequentially after `uv` (#12022)"
  .github/workflows/publish-pypi.yml
Labels: no-build, releases

#11884 Allow overriding module name for uv build backend
  Cargo.lock
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/metadata.rs
  crates/uv-build-backend/src/source_dist.rs
  crates/uv-build-backend/src/wheel.rs
  crates/uv-pypi-types/Cargo.toml
  crates/uv-pypi-types/src/identifier.rs
  crates/uv-pypi-types/src/lib.rs
  crates/uv-workspace/Cargo.toml
  crates/uv/tests/it/build_backend.rs
Labels: enhancement

#12051 Fix `PyPI` typo in publish workflow
  .github/workflows/publish-pypi.yml
Labels: internal, no-build, no-test

#11666 Update versioning policy
  docs/reference/policies/versioning.md
Labels: documentation

#12057 Insert dependencies into fork state prior to fetching metadata
  crates/uv-resolver/src/resolver/mod.rs
Labels: bug, performance

#12058 Integration test uv_build package
  .github/workflows/ci.yml
  crates/uv-build/python/uv_build/__init__.py
Labels: bug, preview

#12064 Remove unused archive timestamp
  crates/uv-cache/src/lib.rs
Labels: internal

#12043 Avoid consider PATH updated when the export is commented in the shellrc
  crates/uv/src/commands/tool/update_shell.rs
Labels: bug

#12053 Fix tool concept page headings
  docs/concepts/tools.md
Labels: documentation

#12076 Add Rustdoc boxes around references
  crates/uv-types/src/traits.rs
Labels: internal, no-build, no-test

#12077 Remove some allocations from `uv-auth`
  Cargo.lock
  crates/uv-auth/Cargo.toml
  crates/uv-auth/src/cache.rs
  crates/uv-auth/src/credentials.rs
  crates/uv-auth/src/middleware.rs
  crates/uv-auth/src/realm.rs
Labels: performance, no-build

#12090 Move config dir functions to public functions in uv_dirs
  Cargo.lock
  crates/uv-dirs/Cargo.toml
  crates/uv-dirs/src/lib.rs
  crates/uv-fs/Cargo.toml
  crates/uv-settings/Cargo.toml
  crates/uv-settings/src/lib.rs
Labels: internal

#12041 Re-add 3 retries in `uv publish`
  crates/uv-publish/src/lib.rs
  crates/uv/src/commands/publish.rs
  scripts/publish/test_publish.py
Labels: bug

#12096 Cache workspace discovery
  Cargo.lock
  crates/uv-bench/Cargo.toml
  crates/uv-bench/benches/uv.rs
  crates/uv-build-frontend/Cargo.toml
  crates/uv-build-frontend/src/lib.rs
  crates/uv-dispatch/Cargo.toml
  crates/uv-dispatch/src/lib.rs
  crates/uv-distribution/src/metadata/build_requires.rs
  crates/uv-distribution/src/metadata/mod.rs
  crates/uv-distribution/src/metadata/requires_dist.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-types/Cargo.toml
  crates/uv-types/src/traits.rs
  crates/uv-workspace/src/lib.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/init.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/commands/python/find.rs
  crates/uv/src/commands/python/pin.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/commands/tool/upgrade.rs
  crates/uv/src/commands/venv.rs
  crates/uv/src/lib.rs
  crates/uv/tests/it/lock.rs
Labels: performance

#12079 Add support for Windows legacy scripts via uv tool run
  crates/uv-shell/src/lib.rs
  crates/uv-shell/src/runnable.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/tests/it/run.rs
  crates/uv/tests/it/tool_run.rs
  docs/concepts/projects/run.md
  docs/guides/tools.md
Labels: windows

#12112 Docs : Quote versions string in python-versions.md
  docs/concepts/python-versions.md
Labels: documentation

#12102 Update the `index.authenticate` docs
  crates/uv-auth/src/policy.rs
  crates/uv-distribution-types/src/index.rs
  docs/configuration/authentication.md
  docs/configuration/indexes.md
  uv.schema.json
Labels: documentation

#12124 Fix `uv python install --reinstall` when the version is not yet installed
  crates/uv/src/commands/python/install.rs
  crates/uv/tests/it/python_install.rs
Labels: bug

#12125 Bump version to 0.6.6
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: no-build, releases

#12133 remove `BaseClientBuild::client`, expose `ExtraMiddleware`
  crates/uv-client/src/base_client.rs
  crates/uv-client/src/lib.rs
  crates/uv-client/src/registry_client.rs
Labels: internal

#12099 Reverse and format the archived changelogs
  changelogs/0.1.x.md
  changelogs/0.2.x.md
  changelogs/0.3.x.md
  changelogs/0.4.x.md
  changelogs/0.5.x.md
  scripts/reverse-changelog.py
Labels: documentation

#12138 Refactor *Settings to clarify and reduce repetition
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/environment.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/commands/tool/upgrade.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/show_settings.rs
Labels: internal

#12135 Render token claims on publish permission error
  crates/uv-publish/src/trusted_publishing.rs
Labels: error messages

#10682 Discard insufficient fork markers
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#12157 Use consistent commas around i.e. and e.g.
  CONTRIBUTING.md
  changelogs/0.1.x.md
  changelogs/0.5.x.md
  crates/uv-globfilter/README.md
  crates/uv-pep440/Readme.md
  crates/uv-pep508/Readme.md
  crates/uv-static/src/env_vars.rs
  docs/concepts/projects/config.md
  docs/concepts/projects/dependencies.md
  docs/concepts/python-versions.md
  docs/concepts/resolution.md
  docs/configuration/authentication.md
  docs/configuration/environment.md
  docs/guides/install-python.md
  docs/guides/package.md
  docs/guides/scripts.md
  docs/guides/tools.md
  docs/reference/troubleshooting/build-failures.md
Labels: documentation

#12154 Fix GraalPy abi tag parsing and discovery
  crates/uv-platform-tags/src/abi_tag.rs
  crates/uv-platform-tags/src/tags.rs
  crates/uv-python/python/get_interpreter_info.py
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/pip_install_scenarios.rs
Labels: bug

#12158 Remove extraneous script packages in `uv sync --script`
  crates/uv/src/commands/project/mod.rs
  crates/uv/tests/it/sync.rs
  crates/uv/tests/it/tool_install.rs
Labels: bug

#9332 Avoid subsequent index hint when no versions are available on the first index
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv/tests/it/pip_compile.rs
Labels: error messages

#12160 Remove redundant `activate.bat` output
  crates/uv-virtualenv/src/activator/activate.bat
Labels: bug, windows

#12159 Avoid replicating core-metadata field on `File` struct
  crates/uv-client/src/html.rs
  crates/uv-distribution-types/src/file.rs
  crates/uv-pypi-types/src/simple_json.rs
Labels: performance

#12171 Fix double space typo
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/it/sync.rs
Labels: error messages

#12180 Ensure `python pin --global` creates parent directories if missing
  crates/uv/src/commands/python/pin.rs
  crates/uv/tests/it/python_pin.rs
Labels: bug

#12182 Remove `setuptools` from edit tests
  crates/uv/tests/it/edit.rs
Labels: testing

#12188 Replace change detection GitHub Action
  .github/workflows/ci.yml
Labels: internal

#12189 Instruct Renovate to pin GitHub Actions based on SHA
  .github/renovate.json5
Labels: internal

#12181 Use `uv sync` in workspace tests
  crates/uv-workspace/src/workspace.rs
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/workspace.rs
  scripts/workspaces/albatross-in-example/examples/bird-feeder/pyproject.toml
  scripts/workspaces/albatross-in-example/examples/bird-feeder/src/bird_feeder/__init__.py
  scripts/workspaces/albatross-in-example/pyproject.toml
  scripts/workspaces/albatross-in-example/src/albatross/__init__.py
  scripts/workspaces/albatross-just-project/pyproject.toml
  scripts/workspaces/albatross-project-in-excluded/excluded/bird-feeder/pyproject.toml
  scripts/workspaces/albatross-project-in-excluded/excluded/bird-feeder/src/bird_feeder/__init__.py
  scripts/workspaces/albatross-project-in-excluded/pyproject.toml
  scripts/workspaces/albatross-project-in-excluded/src/albatross/__init__.py
  scripts/workspaces/albatross-root-workspace/packages/bird-feeder/pyproject.toml
  scripts/workspaces/albatross-root-workspace/packages/bird-feeder/src/bird_feeder/__init__.py
  scripts/workspaces/albatross-root-workspace/pyproject.toml
  scripts/workspaces/albatross-root-workspace/src/albatross/__init__.py
  scripts/workspaces/albatross-virtual-workspace/packages/albatross/pyproject.toml
  scripts/workspaces/albatross-virtual-workspace/packages/albatross/src/albatross/__init__.py
Labels: testing

#12206 Avoid creating duplicate directory entries in built wheels
  crates/uv-build-backend/src/wheel.rs
Labels: bug, preview

#12196 Upgrade zip crate to v2
  Cargo.lock
  Cargo.toml
  crates/uv-build-backend/src/wheel.rs
  crates/uv-trampoline-builder/src/lib.rs
Labels: no-build, dependencies

#12176 Always reinstall local source trees passed to `uv pip install`
  Cargo.lock
  crates/uv-cache/Cargo.toml
  crates/uv-cache/src/lib.rs
  crates/uv-client/src/flat_index.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-configuration/Cargo.toml
  crates/uv-configuration/src/package_options.rs
  crates/uv-distribution-types/src/buildable.rs
  crates/uv-distribution-types/src/installed.rs
  crates/uv-distribution-types/src/lib.rs
  crates/uv-distribution-types/src/resolved.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-installer/src/plan.rs
  crates/uv-installer/src/site_packages.rs
  crates/uv-installer/src/uninstall.rs
  crates/uv-python/src/interpreter.rs
  crates/uv-requirements/src/sources.rs
  crates/uv-requirements/src/specification.rs
  crates/uv-resolver/src/exclusions.rs
  crates/uv-tool/src/lib.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/commands/pip/show.rs
  crates/uv/src/commands/pip/uninstall.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/lib.rs
  crates/uv/tests/it/cache_prune.rs
  crates/uv/tests/it/pip_install.rs
  docs/concepts/cache.md
Labels: enhancement, cache, no-build

#12209 Add support for `-c` constraints in `uv add`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/remove.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/edit.rs
  docs/guides/projects.md
  docs/reference/cli.md
Labels: enhancement, cli

#12062 Add `src` to default cache keys
  crates/uv-cache-info/src/cache_info.rs
  crates/uv-cache-info/src/timestamp.rs
  crates/uv-settings/src/settings.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/run.rs
  crates/uv/tests/it/sync.rs
  docs/concepts/cache.md
  docs/reference/settings.md
  uv.schema.json
Labels: bug

#12235 Error on lockfiles with incoherent wheel versions
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#12249 Include versions in the lockfile coherence error message
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/it/sync.rs
Labels: error messages, no-test

#12252 Allow dirty files in `cargo-dist` for action pins
  Cargo.toml
Labels: no-build, no-test

#12063 Avoid allocations for default cache keys
  crates/uv-cache-info/src/cache_info.rs
Labels: performance

#12278 Allow owned string when deserializing `requires-python`
  crates/uv-pypi-types/src/simple_json.rs
  crates/uv/tests/it/pip_compile.rs
Labels: bug

#12287 Un-pin `maturin-action` version
  .github/workflows/build-binaries.yml
Labels: releases

#12279 Update documentation for `python-preference` and `managed-python`
  docs/concepts/python-versions.md
  docs/guides/install-python.md
Labels: documentation

#12294 Update pytorch test snapshot
  crates/uv/tests/it/lock.rs
Labels: internal

#12295 update ring
  Cargo.lock
Labels: internal

#12289 add `default-groups = "all"` sugar to `pyproject.toml`
  crates/uv-configuration/src/dependency_groups.rs
  crates/uv-normalize/src/group_name.rs
  crates/uv-normalize/src/lib.rs
  crates/uv-workspace/src/pyproject.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/commands/project/mod.rs
  crates/uv/src/commands/project/run.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/tests/it/sync.rs
  docs/concepts/projects/dependencies.md
  docs/reference/settings.md
  uv.schema.json
Labels: enhancement, configuration

#12297 Bump version to 0.6.8
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#12070 Automatically infer the PyTorch index via `--torch-backend=auto`
  Cargo.lock
  Cargo.toml
  clippy.toml
  crates/uv-cli/Cargo.toml
  crates/uv-cli/src/lib.rs
  crates/uv-client/Cargo.toml
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution-types/src/index_url.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-settings/Cargo.toml
  crates/uv-settings/src/combine.rs
  crates/uv-settings/src/settings.rs
  crates/uv-static/src/env_vars.rs
  crates/uv-torch/Cargo.toml
  crates/uv-torch/src/accelerator.rs
  crates/uv-torch/src/backend.rs
  crates/uv-torch/src/lib.rs
  crates/uv/Cargo.toml
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/pip_install.rs
  crates/uv/tests/it/show_settings.rs
  docs/configuration/environment.md
  docs/reference/cli.md
  docs/reference/settings.md
  uv.schema.json
Labels: no-build

#12315 Fix `#keyring-provider` references in alternative index docs
  docs/guides/integration/alternative-indexes.md
Labels: documentation

#12345 Add boolish value parser for *MANAGED_PYTHON flags
  crates/uv-cli/src/lib.rs
Labels: bug

#12347 Bump version to 0.6.9
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#12354 Error on missing argument in `requirements.txt`
  crates/uv-requirements-txt/src/lib.rs
Labels: error messages

#12355 Use small string for index name type
  crates/uv-distribution-types/src/index_name.rs
Labels: performance

#11891 Support `python find --script`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/mod.rs
  crates/uv/src/commands/python/find.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/python_find.rs
  docs/reference/cli.md
Labels: enhancement

#12360 Retain end-of-line comment position when adding dependency
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv/tests/it/edit.rs
Labels: bug

#12342 Add `uv sync --check` flag
  crates/uv-cli/src/lib.rs
  crates/uv-configuration/src/dry_run.rs
  crates/uv/src/commands/pip/operations.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/sync.rs
  docs/reference/cli.md
Labels: enhancement

#12378 Update `python_required_python_major_minor` with note about Homebrew
  crates/uv/tests/it/python_find.rs
Labels: internal

#12377 Update some Python find tests to use filters
  crates/uv/tests/it/python_find.rs
Labels: internal

#12386 Support `.env` files in `uv tool run`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/tool/run.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/tool_run.rs
  docs/reference/cli.md
Labels: enhancement, cli

#12384 Omit fragment when querying for wheels in Simple HTML API
  crates/uv-client/src/html.rs
  crates/uv-client/src/registry_client.rs
Labels: compatibility

#12391 Use a boxed slice for extras and groups
  crates/uv-configuration/src/constraints.rs
  crates/uv-distribution-types/src/requirement.rs
  crates/uv-distribution-types/src/specified_requirement.rs
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-distribution/src/metadata/requires_dist.rs
  crates/uv-pep508/src/lib.rs
  crates/uv-pep508/src/unnamed.rs
  crates/uv-requirements/src/extras.rs
  crates/uv-requirements/src/specification.rs
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-types/src/requirements.rs
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv-workspace/src/workspace.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/tool/install.rs
  crates/uv/src/commands/tool/mod.rs
  crates/uv/src/commands/tool/run.rs
Labels: performance

#12314 Allow virtual packages with `--no-build`
  crates/uv-distribution-types/src/lib.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#12299 Omit wheels from lockfile based on `--exclude-newer`
  crates/uv-bench/benches/uv.rs
  crates/uv-distribution-types/src/prioritized_distribution.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/pip_compile.rs
  crates/uv/tests/it/snapshots/it__ecosystem__saleor-lock-file.snap
Labels: bug

#12374 Add `uv python list` test cases
  crates/uv/tests/it/common/mod.rs
  crates/uv/tests/it/main.rs
  crates/uv/tests/it/python_list.rs
Labels: testing

#12379 Add comments to the `with_filtered_python_keys` regex
  crates/uv/tests/it/common/mod.rs
Labels: internal

#12375 Add support for Python version requests in `uv python list`
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/python/list.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/python_list.rs
  docs/concepts/python-versions.md
  docs/reference/cli.md
Labels: enhancement

#12380 Add support for pre-releases to Python platform key regex
  crates/uv/tests/it/common/mod.rs
Labels: internal

#12396 Ignore `--find-links` entries for pinned indexes
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv/tests/it/lock.rs
Labels: bug

#12240 Support modules with different casing in build backend
  crates/uv-build-backend/src/lib.rs
  crates/uv-build-backend/src/wheel.rs
  crates/uv/tests/it/build_backend.rs
Labels: bug

#12400 Fix log message for `SIGTERM` when child has exited
  crates/uv/src/commands/run.rs
Labels: tracing

#12406 Pass around index with associated metadata
  crates/uv-auth/src/policy.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution-types/src/index.rs
  crates/uv-distribution-types/src/index_name.rs
  crates/uv-distribution-types/src/origin.rs
  crates/uv-distribution-types/src/requirement.rs
  crates/uv-distribution-types/src/resolution.rs
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-publish/src/lib.rs
  crates/uv-resolver/src/fork_indexes.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/pubgrub/report.rs
  crates/uv-resolver/src/resolver/batch_prefetch.rs
  crates/uv-resolver/src/resolver/indexes.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv/src/commands/pip/latest.rs
  crates/uv/src/commands/publish.rs
  crates/uv/tests/it/lock.rs
Labels: internal, no-build

#12438 Show a dedicated hint for `setuptools` dash-separator change
  crates/uv-build-frontend/src/error.rs
  crates/uv/tests/it/pip_install.rs
Labels: error messages

#12466 Use 64-bit host for 32-bit releases to work around OOM
  .github/workflows/build-binaries.yml
Labels: releases

#12470 Add auth policy support for pip commands
  crates/uv-auth/src/middleware.rs
  crates/uv-auth/src/policy.rs
  crates/uv/src/commands/pip/compile.rs
  crates/uv/src/commands/pip/install.rs
  crates/uv/src/commands/pip/list.rs
  crates/uv/src/commands/pip/sync.rs
  crates/uv/src/commands/pip/tree.rs
  crates/uv/src/commands/project/add.rs
  crates/uv/src/commands/venv.rs
  crates/uv/tests/it/edit.rs
Labels: bug

#12346 Use `Box<Path>` in lieu of `PathBuf` for immutable structs
  crates/uv-cache/src/lib.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-configuration/src/package_options.rs
  crates/uv-distribution-types/src/cached.rs
  crates/uv-distribution-types/src/installed.rs
  crates/uv-distribution-types/src/lib.rs
  crates/uv-distribution-types/src/requirement.rs
  crates/uv-distribution/src/distribution_database.rs
  crates/uv-distribution/src/download.rs
  crates/uv-distribution/src/index/cached_wheel.rs
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-distribution/src/source/built_wheel_metadata.rs
  crates/uv-distribution/src/source/mod.rs
  crates/uv-fs/src/path.rs
  crates/uv-git/src/git.rs
  crates/uv-installer/src/plan.rs
  crates/uv-installer/src/satisfies.rs
  crates/uv-pypi-types/src/direct_url.rs
  crates/uv-pypi-types/src/parsed_url.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/requirements_txt.rs
  crates/uv-workspace/src/pyproject.rs
  crates/uv-workspace/src/workspace.rs
Labels: performance

#12430 Bump version to v0.6.10
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#12407 Support `--find-links`-style "flat" indexes in `[[tool.uv.index]]`
  Cargo.lock
  crates/uv-client/Cargo.toml
  crates/uv-client/src/error.rs
  crates/uv-client/src/lib.rs
  crates/uv-client/src/registry_client.rs
  crates/uv-distribution-types/src/index.rs
  crates/uv-distribution-types/src/index_url.rs
  crates/uv-distribution/src/metadata/lowering.rs
  crates/uv-publish/src/lib.rs
  crates/uv-resolver/src/flat_index.rs
  crates/uv-resolver/src/resolver/indexes.rs
  crates/uv-resolver/src/resolver/provider.rs
  crates/uv-resolver/src/version_map.rs
  crates/uv/src/commands/pip/latest.rs
  crates/uv/src/commands/project/tree.rs
  crates/uv/tests/it/lock.rs
  crates/uv/tests/it/show_settings.rs
  docs/configuration/indexes.md
  uv.schema.json
Labels: enhancement, no-build

#12300 distinguish -q and -qq
  crates/uv-cli/src/lib.rs
  crates/uv/src/commands/build_frontend.rs
  crates/uv/src/lib.rs
  crates/uv/src/printer.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/help.rs
  crates/uv/tests/it/show_settings.rs
  docs/reference/cli.md
Labels: enhancement

#12503 Fix schemars macro usage in build backend enum
  crates/uv-configuration/src/project_build_backend.rs
Labels: internal

#12504 Enable necessary optional features in `uv-settings`
  crates/uv-settings/Cargo.toml
Labels: internal, no-build

#12497 Improve trace message in auth middleware
  crates/uv-auth/src/middleware.rs
Labels: tracing

#11628 Add smoke test script in Python
  .github/workflows/ci.yml
  regular_file; echo foo; #
  scripts/smoke-test/__main__.py
  scripts/smoke-test/commands.sh
Labels: testing

#12516 Add `--version` to smoke tests
  scripts/smoke-test/commands.sh
Labels: testing

#12514 Use a boxed slice for various requirement types
  crates/uv-distribution-types/src/dependency_metadata.rs
  crates/uv-distribution/src/metadata/mod.rs
  crates/uv-distribution/src/metadata/requires_dist.rs
  crates/uv-pypi-types/src/metadata/metadata_resolver.rs
  crates/uv-pypi-types/src/metadata/requires_dist.rs
  crates/uv-requirements/src/extras.rs
  crates/uv-requirements/src/lookahead.rs
  crates/uv-requirements/src/source_tree.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/pubgrub/dependencies.rs
  crates/uv-resolver/src/resolver/mod.rs
  crates/uv/src/commands/pip/show.rs
Labels: performance, wish

#12502 Respect build constraints in `uv sync`
  crates/uv-distribution-types/src/requirement.rs
  crates/uv-resolver/src/lock/mod.rs
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_optional_missing.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_optional_present.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__hash_required_present.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_source_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_source_version_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_version_dynamic.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__missing_dependency_version_unambiguous.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_direct_has_subdir.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_direct_no_subdir.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_directory.snap
  crates/uv-resolver/src/lock/snapshots/uv_resolver__lock__tests__source_editable.snap
  crates/uv/src/commands/project/install_target.rs
  crates/uv/src/commands/project/lock.rs
  crates/uv/src/commands/project/sync.rs
  crates/uv/tests/it/sync.rs
Labels: bug

#12501 Add a newline after metadata when initializing scripts with other metadata blocks
  crates/uv-scripts/src/lib.rs
Labels: bug

#12518 Bump least-recent non-EOL macOS version to 13.0
  crates/uv-configuration/src/target_triple.rs
  crates/uv-static/src/env_vars.rs
  docs/configuration/environment.md
  uv.schema.json
Labels: compatibility

#12517 Avoid writing empty `requires-python` to script blocks
  crates/uv-scripts/src/lib.rs
Labels: bug

#12530 Remove dummy file
  regular_file; echo foo; #
Labels: internal

#12350 Add dependents ("via ..." comments) in export command
  crates/uv-cli/src/lib.rs
  crates/uv-resolver/src/lock/requirements_txt.rs
  crates/uv/src/commands/project/export.rs
  crates/uv/src/lib.rs
  crates/uv/src/settings.rs
  crates/uv/tests/it/export.rs
  docs/reference/cli.md
Labels: enhancement

#12551 changed where the fish completions get installed to where fish docs recommend
  docs/getting-started/installation.md
Labels: documentation

#12560 Respect transitive dependencies in `uv tree --only-group`
  crates/uv-resolver/src/lock/tree.rs
  crates/uv/tests/it/tree.rs
Labels: bug

#12561 Use `Entry` API in lockfile-to-requirements.txt construction
  crates/uv-resolver/src/lock/requirements_txt.rs
Labels: internal

#12535 Bump version to v0.6.11
  CHANGELOG.md
  Cargo.lock
  crates/uv-build/Cargo.toml
  crates/uv-build/pyproject.toml
  crates/uv-version/Cargo.toml
  crates/uv/Cargo.toml
  docs/getting-started/installation.md
  docs/guides/integration/aws-lambda.md
  docs/guides/integration/docker.md
  docs/guides/integration/github.md
  docs/guides/integration/pre-commit.md
  pyproject.toml
Labels: releases

#12563 Add `UV_PROJECT` to changelog
  CHANGELOG.md
Labels: documentation

#12583 Fix invalid 'kind' reference in flat index docs
  docs/configuration/indexes.md
Labels: documentation

#12586 Normalize extra and group names in `uv add` and `uv remove`
  crates/uv-workspace/src/pyproject_mut.rs
  crates/uv/tests/it/edit.rs
Labels: bug
